/* Generated by Nim Compiler v0.10.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/jsudlow/Nim/lib -o .nimcache/app.o .nimcache/app.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>
typedef struct app126002 app126002;
typedef struct scene126006 scene126006;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tsurface123011 tsurface123011;
typedef struct scenemanager126008 scenemanager126008;
typedef struct controller126004 controller126004;
typedef struct tcell45135 tcell45135;
typedef struct TNimType TNimType;
typedef struct tcellseq45151 tcellseq45151;
typedef struct tgcheap47216 tgcheap47216;
typedef struct tcellset45147 tcellset45147;
typedef struct tpagedesc45143 tpagedesc45143;
typedef struct tmemregion27410 tmemregion27410;
typedef struct tsmallchunk26640 tsmallchunk26640;
typedef struct tllchunk27404 tllchunk27404;
typedef struct tbigchunk26642 tbigchunk26642;
typedef struct tintset26617 tintset26617;
typedef struct ttrunk26613 ttrunk26613;
typedef struct tavlnode27408 tavlnode27408;
typedef struct tgcstat47214 tgcstat47214;
typedef struct TNimNode TNimNode;
typedef struct table122024 table122024;
typedef struct keyvaluepairseq122027 keyvaluepairseq122027;
typedef struct tevent116219 tevent116219;
typedef struct tkeyboardevent115375 tkeyboardevent115375;
typedef struct keyvaluepair122030 keyvaluepair122030;
typedef struct table126040 table126040;
typedef struct keyvaluepairseq126043 keyvaluepairseq126043;
typedef struct keyvaluepair126046 keyvaluepair126046;
typedef struct tfont123015 tfont123015;
typedef struct TY126059 TY126059;
typedef struct messagebox126018 messagebox126018;
typedef struct tkeysym115365 tkeysym115365;
typedef struct TNimObject TNimObject;
typedef struct tmousebuttonevent115383 tmousebuttonevent115383;
typedef struct tmousemotionevent115379 tmousemotionevent115379;
typedef struct tsurface116255 tsurface116255;
typedef struct tbasechunk26638 tbasechunk26638;
typedef struct tfreecell26630 tfreecell26630;
typedef struct tfont122221 tfont122221;
typedef struct tcolor116233 tcolor116233;
typedef struct tpixelformat116245 tpixelformat116245;
typedef struct trect116227 trect116227;
typedef struct tpalette116241 tpalette116241;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  app126002  {
tsurface123011* Display;
scenemanager126008* Manager;
controller126004* Ctl;
};
struct  tcell45135  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq45151  {
NI Len;
NI Cap;
tcell45135** D;
};
struct  tcellset45147  {
NI Counter;
NI Max;
tpagedesc45143* Head;
tpagedesc45143** Data;
};
typedef tsmallchunk26640* TY27422[512];
typedef ttrunk26613* ttrunkbuckets26615[256];
struct  tintset26617  {
ttrunkbuckets26615 Data;
};
struct  tmemregion27410  {
NI Minlargeobj;
NI Maxlargeobj;
TY27422 Freesmallchunks;
tllchunk27404* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26642* Freechunkslist;
tintset26617 Chunkstarts;
tavlnode27408* Root;
tavlnode27408* Deleted;
tavlnode27408* Last;
tavlnode27408* Freeavlnodes;
};
struct  tgcstat47214  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47216  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq45151 Zct;
tcellseq45151 Decstack;
tcellset45147 Cycleroots;
tcellseq45151 Tempstack;
NI Recgclock;
tmemregion27410 Region;
tgcstat47214 Stat;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
typedef N_CDECL_PTR(void, TY120720) (NCSTRING title, NCSTRING icon);
typedef NU8 TY116275[20];
struct  tevent116219  {
NU8 Kind;
TY116275 Pad;
};
typedef N_CDECL_PTR(NI, TY120214) (tevent116219* event);
struct keyvaluepair122030 {
NU8 Field0;
NI32 Field1;
NIM_BOOL Field2;
};
struct  table122024  {
keyvaluepairseq122027* Data;
NI Counter;
};
struct keyvaluepair126046 {
NU8 Field0;
NimStringDesc* Field1;
tfont123015* Field2;
};
struct  table126040  {
keyvaluepairseq126043* Data;
NI Counter;
};
struct  controller126004  {
tsurface123011* Display;
NIM_BOOL Shouldclose;
table122024 Keys;
table122024 Mods;
NI Mousex;
NI Mousey;
NIM_BOOL Mousedown;
table126040 Fonts;
TY126059* Messages;
};
struct  tkeysym115365  {
NU8 Scancode;
NI32 Sym;
NI32 Modifier;
NU16 Unicode;
};
struct  tkeyboardevent115375  {
NU8 Kind;
NU8 Which;
NU8 State;
tkeysym115365 Keysym;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  scenemanager126008  {
  TNimObject Sup;
controller126004* Ctl;
scene126006* Scene;
};
struct  tmousemotionevent115379  {
NU8 Kind;
NU8 Which;
NU8 State;
NU16 X;
NU16 Y;
NI16 Xrel;
NI16 Yrel;
};
typedef N_CDECL_PTR(NI32, TY119882) (void);
typedef N_CDECL_PTR(void, TY120345) (tsurface116255* screen, NI32 x, NI32 y, NI32 w, NI32 h);
struct  tsurface123011  {
NI W;
NI H;
tsurface116255* S;
};
typedef N_CDECL_PTR(void, TY119447) (void);
struct  scene126006  {
  TNimObject Sup;
controller126004* Ctl;
scenemanager126008* Manager;
};
typedef NI TY26620[16];
struct  tpagedesc45143  {
tpagedesc45143* Next;
NI Key;
TY26620 Bits;
};
struct  tbasechunk26638  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26640  {
  tbasechunk26638 Sup;
tsmallchunk26640* Next;
tsmallchunk26640* Prev;
tfreecell26630* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27404  {
NI Size;
NI Acc;
tllchunk27404* Next;
};
struct  tbigchunk26642  {
  tbasechunk26638 Sup;
tbigchunk26642* Next;
tbigchunk26642* Prev;
NI Align;
NF Data;
};
struct  ttrunk26613  {
ttrunk26613* Next;
NI Key;
TY26620 Bits;
};
typedef tavlnode27408* TY27414[2];
struct  tavlnode27408  {
TY27414 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tcolor116233  {
NU8 R;
NU8 G;
NU8 B;
NU8 Unused;
};
struct  tfont123015  {
tfont122221* F;
tcolor116233 Color;
};
struct  messagebox126018  {
NimStringDesc* Messagetext;
NI X;
NI Y;
NI Size;
tfont123015* Font;
tsurface123011* S;
NIM_BOOL Isvisible;
};
struct  tmousebuttonevent115383  {
NU8 Kind;
NU8 Which;
NU8 Button;
NU8 State;
NU16 X;
NU16 Y;
};
struct  trect116227  {
NI16 X;
NI16 Y;
NU16 W;
NU16 H;
};
struct  tsurface116255  {
NI32 Flags;
tpixelformat116245* Format;
int W;
int H;
NU16 Pitch;
void* Pixels;
int Offset;
void* Hwdata;
trect116227 Cliprect;
NI32 Unused1;
NI32 Locked;
void* Blitmap;
int Formatversion;
int Refcount;
};
struct  tfreecell26630  {
tfreecell26630* Next;
NI Zerofield;
};
struct  tfont122221  {
char dummy;
};
struct  tpixelformat116245  {
tpalette116241* Palette;
NU8 Bitsperpixel;
NU8 Bytesperpixel;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
NI32 Rmask;
NI32 Gmask;
NI32 Bmask;
NI32 Amask;
NI32 Colorkey;
NU8 Alpha;
};
struct  tpalette116241  {
NI Ncolors;
tcolor116233* Colors;
};
struct keyvaluepairseq122027 {
  TGenericSeq Sup;
  keyvaluepair122030 data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq126043 {
  TGenericSeq Sup;
  keyvaluepair126046 data[SEQ_DECL_SIZE];
};
struct TY126059 {
  TGenericSeq Sup;
  messagebox126018* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, init_131007)(app126002* self, scene126006* firstscene, NI32 width, NI32 height, NimStringDesc* title);
N_NIMCALL(tsurface123011*, newscreensurface_123313)(NI width, NI height);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell45135*, usrtocell_48846)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_50404)(tcell45135* c);
N_NOINLINE(void, addzct_48817)(tcellseq45151* s, tcell45135* c);
N_NIMCALL(controller126004*, newcontroller_130004)(tsurface123011* display);
N_NIMCALL(scenemanager126008*, newscenemanager_128116)(controller126004* ctl, scene126006* firstscene);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_51225)(tcell45135* c);
static N_INLINE(NIM_BOOL, canbecycleroot_48867)(tcell45135* c);
static N_INLINE(void, rtladdcycleroot_49629)(tcell45135* c);
N_NOINLINE(void, incl_45871)(tcellset45147* s, tcell45135* cell);
static N_INLINE(void, decref_50804)(tcell45135* c);
N_NIMCALL(void, HEX5BHEX5DHEX3D_131034)(table122024* t_131043, NI32 key_131047, NIM_BOOL val_131049);
N_NIMCALL(void, enlarge_131079)(table122024* t_131088);
N_NIMCALL(void, rawinsert_131149)(table122024* t_131158, keyvaluepairseq122027** data_131166, NI32 key_131170, NIM_BOOL val_131172);
N_NIMCALL(void, pump_131022)(app126002* self);
N_NIMCALL(void, close_130428)(controller126004* self);
N_NIMCALL(tkeyboardevent115375*, evkeyboard_117022)(tevent116219* event);
N_NIMCALL(void, keydown_128040)(scene126006* self, NI32 key, NI32 mods);
N_NIMCALL(void, mousedown_128054)(scene126006* self, tmousebuttonevent115383* event);
N_NIMCALL(tmousebuttonevent115383*, evmousebutton_117422)(tevent116219* event);
N_NIMCALL(tmousemotionevent115379*, evmousemotion_117222)(tevent116219* event);
N_NIMCALL(void, mousemotion_128068)(scene126006* self, tmousemotionevent115379* event);
N_NIMCALL(void, run_131356)(app126002* self);
N_NIMCALL(NIM_BOOL, closing_130438)(controller126004* self);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, update_128096)(scene126006* self, NI t, NI dt);
N_NIMCALL(void, draw_128081)(scene126006* self);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(void, draw_129064)(messagebox126018* self, tsurface123011* target);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(void, failedassertimpl_85425)(NimStringDesc* msg);
STRING_LITERAL(TMP665, "(system.len|system.len|system.len|system.len|system.len|...)(a)"
" (system.==|system.==|system.==|system.==|system.==|system.==|sy"
"stem.==|system.==|system.==|system.==|system.==|system.==|system"
".==|system.==|system.==|system.==|system.==|system.==|system.==|"
"system.==|...)\012    L seq modified while iterating over it", 312);
extern TFrame* frameptr_16242;
extern tgcheap47216 gch_47244;
extern TY120720 Dl_120719;
extern TY120214 Dl_120213;
extern TY119882 Dl_119881;
extern TY120345 Dl_120344;
extern TY119447 Dl_119446;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

static N_INLINE(tcell45135*, usrtocell_48846)(void* usr) {
	tcell45135* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell45135*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell45135))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50404)(tcell45135* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48817((&gch_47244.Zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell45135* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_48846(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell45135* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_48846((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50404(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NIM_BOOL, canbecycleroot_48867)(tcell45135* c) {
	NIM_BOOL result;
	nimfr("canbeCycleRoot", "gc.nim")
	result = 0;
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	result = !((((*(*c).Typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_49629)(tcell45135* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(189, "gc.nim");
	{
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		if (!!((((NI) ((NI)((*c).Refcount & 3))) == 3))) goto LA3;
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		(*c).Refcount = (NI)((NI)((*c).Refcount & -4) | 3);
		nimln(191, "gc.nim");
		incl_45871((&gch_47244.Cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_51225)(tcell45135* c) {
	nimfr("incRef", "gc.nim")
	nimln(216, "gc.nim");
	nimln(216, "gc.nim");
	(*c).Refcount = (NI)((NU32)((*c).Refcount) + (NU32)(8));
	nimln(219, "gc.nim");
	{
		NIM_BOOL LOC3;
		nimln(219, "gc.nim");
		LOC3 = 0;
		LOC3 = canbecycleroot_48867(c);
		if (!LOC3) goto LA4;
		nimln(220, "gc.nim");
		rtladdcycleroot_49629(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(void, decref_50804)(tcell45135* c) {
	nimfr("decRef", "gc.nim")
	nimln(206, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA3;
		nimln(207, "gc.nim");
		rtladdzct_50404(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(208, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_48867(c);
		if (!LOC6) goto LA7;
		nimln(211, "gc.nim");
		rtladdcycleroot_49629(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(244, "gc.nim");
	{
		tcell45135* LOC5;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_48846(src);
		incref_51225(LOC5);
	}
	LA3: ;
	nimln(245, "gc.nim");
	{
		tcell45135* LOC10;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_48846((*dest));
		decref_50804(LOC10);
	}
	LA8: ;
	nimln(246, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, init_131007)(app126002* self, scene126006* firstscene, NI32 width, NI32 height, NimStringDesc* title) {
	nimfr("init", "app.nim")
	nimln(12, "app.nim");
	asgnRefNoCycle((void**) (&(*self).Display), newscreensurface_123313(((NI) (width)), ((NI) (height))));
	nimln(13, "app.nim");
	asgnRefNoCycle((void**) (&(*self).Ctl), newcontroller_130004((*self).Display));
	nimln(14, "app.nim");
	asgnRef((void**) (&(*self).Manager), newscenemanager_128116((*self).Ctl, firstscene));
	nimln(15, "app.nim");
	Dl_120719(title->data, NIM_NIL);
	popFrame();
}

N_NIMCALL(void, pump_131022)(app126002* self) {
	tevent116219 event;
	nimfr("pump", "app.nim")
	memset((void*)(&event), 0, sizeof(event));
	{
		nimln(19, "app.nim");
		while (1) {
			NI LOC3;
			nimln(19, "app.nim");
			nimln(19, "app.nim");
			LOC3 = 0;
			LOC3 = Dl_120213((&event));
			if (!(LOC3 == 1)) goto LA2;
			nimln(20, "app.nim");
			switch (event.Kind) {
			case ((NU8) 12):
			{
				nimln(22, "app.nim");
				close_130428((*self).Ctl);
				nimln(23, "app.nim");
				goto LA1;
			}
			break;
			case ((NU8) 2):
			{
				tkeyboardevent115375* e;
				nimln(25, "app.nim");
				e = evkeyboard_117022((&event));
				nimln(26, "app.nim");
				HEX5BHEX5DHEX3D_131034((&(*(*self).Ctl).Keys), (*e).Keysym.Sym, NIM_TRUE);
				nimln(27, "app.nim");
				HEX5BHEX5DHEX3D_131034((&(*(*self).Ctl).Mods), (*e).Keysym.Modifier, NIM_TRUE);
				nimln(28, "app.nim");
				keydown_128040((*(*self).Manager).Scene, (*e).Keysym.Sym, (*e).Keysym.Modifier);
			}
			break;
			case ((NU8) 3):
			{
				tkeyboardevent115375* e;
				nimln(30, "app.nim");
				e = evkeyboard_117022((&event));
				nimln(31, "app.nim");
				HEX5BHEX5DHEX3D_131034((&(*(*self).Ctl).Keys), (*e).Keysym.Sym, NIM_FALSE);
				nimln(32, "app.nim");
				HEX5BHEX5DHEX3D_131034((&(*(*self).Ctl).Mods), (*e).Keysym.Modifier, NIM_FALSE);
			}
			break;
			case ((NU8) 5):
			{
				tmousebuttonevent115383* LOC8;
				nimln(34, "app.nim");
				(*(*self).Ctl).Mousedown = NIM_TRUE;
				nimln(35, "app.nim");
				nimln(35, "app.nim");
				LOC8 = 0;
				LOC8 = evmousebutton_117422((&event));
				mousedown_128054((*(*self).Manager).Scene, LOC8);
			}
			break;
			case ((NU8) 6):
			{
				nimln(37, "app.nim");
				(*(*self).Ctl).Mousedown = NIM_FALSE;
			}
			break;
			case ((NU8) 4):
			{
				tmousemotionevent115379* e;
				nimln(39, "app.nim");
				e = evmousemotion_117222((&event));
				nimln(40, "app.nim");
				(*(*self).Ctl).Mousex = ((NI) ((*e).X));
				nimln(41, "app.nim");
				(*(*self).Ctl).Mousey = ((NI) ((*e).Y));
				nimln(42, "app.nim");
				mousemotion_128068((*(*self).Manager).Scene, e);
			}
			break;
			default:
			{
			}
			break;
			}
		} LA2: ;
	} LA1: ;
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) - (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU32) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, run_131356)(app126002* self) {
	NI32 currenttime;
	NI32 oldtime;
	nimfr("run", "app.nim")
	nimln(47, "app.nim");
	currenttime = Dl_119881();
	nimln(48, "app.nim");
	oldtime = currenttime;
	{
		nimln(50, "app.nim");
		while (1) {
			NIM_BOOL LOC3;
			NI32 t;
			NI32 dt;
			NI32 TMP664;
			nimln(50, "app.nim");
			nimln(50, "app.nim");
			LOC3 = 0;
			LOC3 = closing_130438((*self).Ctl);
			if (!!(LOC3)) goto LA2;
			nimln(51, "app.nim");
			oldtime = currenttime;
			nimln(52, "app.nim");
			t = Dl_119881();
			nimln(53, "app.nim");
			nimln(53, "app.nim");
			TMP664 = subInt(t, oldtime);
			dt = (NI32)(TMP664);
			nimln(54, "app.nim");
			pump_131022(self);
			nimln(55, "app.nim");
			update_128096((*(*self).Manager).Scene, ((NI) (t)), ((NI) (dt)));
			nimln(56, "app.nim");
			draw_128081((*(*self).Manager).Scene);
			{
				messagebox126018* msgbox_131622;
				TY126059* HEX3Atmp_131625;
				NI i_131628;
				NI l_131630;
				msgbox_131622 = 0;
				HEX3Atmp_131625 = 0;
				nimln(57, "app.nim");
				HEX3Atmp_131625 = (*(*self).Ctl).Messages;
				nimln(2986, "system.nim");
				i_131628 = 0;
				nimln(2987, "system.nim");
				nimln(2987, "system.nim");
				l_131630 = HEX3Atmp_131625->Sup.len;
				{
					nimln(2988, "system.nim");
					while (1) {
						nimln(2988, "system.nim");
						if (!(i_131628 < l_131630)) goto LA6;
						nimln(2989, "system.nim");
						if ((NU)(i_131628) >= (NU)(HEX3Atmp_131625->Sup.len)) raiseIndexError();
						msgbox_131622 = HEX3Atmp_131625->data[i_131628];
						nimln(58, "app.nim");
						draw_129064(msgbox_131622, (*self).Display);
						nimln(2990, "system.nim");
						i_131628 = addInt(i_131628, 1);
						nimln(2991, "system.nim");
						{
							nimln(2991, "system.nim");
							nimln(2991, "system.nim");
							nimln(2991, "system.nim");
							if (!!((HEX3Atmp_131625->Sup.len == l_131630))) goto LA9;
							nimln(2991, "system.nim");
							failedassertimpl_85425(((NimStringDesc*) &TMP665));
						}
						LA9: ;
					} LA6: ;
				}
			}
			nimln(59, "app.nim");
			Dl_120344((*(*self).Display).S, ((NI32) 0), ((NI32) 0), ((NI32) ((*(*self).Display).W)), ((NI32) ((*(*self).Display).H)));
		} LA2: ;
	}
	nimln(60, "app.nim");
	Dl_119446();
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, HEX00_appInit)(void) {
	nimfr("app", "app.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_appDatInit)(void) {
}

