/* Generated by Nim Compiler v0.10.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/jsudlow/Nim/lib -o .nimcache/controller.o .nimcache/controller.c */
#define NIM_INTBITS 32
#include "nimbase.h"
typedef struct controller126004 controller126004;
typedef struct TY126059 TY126059;
typedef struct messagebox126018 messagebox126018;
typedef struct TGenericSeq TGenericSeq;
typedef struct table122024 table122024;
typedef struct keyvaluepairseq122027 keyvaluepairseq122027;
typedef struct keyvaluepair122030 keyvaluepair122030;
typedef struct table126040 table126040;
typedef struct keyvaluepairseq126043 keyvaluepairseq126043;
typedef struct keyvaluepair126046 keyvaluepair126046;
typedef struct NimStringDesc NimStringDesc;
typedef struct tfont123015 tfont123015;
typedef struct tsurface123011 tsurface123011;
typedef struct tcell45135 tcell45135;
typedef struct TNimType TNimType;
typedef struct tcellseq45151 tcellseq45151;
typedef struct tgcheap47216 tgcheap47216;
typedef struct tcellset45147 tcellset45147;
typedef struct tpagedesc45143 tpagedesc45143;
typedef struct tmemregion27410 tmemregion27410;
typedef struct tsmallchunk26640 tsmallchunk26640;
typedef struct tllchunk27404 tllchunk27404;
typedef struct tbigchunk26642 tbigchunk26642;
typedef struct tintset26617 tintset26617;
typedef struct ttrunk26613 ttrunk26613;
typedef struct tavlnode27408 tavlnode27408;
typedef struct tgcstat47214 tgcstat47214;
typedef struct tfont122221 tfont122221;
typedef struct tcolor116233 tcolor116233;
typedef struct tsurface116255 tsurface116255;
typedef struct TNimNode TNimNode;
typedef struct tbasechunk26638 tbasechunk26638;
typedef struct tfreecell26630 tfreecell26630;
typedef struct tpixelformat116245 tpixelformat116245;
typedef struct trect116227 trect116227;
typedef struct tpalette116241 tpalette116241;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct keyvaluepair122030 {
NU8 Field0;
NI32 Field1;
NIM_BOOL Field2;
};
struct  table122024  {
keyvaluepairseq122027* Data;
NI Counter;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct keyvaluepair126046 {
NU8 Field0;
NimStringDesc* Field1;
tfont123015* Field2;
};
struct  table126040  {
keyvaluepairseq126043* Data;
NI Counter;
};
struct  controller126004  {
tsurface123011* Display;
NIM_BOOL Shouldclose;
table122024 Keys;
table122024 Mods;
NI Mousex;
NI Mousey;
NIM_BOOL Mousedown;
table126040 Fonts;
TY126059* Messages;
};
struct  tcell45135  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq45151  {
NI Len;
NI Cap;
tcell45135** D;
};
struct  tcellset45147  {
NI Counter;
NI Max;
tpagedesc45143* Head;
tpagedesc45143** Data;
};
typedef tsmallchunk26640* TY27422[512];
typedef ttrunk26613* ttrunkbuckets26615[256];
struct  tintset26617  {
ttrunkbuckets26615 Data;
};
struct  tmemregion27410  {
NI Minlargeobj;
NI Maxlargeobj;
TY27422 Freesmallchunks;
tllchunk27404* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26642* Freechunkslist;
tintset26617 Chunkstarts;
tavlnode27408* Root;
tavlnode27408* Deleted;
tavlnode27408* Last;
tavlnode27408* Freeavlnodes;
};
struct  tgcstat47214  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47216  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq45151 Zct;
tcellseq45151 Decstack;
tcellset45147 Cycleroots;
tcellseq45151 Tempstack;
NI Recgclock;
tmemregion27410 Region;
tgcstat47214 Stat;
};
struct  messagebox126018  {
NimStringDesc* Messagetext;
NI X;
NI Y;
NI Size;
tfont123015* Font;
tsurface123011* S;
NIM_BOOL Isvisible;
};
struct  tcolor116233  {
NU8 R;
NU8 G;
NU8 B;
NU8 Unused;
};
struct  tfont123015  {
tfont122221* F;
tcolor116233 Color;
};
struct  tsurface123011  {
NI W;
NI H;
tsurface116255* S;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
typedef NI TY26620[16];
struct  tpagedesc45143  {
tpagedesc45143* Next;
NI Key;
TY26620 Bits;
};
struct  tbasechunk26638  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26640  {
  tbasechunk26638 Sup;
tsmallchunk26640* Next;
tsmallchunk26640* Prev;
tfreecell26630* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27404  {
NI Size;
NI Acc;
tllchunk27404* Next;
};
struct  tbigchunk26642  {
  tbasechunk26638 Sup;
tbigchunk26642* Next;
tbigchunk26642* Prev;
NI Align;
NF Data;
};
struct  ttrunk26613  {
ttrunk26613* Next;
NI Key;
TY26620 Bits;
};
typedef tavlnode27408* TY27414[2];
struct  tavlnode27408  {
TY27414 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfont122221  {
char dummy;
};
struct  trect116227  {
NI16 X;
NI16 Y;
NU16 W;
NU16 H;
};
struct  tsurface116255  {
NI32 Flags;
tpixelformat116245* Format;
int W;
int H;
NU16 Pitch;
void* Pixels;
int Offset;
void* Hwdata;
trect116227 Cliprect;
NI32 Unused1;
NI32 Locked;
void* Blitmap;
int Formatversion;
int Refcount;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tfreecell26630  {
tfreecell26630* Next;
NI Zerofield;
};
struct  tpixelformat116245  {
tpalette116241* Palette;
NU8 Bitsperpixel;
NU8 Bytesperpixel;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
NI32 Rmask;
NI32 Gmask;
NI32 Bmask;
NI32 Amask;
NI32 Colorkey;
NU8 Alpha;
};
struct  tpalette116241  {
NI Ncolors;
tcolor116233* Colors;
};
struct TY126059 {
  TGenericSeq Sup;
  messagebox126018* data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq122027 {
  TGenericSeq Sup;
  keyvaluepair122030 data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq126043 {
  TGenericSeq Sup;
  keyvaluepair126046 data[SEQ_DECL_SIZE];
};
N_NIMCALL(controller126004*, new_130012)(void);
N_NIMCALL(TY126059*, newseq_130041)(NI len_130045);
N_NIMCALL(void, inittable_130090)(NI initialsize_130095, table122024* Result);
N_NIMCALL(void, inittable_130232)(NI initialsize_130237, table126040* Result);
N_NIMCALL(controller126004*, newcontroller_130004)(tsurface123011* display);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell45135*, usrtocell_48846)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_50404)(tcell45135* c);
N_NOINLINE(void, addzct_48817)(tcellseq45151* s, tcell45135* c);
N_NIMCALL(void, close_130428)(controller126004* self);
N_NIMCALL(NIM_BOOL, closing_130438)(controller126004* self);
N_NIMCALL(NIM_BOOL, hasplayerwon_130449)(controller126004* self);
N_NIMCALL(void, HEX5BHEX5DHEX3D_130471)(table126040* t_130480, NimStringDesc* key_130484, tfont123015* val_130486);
N_NIMCALL(NI, rawget_130489)(table126040 t_130496, NimStringDesc* key_130499);
N_NIMCALL(void, enlarge_130546)(table126040* t_130555);
N_NIMCALL(void, rawinsert_130616)(table126040* t_130625, keyvaluepairseq126043** data_130633, NimStringDesc* key_130637, tfont123015* val_130639);
N_NIMCALL(void, newfont_130460)(controller126004* self, NimStringDesc* name, NimStringDesc* fontfile, NI size, NI color);
N_NIMCALL(tfont123015*, newfont_123216)(NimStringDesc* name, NI size, NI color);
N_NIMCALL(tfont123015*, HEX5BHEX5D_130761)(table126040 t_130768, NimStringDesc* key_130771);
N_NIMCALL(messagebox126018*, addmessage_130749)(controller126004* self, NimStringDesc* msg, NimStringDesc* fontname, NI x, NI y);
N_NIMCALL(messagebox126018*, newmessagebox_129017)(NimStringDesc* messagetext, NI x, NI y, tfont123015* font);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
extern TFrame* frameptr_16242;
extern tgcheap47216 gch_47244;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

static N_INLINE(tcell45135*, usrtocell_48846)(void* usr) {
	tcell45135* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell45135*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell45135))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50404)(tcell45135* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48817((&gch_47244.Zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell45135* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_48846(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell45135* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_48846((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50404(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(controller126004*, newcontroller_130004)(tsurface123011* display) {
	controller126004* result;
	nimfr("newController", "controller.nim")
	result = 0;
	nimln(4, "controller.nim");
	result = new_130012();
	nimln(5, "controller.nim");
	asgnRefNoCycle((void**) (&(*result).Messages), newseq_130041(0));
	nimln(6, "controller.nim");
	asgnRefNoCycle((void**) (&(*result).Display), display);
	nimln(7, "controller.nim");
	(*result).Shouldclose = NIM_FALSE;
	nimln(8, "controller.nim");
	inittable_130090(64, (&(*result).Keys));
	nimln(9, "controller.nim");
	inittable_130090(64, (&(*result).Mods));
	nimln(10, "controller.nim");
	inittable_130232(64, (&(*result).Fonts));
	popFrame();
	return result;
}

N_NIMCALL(void, close_130428)(controller126004* self) {
	nimfr("close", "controller.nim")
	nimln(13, "controller.nim");
	(*self).Shouldclose = NIM_TRUE;
	popFrame();
}

N_NIMCALL(NIM_BOOL, closing_130438)(controller126004* self) {
	NIM_BOOL result;
	nimfr("closing", "controller.nim")
	result = 0;
	nimln(16, "controller.nim");
	result = (*self).Shouldclose;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, hasplayerwon_130449)(controller126004* self) {
	NIM_BOOL result;
	nimfr("hasPlayerWon", "controller.nim")
	result = 0;
	nimln(20, "controller.nim");
	nimln(20, "controller.nim");
	result = NIM_TRUE;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, newfont_130460)(controller126004* self, NimStringDesc* name, NimStringDesc* fontfile, NI size, NI color) {
	tfont123015* LOC1;
	nimfr("newFont", "controller.nim")
	nimln(23, "controller.nim");
	nimln(23, "controller.nim");
	LOC1 = 0;
	LOC1 = newfont_123216(fontfile, size, color);
	HEX5BHEX5DHEX3D_130471((&(*self).Fonts), name, LOC1);
	popFrame();
}

N_NIMCALL(messagebox126018*, addmessage_130749)(controller126004* self, NimStringDesc* msg, NimStringDesc* fontname, NI x, NI y) {
	messagebox126018* result;
	tfont123015* font;
	nimfr("addMessage", "controller.nim")
	result = 0;
	nimln(26, "controller.nim");
	font = HEX5BHEX5D_130761((*self).Fonts, fontname);
	nimln(27, "controller.nim");
	result = newmessagebox_129017(msg, x, y, font);
	nimln(28, "controller.nim");
	(*self).Messages = (TY126059*) incrSeq(&((*self).Messages)->Sup, sizeof(messagebox126018*));
	asgnRefNoCycle((void**) (&(*self).Messages->data[(*self).Messages->Sup.len-1]), result);
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_controllerInit)(void) {
	nimfr("controller", "controller.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_controllerDatInit)(void) {
}

