/* Generated by Nim Compiler v0.10.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/jsudlow/Nim/lib -o .nimcache/magic.o .nimcache/magic.c */
#define NIM_INTBITS 32
#include "nimbase.h"
typedef struct table122024 table122024;
typedef struct keyvaluepairseq122027 keyvaluepairseq122027;
typedef struct keyvaluepair122030 keyvaluepair122030;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct scenemanager126008 scenemanager126008;
typedef struct TNimObject TNimObject;
typedef struct controller126004 controller126004;
typedef struct scene126006 scene126006;
typedef struct tsurface123011 tsurface123011;
typedef struct table126040 table126040;
typedef struct keyvaluepairseq126043 keyvaluepairseq126043;
typedef struct keyvaluepair126046 keyvaluepair126046;
typedef struct NimStringDesc NimStringDesc;
typedef struct tfont123015 tfont123015;
typedef struct TY126059 TY126059;
typedef struct messagebox126018 messagebox126018;
typedef struct gamescene126010 gamescene126010;
typedef struct hoversystem126014 hoversystem126014;
typedef struct clicksystem126016 clicksystem126016;
typedef struct menuscene126012 menuscene126012;
typedef struct app126002 app126002;
typedef struct tsurface116255 tsurface116255;
typedef struct tfont122221 tfont122221;
typedef struct tcolor116233 tcolor116233;
typedef struct tpixelformat116245 tpixelformat116245;
typedef struct trect116227 trect116227;
typedef struct tpalette116241 tpalette116241;
struct keyvaluepair122030 {
NU8 Field0;
NI32 Field1;
NIM_BOOL Field2;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  table122024  {
keyvaluepairseq122027* Data;
NI Counter;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  scenemanager126008  {
  TNimObject Sup;
controller126004* Ctl;
scene126006* Scene;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct keyvaluepair126046 {
NU8 Field0;
NimStringDesc* Field1;
tfont123015* Field2;
};
struct  table126040  {
keyvaluepairseq126043* Data;
NI Counter;
};
struct  controller126004  {
tsurface123011* Display;
NIM_BOOL Shouldclose;
table122024 Keys;
table122024 Mods;
NI Mousex;
NI Mousey;
NIM_BOOL Mousedown;
table126040 Fonts;
TY126059* Messages;
};
struct  messagebox126018  {
NimStringDesc* Messagetext;
NI X;
NI Y;
NI Size;
tfont123015* Font;
tsurface123011* S;
NIM_BOOL Isvisible;
};
struct  scene126006  {
  TNimObject Sup;
controller126004* Ctl;
scenemanager126008* Manager;
};
struct  gamescene126010  {
  scene126006 Sup;
hoversystem126014* Hoversystem;
clicksystem126016* Clicksystem;
NIM_BOOL Haswon;
};
struct  hoversystem126014  {
gamescene126010* Scene;
NI I;
NI K;
};
struct  clicksystem126016  {
gamescene126010* Scene;
};
struct  menuscene126012  {
  scene126006 Sup;
messagebox126018* Playmsg;
messagebox126018* Quitmsg;
};
struct  app126002  {
tsurface123011* Display;
scenemanager126008* Manager;
controller126004* Ctl;
};
struct  tsurface123011  {
NI W;
NI H;
tsurface116255* S;
};
struct  tcolor116233  {
NU8 R;
NU8 G;
NU8 B;
NU8 Unused;
};
struct  tfont123015  {
tfont122221* F;
tcolor116233 Color;
};
struct  trect116227  {
NI16 X;
NI16 Y;
NU16 W;
NU16 H;
};
struct  tsurface116255  {
NI32 Flags;
tpixelformat116245* Format;
int W;
int H;
NU16 Pitch;
void* Pixels;
int Offset;
void* Hwdata;
trect116227 Cliprect;
NI32 Unused1;
NI32 Locked;
void* Blitmap;
int Formatversion;
int Refcount;
};
struct  tfont122221  {
char dummy;
};
struct  tpixelformat116245  {
tpalette116241* Palette;
NU8 Bitsperpixel;
NU8 Bytesperpixel;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
NI32 Rmask;
NI32 Gmask;
NI32 Bmask;
NI32 Amask;
NI32 Colorkey;
NU8 Alpha;
};
struct  tpalette116241  {
NI Ncolors;
tcolor116233* Colors;
};
struct keyvaluepairseq122027 {
  TGenericSeq Sup;
  keyvaluepair122030 data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq126043 {
  TGenericSeq Sup;
  keyvaluepair126046 data[SEQ_DECL_SIZE];
};
struct TY126059 {
  TGenericSeq Sup;
  messagebox126018* data[SEQ_DECL_SIZE];
};
N_NIMCALL(NIM_BOOL, haskey_122049)(table122024 t_122056, NI32 key_122059);
N_NIMCALL(NI, rawget_122063)(table122024 t_122070, NI32 key_122073);
N_NIMCALL(NIM_BOOL, HEX5BHEX5D_122110)(table122024 t_122117, NI32 key_122120);
N_NIMCALL(NIM_BOOL, pressed_122042)(table122024 self, NI32 key);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP647)(void* p, NI op);
N_NIMCALL(void, TMP648)(void* p, NI op);
N_NIMCALL(void, TMP649)(void* p, NI op);
N_NIMCALL(void, TMP651)(void* p, NI op);
N_NIMCALL(void, TMP652)(void* p, NI op);
N_NIMCALL(void, TMP674)(void* p, NI op);
N_NIMCALL(void, TMP675)(void* p, NI op);
N_NIMCALL(void, TMP676)(void* p, NI op);
N_NIMCALL(void, TMP762)(void* p, NI op);
N_NIMCALL(void, TMP764)(void* p, NI op);
extern TFrame* frameptr_16242;
extern TNimType NTI3211; /* RootObj */
TNimType NTI126008; /* SceneManager */
TNimType NTI126004; /* Controller */
extern TNimType NTI123009; /* PSurface */
extern TNimType NTI138; /* bool */
extern TNimType NTI122024; /* Table */
extern TNimType NTI108; /* int */
extern TNimType NTI126040; /* Table */
TNimType NTI126018; /* MessageBox */
extern TNimType NTI149; /* string */
extern TNimType NTI123017; /* PFont */
TNimType NTI126060; /* ref MessageBox */
TNimType NTI126059; /* seq[ref MessageBox] */
TNimType NTI126066; /* ref Controller */
TNimType NTI126006; /* Scene */
TNimType NTI128006; /* ref Scene */
TNimType NTI128103; /* ref SceneManager */
TNimType NTI126010; /* GameScene */
TNimType NTI126014; /* HoverSystem */
TNimType NTI126070; /* ref HoverSystem */
TNimType NTI126016; /* ClickSystem */
TNimType NTI126072; /* ref ClickSystem */
TNimType NTI132053; /* ref GameScene */
TNimType NTI126012; /* MenuScene */
TNimType NTI132020; /* ref MenuScene */
TNimType NTI126002; /* App */
TNimType NTI131009; /* ref App */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

N_NIMCALL(NIM_BOOL, pressed_122042)(table122024 self, NI32 key) {
	NIM_BOOL result;
	nimfr("pressed", "utils.nim")
	result = 0;
	nimln(12, "utils.nim");
	{
		NIM_BOOL LOC3;
		nimln(12, "utils.nim");
		nimln(12, "utils.nim");
		LOC3 = 0;
		LOC3 = haskey_122049(self, key);
		if (!!(LOC3)) goto LA4;
		nimln(13, "utils.nim");
		nimln(13, "utils.nim");
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA4: ;
	nimln(14, "utils.nim");
	nimln(14, "utils.nim");
	result = HEX5BHEX5D_122110(self, key);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}
N_NIMCALL(void, TMP647)(void* p, NI op) {
	messagebox126018* a;
	a = (messagebox126018*)p;
	nimGCvisit((void*)(*a).Messagetext, op);
	nimGCvisit((void*)(*a).Font, op);
	nimGCvisit((void*)(*a).S, op);
}
N_NIMCALL(void, TMP648)(void* p, NI op) {
	TY126059* a;
	NI LOC1;
	a = (TY126059*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);
	}
}
N_NIMCALL(void, TMP649)(void* p, NI op) {
	controller126004* a;
	a = (controller126004*)p;
	nimGCvisit((void*)(*a).Display, op);
	nimGCvisit((void*)(*a).Keys.Data, op);
	nimGCvisit((void*)(*a).Mods.Data, op);
	nimGCvisit((void*)(*a).Fonts.Data, op);
	nimGCvisit((void*)(*a).Messages, op);
}
N_NIMCALL(void, TMP651)(void* p, NI op) {
	scene126006* a;
	a = (scene126006*)p;
	nimGCvisit((void*)(*a).Ctl, op);
	nimGCvisit((void*)(*a).Manager, op);
}
N_NIMCALL(void, TMP652)(void* p, NI op) {
	scenemanager126008* a;
	a = (scenemanager126008*)p;
	nimGCvisit((void*)(*a).Ctl, op);
	nimGCvisit((void*)(*a).Scene, op);
}
N_NIMCALL(void, TMP674)(void* p, NI op) {
	hoversystem126014* a;
	a = (hoversystem126014*)p;
	nimGCvisit((void*)(*a).Scene, op);
}
N_NIMCALL(void, TMP675)(void* p, NI op) {
	clicksystem126016* a;
	a = (clicksystem126016*)p;
	nimGCvisit((void*)(*a).Scene, op);
}
N_NIMCALL(void, TMP676)(void* p, NI op) {
	gamescene126010* a;
	a = (gamescene126010*)p;
	nimGCvisit((void*)(*a).Sup.Ctl, op);
	nimGCvisit((void*)(*a).Sup.Manager, op);
	nimGCvisit((void*)(*a).Hoversystem, op);
	nimGCvisit((void*)(*a).Clicksystem, op);
}
N_NIMCALL(void, TMP762)(void* p, NI op) {
	menuscene126012* a;
	a = (menuscene126012*)p;
	nimGCvisit((void*)(*a).Sup.Ctl, op);
	nimGCvisit((void*)(*a).Sup.Manager, op);
	nimGCvisit((void*)(*a).Playmsg, op);
	nimGCvisit((void*)(*a).Quitmsg, op);
}
N_NIMCALL(void, TMP764)(void* p, NI op) {
	app126002* a;
	a = (app126002*)p;
	nimGCvisit((void*)(*a).Display, op);
	nimGCvisit((void*)(*a).Manager, op);
	nimGCvisit((void*)(*a).Ctl, op);
}
NIM_EXTERNC N_NOINLINE(void, HEX00_magicInit)(void) {
	nimfr("magic", "magic.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_magicDatInit)(void) {
static TNimNode* TMP635[2];
static TNimNode* TMP636[9];
static TNimNode* TMP646[7];
static TNimNode* TMP650[2];
static TNimNode* TMP672[3];
static TNimNode* TMP673[3];
static TNimNode* TMP761[2];
static TNimNode* TMP763[3];
static TNimNode TMP131[40];
NTI126008.size = sizeof(scenemanager126008);
NTI126008.kind = 17;
NTI126008.base = (&NTI3211);
TMP635[0] = &TMP131[1];
NTI126004.size = sizeof(controller126004);
NTI126004.kind = 18;
NTI126004.base = 0;
NTI126004.flags = 2;
TMP636[0] = &TMP131[3];
TMP131[3].kind = 1;
TMP131[3].offset = offsetof(controller126004, Display);
TMP131[3].typ = (&NTI123009);
TMP131[3].name = "display";
TMP636[1] = &TMP131[4];
TMP131[4].kind = 1;
TMP131[4].offset = offsetof(controller126004, Shouldclose);
TMP131[4].typ = (&NTI138);
TMP131[4].name = "should_close";
TMP636[2] = &TMP131[5];
TMP131[5].kind = 1;
TMP131[5].offset = offsetof(controller126004, Keys);
TMP131[5].typ = (&NTI122024);
TMP131[5].name = "keys";
TMP636[3] = &TMP131[6];
TMP131[6].kind = 1;
TMP131[6].offset = offsetof(controller126004, Mods);
TMP131[6].typ = (&NTI122024);
TMP131[6].name = "mods";
TMP636[4] = &TMP131[7];
TMP131[7].kind = 1;
TMP131[7].offset = offsetof(controller126004, Mousex);
TMP131[7].typ = (&NTI108);
TMP131[7].name = "mouseX";
TMP636[5] = &TMP131[8];
TMP131[8].kind = 1;
TMP131[8].offset = offsetof(controller126004, Mousey);
TMP131[8].typ = (&NTI108);
TMP131[8].name = "mouseY";
TMP636[6] = &TMP131[9];
TMP131[9].kind = 1;
TMP131[9].offset = offsetof(controller126004, Mousedown);
TMP131[9].typ = (&NTI138);
TMP131[9].name = "mouseDown";
TMP636[7] = &TMP131[10];
TMP131[10].kind = 1;
TMP131[10].offset = offsetof(controller126004, Fonts);
TMP131[10].typ = (&NTI126040);
TMP131[10].name = "fonts";
TMP636[8] = &TMP131[11];
NTI126018.size = sizeof(messagebox126018);
NTI126018.kind = 18;
NTI126018.base = 0;
NTI126018.flags = 2;
TMP646[0] = &TMP131[13];
TMP131[13].kind = 1;
TMP131[13].offset = offsetof(messagebox126018, Messagetext);
TMP131[13].typ = (&NTI149);
TMP131[13].name = "messageText";
TMP646[1] = &TMP131[14];
TMP131[14].kind = 1;
TMP131[14].offset = offsetof(messagebox126018, X);
TMP131[14].typ = (&NTI108);
TMP131[14].name = "x";
TMP646[2] = &TMP131[15];
TMP131[15].kind = 1;
TMP131[15].offset = offsetof(messagebox126018, Y);
TMP131[15].typ = (&NTI108);
TMP131[15].name = "y";
TMP646[3] = &TMP131[16];
TMP131[16].kind = 1;
TMP131[16].offset = offsetof(messagebox126018, Size);
TMP131[16].typ = (&NTI108);
TMP131[16].name = "size";
TMP646[4] = &TMP131[17];
TMP131[17].kind = 1;
TMP131[17].offset = offsetof(messagebox126018, Font);
TMP131[17].typ = (&NTI123017);
TMP131[17].name = "font";
TMP646[5] = &TMP131[18];
TMP131[18].kind = 1;
TMP131[18].offset = offsetof(messagebox126018, S);
TMP131[18].typ = (&NTI123009);
TMP131[18].name = "s";
TMP646[6] = &TMP131[19];
TMP131[19].kind = 1;
TMP131[19].offset = offsetof(messagebox126018, Isvisible);
TMP131[19].typ = (&NTI138);
TMP131[19].name = "isVisible";
TMP131[12].len = 7; TMP131[12].kind = 2; TMP131[12].sons = &TMP646[0];
NTI126018.node = &TMP131[12];
NTI126060.size = sizeof(messagebox126018*);
NTI126060.kind = 22;
NTI126060.base = (&NTI126018);
NTI126060.flags = 2;
NTI126060.marker = TMP647;
NTI126059.size = sizeof(TY126059*);
NTI126059.kind = 24;
NTI126059.base = (&NTI126060);
NTI126059.flags = 2;
NTI126059.marker = TMP648;
TMP131[11].kind = 1;
TMP131[11].offset = offsetof(controller126004, Messages);
TMP131[11].typ = (&NTI126059);
TMP131[11].name = "messages";
TMP131[2].len = 9; TMP131[2].kind = 2; TMP131[2].sons = &TMP636[0];
NTI126004.node = &TMP131[2];
NTI126066.size = sizeof(controller126004*);
NTI126066.kind = 22;
NTI126066.base = (&NTI126004);
NTI126066.flags = 2;
NTI126066.marker = TMP649;
TMP131[1].kind = 1;
TMP131[1].offset = offsetof(scenemanager126008, Ctl);
TMP131[1].typ = (&NTI126066);
TMP131[1].name = "ctl";
TMP635[1] = &TMP131[20];
NTI126006.size = sizeof(scene126006);
NTI126006.kind = 17;
NTI126006.base = (&NTI3211);
TMP650[0] = &TMP131[22];
TMP131[22].kind = 1;
TMP131[22].offset = offsetof(scene126006, Ctl);
TMP131[22].typ = (&NTI126066);
TMP131[22].name = "ctl";
TMP650[1] = &TMP131[23];
TMP131[23].kind = 1;
TMP131[23].offset = offsetof(scene126006, Manager);
TMP131[23].typ = (&NTI128103);
TMP131[23].name = "manager";
TMP131[21].len = 2; TMP131[21].kind = 2; TMP131[21].sons = &TMP650[0];
NTI126006.node = &TMP131[21];
NTI128006.size = sizeof(scene126006*);
NTI128006.kind = 22;
NTI128006.base = (&NTI126006);
NTI128006.marker = TMP651;
TMP131[20].kind = 1;
TMP131[20].offset = offsetof(scenemanager126008, Scene);
TMP131[20].typ = (&NTI128006);
TMP131[20].name = "scene";
TMP131[0].len = 2; TMP131[0].kind = 2; TMP131[0].sons = &TMP635[0];
NTI126008.node = &TMP131[0];
NTI128103.size = sizeof(scenemanager126008*);
NTI128103.kind = 22;
NTI128103.base = (&NTI126008);
NTI128103.marker = TMP652;
NTI126010.size = sizeof(gamescene126010);
NTI126010.kind = 17;
NTI126010.base = (&NTI126006);
TMP672[0] = &TMP131[25];
NTI126014.size = sizeof(hoversystem126014);
NTI126014.kind = 18;
NTI126014.base = 0;
TMP673[0] = &TMP131[27];
TMP131[27].kind = 1;
TMP131[27].offset = offsetof(hoversystem126014, Scene);
TMP131[27].typ = (&NTI132053);
TMP131[27].name = "scene";
TMP673[1] = &TMP131[28];
TMP131[28].kind = 1;
TMP131[28].offset = offsetof(hoversystem126014, I);
TMP131[28].typ = (&NTI108);
TMP131[28].name = "i";
TMP673[2] = &TMP131[29];
TMP131[29].kind = 1;
TMP131[29].offset = offsetof(hoversystem126014, K);
TMP131[29].typ = (&NTI108);
TMP131[29].name = "k";
TMP131[26].len = 3; TMP131[26].kind = 2; TMP131[26].sons = &TMP673[0];
NTI126014.node = &TMP131[26];
NTI126070.size = sizeof(hoversystem126014*);
NTI126070.kind = 22;
NTI126070.base = (&NTI126014);
NTI126070.marker = TMP674;
TMP131[25].kind = 1;
TMP131[25].offset = offsetof(gamescene126010, Hoversystem);
TMP131[25].typ = (&NTI126070);
TMP131[25].name = "hoverSystem";
TMP672[1] = &TMP131[30];
NTI126016.size = sizeof(clicksystem126016);
NTI126016.kind = 18;
NTI126016.base = 0;
TMP131[31].kind = 1;
TMP131[31].offset = offsetof(clicksystem126016, Scene);
TMP131[31].typ = (&NTI132053);
TMP131[31].name = "scene";
NTI126016.node = &TMP131[31];
NTI126072.size = sizeof(clicksystem126016*);
NTI126072.kind = 22;
NTI126072.base = (&NTI126016);
NTI126072.marker = TMP675;
TMP131[30].kind = 1;
TMP131[30].offset = offsetof(gamescene126010, Clicksystem);
TMP131[30].typ = (&NTI126072);
TMP131[30].name = "clickSystem";
TMP672[2] = &TMP131[32];
TMP131[32].kind = 1;
TMP131[32].offset = offsetof(gamescene126010, Haswon);
TMP131[32].typ = (&NTI138);
TMP131[32].name = "hasWon";
TMP131[24].len = 3; TMP131[24].kind = 2; TMP131[24].sons = &TMP672[0];
NTI126010.node = &TMP131[24];
NTI132053.size = sizeof(gamescene126010*);
NTI132053.kind = 22;
NTI132053.base = (&NTI126010);
NTI132053.marker = TMP676;
NTI126012.size = sizeof(menuscene126012);
NTI126012.kind = 17;
NTI126012.base = (&NTI126006);
TMP761[0] = &TMP131[34];
TMP131[34].kind = 1;
TMP131[34].offset = offsetof(menuscene126012, Playmsg);
TMP131[34].typ = (&NTI126060);
TMP131[34].name = "play_msg";
TMP761[1] = &TMP131[35];
TMP131[35].kind = 1;
TMP131[35].offset = offsetof(menuscene126012, Quitmsg);
TMP131[35].typ = (&NTI126060);
TMP131[35].name = "quit_msg";
TMP131[33].len = 2; TMP131[33].kind = 2; TMP131[33].sons = &TMP761[0];
NTI126012.node = &TMP131[33];
NTI132020.size = sizeof(menuscene126012*);
NTI132020.kind = 22;
NTI132020.base = (&NTI126012);
NTI132020.marker = TMP762;
NTI126002.size = sizeof(app126002);
NTI126002.kind = 18;
NTI126002.base = 0;
TMP763[0] = &TMP131[37];
TMP131[37].kind = 1;
TMP131[37].offset = offsetof(app126002, Display);
TMP131[37].typ = (&NTI123009);
TMP131[37].name = "display";
TMP763[1] = &TMP131[38];
TMP131[38].kind = 1;
TMP131[38].offset = offsetof(app126002, Manager);
TMP131[38].typ = (&NTI128103);
TMP131[38].name = "manager";
TMP763[2] = &TMP131[39];
TMP131[39].kind = 1;
TMP131[39].offset = offsetof(app126002, Ctl);
TMP131[39].typ = (&NTI126066);
TMP131[39].name = "ctl";
TMP131[36].len = 3; TMP131[36].kind = 2; TMP131[36].sons = &TMP763[0];
NTI126002.node = &TMP131[36];
NTI131009.size = sizeof(app126002*);
NTI131009.kind = 22;
NTI131009.base = (&NTI126002);
NTI131009.marker = TMP764;
}

