/* Generated by Nim Compiler v0.10.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/jsudlow/Nim/lib -o .nimcache/menu.o .nimcache/menu.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <stdlib.h>
typedef struct menuscene126012 menuscene126012;
typedef struct controller126004 controller126004;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct scene126006 scene126006;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct scenemanager126008 scenemanager126008;
typedef struct messagebox126018 messagebox126018;
typedef struct tcell45135 tcell45135;
typedef struct tcellseq45151 tcellseq45151;
typedef struct tgcheap47216 tgcheap47216;
typedef struct tcellset45147 tcellset45147;
typedef struct tpagedesc45143 tpagedesc45143;
typedef struct tmemregion27410 tmemregion27410;
typedef struct tsmallchunk26640 tsmallchunk26640;
typedef struct tllchunk27404 tllchunk27404;
typedef struct tbigchunk26642 tbigchunk26642;
typedef struct tintset26617 tintset26617;
typedef struct ttrunk26613 ttrunk26613;
typedef struct tavlnode27408 tavlnode27408;
typedef struct tgcstat47214 tgcstat47214;
typedef struct tfont123015 tfont123015;
typedef struct tsurface123011 tsurface123011;
typedef struct gamescene126010 gamescene126010;
typedef struct trect123005 trect123005;
typedef struct table122024 table122024;
typedef struct keyvaluepairseq122027 keyvaluepairseq122027;
typedef struct keyvaluepair122030 keyvaluepair122030;
typedef struct table126040 table126040;
typedef struct keyvaluepairseq126043 keyvaluepairseq126043;
typedef struct keyvaluepair126046 keyvaluepair126046;
typedef struct TY126059 TY126059;
typedef struct tsurface116255 tsurface116255;
typedef struct tbasechunk26638 tbasechunk26638;
typedef struct tfreecell26630 tfreecell26630;
typedef struct tfont122221 tfont122221;
typedef struct tcolor116233 tcolor116233;
typedef struct hoversystem126014 hoversystem126014;
typedef struct clicksystem126016 clicksystem126016;
typedef struct tpixelformat116245 tpixelformat116245;
typedef struct trect116227 trect116227;
typedef struct tpalette116241 tpalette116241;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  scene126006  {
  TNimObject Sup;
controller126004* Ctl;
scenemanager126008* Manager;
};
struct  menuscene126012  {
  scene126006 Sup;
messagebox126018* Playmsg;
messagebox126018* Quitmsg;
};
struct  tcell45135  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq45151  {
NI Len;
NI Cap;
tcell45135** D;
};
struct  tcellset45147  {
NI Counter;
NI Max;
tpagedesc45143* Head;
tpagedesc45143** Data;
};
typedef tsmallchunk26640* TY27422[512];
typedef ttrunk26613* ttrunkbuckets26615[256];
struct  tintset26617  {
ttrunkbuckets26615 Data;
};
struct  tmemregion27410  {
NI Minlargeobj;
NI Maxlargeobj;
TY27422 Freesmallchunks;
tllchunk27404* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26642* Freechunkslist;
tintset26617 Chunkstarts;
tavlnode27408* Root;
tavlnode27408* Deleted;
tavlnode27408* Last;
tavlnode27408* Freeavlnodes;
};
struct  tgcstat47214  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47216  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq45151 Zct;
tcellseq45151 Decstack;
tcellset45147 Cycleroots;
tcellseq45151 Tempstack;
NI Recgclock;
tmemregion27410 Region;
tgcstat47214 Stat;
};
struct  messagebox126018  {
NimStringDesc* Messagetext;
NI X;
NI Y;
NI Size;
tfont123015* Font;
tsurface123011* S;
NIM_BOOL Isvisible;
};
struct trect123005 {
NI Field0;
NI Field1;
NI Field2;
NI Field3;
};
struct keyvaluepair122030 {
NU8 Field0;
NI32 Field1;
NIM_BOOL Field2;
};
struct  table122024  {
keyvaluepairseq122027* Data;
NI Counter;
};
struct keyvaluepair126046 {
NU8 Field0;
NimStringDesc* Field1;
tfont123015* Field2;
};
struct  table126040  {
keyvaluepairseq126043* Data;
NI Counter;
};
struct  controller126004  {
tsurface123011* Display;
NIM_BOOL Shouldclose;
table122024 Keys;
table122024 Mods;
NI Mousex;
NI Mousey;
NIM_BOOL Mousedown;
table126040 Fonts;
TY126059* Messages;
};
struct  tsurface123011  {
NI W;
NI H;
tsurface116255* S;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  scenemanager126008  {
  TNimObject Sup;
controller126004* Ctl;
scene126006* Scene;
};
typedef NI TY26620[16];
struct  tpagedesc45143  {
tpagedesc45143* Next;
NI Key;
TY26620 Bits;
};
struct  tbasechunk26638  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26640  {
  tbasechunk26638 Sup;
tsmallchunk26640* Next;
tsmallchunk26640* Prev;
tfreecell26630* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27404  {
NI Size;
NI Acc;
tllchunk27404* Next;
};
struct  tbigchunk26642  {
  tbasechunk26638 Sup;
tbigchunk26642* Next;
tbigchunk26642* Prev;
NI Align;
NF Data;
};
struct  ttrunk26613  {
ttrunk26613* Next;
NI Key;
TY26620 Bits;
};
typedef tavlnode27408* TY27414[2];
struct  tavlnode27408  {
TY27414 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tcolor116233  {
NU8 R;
NU8 G;
NU8 B;
NU8 Unused;
};
struct  tfont123015  {
tfont122221* F;
tcolor116233 Color;
};
struct  gamescene126010  {
  scene126006 Sup;
hoversystem126014* Hoversystem;
clicksystem126016* Clicksystem;
NIM_BOOL Haswon;
};
struct  trect116227  {
NI16 X;
NI16 Y;
NU16 W;
NU16 H;
};
struct  tsurface116255  {
NI32 Flags;
tpixelformat116245* Format;
int W;
int H;
NU16 Pitch;
void* Pixels;
int Offset;
void* Hwdata;
trect116227 Cliprect;
NI32 Unused1;
NI32 Locked;
void* Blitmap;
int Formatversion;
int Refcount;
};
struct  tfreecell26630  {
tfreecell26630* Next;
NI Zerofield;
};
struct  tfont122221  {
char dummy;
};
struct  hoversystem126014  {
gamescene126010* Scene;
NI I;
NI K;
};
struct  clicksystem126016  {
gamescene126010* Scene;
};
struct  tpixelformat116245  {
tpalette116241* Palette;
NU8 Bitsperpixel;
NU8 Bytesperpixel;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
NI32 Rmask;
NI32 Gmask;
NI32 Bmask;
NI32 Amask;
NI32 Colorkey;
NU8 Alpha;
};
struct  tpalette116241  {
NI Ncolors;
tcolor116233* Colors;
};
struct keyvaluepairseq122027 {
  TGenericSeq Sup;
  keyvaluepair122030 data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq126043 {
  TGenericSeq Sup;
  keyvaluepair126046 data[SEQ_DECL_SIZE];
};
struct TY126059 {
  TGenericSeq Sup;
  messagebox126018* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, enter_132018)(menuscene126012* self);
N_NIMCALL(void, newfont_130460)(controller126004* self, NimStringDesc* name, NimStringDesc* fontfile, NI size, NI color);
N_NIMCALL(messagebox126018*, addmessage_130749)(controller126004* self, NimStringDesc* msg, NimStringDesc* fontname, NI x, NI y);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell45135*, usrtocell_48846)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_50404)(tcell45135* c);
N_NOINLINE(void, addzct_48817)(tcellseq45151* s, tcell45135* c);
N_NIMCALL(void, leave_132030)(menuscene126012* self);
N_NIMCALL(gamescene126010*, new_132048)(void);
N_NIMCALL(void, keydown_132040)(menuscene126012* self, NI32 key, NI32 mods);
N_NIMCALL(void, setscene_128111)(scenemanager126008* self, scene126006* scene);
N_NIMCALL(void, draw_132082)(menuscene126012* self);
N_NIMCALL(void, fillrect_124845)(tsurface123011* sur, trect123005 r, NI col);
STRING_LITERAL(TMP668, "title", 5);
STRING_LITERAL(TMP669, "fonts/Pacifico.ttf", 18);
STRING_LITERAL(TMP670, "Welcome to the Cush Game Framework", 34);
STRING_LITERAL(TMP671, "Press Space to Quit, Enter to init Game Scene", 45);
extern TFrame* frameptr_16242;
extern tgcheap47216 gch_47244;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

static N_INLINE(tcell45135*, usrtocell_48846)(void* usr) {
	tcell45135* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell45135*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell45135))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50404)(tcell45135* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48817((&gch_47244.Zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell45135* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_48846(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell45135* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_48846((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50404(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, enter_132018)(menuscene126012* self) {
	nimfr("enter", "menu.nim")
	nimln(8, "menu.nim");
	newfont_130460((*self).Sup.Ctl, ((NimStringDesc*) &TMP668), ((NimStringDesc*) &TMP669), 22, 32768);
	nimln(10, "menu.nim");
	asgnRefNoCycle((void**) (&(*self).Playmsg), addmessage_130749((*self).Sup.Ctl, ((NimStringDesc*) &TMP670), ((NimStringDesc*) &TMP668), 25, 200));
	nimln(12, "menu.nim");
	asgnRefNoCycle((void**) (&(*self).Quitmsg), addmessage_130749((*self).Sup.Ctl, ((NimStringDesc*) &TMP671), ((NimStringDesc*) &TMP668), 25, 280));
	nimln(15, "menu.nim");
	(*(*self).Playmsg).Isvisible = NIM_TRUE;
	nimln(16, "menu.nim");
	(*(*self).Quitmsg).Isvisible = NIM_TRUE;
	popFrame();
}

N_NIMCALL(void, leave_132030)(menuscene126012* self) {
	nimfr("leave", "menu.nim")
	nimln(20, "menu.nim");
	(*(*self).Playmsg).Isvisible = NIM_FALSE;
	nimln(21, "menu.nim");
	(*(*self).Quitmsg).Isvisible = NIM_FALSE;
	popFrame();
}

N_NIMCALL(void, keydown_132040)(menuscene126012* self, NI32 key, NI32 mods) {
	nimfr("key_down", "menu.nim")
	nimln(24, "menu.nim");
	switch (key) {
	case 32:
	{
		nimln(26, "menu.nim");
		exit(0);
	}
	break;
	case 13:
	{
		gamescene126010* gamescene;
		scene126006* LOC3;
		nimln(28, "menu.nim");
		gamescene = new_132048();
		nimln(29, "menu.nim");
		LOC3 = 0;
		LOC3 = &gamescene->Sup;
		setscene_128111((*self).Sup.Manager, LOC3);
	}
	break;
	default:
	{
	}
	break;
	}
	popFrame();
}

N_NIMCALL(void, draw_132082)(menuscene126012* self) {
	trect123005 screenrect;
	trect123005 LOC1;
	nimfr("draw", "menu.nim")
	nimln(34, "menu.nim");
	LOC1.Field0 = 0;
	LOC1.Field1 = 0;
	LOC1.Field2 = (*(*(*self).Sup.Ctl).Display).W;
	LOC1.Field3 = (*(*(*self).Sup.Ctl).Display).H;
	screenrect = (*(trect123005*) ((&LOC1)));
	nimln(36, "menu.nim");
	fillrect_124845((*(*self).Sup.Ctl).Display, screenrect, 0);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, HEX00_menuInit)(void) {
	nimfr("menu", "menu.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_menuDatInit)(void) {
}

