/* Generated by Nim Compiler v0.10.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/jsudlow/Nim/lib -o .nimcache/random_random.o .nimcache/random_random.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>

#include <math.h>

#include <setjmp.h>
typedef struct TY161209 TY161209;
typedef struct TGenericSeq TGenericSeq;
typedef struct tmersennetwister162426 tmersennetwister162426;
typedef struct tmtstate160026 tmtstate160026;
typedef struct TY162475 TY162475;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TY162644 TY162644;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct NimStringDesc NimStringDesc;
typedef struct TSafePoint TSafePoint;
typedef struct tcell45135 tcell45135;
typedef struct tcellset45147 tcellset45147;
typedef struct tgcheap47216 tgcheap47216;
typedef struct tcellseq45151 tcellseq45151;
typedef struct tpagedesc45143 tpagedesc45143;
typedef struct tmemregion27410 tmemregion27410;
typedef struct tsmallchunk26640 tsmallchunk26640;
typedef struct tllchunk27404 tllchunk27404;
typedef struct tbigchunk26642 tbigchunk26642;
typedef struct tintset26617 tintset26617;
typedef struct ttrunk26613 ttrunk26613;
typedef struct tavlnode27408 tavlnode27408;
typedef struct tgcstat47214 tgcstat47214;
typedef struct tsystemrandom162793 tsystemrandom162793;
typedef struct TY163034 TY163034;
typedef struct TY163078 TY163078;
typedef struct TY163081 TY163081;
typedef struct slice84665 slice84665;
typedef struct tbasechunk26638 tbasechunk26638;
typedef struct tfreecell26630 tfreecell26630;
struct  TGenericSeq  {
NI len;
NI reserved;
};
typedef NU32 TY160027[624];
struct  tmtstate160026  {
TY160027 Mt;
NI Mti;
};
typedef struct {
N_NIMCALL_PTR(NU8, ClPrc) (tmersennetwister162426* self, void* ClEnv);
void* ClEnv;
} TY162428;
struct  tmersennetwister162426  {
tmtstate160026 State;
TY162428 Bytesit;
};
typedef N_CLOSURE_PTR(NU8, TMP733) (tmersennetwister162426* self);
struct  TY162475  {
NI HEX3Astate;
NU32 N162442;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e, void* ClEnv);
void* ClEnv;
} TY14809;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY14809 raiseAction;
};
struct  tcell45135  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq45151  {
NI Len;
NI Cap;
tcell45135** D;
};
struct  tcellset45147  {
NI Counter;
NI Max;
tpagedesc45143* Head;
tpagedesc45143** Data;
};
typedef tsmallchunk26640* TY27422[512];
typedef ttrunk26613* ttrunkbuckets26615[256];
struct  tintset26617  {
ttrunkbuckets26615 Data;
};
struct  tmemregion27410  {
NI Minlargeobj;
NI Maxlargeobj;
TY27422 Freesmallchunks;
tllchunk27404* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26642* Freechunkslist;
tintset26617 Chunkstarts;
tavlnode27408* Root;
tavlnode27408* Deleted;
tavlnode27408* Last;
tavlnode27408* Freeavlnodes;
};
struct  tgcstat47214  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47216  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq45151 Zct;
tcellseq45151 Decstack;
tcellset45147 Cycleroots;
tcellseq45151 Tempstack;
NI Recgclock;
tmemregion27410 Region;
tgcstat47214 Stat;
};
typedef struct {
N_NIMCALL_PTR(NU8, ClPrc) (tsystemrandom162793* self, void* ClEnv);
void* ClEnv;
} TY162794;
struct  tsystemrandom162793  {
TY162794 Bytesit;
};
typedef N_CLOSURE_PTR(NU8, TMP745) (tsystemrandom162793* self);
struct  TY163034  {
NI HEX3Astate;
NU8 B163022;
TY161209* HEX3Atmp163025;
NI I163028;
NI L163030;
};
struct TY163078 {
void* Field0;
TY163081* Field1;
};
struct TY163081 {
char dummy;
};
struct  slice84665  {
NI A;
NI B;
};
typedef NI TY26620[16];
struct  tpagedesc45143  {
tpagedesc45143* Next;
NI Key;
TY26620 Bits;
};
struct  tbasechunk26638  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26640  {
  tbasechunk26638 Sup;
tsmallchunk26640* Next;
tsmallchunk26640* Prev;
tfreecell26630* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27404  {
NI Size;
NI Acc;
tllchunk27404* Next;
};
struct  tbigchunk26642  {
  tbasechunk26638 Sup;
tbigchunk26642* Next;
tbigchunk26642* Prev;
NI Align;
NF Data;
};
struct  ttrunk26613  {
ttrunk26613* Next;
NI Key;
TY26620 Bits;
};
typedef tavlnode27408* TY27414[2];
struct  tavlnode27408  {
TY27414 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell26630  {
tfreecell26630* Next;
NI Zerofield;
};
struct TY161209 {
  TGenericSeq Sup;
  NU8 data[SEQ_DECL_SIZE];
};
struct TY162644 {
  TGenericSeq Sup;
  NU32 data[SEQ_DECL_SIZE];
};
static N_INLINE(TY161209*, urandom_162204)(NI size);
N_NIMCALL(TY161209*, urandom_161206)(NI size);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NU8, randombyte_162484)(tmersennetwister162426* self);
N_NIMCALL(NF, random_162495)(tmersennetwister162426* self);
N_NIMCALL(NF, genrandres53_160751)(tmtstate160026* self);
N_NIMCALL(void, initmersennetwister_162507)(tmersennetwister162426* Result);
N_NIMCALL(tmtstate160026, initmtstate_160034)(void);
N_NIMCALL(void, TMP735)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_CLOSURE(NU8, mtrandombytes_162436)(tmersennetwister162426* self, void* ClEnv);
N_NIMCALL(NU32, genrandint32_160324)(tmtstate160026* self);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(void, seed_162518)(tmersennetwister162426* self, NI seed);
N_NIMCALL(void, initgenrand_160044)(tmtstate160026* self, NU32 s);
N_NIMCALL(TY161209*, HEX40_162539)(NU8* a_162545, NI a_162545Len0);
N_NIMCALL(TY162644*, newseq_162639)(NI len_162643);
N_NIMCALL(void, seed_162531)(tmersennetwister162426* self, NU8* seed, NI seedLen0);
static N_INLINE(NF, HEX2F_84603)(NI x, NI y);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemsize, NI newlen);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(void, initbyarray_160111)(tmtstate160026* self, NU32* initkey, NI initkeyLen0);
N_NIMCALL(void, seed_162777)(tmersennetwister162426* self);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(NIM_BOOL, isObj)(TNimType* obj, TNimType* subclass);
static N_INLINE(Exception*, getCurrentException)(void);
N_NIMCALL(NF, ntepochTime)(void);
static N_INLINE(void, popCurrentException)(void);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_51225)(tcell45135* c);
static N_INLINE(NIM_BOOL, canbecycleroot_48867)(tcell45135* c);
static N_INLINE(void, rtladdcycleroot_49629)(tcell45135* c);
N_NOINLINE(void, incl_45871)(tcellset45147* s, tcell45135* cell);
static N_INLINE(tcell45135*, usrtocell_48846)(void* usr);
static N_INLINE(void, decref_50804)(tcell45135* c);
static N_INLINE(void, rtladdzct_50404)(tcell45135* c);
N_NOINLINE(void, addzct_48817)(tcellseq45151* s, tcell45135* c);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(NU8, randombyte_163046)(tsystemrandom162793* self);
N_NIMCALL(void, initsystemrandom_163057)(tsystemrandom162793* Result);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP747)(void* p, NI op);
N_CLOSURE(NU8, sysrandombytes_162802)(tsystemrandom162793* self, void* ClEnv);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(void, failedassertimpl_85425)(NimStringDesc* msg);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, TMP752)(void* p, NI op);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
static N_INLINE(NU8, randombyte_163107)(void);
static N_INLINE(NF, random_163118)(void);
N_NIMCALL(NF, random_163139)(tmersennetwister162426* self_163145, NF max_163148);
static N_INLINE(NF, random_163131)(NF max);
N_NIMCALL(NF, random_163172)(tmersennetwister162426* self_163178, NF min_163181, NF max_163183);
static N_INLINE(NF, random_163163)(NF min, NF max);
N_NIMCALL(NI, randomint_163206)(tmersennetwister162426* self_163212, NI max_163215);
N_NIMCALL(NF, log2_108055)(NF x);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(NI, randomint_163198)(NI max);
N_NIMCALL(NI, randomint_163287)(tmersennetwister162426* self_163293, NI min_163296, NI max_163298);
static N_INLINE(NI, randomint_163278)(NI min, NI max);
static N_INLINE(NI, randomint_163336)(tmersennetwister162426* self_163342, slice84665 slice_163347);
static N_INLINE(NI, randomint_163325)(slice84665 slice);
static N_INLINE(NIM_BOOL, randombool_163382)(tmersennetwister162426* self_163388);
static N_INLINE(NIM_BOOL, randombool_163377)(void);
STRING_LITERAL(TMP748, "(system.len|system.len|system.len|system.len|system.len|...)(a)"
" (system.==|system.==|system.==|system.==|system.==|system.==|sy"
"stem.==|system.==|system.==|system.==|system.==|system.==|system"
".==|system.==|system.==|system.==|system.==|system.==|system.==|"
"system.==|...)\012    L seq modified while iterating over it", 312);
extern TFrame* frameptr_16242;
TNimType NTI162475; /* object */
extern TNimType NTI108; /* int */
TNimType NTI162477; /* range -1..4(int) */
extern TNimType NTI124; /* uint32 */
TNimType NTI162479; /* ref object */
extern TSafePoint* exchandler_16243;
extern TNimType NTI3233; /* OSError */
extern Exception* currexception_16245;
extern tgcheap47216 gch_47244;
TNimType NTI163034; /* object */
TNimType NTI163036; /* range -1..1(int) */
extern TNimType NTI120; /* uint8 */
extern TNimType NTI161209; /* seq[uint8] */
TNimType NTI163038; /* ref object */
tmersennetwister162426 mersennetwisterinst_163068;
TNimType NTI162426; /* TMersenneTwister */
extern TNimType NTI160026; /* TMTState */
TNimType NTI162428; /* tuple[pointer, ref tuple[]] */
extern TNimType NTI153; /* pointer */
TNimType NTI163081; /* tuple[] */
TNimType NTI163080; /* ref tuple[] */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

static N_INLINE(TY161209*, urandom_162204)(NI size) {
	TY161209* result;
	nimfr("urandom", "random.nim")
	result = 0;
	nimln(19, "random.nim");
	nimln(21, "random.nim");
	result = urandom_161206(size);
	popFrame();
	return result;
}

N_NIMCALL(NU8, randombyte_162484)(tmersennetwister162426* self) {
	NU8 result;
	nimfr("random_byte", "random.nim")
	result = 0;
	nimln(131, "random.nim");
	result = (*self).Bytesit.ClPrc(self, (*self).Bytesit.ClEnv);
	popFrame();
	return result;
}

N_NIMCALL(NF, random_162495)(tmersennetwister162426* self) {
	NF result;
	nimfr("random", "random.nim")
	result = 0;
	nimln(134, "random.nim");
	result = genrandres53_160751((&(*self).State));
	popFrame();
	return result;
}
N_NIMCALL(void, TMP735)(void* p, NI op) {
	TY162475* a;
	a = (TY162475*)p;
}

N_CLOSURE(NU8, mtrandombytes_162436)(tmersennetwister162426* self, void* ClEnv) {
	NU8 result;
	TY162475* HEX3Aenvp_162478;
	nimfr("mt_random_bytes", "random.nim")
	result = 0;
	HEX3Aenvp_162478 = (TY162475*) ClEnv;
	switch ((*HEX3Aenvp_162478).HEX3Astate) {
	case -1: goto BeforeRet;
	case 0: goto STATE0;
	case 1: goto STATE1;
	case 2: goto STATE2;
	case 3: goto STATE3;
	case 4: goto STATE4;
	}
	STATE0: ;
	{
		nimln(123, "random.nim");
		while (1) {
			nimln(124, "random.nim");
			(*HEX3Aenvp_162478).N162442 = genrandint32_160324((&(*self).State));
			nimln(125, "random.nim");
			(*HEX3Aenvp_162478).HEX3Astate = 1;
			nimln(125, "random.nim");
			nimln(125, "random.nim");
			result = ((NU8) ((*HEX3Aenvp_162478).N162442));
			goto BeforeRet;
			STATE1: ;
			nimln(126, "random.nim");
			(*HEX3Aenvp_162478).HEX3Astate = 2;
			nimln(126, "random.nim");
			nimln(126, "random.nim");
			nimln(126, "random.nim");
			result = ((NU8) ((NU32)((NU32)((*HEX3Aenvp_162478).N162442) >> (NU32)(((NU32) 8)))));
			goto BeforeRet;
			STATE2: ;
			nimln(127, "random.nim");
			(*HEX3Aenvp_162478).HEX3Astate = 3;
			nimln(127, "random.nim");
			nimln(127, "random.nim");
			nimln(127, "random.nim");
			result = ((NU8) ((NU32)((NU32)((*HEX3Aenvp_162478).N162442) >> (NU32)(((NU32) 16)))));
			goto BeforeRet;
			STATE3: ;
			nimln(128, "random.nim");
			(*HEX3Aenvp_162478).HEX3Astate = 4;
			nimln(128, "random.nim");
			nimln(128, "random.nim");
			nimln(128, "random.nim");
			result = ((NU8) ((NU32)((NU32)((*HEX3Aenvp_162478).N162442) >> (NU32)(((NU32) 24)))));
			goto BeforeRet;
			STATE4: ;
		}
	}
	nimln(122, "random.nim");
	(*HEX3Aenvp_162478).HEX3Astate = -1;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, initmersennetwister_162507)(tmersennetwister162426* Result) {
	TY162475* HEX3Aenvp_162514;
	TY162428 LOC1;
	nimfr("init_MersenneTwister", "random.nim")
	nimln(138, "random.nim");
	(*Result).State = initmtstate_160034();
	nimln(139, "random.nim");
	HEX3Aenvp_162514 = 0;
	nimln(172, "system.nim");
	HEX3Aenvp_162514 = (TY162475*) newObj((&NTI162479), sizeof(TY162475));
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.ClPrc = mtrandombytes_162436; LOC1.ClEnv = HEX3Aenvp_162514;
	unsureAsgnRef((void**) (&(*Result).Bytesit.ClEnv), LOC1.ClEnv);
	(*Result).Bytesit.ClPrc = LOC1.ClPrc;
	popFrame();
}

N_NIMCALL(void, seed_162518)(tmersennetwister162426* self, NI seed) {
	nimfr("seed", "random.nim")
	nimln(143, "random.nim");
	initgenrand_160044((&(*self).State), ((NU32) (seed)));
	popFrame();
}

static N_INLINE(NF, HEX2F_84603)(NI x, NI y) {
	NF result;
	nimfr("/", "system.nim")
	result = 0;
	nimln(2749, "system.nim");
	nimln(2749, "system.nim");
	nimln(2749, "system.nim");
	nimln(2749, "system.nim");
	result = ((NF)(((double) (x))) / (NF)(((double) (y))));
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) - (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU32) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, seed_162531)(tmersennetwister162426* self, NU8* seed, NI seedLen0) {
	TY161209* bytes;
	NI n;
	NF LOC1;
	NF LOC2;
	NI TMP738;
	TY162644* words;
	nimfr("seed", "random.nim")
	nimln(150, "random.nim");
	bytes = HEX40_162539(seed, seedLen0);
	nimln(151, "random.nim");
	nimln(151, "random.nim");
	nimln(151, "random.nim");
	nimln(151, "random.nim");
	LOC1 = 0;
	LOC1 = HEX2F_84603(bytes->Sup.len, 4);
	LOC2 = 0;
	LOC2 = ceil(LOC1);
	n = ((NI) (LOC2));
	nimln(152, "random.nim");
	nimln(152, "random.nim");
	TMP738 = mulInt(n, 4);
	bytes = (TY161209*) setLengthSeq(&(bytes)->Sup, sizeof(NU8), (NI32)(TMP738));
	nimln(154, "random.nim");
	words = newseq_162639(n);
	{
		NI i_162698;
		NI HEX3Atmp_162757;
		NI TMP739;
		NI res_162760;
		i_162698 = 0;
		HEX3Atmp_162757 = 0;
		nimln(155, "random.nim");
		nimln(155, "random.nim");
		TMP739 = subInt(n, 1);
		HEX3Atmp_162757 = (NI32)(TMP739);
		nimln(1576, "system.nim");
		res_162760 = 0;
		{
			nimln(1577, "system.nim");
			while (1) {
				NI i4;
				NI TMP740;
				NI TMP741;
				NI TMP742;
				NI TMP743;
				nimln(1577, "system.nim");
				if (!(res_162760 <= HEX3Atmp_162757)) goto LA5;
				nimln(1576, "system.nim");
				i_162698 = res_162760;
				nimln(156, "random.nim");
				nimln(156, "random.nim");
				TMP740 = mulInt(i_162698, 4);
				i4 = (NI32)(TMP740);
				nimln(157, "random.nim");
				if ((NU)(i_162698) >= (NU)(words->Sup.len)) raiseIndexError();
				nimln(157, "random.nim");
				nimln(157, "random.nim");
				nimln(157, "random.nim");
				if ((NU)(i4) >= (NU)(bytes->Sup.len)) raiseIndexError();
				nimln(157, "random.nim");
				nimln(157, "random.nim");
				TMP741 = addInt(i4, 1);
				if ((NU)((NI32)(TMP741)) >= (NU)(bytes->Sup.len)) raiseIndexError();
				nimln(157, "random.nim");
				nimln(157, "random.nim");
				TMP742 = addInt(i4, 2);
				if ((NU)((NI32)(TMP742)) >= (NU)(bytes->Sup.len)) raiseIndexError();
				nimln(157, "random.nim");
				nimln(157, "random.nim");
				TMP743 = addInt(i4, 3);
				if ((NU)((NI32)(TMP743)) >= (NU)(bytes->Sup.len)) raiseIndexError();
				words->data[i_162698] = ((NU32) ((NU8)((NU8)((NU8)(bytes->data[i4] | (NU8)((NU8)(bytes->data[(NI32)(TMP741)]) << (NU8)(((NU8) 8)))) | (NU8)((NU8)(bytes->data[(NI32)(TMP742)]) << (NU8)(((NU8) 16)))) | (NU8)((NU8)(bytes->data[(NI32)(TMP743)]) << (NU8)(((NU8) 24))))));
				nimln(1579, "system.nim");
				res_162760 = addInt(res_162760, 1);
			} LA5: ;
		}
	}
	nimln(159, "random.nim");
	initbyarray_160111((&(*self).State), words->data, words->Sup.len);
	popFrame();
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = exchandler_16243;
	exchandler_16243 = s;
}

static N_INLINE(void, popSafePoint)(void) {
	exchandler_16243 = (*exchandler_16243).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	frameptr_16242 = s;
}

static N_INLINE(Exception*, getCurrentException)(void) {
	Exception* result;
	nimfr("getCurrentException", "system.nim")
	result = 0;
	nimln(2619, "system.nim");
	result = currexception_16245;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, canbecycleroot_48867)(tcell45135* c) {
	NIM_BOOL result;
	nimfr("canbeCycleRoot", "gc.nim")
	result = 0;
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	result = !((((*(*c).Typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_49629)(tcell45135* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(189, "gc.nim");
	{
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		if (!!((((NI) ((NI)((*c).Refcount & 3))) == 3))) goto LA3;
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		(*c).Refcount = (NI)((NI)((*c).Refcount & -4) | 3);
		nimln(191, "gc.nim");
		incl_45871((&gch_47244.Cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_51225)(tcell45135* c) {
	nimfr("incRef", "gc.nim")
	nimln(216, "gc.nim");
	nimln(216, "gc.nim");
	(*c).Refcount = (NI)((NU32)((*c).Refcount) + (NU32)(8));
	nimln(219, "gc.nim");
	{
		NIM_BOOL LOC3;
		nimln(219, "gc.nim");
		LOC3 = 0;
		LOC3 = canbecycleroot_48867(c);
		if (!LOC3) goto LA4;
		nimln(220, "gc.nim");
		rtladdcycleroot_49629(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(tcell45135*, usrtocell_48846)(void* usr) {
	tcell45135* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell45135*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell45135))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50404)(tcell45135* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48817((&gch_47244.Zct), c);
	popFrame();
}

static N_INLINE(void, decref_50804)(tcell45135* c) {
	nimfr("decRef", "gc.nim")
	nimln(206, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA3;
		nimln(207, "gc.nim");
		rtladdzct_50404(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(208, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_48867(c);
		if (!LOC6) goto LA7;
		nimln(211, "gc.nim");
		rtladdcycleroot_49629(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(244, "gc.nim");
	{
		tcell45135* LOC5;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_48846(src);
		incref_51225(LOC5);
	}
	LA3: ;
	nimln(245, "gc.nim");
	{
		tcell45135* LOC10;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_48846((*dest));
		decref_50804(LOC10);
	}
	LA8: ;
	nimln(246, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currexception_16245), (*currexception_16245).parent);
}

N_NIMCALL(void, seed_162777)(tmersennetwister162426* self) {
	TSafePoint TMP744;
	nimfr("seed", "random.nim")
	nimln(164, "random.nim");
	pushSafePoint(&TMP744);
	TMP744.status = setjmp(TMP744.context);
	if (TMP744.status == 0) {
		TY161209* LOC2;
		nimln(165, "random.nim");
		nimln(165, "random.nim");
		LOC2 = 0;
		LOC2 = urandom_162204(2500);
		seed_162531(self, LOC2->data, LOC2->Sup.len);
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&F);
		if (isObj(getCurrentException()->Sup.m_type, (&NTI3233))) {
			NF LOC5;
			TMP744.status = 0;
			nimln(167, "random.nim");
			nimln(167, "random.nim");
			nimln(167, "random.nim");
			LOC5 = 0;
			LOC5 = ntepochTime();
			seed_162518(self, ((NI) (((NF)(LOC5) * (NF)(2.5600000000000000e+02)))));
			popCurrentException();
		}
	}
	if (TMP744.status != 0) reraiseException();
	popFrame();
}

N_NIMCALL(NU8, randombyte_163046)(tsystemrandom162793* self) {
	NU8 result;
	nimfr("random_byte", "random.nim")
	result = 0;
	nimln(184, "random.nim");
	result = (*self).Bytesit.ClPrc(self, (*self).Bytesit.ClEnv);
	popFrame();
	return result;
}
N_NIMCALL(void, TMP747)(void* p, NI op) {
	TY163034* a;
	a = (TY163034*)p;
	nimGCvisit((void*)(*a).HEX3Atmp163025, op);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell45135* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_48846(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell45135* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_48846((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50404(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_CLOSURE(NU8, sysrandombytes_162802)(tsystemrandom162793* self, void* ClEnv) {
	NU8 result;
	TY163034* HEX3Aenvp_163037;
	nimfr("sys_random_bytes", "random.nim")
	result = 0;
	HEX3Aenvp_163037 = (TY163034*) ClEnv;
	switch ((*HEX3Aenvp_163037).HEX3Astate) {
	case -1: goto BeforeRet;
	case 0: goto STATE0;
	case 1: goto STATE1;
	}
	STATE0: ;
	{
		nimln(179, "random.nim");
		while (1) {
			{
				nimln(180, "random.nim");
				asgnRefNoCycle((void**) (&(*HEX3Aenvp_163037).HEX3Atmp163025), urandom_162204(128));
				nimln(2986, "system.nim");
				(*HEX3Aenvp_163037).I163028 = 0;
				nimln(2987, "system.nim");
				nimln(2987, "system.nim");
				(*HEX3Aenvp_163037).L163030 = (*HEX3Aenvp_163037).HEX3Atmp163025->Sup.len;
				{
					nimln(2988, "system.nim");
					while (1) {
						nimln(2988, "system.nim");
						if (!((*HEX3Aenvp_163037).I163028 < (*HEX3Aenvp_163037).L163030)) goto LA5;
						nimln(2989, "system.nim");
						if ((NU)((*HEX3Aenvp_163037).I163028) >= (NU)((*HEX3Aenvp_163037).HEX3Atmp163025->Sup.len)) raiseIndexError();
						(*HEX3Aenvp_163037).B163022 = (*HEX3Aenvp_163037).HEX3Atmp163025->data[(*HEX3Aenvp_163037).I163028];
						nimln(181, "random.nim");
						(*HEX3Aenvp_163037).HEX3Astate = 1;
						nimln(181, "random.nim");
						nimln(181, "random.nim");
						result = (*HEX3Aenvp_163037).B163022;
						goto BeforeRet;
						STATE1: ;
						nimln(2990, "system.nim");
						(*HEX3Aenvp_163037).I163028 = addInt((*HEX3Aenvp_163037).I163028, 1);
						nimln(2991, "system.nim");
						{
							nimln(2991, "system.nim");
							nimln(2991, "system.nim");
							nimln(2991, "system.nim");
							if (!!(((*HEX3Aenvp_163037).HEX3Atmp163025->Sup.len == (*HEX3Aenvp_163037).L163030))) goto LA8;
							nimln(2991, "system.nim");
							failedassertimpl_85425(((NimStringDesc*) &TMP748));
						}
						LA8: ;
					} LA5: ;
				}
			}
		}
	}
	nimln(176, "random.nim");
	(*HEX3Aenvp_163037).HEX3Astate = -1;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, initsystemrandom_163057)(tsystemrandom162793* Result) {
	TY163034* HEX3Aenvp_163064;
	TY162794 LOC1;
	nimfr("init_SystemRandom", "random.nim")
	nimln(188, "random.nim");
	HEX3Aenvp_163064 = 0;
	nimln(172, "system.nim");
	HEX3Aenvp_163064 = (TY163034*) newObj((&NTI163038), sizeof(TY163034));
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.ClPrc = sysrandombytes_162802; LOC1.ClEnv = HEX3Aenvp_163064;
	unsureAsgnRef((void**) (&(*Result).Bytesit.ClEnv), LOC1.ClEnv);
	(*Result).Bytesit.ClPrc = LOC1.ClPrc;
	popFrame();
}
N_NIMCALL(void, TMP752)(void* p, NI op) {
	TY163081* a;
	a = (TY163081*)p;
}

static N_INLINE(NU8, randombyte_163107)(void) {
	NU8 result;
	nimfr("random_byte", "random.nim")
	result = 0;
	nimln(199, "random.nim");
	nimln(200, "random.nim");
	result = randombyte_162484((&mersennetwisterinst_163068));
	popFrame();
	return result;
}

static N_INLINE(NF, random_163118)(void) {
	NF result;
	nimfr("random", "random.nim")
	result = 0;
	nimln(202, "random.nim");
	nimln(203, "random.nim");
	result = random_162495((&mersennetwisterinst_163068));
	popFrame();
	return result;
}

N_NIMCALL(NF, random_163139)(tmersennetwister162426* self_163145, NF max_163148) {
	NF result;
	NF LOC1;
	nimfr("random", "random.nim")
	result = 0;
	nimln(64, "random.nim");
	nimln(65, "random.nim");
	nimln(65, "random.nim");
	LOC1 = 0;
	LOC1 = random_162495(self_163145);
	result = ((NF)(max_163148) * (NF)(LOC1));
	popFrame();
	return result;
}

static N_INLINE(NF, random_163131)(NF max) {
	NF result;
	nimfr("random", "random.nim")
	result = 0;
	nimln(205, "random.nim");
	nimln(206, "random.nim");
	result = random_163139((&mersennetwisterinst_163068), max);
	popFrame();
	return result;
}

N_NIMCALL(NF, random_163172)(tmersennetwister162426* self_163178, NF min_163181, NF max_163183) {
	NF result;
	NF LOC1;
	nimfr("random", "random.nim")
	result = 0;
	nimln(60, "random.nim");
	nimln(61, "random.nim");
	nimln(61, "random.nim");
	nimln(61, "random.nim");
	nimln(61, "random.nim");
	LOC1 = 0;
	LOC1 = random_162495(self_163178);
	result = ((NF)(min_163181) + (NF)(((NF)(((NF)(max_163183) - (NF)(min_163181))) * (NF)(LOC1))));
	popFrame();
	return result;
}

static N_INLINE(NF, random_163163)(NF min, NF max) {
	NF result;
	nimfr("random", "random.nim")
	result = 0;
	nimln(208, "random.nim");
	nimln(209, "random.nim");
	result = random_163172((&mersennetwisterinst_163068), min, max);
	popFrame();
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
	result = 0;
	{
		if (!(b == 0)) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == (-2147483647 -1));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == -1);
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI32)(a / b);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, randomint_163206)(tmersennetwister162426* self_163212, NI max_163215) {
	NI result;
	NI neededbits;
	NF LOC1;
	NF LOC2;
	NI neededbytes;
	NI TMP753;
	NI TMP754;
	nimfr("random_int", "random.nim")
	result = 0;
	nimln(31, "random.nim");
	nimln(31, "random.nim");
	nimln(31, "random.nim");
	LOC1 = 0;
	LOC1 = log2_108055(((NF) (max_163215)));
	LOC2 = 0;
	LOC2 = ceil(LOC1);
	neededbits = ((NI) (LOC2));
	nimln(32, "random.nim");
	nimln(32, "random.nim");
	nimln(32, "random.nim");
	TMP753 = addInt(neededbits, 7);
	TMP754 = divInt((NI32)(TMP753), 8);
	neededbytes = (NI32)(TMP754);
	{
		nimln(33, "random.nim");
		while (1) {
			NI TMP755;
			NI TMP756;
			nimln(34, "random.nim");
			result = 0;
			{
				NI i_163229;
				NI res_163251;
				i_163229 = 0;
				nimln(1576, "system.nim");
				res_163251 = 1;
				{
					nimln(1577, "system.nim");
					while (1) {
						NU8 LOC8;
						nimln(1577, "system.nim");
						if (!(res_163251 <= neededbytes)) goto LA7;
						nimln(1576, "system.nim");
						i_163229 = res_163251;
						nimln(36, "random.nim");
						nimln(36, "random.nim");
						result = ((NI)chckRange((NI)((NU32)(((NI) (result))) << (NU32)(8)), 0, 2147483647));
						nimln(37, "random.nim");
						nimln(37, "random.nim");
						LOC8 = 0;
						LOC8 = randombyte_162484(self_163212);
						result = addInt(result, ((NI)chckRange(((NI) (LOC8)), 0, 2147483647)));
						nimln(1579, "system.nim");
						res_163251 = addInt(res_163251, 1);
					} LA7: ;
				}
			}
			nimln(38, "random.nim");
			nimln(38, "random.nim");
			nimln(38, "random.nim");
			nimln(38, "random.nim");
			TMP755 = mulInt(neededbytes, 8);
			TMP756 = subInt((NI32)(TMP755), neededbits);
			result = ((NI)chckRange((NI)((NU32)(((NI) (result))) >> (NU32)((NI32)(TMP756))), 0, 2147483647));
			nimln(39, "random.nim");
			{
				nimln(39, "random.nim");
				if (!(((NI) (result)) < ((NI) (max_163215)))) goto LA11;
				nimln(40, "random.nim");
				goto LA3;
			}
			LA11: ;
		}
	} LA3: ;
	popFrame();
	return result;
}

static N_INLINE(NI, randomint_163198)(NI max) {
	NI result;
	nimfr("random_int", "random.nim")
	result = 0;
	nimln(211, "random.nim");
	nimln(212, "random.nim");
	result = randomint_163206((&mersennetwisterinst_163068), max);
	popFrame();
	return result;
}

N_NIMCALL(NI, randomint_163287)(tmersennetwister162426* self_163293, NI min_163296, NI max_163298) {
	NI result;
	NI TMP757;
	NI LOC1;
	NI TMP758;
	nimfr("random_int", "random.nim")
	result = 0;
	nimln(48, "random.nim");
	nimln(49, "random.nim");
	nimln(49, "random.nim");
	nimln(49, "random.nim");
	TMP757 = subInt(max_163298, min_163296);
	LOC1 = 0;
	LOC1 = randomint_163206(self_163293, ((NI)chckRange((NI32)(TMP757), 1, 2147483647)));
	TMP758 = addInt(min_163296, ((NI) (LOC1)));
	result = (NI32)(TMP758);
	popFrame();
	return result;
}

static N_INLINE(NI, randomint_163278)(NI min, NI max) {
	NI result;
	nimfr("random_int", "random.nim")
	result = 0;
	nimln(214, "random.nim");
	nimln(215, "random.nim");
	result = randomint_163287((&mersennetwisterinst_163068), min, max);
	popFrame();
	return result;
}

static N_INLINE(NI, randomint_163336)(tmersennetwister162426* self_163342, slice84665 slice_163347) {
	NI result;
	NI TMP759;
	nimfr("random_int", "random.nim")
	result = 0;
	nimln(52, "random.nim");
	nimln(53, "random.nim");
	nimln(53, "random.nim");
	TMP759 = addInt(slice_163347.B, 1);
	result = randomint_163287(self_163342, slice_163347.A, (NI32)(TMP759));
	popFrame();
	return result;
}

static N_INLINE(NI, randomint_163325)(slice84665 slice) {
	NI result;
	nimfr("random_int", "random.nim")
	result = 0;
	nimln(217, "random.nim");
	nimln(218, "random.nim");
	result = randomint_163336((&mersennetwisterinst_163068), slice);
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, randombool_163382)(tmersennetwister162426* self_163388) {
	NIM_BOOL result;
	NI LOC1;
	nimfr("random_bool", "random.nim")
	result = 0;
	nimln(56, "random.nim");
	nimln(57, "random.nim");
	LOC1 = 0;
	LOC1 = randomint_163206(self_163388, 2);
	result = ((NIM_BOOL)chckRange(LOC1, NIM_FALSE, NIM_TRUE));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, randombool_163377)(void) {
	NIM_BOOL result;
	nimfr("random_bool", "random.nim")
	result = 0;
	nimln(220, "random.nim");
	nimln(221, "random.nim");
	result = randombool_163382((&mersennetwisterinst_163068));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, random_randomInit)(void) {
	nimfr("random", "random.nim")
	nimln(193, "random.nim");
	chckNil((void*)(&mersennetwisterinst_163068));
	genericReset((void*)(&mersennetwisterinst_163068), (&NTI162426));
	initmersennetwister_162507((&mersennetwisterinst_163068));
	nimln(196, "random.nim");
	seed_162777((&mersennetwisterinst_163068));
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, random_randomDatInit)(void) {
static TNimNode* TMP734[2];
static TNimNode* TMP746[5];
static TNimNode* TMP749[2];
static TNimNode* TMP751[2];
static TNimNode TMP683[16];
NTI162475.size = sizeof(TY162475);
NTI162475.kind = 18;
NTI162475.base = 0;
NTI162475.flags = 3;
TMP734[0] = &TMP683[1];
NTI162477.size = sizeof(NI);
NTI162477.kind = 20;
NTI162477.base = (&NTI108);
NTI162477.flags = 3;
TMP683[1].kind = 1;
TMP683[1].offset = offsetof(TY162475, HEX3Astate);
TMP683[1].typ = (&NTI162477);
TMP683[1].name = ":state";
TMP734[1] = &TMP683[2];
TMP683[2].kind = 1;
TMP683[2].offset = offsetof(TY162475, N162442);
TMP683[2].typ = (&NTI124);
TMP683[2].name = "n162442";
TMP683[0].len = 2; TMP683[0].kind = 2; TMP683[0].sons = &TMP734[0];
NTI162475.node = &TMP683[0];
NTI162479.size = sizeof(TY162475*);
NTI162479.kind = 22;
NTI162479.base = (&NTI162475);
NTI162479.flags = 2;
NTI162479.marker = TMP735;
NTI163034.size = sizeof(TY163034);
NTI163034.kind = 18;
NTI163034.base = 0;
NTI163034.flags = 2;
TMP746[0] = &TMP683[4];
NTI163036.size = sizeof(NI);
NTI163036.kind = 20;
NTI163036.base = (&NTI108);
NTI163036.flags = 3;
TMP683[4].kind = 1;
TMP683[4].offset = offsetof(TY163034, HEX3Astate);
TMP683[4].typ = (&NTI163036);
TMP683[4].name = ":state";
TMP746[1] = &TMP683[5];
TMP683[5].kind = 1;
TMP683[5].offset = offsetof(TY163034, B163022);
TMP683[5].typ = (&NTI120);
TMP683[5].name = "b163022";
TMP746[2] = &TMP683[6];
TMP683[6].kind = 1;
TMP683[6].offset = offsetof(TY163034, HEX3Atmp163025);
TMP683[6].typ = (&NTI161209);
TMP683[6].name = ":tmp163025";
TMP746[3] = &TMP683[7];
TMP683[7].kind = 1;
TMP683[7].offset = offsetof(TY163034, I163028);
TMP683[7].typ = (&NTI108);
TMP683[7].name = "i163028";
TMP746[4] = &TMP683[8];
TMP683[8].kind = 1;
TMP683[8].offset = offsetof(TY163034, L163030);
TMP683[8].typ = (&NTI108);
TMP683[8].name = "L163030";
TMP683[3].len = 5; TMP683[3].kind = 2; TMP683[3].sons = &TMP746[0];
NTI163034.node = &TMP683[3];
NTI163038.size = sizeof(TY163034*);
NTI163038.kind = 22;
NTI163038.base = (&NTI163034);
NTI163038.flags = 2;
NTI163038.marker = TMP747;
NTI162426.size = sizeof(tmersennetwister162426);
NTI162426.kind = 18;
NTI162426.base = 0;
TMP749[0] = &TMP683[10];
TMP683[10].kind = 1;
TMP683[10].offset = offsetof(tmersennetwister162426, State);
TMP683[10].typ = (&NTI160026);
TMP683[10].name = "state";
TMP749[1] = &TMP683[11];
NTI162428.size = sizeof(TY163078);
NTI162428.kind = 18;
NTI162428.base = 0;
NTI162428.flags = 2;
TMP751[0] = &TMP683[13];
TMP683[13].kind = 1;
TMP683[13].offset = offsetof(TY163078, Field0);
TMP683[13].typ = (&NTI153);
TMP683[13].name = "Field0";
TMP751[1] = &TMP683[14];
NTI163081.size = sizeof(TY163081);
NTI163081.kind = 18;
NTI163081.base = 0;
NTI163081.flags = 3;
TMP683[15].len = 0; TMP683[15].kind = 2;
NTI163081.node = &TMP683[15];
NTI163080.size = sizeof(TY163081*);
NTI163080.kind = 22;
NTI163080.base = (&NTI163081);
NTI163080.flags = 2;
NTI163080.marker = TMP752;
TMP683[14].kind = 1;
TMP683[14].offset = offsetof(TY163078, Field1);
TMP683[14].typ = (&NTI163080);
TMP683[14].name = "Field1";
TMP683[12].len = 2; TMP683[12].kind = 2; TMP683[12].sons = &TMP751[0];
NTI162428.node = &TMP683[12];
TMP683[11].kind = 1;
TMP683[11].offset = offsetof(tmersennetwister162426, Bytesit);
TMP683[11].typ = (&NTI162428);
TMP683[11].name = "bytes_it";
TMP683[9].len = 2; TMP683[9].kind = 2; TMP683[9].sons = &TMP749[0];
NTI162426.node = &TMP683[9];
}

