/* Generated by Nim Compiler v0.10.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/jsudlow/Nim/lib -o .nimcache/random_mt19937ar.o .nimcache/random_mt19937ar.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>
typedef struct tmtstate160026 tmtstate160026;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef NU32 TY160027[624];
struct  tmtstate160026  {
TY160027 Mt;
NI Mti;
};
typedef NU32 TY160330[2];
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_NIMCALL(tmtstate160026, initmtstate_160034)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, initgenrand_160044)(tmtstate160026* self, NU32 s);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(void, initbyarray_160111)(tmtstate160026* self, NU32* initkey, NI initkeyLen0);
N_NIMCALL(NU32, genrandint32_160324)(tmtstate160026* self);
N_NIMCALL(NI32, genrandint31_160685)(tmtstate160026* self);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(NF, genrandreal1_160705)(tmtstate160026* self);
N_NIMCALL(NF, genrandreal2_160720)(tmtstate160026* self);
N_NIMCALL(NF, genrandreal3_160735)(tmtstate160026* self);
N_NIMCALL(NF, genrandres53_160751)(tmtstate160026* self);
extern TFrame* frameptr_16242;
TNimType NTI160026; /* TMTState */
extern TNimType NTI124; /* uint32 */
TNimType NTI160027; /* array[0..623, uint32] */
extern TNimType NTI108; /* int */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

N_NIMCALL(tmtstate160026, initmtstate_160034)(void) {
	tmtstate160026 result;
	nimfr("init_MTState", "mt19937ar.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(74, "mt19937ar.nim");
	result.Mti = 625;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) - (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU32) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, initgenrand_160044)(tmtstate160026* self, NU32 s) {
	nimfr("init_genrand", "mt19937ar.nim")
	nimln(80, "mt19937ar.nim");
	(*self).Mt[(0)- 0] = s;
	nimln(81, "mt19937ar.nim");
	(*self).Mti = 1;
	{
		nimln(82, "mt19937ar.nim");
		while (1) {
			NI TMP715;
			NI TMP716;
			nimln(82, "mt19937ar.nim");
			if (!((*self).Mti < 624)) goto LA2;
			nimln(83, "mt19937ar.nim");
			if ((NU)((*self).Mti) > (NU)(623)) raiseIndexError();
			nimln(84, "mt19937ar.nim");
			nimln(84, "mt19937ar.nim");
			nimln(84, "mt19937ar.nim");
			nimln(84, "mt19937ar.nim");
			TMP715 = subInt((*self).Mti, 1);
			if ((NU)((NI32)(TMP715)) > (NU)(623)) raiseIndexError();
			nimln(84, "mt19937ar.nim");
			nimln(84, "mt19937ar.nim");
			TMP716 = subInt((*self).Mti, 1);
			if ((NU)((NI32)(TMP716)) > (NU)(623)) raiseIndexError();
			(*self).Mt[((*self).Mti)- 0] = (NU32)((NU32)((NU32)((NU32)(((NU32) 1812433253)) * (NU32)((NU32)((*self).Mt[((NI32)(TMP715))- 0] ^ (NU32)((NU32)((*self).Mt[((NI32)(TMP716))- 0]) >> (NU32)(((NU32) 30))))))) + (NU32)(((NU32) ((*self).Mti))));
			nimln(93, "mt19937ar.nim");
			(*self).Mti = addInt((*self).Mti, 1);
		} LA2: ;
	}
	popFrame();
}

N_NIMCALL(void, initbyarray_160111)(tmtstate160026* self, NU32* initkey, NI initkeyLen0) {
	NI keylength;
	NI i;
	NI j;
	nimfr("init_by_array", "mt19937ar.nim")
	nimln(101, "mt19937ar.nim");
	nimln(101, "mt19937ar.nim");
	keylength = initkeyLen0;
	nimln(102, "mt19937ar.nim");
	initgenrand_160044(self, ((NU32) 19650218));
	nimln(104, "mt19937ar.nim");
	i = 1;
	nimln(105, "mt19937ar.nim");
	j = 0;
	{
		NI k_160139;
		NI HEX3Atmp_160292;
		NI res_160295;
		k_160139 = 0;
		HEX3Atmp_160292 = 0;
		nimln(106, "mt19937ar.nim");
		nimln(106, "mt19937ar.nim");
		{
			nimln(106, "mt19937ar.nim");
			if (!(keylength < 624)) goto LA4;
			HEX3Atmp_160292 = 624;
		}
		goto LA2;
		LA4: ;
		{
			HEX3Atmp_160292 = keylength;
		}
		LA2: ;
		nimln(1560, "system.nim");
		res_160295 = HEX3Atmp_160292;
		{
			nimln(1561, "system.nim");
			while (1) {
				NI TMP717;
				NI TMP718;
				nimln(1561, "system.nim");
				if (!(1 <= res_160295)) goto LA8;
				nimln(1560, "system.nim");
				k_160139 = res_160295;
				nimln(107, "mt19937ar.nim");
				if ((NU)(i) > (NU)(623)) raiseIndexError();
				nimln(108, "mt19937ar.nim");
				if ((NU)(i) > (NU)(623)) raiseIndexError();
				nimln(109, "mt19937ar.nim");
				nimln(108, "mt19937ar.nim");
				nimln(108, "mt19937ar.nim");
				nimln(108, "mt19937ar.nim");
				nimln(108, "mt19937ar.nim");
				TMP717 = subInt(i, 1);
				if ((NU)((NI32)(TMP717)) > (NU)(623)) raiseIndexError();
				nimln(108, "mt19937ar.nim");
				nimln(108, "mt19937ar.nim");
				TMP718 = subInt(i, 1);
				if ((NU)((NI32)(TMP718)) > (NU)(623)) raiseIndexError();
				if ((NU)(j) >= (NU)(initkeyLen0)) raiseIndexError();
				(*self).Mt[(i)- 0] = (NU32)((*self).Mt[(i)- 0] ^ (NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((*self).Mt[((NI32)(TMP717))- 0] ^ (NU32)((NU32)((*self).Mt[((NI32)(TMP718))- 0]) >> (NU32)(((NU32) 30))))) * (NU32)(((NU32) 1664525)))) + (NU32)(initkey[j]))) + (NU32)(((NU32) (j)))));
				nimln(111, "mt19937ar.nim");
				i = addInt(i, 1);
				nimln(112, "mt19937ar.nim");
				j = addInt(j, 1);
				nimln(113, "mt19937ar.nim");
				{
					nimln(113, "mt19937ar.nim");
					if (!(624 <= i)) goto LA11;
					nimln(114, "mt19937ar.nim");
					(*self).Mt[(0)- 0] = (*self).Mt[(623)- 0];
					nimln(115, "mt19937ar.nim");
					i = 1;
				}
				LA11: ;
				nimln(116, "mt19937ar.nim");
				{
					nimln(116, "mt19937ar.nim");
					nimln(116, "mt19937ar.nim");
					if (!((initkeyLen0-1) < j)) goto LA15;
					nimln(117, "mt19937ar.nim");
					j = 0;
				}
				LA15: ;
				nimln(1563, "system.nim");
				res_160295 = subInt(res_160295, 1);
			} LA8: ;
		}
	}
	{
		NI k_160232;
		NI res_160299;
		k_160232 = 0;
		nimln(1560, "system.nim");
		res_160299 = 623;
		{
			nimln(1561, "system.nim");
			while (1) {
				NI TMP719;
				NI TMP720;
				nimln(1561, "system.nim");
				if (!(1 <= res_160299)) goto LA19;
				nimln(1560, "system.nim");
				k_160232 = res_160299;
				nimln(119, "mt19937ar.nim");
				if ((NU)(i) > (NU)(623)) raiseIndexError();
				nimln(120, "mt19937ar.nim");
				if ((NU)(i) > (NU)(623)) raiseIndexError();
				nimln(120, "mt19937ar.nim");
				nimln(120, "mt19937ar.nim");
				nimln(120, "mt19937ar.nim");
				nimln(120, "mt19937ar.nim");
				TMP719 = subInt(i, 1);
				if ((NU)((NI32)(TMP719)) > (NU)(623)) raiseIndexError();
				nimln(120, "mt19937ar.nim");
				nimln(120, "mt19937ar.nim");
				TMP720 = subInt(i, 1);
				if ((NU)((NI32)(TMP720)) > (NU)(623)) raiseIndexError();
				(*self).Mt[(i)- 0] = (NU32)((*self).Mt[(i)- 0] ^ (NU32)((NU32)((NU32)((NU32)((NU32)((*self).Mt[((NI32)(TMP719))- 0] ^ (NU32)((NU32)((*self).Mt[((NI32)(TMP720))- 0]) >> (NU32)(((NU32) 30))))) * (NU32)(((NU32) 1566083941)))) - (NU32)(((NU32) (i)))));
				nimln(123, "mt19937ar.nim");
				i = addInt(i, 1);
				nimln(124, "mt19937ar.nim");
				{
					nimln(124, "mt19937ar.nim");
					if (!(624 <= i)) goto LA22;
					nimln(125, "mt19937ar.nim");
					(*self).Mt[(0)- 0] = (*self).Mt[(623)- 0];
					nimln(126, "mt19937ar.nim");
					i = 1;
				}
				LA22: ;
				nimln(1563, "system.nim");
				res_160299 = subInt(res_160299, 1);
			} LA19: ;
		}
	}
	nimln(127, "mt19937ar.nim");
	(*self).Mt[(0)- 0] = ((NU32) (-2147483647 -1));
	popFrame();
}

N_NIMCALL(NU32, genrandint32_160324)(tmtstate160026* self) {
	NU32 result;
	NU32 y;
	TY160330 mag01;
	nimfr("genrand_int32", "mt19937ar.nim")
	result = 0;
	y = 0;
	memset((void*)mag01, 0, sizeof(mag01));
	nimln(132, "mt19937ar.nim");
	mag01[0] = ((NU32) 0);
	mag01[1] = ((NU32) -1727483681);
	nimln(135, "mt19937ar.nim");
	{
		NI kk;
		nimln(135, "mt19937ar.nim");
		if (!(624 <= (*self).Mti)) goto LA3;
		nimln(138, "mt19937ar.nim");
		{
			nimln(138, "mt19937ar.nim");
			if (!((*self).Mti == 625)) goto LA7;
			nimln(139, "mt19937ar.nim");
			initgenrand_160044(self, ((NU32) 5489));
		}
		LA7: ;
		nimln(141, "mt19937ar.nim");
		kk = 0;
		{
			nimln(142, "mt19937ar.nim");
			while (1) {
				NI TMP721;
				NI TMP722;
				nimln(142, "mt19937ar.nim");
				if (!(kk < 227)) goto LA10;
				nimln(143, "mt19937ar.nim");
				nimln(143, "mt19937ar.nim");
				nimln(143, "mt19937ar.nim");
				if ((NU)(kk) > (NU)(623)) raiseIndexError();
				nimln(143, "mt19937ar.nim");
				nimln(143, "mt19937ar.nim");
				TMP721 = addInt(kk, 1);
				if ((NU)((NI32)(TMP721)) > (NU)(623)) raiseIndexError();
				y = (NU32)((NU32)((*self).Mt[(kk)- 0] & ((NU32) (-2147483647 -1))) | ((NU32) ((NU32)((*self).Mt[((NI32)(TMP721))- 0] & ((NU32) 2147483647)))));
				nimln(144, "mt19937ar.nim");
				if ((NU)(kk) > (NU)(623)) raiseIndexError();
				nimln(144, "mt19937ar.nim");
				nimln(144, "mt19937ar.nim");
				nimln(144, "mt19937ar.nim");
				TMP722 = addInt(kk, 397);
				if ((NU)((NI32)(TMP722)) > (NU)(623)) raiseIndexError();
				nimln(144, "mt19937ar.nim");
				nimln(144, "mt19937ar.nim");
				(*self).Mt[(kk)- 0] = (NU32)((NU32)((*self).Mt[((NI32)(TMP722))- 0] ^ (NU32)((NU32)(y) >> (NU32)(((NU32) 1)))) ^ mag01[((NU32)(y & ((NU32) 1)))- 0]);
				nimln(145, "mt19937ar.nim");
				kk = addInt(kk, 1);
			} LA10: ;
		}
		{
			nimln(146, "mt19937ar.nim");
			while (1) {
				NI TMP723;
				NI TMP724;
				nimln(146, "mt19937ar.nim");
				if (!(kk < 623)) goto LA12;
				nimln(147, "mt19937ar.nim");
				nimln(147, "mt19937ar.nim");
				nimln(147, "mt19937ar.nim");
				if ((NU)(kk) > (NU)(623)) raiseIndexError();
				nimln(147, "mt19937ar.nim");
				nimln(147, "mt19937ar.nim");
				TMP723 = addInt(kk, 1);
				if ((NU)((NI32)(TMP723)) > (NU)(623)) raiseIndexError();
				y = (NU32)((NU32)((*self).Mt[(kk)- 0] & ((NU32) (-2147483647 -1))) | ((NU32) ((NU32)((*self).Mt[((NI32)(TMP723))- 0] & ((NU32) 2147483647)))));
				nimln(148, "mt19937ar.nim");
				if ((NU)(kk) > (NU)(623)) raiseIndexError();
				nimln(148, "mt19937ar.nim");
				nimln(148, "mt19937ar.nim");
				nimln(148, "mt19937ar.nim");
				TMP724 = addInt(kk, -227);
				if ((NU)((NI32)(TMP724)) > (NU)(623)) raiseIndexError();
				nimln(148, "mt19937ar.nim");
				nimln(148, "mt19937ar.nim");
				(*self).Mt[(kk)- 0] = (NU32)((NU32)((*self).Mt[((NI32)(TMP724))- 0] ^ (NU32)((NU32)(y) >> (NU32)(((NU32) 1)))) ^ mag01[((NU32)(y & ((NU32) 1)))- 0]);
				nimln(149, "mt19937ar.nim");
				kk = addInt(kk, 1);
			} LA12: ;
		}
		nimln(150, "mt19937ar.nim");
		nimln(150, "mt19937ar.nim");
		nimln(150, "mt19937ar.nim");
		nimln(150, "mt19937ar.nim");
		y = (NU32)((NU32)((*self).Mt[(623)- 0] & ((NU32) (-2147483647 -1))) | ((NU32) ((NU32)((*self).Mt[(0)- 0] & ((NU32) 2147483647)))));
		nimln(151, "mt19937ar.nim");
		nimln(151, "mt19937ar.nim");
		nimln(151, "mt19937ar.nim");
		nimln(151, "mt19937ar.nim");
		nimln(151, "mt19937ar.nim");
		(*self).Mt[(623)- 0] = (NU32)((NU32)((*self).Mt[(396)- 0] ^ (NU32)((NU32)(y) >> (NU32)(((NU32) 1)))) ^ mag01[((NU32)(y & ((NU32) 1)))- 0]);
		nimln(153, "mt19937ar.nim");
		(*self).Mti = 0;
	}
	LA3: ;
	nimln(155, "mt19937ar.nim");
	if ((NU)((*self).Mti) > (NU)(623)) raiseIndexError();
	y = (*self).Mt[((*self).Mti)- 0];
	nimln(156, "mt19937ar.nim");
	(*self).Mti = addInt((*self).Mti, 1);
	nimln(159, "mt19937ar.nim");
	nimln(159, "mt19937ar.nim");
	nimln(159, "mt19937ar.nim");
	y = (NU32)(y ^ (NU32)((NU32)(y) >> (NU32)(((NU32) 11))));
	nimln(160, "mt19937ar.nim");
	nimln(160, "mt19937ar.nim");
	nimln(160, "mt19937ar.nim");
	nimln(160, "mt19937ar.nim");
	y = (NU32)(y ^ (NU32)((NU32)((NU32)(y) << (NU32)(((NU32) 7))) & ((NU32) -1658038656)));
	nimln(161, "mt19937ar.nim");
	nimln(161, "mt19937ar.nim");
	nimln(161, "mt19937ar.nim");
	nimln(161, "mt19937ar.nim");
	y = (NU32)(y ^ (NU32)((NU32)((NU32)(y) << (NU32)(((NU32) 15))) & ((NU32) -272236544)));
	nimln(162, "mt19937ar.nim");
	nimln(162, "mt19937ar.nim");
	nimln(162, "mt19937ar.nim");
	y = (NU32)(y ^ (NU32)((NU32)(y) >> (NU32)(((NU32) 18))));
	nimln(164, "mt19937ar.nim");
	nimln(164, "mt19937ar.nim");
	result = y;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI32, genrandint31_160685)(tmtstate160026* self) {
	NI32 result;
	NU32 LOC1;
	nimfr("genrand_int31", "mt19937ar.nim")
	result = 0;
	nimln(168, "mt19937ar.nim");
	nimln(168, "mt19937ar.nim");
	nimln(168, "mt19937ar.nim");
	nimln(168, "mt19937ar.nim");
	LOC1 = 0;
	LOC1 = genrandint32_160324(self);
	result = ((NI32)chckRange((NU32)((NU32)(LOC1) >> (NU32)(((NU32) 1))), ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NF, genrandreal1_160705)(tmtstate160026* self) {
	NF result;
	NU32 LOC1;
	nimfr("genrand_real1", "mt19937ar.nim")
	result = 0;
	nimln(172, "mt19937ar.nim");
	nimln(172, "mt19937ar.nim");
	nimln(172, "mt19937ar.nim");
	nimln(172, "mt19937ar.nim");
	LOC1 = 0;
	LOC1 = genrandint32_160324(self);
	result = ((NF)(((NF) (LOC1))) * (NF)(2.3283064370807974e-10));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NF, genrandreal2_160720)(tmtstate160026* self) {
	NF result;
	NU32 LOC1;
	nimfr("genrand_real2", "mt19937ar.nim")
	result = 0;
	nimln(177, "mt19937ar.nim");
	nimln(177, "mt19937ar.nim");
	nimln(177, "mt19937ar.nim");
	nimln(177, "mt19937ar.nim");
	LOC1 = 0;
	LOC1 = genrandint32_160324(self);
	result = ((NF)(((NF) (LOC1))) * (NF)(2.3283064365386963e-10));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NF, genrandreal3_160735)(tmtstate160026* self) {
	NF result;
	NU32 LOC1;
	nimfr("genrand_real3", "mt19937ar.nim")
	result = 0;
	nimln(182, "mt19937ar.nim");
	nimln(182, "mt19937ar.nim");
	nimln(182, "mt19937ar.nim");
	nimln(182, "mt19937ar.nim");
	nimln(182, "mt19937ar.nim");
	LOC1 = 0;
	LOC1 = genrandint32_160324(self);
	result = ((NF)(((NF)(((NF) (LOC1))) + (NF)(5.0000000000000000e-01))) * (NF)(2.3283064365386963e-10));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NF, genrandres53_160751)(tmtstate160026* self) {
	NF result;
	NU32 a;
	NU32 LOC1;
	NU32 b;
	NU32 LOC2;
	nimfr("genrand_res53", "mt19937ar.nim")
	result = 0;
	nimln(188, "mt19937ar.nim");
	nimln(188, "mt19937ar.nim");
	nimln(188, "mt19937ar.nim");
	LOC1 = 0;
	LOC1 = genrandint32_160324(self);
	a = (NU32)((NU32)(LOC1) >> (NU32)(((NU32) 5)));
	nimln(189, "mt19937ar.nim");
	nimln(189, "mt19937ar.nim");
	nimln(189, "mt19937ar.nim");
	LOC2 = 0;
	LOC2 = genrandint32_160324(self);
	b = (NU32)((NU32)(LOC2) >> (NU32)(((NU32) 6)));
	nimln(190, "mt19937ar.nim");
	nimln(190, "mt19937ar.nim");
	nimln(190, "mt19937ar.nim");
	nimln(190, "mt19937ar.nim");
	nimln(190, "mt19937ar.nim");
	result = ((NF)(((NF)(((NF)(((NF) (a))) * (NF)(6.7108864000000000e+07))) + (NF)(((NF) (b))))) * (NF)(1.1102230246251565e-16));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, random_mt19937arInit)(void) {
	nimfr("mt19937ar", "mt19937ar.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, random_mt19937arDatInit)(void) {
static TNimNode* TMP750[2];
static TNimNode TMP713[3];
NTI160026.size = sizeof(tmtstate160026);
NTI160026.kind = 18;
NTI160026.base = 0;
NTI160026.flags = 3;
TMP750[0] = &TMP713[1];
NTI160027.size = sizeof(TY160027);
NTI160027.kind = 16;
NTI160027.base = (&NTI124);
NTI160027.flags = 3;
TMP713[1].kind = 1;
TMP713[1].offset = offsetof(tmtstate160026, Mt);
TMP713[1].typ = (&NTI160027);
TMP713[1].name = "mt";
TMP750[1] = &TMP713[2];
TMP713[2].kind = 1;
TMP713[2].offset = offsetof(tmtstate160026, Mti);
TMP713[2].typ = (&NTI108);
TMP713[2].name = "mti";
TMP713[0].len = 2; TMP713[0].kind = 2; TMP713[0].sons = &TMP750[0];
NTI160026.node = &TMP713[0];
}

