/* Generated by Nim Compiler v0.10.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/jsudlow/Nim/lib -o .nimcache/stdlib_tables.o .nimcache/stdlib_tables.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct table122024 table122024;
typedef struct keyvaluepairseq122027 keyvaluepairseq122027;
typedef struct keyvaluepair122030 keyvaluepair122030;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct table126040 table126040;
typedef struct keyvaluepairseq126043 keyvaluepairseq126043;
typedef struct keyvaluepair126046 keyvaluepair126046;
typedef struct tfont123015 tfont123015;
typedef struct tcell45135 tcell45135;
typedef struct tcellseq45151 tcellseq45151;
typedef struct tgcheap47216 tgcheap47216;
typedef struct tcellset45147 tcellset45147;
typedef struct tpagedesc45143 tpagedesc45143;
typedef struct tmemregion27410 tmemregion27410;
typedef struct tsmallchunk26640 tsmallchunk26640;
typedef struct tllchunk27404 tllchunk27404;
typedef struct tbigchunk26642 tbigchunk26642;
typedef struct tintset26617 tintset26617;
typedef struct ttrunk26613 ttrunk26613;
typedef struct tavlnode27408 tavlnode27408;
typedef struct tgcstat47214 tgcstat47214;
typedef struct tfont122221 tfont122221;
typedef struct tcolor116233 tcolor116233;
typedef struct tbasechunk26638 tbasechunk26638;
typedef struct tfreecell26630 tfreecell26630;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct keyvaluepair122030 {
NU8 Field0;
NI32 Field1;
NIM_BOOL Field2;
};
struct  table122024  {
keyvaluepairseq122027* Data;
NI Counter;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct keyvaluepair126046 {
NU8 Field0;
NimStringDesc* Field1;
tfont123015* Field2;
};
struct  table126040  {
keyvaluepairseq126043* Data;
NI Counter;
};
struct  tcell45135  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq45151  {
NI Len;
NI Cap;
tcell45135** D;
};
struct  tcellset45147  {
NI Counter;
NI Max;
tpagedesc45143* Head;
tpagedesc45143** Data;
};
typedef tsmallchunk26640* TY27422[512];
typedef ttrunk26613* ttrunkbuckets26615[256];
struct  tintset26617  {
ttrunkbuckets26615 Data;
};
struct  tmemregion27410  {
NI Minlargeobj;
NI Maxlargeobj;
TY27422 Freesmallchunks;
tllchunk27404* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26642* Freechunkslist;
tintset26617 Chunkstarts;
tavlnode27408* Root;
tavlnode27408* Deleted;
tavlnode27408* Last;
tavlnode27408* Freeavlnodes;
};
struct  tgcstat47214  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47216  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq45151 Zct;
tcellseq45151 Decstack;
tcellset45147 Cycleroots;
tcellseq45151 Tempstack;
NI Recgclock;
tmemregion27410 Region;
tgcstat47214 Stat;
};
struct  tcolor116233  {
NU8 R;
NU8 G;
NU8 B;
NU8 Unused;
};
struct  tfont123015  {
tfont122221* F;
tcolor116233 Color;
};
typedef NI TY26620[16];
struct  tpagedesc45143  {
tpagedesc45143* Next;
NI Key;
TY26620 Bits;
};
struct  tbasechunk26638  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26640  {
  tbasechunk26638 Sup;
tsmallchunk26640* Next;
tsmallchunk26640* Prev;
tfreecell26630* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27404  {
NI Size;
NI Acc;
tllchunk27404* Next;
};
struct  tbigchunk26642  {
  tbasechunk26638 Sup;
tbigchunk26642* Next;
tbigchunk26642* Prev;
NI Align;
NF Data;
};
struct  ttrunk26613  {
ttrunk26613* Next;
NI Key;
TY26620 Bits;
};
typedef tavlnode27408* TY27414[2];
struct  tavlnode27408  {
TY27414 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfont122221  {
char dummy;
};
struct  tfreecell26630  {
tfreecell26630* Next;
NI Zerofield;
};
struct keyvaluepairseq122027 {
  TGenericSeq Sup;
  keyvaluepair122030 data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq126043 {
  TGenericSeq Sup;
  keyvaluepair126046 data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, mustrehash_110302)(NI length, NI counter);
N_NIMCALL(void, failedassertimpl_85425)(NimStringDesc* msg);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, nexttry_110410)(NI h, NI maxhash);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(NI, rawget_122063)(table122024 t_122070, NI32 key_122073);
static N_INLINE(NI, hash_100804)(NI x);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(void, TMP642)(void* p, NI op);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP645)(void* p, NI op);
N_NIMCALL(NIM_BOOL, ispoweroftwo_107318)(NI x);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NI, rawget_130489)(table126040 t_130496, NimStringDesc* key_130499);
N_NIMCALL(NI, hash_100842)(NimStringDesc* x);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell45135*, usrtocell_48846)(void* usr);
static N_INLINE(void, rtladdzct_50404)(tcell45135* c);
N_NOINLINE(void, addzct_48817)(tcellseq45151* s, tcell45135* c);
N_NIMCALL(void, enlarge_130546)(table126040* t_130555);
N_NIMCALL(void, rawinsert_130616)(table126040* t_130625, keyvaluepairseq126043** data_130633, NimStringDesc* key_130637, tfont123015* val_130639);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(void, enlarge_131079)(table122024* t_131088);
N_NIMCALL(void, rawinsert_131149)(table122024* t_131158, keyvaluepairseq122027** data_131166, NI32 key_131170, NIM_BOOL val_131172);
STRING_LITERAL(TMP375, "length > counter ", 17);
STRING_LITERAL(TMP658, "isPowerOfTwo(initialSize) ", 26);
extern TFrame* frameptr_16242;
TNimType NTI122024; /* Table */
TNimType NTI122030; /* KeyValuePair */
TNimType NTI110009; /* SlotEnum */
extern TNimType NTI115359; /* TKey */
extern TNimType NTI138; /* bool */
TNimType NTI122027; /* KeyValuePairSeq */
extern TNimType NTI108; /* int */
TNimType NTI126040; /* Table */
TNimType NTI126046; /* KeyValuePair */
extern TNimType NTI149; /* string */
extern TNimType NTI123017; /* PFont */
TNimType NTI126043; /* KeyValuePairSeq */
extern tgcheap47216 gch_47244;

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) - (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU32) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

static N_INLINE(NIM_BOOL, mustrehash_110302)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL LOC5;
	NI TMP376;
	NI TMP377;
	NI TMP378;
	nimfr("mustRehash", "tables.nim")
	result = 0;
	nimln(120, "tables.nim");
	{
		nimln(120, "tables.nim");
		nimln(120, "tables.nim");
		if (!!((counter < length))) goto LA3;
		nimln(120, "tables.nim");
		failedassertimpl_85425(((NimStringDesc*) &TMP375));
	}
	LA3: ;
	nimln(121, "tables.nim");
	nimln(121, "tables.nim");
	LOC5 = 0;
	nimln(121, "tables.nim");
	nimln(121, "tables.nim");
	TMP376 = mulInt(length, 2);
	nimln(121, "tables.nim");
	TMP377 = mulInt(counter, 3);
	LOC5 = ((NI32)(TMP376) < (NI32)(TMP377));
	if (LOC5) goto LA6;
	nimln(121, "tables.nim");
	nimln(121, "tables.nim");
	TMP378 = subInt(length, counter);
	LOC5 = ((NI32)(TMP378) < 4);
	LA6: ;
	result = LOC5;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, nexttry_110410)(NI h, NI maxhash) {
	NI result;
	NI TMP379;
	NI TMP380;
	nimfr("nextTry", "tables.nim")
	result = 0;
	nimln(124, "tables.nim");
	nimln(124, "tables.nim");
	nimln(124, "tables.nim");
	nimln(124, "tables.nim");
	TMP379 = mulInt(5, h);
	TMP380 = addInt((NI32)(TMP379), 1);
	result = (NI)((NI32)(TMP380) & maxhash);
	popFrame();
	return result;
}

static N_INLINE(NI, hash_100804)(NI x) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(107, "hashes.nim");
	result = x;
	popFrame();
	return result;
}

N_NIMCALL(NI, rawget_122063)(table122024 t_122070, NI32 key_122073) {
	NI result;
	NI h;
	NI LOC1;
	nimfr("rawGet", "tables.nim")
	result = 0;
	nimln(127, "tables.nim");
	nimln(127, "tables.nim");
	nimln(127, "tables.nim");
	LOC1 = 0;
	LOC1 = hash_100804(((NI) (key_122073)));
	nimln(127, "tables.nim");
	h = (NI)(LOC1 & (t_122070.Data->Sup.len-1));
	{
		nimln(128, "tables.nim");
		while (1) {
			nimln(128, "tables.nim");
			nimln(128, "tables.nim");
			if ((NU)(h) >= (NU)(t_122070.Data->Sup.len)) raiseIndexError();
			if (!!((t_122070.Data->data[h].Field0 == ((NU8) 0)))) goto LA3;
			nimln(129, "tables.nim");
			{
				NIM_BOOL LOC6;
				nimln(129, "tables.nim");
				LOC6 = 0;
				nimln(129, "tables.nim");
				if ((NU)(h) >= (NU)(t_122070.Data->Sup.len)) raiseIndexError();
				LOC6 = (t_122070.Data->data[h].Field1 == key_122073);
				if (!(LOC6)) goto LA7;
				nimln(129, "tables.nim");
				if ((NU)(h) >= (NU)(t_122070.Data->Sup.len)) raiseIndexError();
				LOC6 = (t_122070.Data->data[h].Field0 == ((NU8) 1));
				LA7: ;
				if (!LOC6) goto LA8;
				nimln(130, "tables.nim");
				nimln(130, "tables.nim");
				result = h;
				goto BeforeRet;
			}
			LA8: ;
			nimln(131, "tables.nim");
			nimln(131, "tables.nim");
			h = nexttry_110410(h, (t_122070.Data->Sup.len-1));
		} LA3: ;
	}
	nimln(132, "tables.nim");
	result = -1;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, haskey_122049)(table122024 t_122056, NI32 key_122059) {
	NIM_BOOL result;
	NI LOC1;
	nimfr("hasKey", "tables.nim")
	result = 0;
	nimln(170, "tables.nim");
	nimln(170, "tables.nim");
	nimln(170, "tables.nim");
	LOC1 = 0;
	LOC1 = rawget_122063(t_122056, key_122059);
	result = (0 <= LOC1);
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, HEX5BHEX5D_122110)(table122024 t_122117, NI32 key_122120) {
	NIM_BOOL result;
	NI index;
	nimfr("[]", "tables.nim")
	result = 0;
	nimln(150, "tables.nim");
	index = rawget_122063(t_122117, key_122120);
	nimln(151, "tables.nim");
	{
		nimln(151, "tables.nim");
		if (!(0 <= index)) goto LA3;
		nimln(151, "tables.nim");
		if ((NU)(index) >= (NU)(t_122117.Data->Sup.len)) raiseIndexError();
		result = t_122117.Data->data[index].Field2;
	}
	LA3: ;
	popFrame();
	return result;
}
N_NIMCALL(void, TMP642)(void* p, NI op) {
	keyvaluepairseq122027* a;
	NI LOC1;
	a = (keyvaluepairseq122027*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}
N_NIMCALL(void, TMP645)(void* p, NI op) {
	keyvaluepairseq126043* a;
	NI LOC1;
	a = (keyvaluepairseq126043*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field1, op);
	nimGCvisit((void*)a->data[LOC1].Field2, op);
	}
}

N_NIMCALL(void, inittable_130090)(NI initialsize_130095, table122024* Result) {
	nimfr("initTable", "tables.nim")
	nimln(229, "tables.nim");
	{
		NIM_BOOL LOC3;
		nimln(229, "tables.nim");
		nimln(229, "tables.nim");
		LOC3 = 0;
		LOC3 = ispoweroftwo_107318(initialsize_130095);
		if (!!(LOC3)) goto LA4;
		nimln(229, "tables.nim");
		failedassertimpl_85425(((NimStringDesc*) &TMP658));
	}
	LA4: ;
	nimln(230, "tables.nim");
	(*Result).Counter = 0;
	nimln(231, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).Data), (keyvaluepairseq122027*) newSeq((&NTI122027), initialsize_130095));
	popFrame();
}

N_NIMCALL(void, inittable_130232)(NI initialsize_130237, table126040* Result) {
	nimfr("initTable", "tables.nim")
	nimln(229, "tables.nim");
	{
		NIM_BOOL LOC3;
		nimln(229, "tables.nim");
		nimln(229, "tables.nim");
		LOC3 = 0;
		LOC3 = ispoweroftwo_107318(initialsize_130237);
		if (!!(LOC3)) goto LA4;
		nimln(229, "tables.nim");
		failedassertimpl_85425(((NimStringDesc*) &TMP658));
	}
	LA4: ;
	nimln(230, "tables.nim");
	(*Result).Counter = 0;
	nimln(231, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).Data), (keyvaluepairseq126043*) newSeq((&NTI126043), initialsize_130237));
	popFrame();
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (NI32)((*a).Sup.len * 1));
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, rawget_130489)(table126040 t_130496, NimStringDesc* key_130499) {
	NI result;
	NI h;
	NI LOC1;
	nimfr("rawGet", "tables.nim")
	result = 0;
	nimln(127, "tables.nim");
	nimln(127, "tables.nim");
	nimln(127, "tables.nim");
	LOC1 = 0;
	LOC1 = hash_100842(key_130499);
	nimln(127, "tables.nim");
	h = (NI)(LOC1 & (t_130496.Data->Sup.len-1));
	{
		nimln(128, "tables.nim");
		while (1) {
			nimln(128, "tables.nim");
			nimln(128, "tables.nim");
			if ((NU)(h) >= (NU)(t_130496.Data->Sup.len)) raiseIndexError();
			if (!!((t_130496.Data->data[h].Field0 == ((NU8) 0)))) goto LA3;
			nimln(129, "tables.nim");
			{
				NIM_BOOL LOC6;
				nimln(129, "tables.nim");
				LOC6 = 0;
				nimln(129, "tables.nim");
				if ((NU)(h) >= (NU)(t_130496.Data->Sup.len)) raiseIndexError();
				LOC6 = eqStrings(t_130496.Data->data[h].Field1, key_130499);
				if (!(LOC6)) goto LA7;
				nimln(129, "tables.nim");
				if ((NU)(h) >= (NU)(t_130496.Data->Sup.len)) raiseIndexError();
				LOC6 = (t_130496.Data->data[h].Field0 == ((NU8) 1));
				LA7: ;
				if (!LOC6) goto LA8;
				nimln(130, "tables.nim");
				nimln(130, "tables.nim");
				result = h;
				goto BeforeRet;
			}
			LA8: ;
			nimln(131, "tables.nim");
			nimln(131, "tables.nim");
			h = nexttry_110410(h, (t_130496.Data->Sup.len-1));
		} LA3: ;
	}
	nimln(132, "tables.nim");
	result = -1;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(tcell45135*, usrtocell_48846)(void* usr) {
	tcell45135* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell45135*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell45135))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50404)(tcell45135* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48817((&gch_47244.Zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell45135* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_48846(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell45135* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_48846((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50404(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell45135* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_48846(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_50404(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, rawinsert_130616)(table126040* t_130625, keyvaluepairseq126043** data_130633, NimStringDesc* key_130637, tfont123015* val_130639) {
	NI h;
	NI LOC1;
	NimStringDesc* LOC4;
	nimfr("rawInsert", "tables.nim")
	nimln(135, "tables.nim");
	nimln(135, "tables.nim");
	nimln(135, "tables.nim");
	LOC1 = 0;
	LOC1 = hash_100842(key_130637);
	nimln(135, "tables.nim");
	h = (NI)(LOC1 & ((*data_130633)->Sup.len-1));
	{
		nimln(136, "tables.nim");
		while (1) {
			nimln(136, "tables.nim");
			if ((NU)(h) >= (NU)((*data_130633)->Sup.len)) raiseIndexError();
			if (!((*data_130633)->data[h].Field0 == ((NU8) 1))) goto LA3;
			nimln(137, "tables.nim");
			nimln(137, "tables.nim");
			h = nexttry_110410(h, ((*data_130633)->Sup.len-1));
		} LA3: ;
	}
	nimln(138, "tables.nim");
	if ((NU)(h) >= (NU)((*data_130633)->Sup.len)) raiseIndexError();
	LOC4 = 0;
	LOC4 = (*data_130633)->data[h].Field1; (*data_130633)->data[h].Field1 = copyStringRC1(key_130637);
	if (LOC4) nimGCunrefNoCycle(LOC4);
	nimln(139, "tables.nim");
	if ((NU)(h) >= (NU)((*data_130633)->Sup.len)) raiseIndexError();
	asgnRefNoCycle((void**) (&(*data_130633)->data[h].Field2), val_130639);
	nimln(140, "tables.nim");
	if ((NU)(h) >= (NU)((*data_130633)->Sup.len)) raiseIndexError();
	(*data_130633)->data[h].Field0 = ((NU8) 1);
	popFrame();
}

N_NIMCALL(void, enlarge_130546)(table126040* t_130555) {
	keyvaluepairseq126043* n;
	NI TMP659;
	keyvaluepairseq126043* LOC8;
	nimfr("enlarge", "tables.nim")
	n = 0;
	nimln(178, "tables.nim");
	nimln(178, "tables.nim");
	nimln(178, "tables.nim");
	TMP659 = mulInt((*t_130555).Data->Sup.len, 2);
	n = (keyvaluepairseq126043*) newSeq((&NTI126043), (NI32)(TMP659));
	{
		NI i_130601;
		NI HEX3Atmp_130680;
		NI res_130683;
		i_130601 = 0;
		HEX3Atmp_130680 = 0;
		nimln(179, "tables.nim");
		nimln(179, "tables.nim");
		HEX3Atmp_130680 = ((*t_130555).Data->Sup.len-1);
		nimln(1569, "system.nim");
		res_130683 = 0;
		{
			nimln(1570, "system.nim");
			while (1) {
				nimln(1570, "system.nim");
				if (!(res_130683 <= HEX3Atmp_130680)) goto LA3;
				nimln(1569, "system.nim");
				i_130601 = res_130683;
				nimln(180, "tables.nim");
				{
					nimln(180, "tables.nim");
					if ((NU)(i_130601) >= (NU)((*t_130555).Data->Sup.len)) raiseIndexError();
					if (!((*t_130555).Data->data[i_130601].Field0 == ((NU8) 1))) goto LA6;
					nimln(180, "tables.nim");
					if ((NU)(i_130601) >= (NU)((*t_130555).Data->Sup.len)) raiseIndexError();
					if ((NU)(i_130601) >= (NU)((*t_130555).Data->Sup.len)) raiseIndexError();
					rawinsert_130616(t_130555, (&n), (*t_130555).Data->data[i_130601].Field1, (*t_130555).Data->data[i_130601].Field2);
				}
				LA6: ;
				nimln(1572, "system.nim");
				res_130683 = addInt(res_130683, 1);
			} LA3: ;
		}
	}
	nimln(181, "tables.nim");
	LOC8 = 0;
	LOC8 = (*t_130555).Data;
	unsureAsgnRef((void**) (&(*t_130555).Data), n);
	n = LOC8;
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_130471)(table126040* t_130480, NimStringDesc* key_130484, tfont123015* val_130486) {
	NI index;
	nimfr("[]=", "tables.nim")
	nimln(189, "tables.nim");
	index = rawget_130489((*t_130480), key_130484);
	nimln(190, "tables.nim");
	{
		nimln(190, "tables.nim");
		if (!(0 <= index)) goto LA3;
		nimln(191, "tables.nim");
		if ((NU)(index) >= (NU)((*t_130480).Data->Sup.len)) raiseIndexError();
		asgnRefNoCycle((void**) (&(*t_130480).Data->data[index].Field2), val_130486);
	}
	goto LA1;
	LA3: ;
	{
		nimln(184, "tables.nim");
		{
			NIM_BOOL LOC8;
			nimln(184, "tables.nim");
			nimln(184, "tables.nim");
			LOC8 = 0;
			LOC8 = mustrehash_110302((*t_130480).Data->Sup.len, (*t_130480).Counter);
			if (!LOC8) goto LA9;
			nimln(184, "tables.nim");
			enlarge_130546(t_130480);
		}
		LA9: ;
		nimln(185, "tables.nim");
		rawinsert_130616(t_130480, (&(*t_130480).Data), key_130484, val_130486);
		nimln(186, "tables.nim");
		(*t_130480).Counter = addInt((*t_130480).Counter, 1);
	}
	LA1: ;
	popFrame();
}

N_NIMCALL(tfont123015*, HEX5BHEX5D_130761)(table126040 t_130768, NimStringDesc* key_130771) {
	tfont123015* result;
	NI index;
	nimfr("[]", "tables.nim")
	result = 0;
	nimln(150, "tables.nim");
	index = rawget_130489(t_130768, key_130771);
	nimln(151, "tables.nim");
	{
		nimln(151, "tables.nim");
		if (!(0 <= index)) goto LA3;
		nimln(151, "tables.nim");
		if ((NU)(index) >= (NU)(t_130768.Data->Sup.len)) raiseIndexError();
		result = t_130768.Data->data[index].Field2;
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(void, rawinsert_131149)(table122024* t_131158, keyvaluepairseq122027** data_131166, NI32 key_131170, NIM_BOOL val_131172) {
	NI h;
	NI LOC1;
	nimfr("rawInsert", "tables.nim")
	nimln(135, "tables.nim");
	nimln(135, "tables.nim");
	nimln(135, "tables.nim");
	LOC1 = 0;
	LOC1 = hash_100804(((NI) (key_131170)));
	nimln(135, "tables.nim");
	h = (NI)(LOC1 & ((*data_131166)->Sup.len-1));
	{
		nimln(136, "tables.nim");
		while (1) {
			nimln(136, "tables.nim");
			if ((NU)(h) >= (NU)((*data_131166)->Sup.len)) raiseIndexError();
			if (!((*data_131166)->data[h].Field0 == ((NU8) 1))) goto LA3;
			nimln(137, "tables.nim");
			nimln(137, "tables.nim");
			h = nexttry_110410(h, ((*data_131166)->Sup.len-1));
		} LA3: ;
	}
	nimln(138, "tables.nim");
	if ((NU)(h) >= (NU)((*data_131166)->Sup.len)) raiseIndexError();
	(*data_131166)->data[h].Field1 = key_131170;
	nimln(139, "tables.nim");
	if ((NU)(h) >= (NU)((*data_131166)->Sup.len)) raiseIndexError();
	(*data_131166)->data[h].Field2 = val_131172;
	nimln(140, "tables.nim");
	if ((NU)(h) >= (NU)((*data_131166)->Sup.len)) raiseIndexError();
	(*data_131166)->data[h].Field0 = ((NU8) 1);
	popFrame();
}

N_NIMCALL(void, enlarge_131079)(table122024* t_131088) {
	keyvaluepairseq122027* n;
	NI TMP660;
	keyvaluepairseq122027* LOC8;
	nimfr("enlarge", "tables.nim")
	n = 0;
	nimln(178, "tables.nim");
	nimln(178, "tables.nim");
	nimln(178, "tables.nim");
	TMP660 = mulInt((*t_131088).Data->Sup.len, 2);
	n = (keyvaluepairseq122027*) newSeq((&NTI122027), (NI32)(TMP660));
	{
		NI i_131134;
		NI HEX3Atmp_131213;
		NI res_131216;
		i_131134 = 0;
		HEX3Atmp_131213 = 0;
		nimln(179, "tables.nim");
		nimln(179, "tables.nim");
		HEX3Atmp_131213 = ((*t_131088).Data->Sup.len-1);
		nimln(1569, "system.nim");
		res_131216 = 0;
		{
			nimln(1570, "system.nim");
			while (1) {
				nimln(1570, "system.nim");
				if (!(res_131216 <= HEX3Atmp_131213)) goto LA3;
				nimln(1569, "system.nim");
				i_131134 = res_131216;
				nimln(180, "tables.nim");
				{
					nimln(180, "tables.nim");
					if ((NU)(i_131134) >= (NU)((*t_131088).Data->Sup.len)) raiseIndexError();
					if (!((*t_131088).Data->data[i_131134].Field0 == ((NU8) 1))) goto LA6;
					nimln(180, "tables.nim");
					if ((NU)(i_131134) >= (NU)((*t_131088).Data->Sup.len)) raiseIndexError();
					if ((NU)(i_131134) >= (NU)((*t_131088).Data->Sup.len)) raiseIndexError();
					rawinsert_131149(t_131088, (&n), (*t_131088).Data->data[i_131134].Field1, (*t_131088).Data->data[i_131134].Field2);
				}
				LA6: ;
				nimln(1572, "system.nim");
				res_131216 = addInt(res_131216, 1);
			} LA3: ;
		}
	}
	nimln(181, "tables.nim");
	LOC8 = 0;
	LOC8 = (*t_131088).Data;
	unsureAsgnRef((void**) (&(*t_131088).Data), n);
	n = LOC8;
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_131034)(table122024* t_131043, NI32 key_131047, NIM_BOOL val_131049) {
	NI index;
	nimfr("[]=", "tables.nim")
	nimln(189, "tables.nim");
	index = rawget_122063((*t_131043), key_131047);
	nimln(190, "tables.nim");
	{
		nimln(190, "tables.nim");
		if (!(0 <= index)) goto LA3;
		nimln(191, "tables.nim");
		if ((NU)(index) >= (NU)((*t_131043).Data->Sup.len)) raiseIndexError();
		(*t_131043).Data->data[index].Field2 = val_131049;
	}
	goto LA1;
	LA3: ;
	{
		nimln(184, "tables.nim");
		{
			NIM_BOOL LOC8;
			nimln(184, "tables.nim");
			nimln(184, "tables.nim");
			LOC8 = 0;
			LOC8 = mustrehash_110302((*t_131043).Data->Sup.len, (*t_131043).Counter);
			if (!LOC8) goto LA9;
			nimln(184, "tables.nim");
			enlarge_131079(t_131043);
		}
		LA9: ;
		nimln(185, "tables.nim");
		rawinsert_131149(t_131043, (&(*t_131043).Data), key_131047, val_131049);
		nimln(186, "tables.nim");
		(*t_131043).Counter = addInt((*t_131043).Counter, 1);
	}
	LA1: ;
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit)(void) {
	nimfr("tables", "tables.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit)(void) {
static TNimNode* TMP637[2];
static TNimNode* TMP638[3];
static TNimNode* TMP639[3];
NI TMP641;
static char* NIM_CONST TMP640[3] = {
"seEmpty", 
"seFilled", 
"seDeleted"};
static TNimNode* TMP643[2];
static TNimNode* TMP644[3];
static TNimNode TMP298[18];
NTI122024.size = sizeof(table122024);
NTI122024.kind = 18;
NTI122024.base = 0;
NTI122024.flags = 2;
TMP637[0] = &TMP298[1];
NTI122030.size = sizeof(keyvaluepair122030);
NTI122030.kind = 18;
NTI122030.base = 0;
NTI122030.flags = 3;
TMP638[0] = &TMP298[3];
NTI110009.size = sizeof(NU8);
NTI110009.kind = 14;
NTI110009.base = 0;
NTI110009.flags = 3;
for (TMP641 = 0; TMP641 < 3; TMP641++) {
TMP298[TMP641+4].kind = 1;
TMP298[TMP641+4].offset = TMP641;
TMP298[TMP641+4].name = TMP640[TMP641];
TMP639[TMP641] = &TMP298[TMP641+4];
}
TMP298[7].len = 3; TMP298[7].kind = 2; TMP298[7].sons = &TMP639[0];
NTI110009.node = &TMP298[7];
TMP298[3].kind = 1;
TMP298[3].offset = offsetof(keyvaluepair122030, Field0);
TMP298[3].typ = (&NTI110009);
TMP298[3].name = "Field0";
TMP638[1] = &TMP298[8];
TMP298[8].kind = 1;
TMP298[8].offset = offsetof(keyvaluepair122030, Field1);
TMP298[8].typ = (&NTI115359);
TMP298[8].name = "Field1";
TMP638[2] = &TMP298[9];
TMP298[9].kind = 1;
TMP298[9].offset = offsetof(keyvaluepair122030, Field2);
TMP298[9].typ = (&NTI138);
TMP298[9].name = "Field2";
TMP298[2].len = 3; TMP298[2].kind = 2; TMP298[2].sons = &TMP638[0];
NTI122030.node = &TMP298[2];
NTI122027.size = sizeof(keyvaluepairseq122027*);
NTI122027.kind = 24;
NTI122027.base = (&NTI122030);
NTI122027.flags = 2;
NTI122027.marker = TMP642;
TMP298[1].kind = 1;
TMP298[1].offset = offsetof(table122024, Data);
TMP298[1].typ = (&NTI122027);
TMP298[1].name = "data";
TMP637[1] = &TMP298[10];
TMP298[10].kind = 1;
TMP298[10].offset = offsetof(table122024, Counter);
TMP298[10].typ = (&NTI108);
TMP298[10].name = "counter";
TMP298[0].len = 2; TMP298[0].kind = 2; TMP298[0].sons = &TMP637[0];
NTI122024.node = &TMP298[0];
NTI126040.size = sizeof(table126040);
NTI126040.kind = 18;
NTI126040.base = 0;
NTI126040.flags = 2;
TMP643[0] = &TMP298[12];
NTI126046.size = sizeof(keyvaluepair126046);
NTI126046.kind = 18;
NTI126046.base = 0;
NTI126046.flags = 2;
TMP644[0] = &TMP298[14];
TMP298[14].kind = 1;
TMP298[14].offset = offsetof(keyvaluepair126046, Field0);
TMP298[14].typ = (&NTI110009);
TMP298[14].name = "Field0";
TMP644[1] = &TMP298[15];
TMP298[15].kind = 1;
TMP298[15].offset = offsetof(keyvaluepair126046, Field1);
TMP298[15].typ = (&NTI149);
TMP298[15].name = "Field1";
TMP644[2] = &TMP298[16];
TMP298[16].kind = 1;
TMP298[16].offset = offsetof(keyvaluepair126046, Field2);
TMP298[16].typ = (&NTI123017);
TMP298[16].name = "Field2";
TMP298[13].len = 3; TMP298[13].kind = 2; TMP298[13].sons = &TMP644[0];
NTI126046.node = &TMP298[13];
NTI126043.size = sizeof(keyvaluepairseq126043*);
NTI126043.kind = 24;
NTI126043.base = (&NTI126046);
NTI126043.flags = 2;
NTI126043.marker = TMP645;
TMP298[12].kind = 1;
TMP298[12].offset = offsetof(table126040, Data);
TMP298[12].typ = (&NTI126043);
TMP298[12].name = "data";
TMP643[1] = &TMP298[17];
TMP298[17].kind = 1;
TMP298[17].offset = offsetof(table126040, Counter);
TMP298[17].typ = (&NTI108);
TMP298[17].name = "counter";
TMP298[11].len = 2; TMP298[11].kind = 2; TMP298[11].sons = &TMP643[0];
NTI126040.node = &TMP298[11];
}

