/* Generated by Nim Compiler v0.10.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/jsudlow/Nim/lib -o .nimcache/stdlib_math.o .nimcache/stdlib_math.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <math.h>

#include <stdlib.h>
typedef struct runningstat108844 runningstat108844;
struct  runningstat108844  {
NI N;
NF Sum;
NF Min;
NF Max;
NF Mean;
NF Oldm;
NF Olds;
NF News;
};
N_NIMCALL(NU8, classify_107226)(NF x);
N_NIMCALL(NI, binom_107242)(NI n, NI k);
N_NIMCALL(NI, fac_107281)(NI n);
N_NIMCALL(NIM_BOOL, ispoweroftwo_107318)(NI x);
N_NIMCALL(NI, nextpoweroftwo_107328)(NI x);
N_NIMCALL(NI, countbits32_107828)(NI32 n);
N_NIMCALL(NF, sum_107895)(NF* x_107901, NI x_107901Len0);
N_NIMCALL(NF, mean_107888)(NF* x, NI xLen0);
N_NIMCALL(NF, variance_107976)(NF* x, NI xLen0);
N_NIMCALL(NF, log2_108055)(NF x);
N_NIMCALL(NF, random_108029)(NF max);
N_NIMCALL(void, randomize_108035)(void);
N_NIMCALL(void, randomize_108040)(NI seed);
N_NIMCALL(NF, ntepochTime)(void);
N_NIMCALL(NI, random_108023)(NI max);
N_NIMCALL(NF, mod_108804)(NF x, NF y);
N_NIMCALL(void, push_108861)(runningstat108844* s, NF x);
N_NIMCALL(void, push_108885)(runningstat108844* s, NI x);
N_NIMCALL(NF, variance_108896)(runningstat108844* s);
N_NIMCALL(NF, standarddeviation_108907)(runningstat108844* s);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
extern TFrame* frameptr_16242;

N_NIMCALL(NU8, classify_107226)(NF x) {
	NU8 result;
	result = 0;
	{
		if (!(x == 0.0)) goto LA3;
		{
			if (!(((NF)(1.0000000000000000e+00) / (NF)(x)) == INF)) goto LA7;
			result = ((NU8) 2);
			goto BeforeRet;
		}
		goto LA5;
		LA7: ;
		{
			result = ((NU8) 3);
			goto BeforeRet;
		}
		LA5: ;
	}
	LA3: ;
	{
		if (!(((NF)(x) * (NF)(5.0000000000000000e-01)) == x)) goto LA12;
		{
			if (!(0.0 < x)) goto LA16;
			result = ((NU8) 5);
			goto BeforeRet;
		}
		goto LA14;
		LA16: ;
		{
			result = ((NU8) 6);
			goto BeforeRet;
		}
		LA14: ;
	}
	LA12: ;
	{
		if (!!((x == x))) goto LA21;
		result = ((NU8) 4);
		goto BeforeRet;
	}
	LA21: ;
	result = ((NU8) 0);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, binom_107242)(NI n, NI k) {
	NI result;
	result = 0;
	{
		if (!(k <= 0)) goto LA3;
		result = 1;
		goto BeforeRet;
	}
	LA3: ;
	{
		if (!(n < (NI32)(2 * k))) goto LA7;
		result = binom_107242(n, (NI32)(n - k));
		goto BeforeRet;
	}
	LA7: ;
	result = n;
	{
		NI i_107260;
		NI res_107264;
		i_107260 = 0;
		res_107264 = 2;
		{
			while (1) {
				if (!(res_107264 <= k)) goto LA11;
				i_107260 = res_107264;
				result = (NI32)((NI32)(result * (NI32)((NI32)(n + 1) - i_107260)) / i_107260);
				res_107264 += 1;
			} LA11: ;
		}
	}
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, fac_107281)(NI n) {
	NI result;
	result = 0;
	result = 1;
	{
		NI i_107297;
		NI res_107301;
		i_107297 = 0;
		res_107301 = 2;
		{
			while (1) {
				if (!(res_107301 <= n)) goto LA3;
				i_107297 = res_107301;
				result = (NI32)(result * i_107297);
				res_107301 += 1;
			} LA3: ;
		}
	}
	return result;
}

N_NIMCALL(NIM_BOOL, ispoweroftwo_107318)(NI x) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = !((x == 0));
	if (!(LOC1)) goto LA2;
	LOC1 = ((NI)(x & (NI32)(x - 1)) == 0);
	LA2: ;
	result = LOC1;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, nextpoweroftwo_107328)(NI x) {
	NI result;
	result = 0;
	result = (NI32)(x - 1);
	result = (NI)(result | (NI)((NU32)(result) >> (NU32)(4)));
	result = (NI)(result | (NI)((NU32)(result) >> (NU32)(2)));
	result = (NI)(result | (NI)((NU32)(result) >> (NU32)(1)));
	result += ((NI) ((NI32)(1 + ((NI) ((x <= 0))))));
	return result;
}

N_NIMCALL(NI, countbits32_107828)(NI32 n) {
	NI result;
	NI32 v;
	result = 0;
	v = n;
	v = (NI32)((NU32)(v) - (NU32)((NI32)((NI32)((NU32)(v) >> (NU32)(((NI32) 1))) & ((NI32) 1431655765))));
	v = (NI32)((NU32)((NI32)(v & ((NI32) 858993459))) + (NU32)((NI32)((NI32)((NU32)(v) >> (NU32)(((NI32) 2))) & ((NI32) 858993459))));
	result = ((NI) ((NI32)((NU32)((NI32)((NU32)((NI32)((NI32)((NU32)(v) + (NU32)((NI32)((NU32)(v) >> (NU32)(((NI32) 4))))) & ((NI32) 252645135))) * (NU32)(((NI32) 16843009)))) >> (NU32)(((NI32) 24)))));
	return result;
}

N_NIMCALL(NF, sum_107895)(NF* x_107901, NI x_107901Len0) {
	NF result;
	result = 0;
	{
		NF i_107946;
		NI i_107950;
		i_107946 = 0;
		i_107950 = 0;
		{
			while (1) {
				if (!(i_107950 < x_107901Len0)) goto LA3;
				i_107946 = x_107901[i_107950];
				result = ((NF)(result) + (NF)(i_107946));
				i_107950 += 1;
			} LA3: ;
		}
	}
	return result;
}

N_NIMCALL(NF, mean_107888)(NF* x, NI xLen0) {
	NF result;
	NF LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = sum_107895(x, xLen0);
	result = ((NF)(LOC1) / (NF)(((double) (xLen0))));
	return result;
}

N_NIMCALL(NF, variance_107976)(NF* x, NI xLen0) {
	NF result;
	NF m;
	result = 0;
	result = 0.0;
	m = mean_107888(x, xLen0);
	{
		NI i_107993;
		NI HEX3Atmp_108003;
		NI res_108006;
		i_107993 = 0;
		HEX3Atmp_108003 = 0;
		HEX3Atmp_108003 = (xLen0-1);
		res_108006 = 0;
		{
			while (1) {
				NF diff;
				if (!(res_108006 <= HEX3Atmp_108003)) goto LA3;
				i_107993 = res_108006;
				diff = ((NF)(x[i_107993]) - (NF)(m));
				result = ((NF)(result) + (NF)(((NF)(diff) * (NF)(diff))));
				res_108006 += 1;
			} LA3: ;
		}
	}
	result = ((NF)(result) / (NF)(((double) (xLen0))));
	return result;
}

N_NIMCALL(NF, log2_108055)(NF x) {
	NF result;
	NF LOC1;
	NF LOC2;
	result = 0;
	LOC1 = 0;
	LOC1 = log(x);
	LOC2 = 0;
	LOC2 = log(2.0000000000000000e+00);
	result = ((NF)(LOC1) / (NF)(LOC2));
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NF, random_108029)(NF max) {
	NF result;
	NF LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = drand48();
	result = ((NF)(LOC1) * (NF)(max));
	return result;
}

N_NIMCALL(void, randomize_108040)(NI seed) {
	srand(((int) (seed)));
	srand48(seed);
}

N_NIMCALL(void, randomize_108035)(void) {
	union { NF source; NI dest; } LOC1;
	LOC1.source = ntepochTime();
	randomize_108040(LOC1.dest);
}

N_NIMCALL(NI, random_108023)(NI max) {
	NI result;
	int LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = rand();
	result = (NI32)(((NI) (LOC1)) % max);
	return result;
}

N_NIMCALL(NF, mod_108804)(NF x, NF y) {
	NF result;
	result = 0;
	{
		if (!(y == 0.0)) goto LA3;
		result = x;
	}
	goto LA1;
	LA3: ;
	{
		NF LOC6;
		LOC6 = 0;
		LOC6 = floor(((NF)(x) / (NF)(y)));
		result = ((NF)(x) - (NF)(((NF)(y) * (NF)(LOC6))));
	}
	LA1: ;
	return result;
}

N_NIMCALL(void, push_108861)(runningstat108844* s, NF x) {
	(*s).N += 1;
	{
		if (!((*s).N == 1)) goto LA3;
		(*s).Min = x;
		(*s).Max = x;
		(*s).Oldm = x;
		(*s).Mean = x;
		(*s).Olds = 0.0;
	}
	goto LA1;
	LA3: ;
	{
		{
			if (!(x < (*s).Min)) goto LA8;
			(*s).Min = x;
		}
		LA8: ;
		{
			if (!((*s).Max < x)) goto LA12;
			(*s).Max = x;
		}
		LA12: ;
		(*s).Mean = ((NF)((*s).Oldm) + (NF)(((NF)(((NF)(x) - (NF)((*s).Oldm))) / (NF)(((double) ((*s).N))))));
		(*s).News = ((NF)((*s).Olds) + (NF)(((NF)(((NF)(x) - (NF)((*s).Oldm))) * (NF)(((NF)(x) - (NF)((*s).Mean))))));
		(*s).Oldm = (*s).Mean;
		(*s).Olds = (*s).News;
	}
	LA1: ;
	(*s).Sum = ((NF)((*s).Sum) + (NF)(x));
}

N_NIMCALL(void, push_108885)(runningstat108844* s, NI x) {
	push_108861(s, ((double) (x)));
}

N_NIMCALL(NF, variance_108896)(runningstat108844* s) {
	NF result;
	result = 0;
	{
		if (!(1 < (*s).N)) goto LA3;
		result = ((NF)((*s).News) / (NF)(((double) ((NI32)((*s).N - 1)))));
	}
	LA3: ;
	return result;
}

N_NIMCALL(NF, standarddeviation_108907)(runningstat108844* s) {
	NF result;
	NF LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = variance_108896(s);
	result = sqrt(LOC1);
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit)(void) {
	nimfr("math", "math.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit)(void) {
}

