/* Generated by Nim Compiler v0.10.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/jsudlow/Nim/lib -o .nimcache/stdlib_sdl_ttf.o .nimcache/stdlib_sdl_ttf.c */
#define NIM_INTBITS 32
#include "nimbase.h"
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tversion115357 tversion115357;
typedef struct tfont122221 tfont122221;
typedef struct trwops115297 trwops115297;
typedef struct tsurface116255 tsurface116255;
typedef struct tcolor116233 tcolor116233;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tmem115285 tmem115285;
typedef struct tpixelformat116245 tpixelformat116245;
typedef struct trect116227 trect116227;
typedef struct tpalette116241 tpalette116241;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(tversion115357*, TY122226) (void);
typedef N_CDECL_PTR(void, TY122232) (int swapped);
typedef N_CDECL_PTR(int, TY122238) (void);
typedef N_CDECL_PTR(tfont122221*, TY122243) (NCSTRING filename, int ptsize);
typedef N_CDECL_PTR(tfont122221*, TY122250) (NCSTRING filename, int ptsize, NI32 index);
typedef N_CDECL_PTR(tfont122221*, TY122258) (trwops115297* src, int freesrc, int ptsize);
typedef N_CDECL_PTR(tfont122221*, TY122266) (trwops115297* src, int freesrc, int ptsize, NI32 index);
typedef N_CDECL_PTR(int, TY122275) (tfont122221* font);
typedef N_CDECL_PTR(void, TY122281) (tfont122221* font, int style);
typedef N_CDECL_PTR(int, TY122288) (tfont122221* font);
typedef N_CDECL_PTR(int, TY122294) (tfont122221* font);
typedef N_CDECL_PTR(int, TY122300) (tfont122221* font);
typedef N_CDECL_PTR(int, TY122306) (tfont122221* font);
typedef N_CDECL_PTR(NI32, TY122312) (tfont122221* font);
typedef N_CDECL_PTR(int, TY122318) (tfont122221* font);
typedef N_CDECL_PTR(NCSTRING, TY122324) (tfont122221* font);
typedef N_CDECL_PTR(NCSTRING, TY122330) (tfont122221* font);
typedef N_CDECL_PTR(int, TY122336) (tfont122221* font, NU16 ch, int* minx, int* maxx, int* miny, int* maxy, int* advance);
typedef N_CDECL_PTR(int, TY122353) (tfont122221* font, NCSTRING text, int* w, int* y);
typedef N_CDECL_PTR(int, TY122364) (tfont122221* font, NCSTRING text, int* w, int* y);
typedef N_CDECL_PTR(int, TY122375) (tfont122221* font, NU16* text, int* w, int* y);
struct  tcolor116233  {
NU8 R;
NU8 G;
NU8 B;
NU8 Unused;
};
typedef N_CDECL_PTR(tsurface116255*, TY122386) (tfont122221* font, NCSTRING text, tcolor116233 fg);
typedef N_CDECL_PTR(tsurface116255*, TY122394) (tfont122221* font, NU16* text, tcolor116233 fg);
typedef N_CDECL_PTR(tsurface116255*, TY122402) (tfont122221* font, NU16 ch, tcolor116233 fg);
typedef N_CDECL_PTR(tsurface116255*, TY122410) (tfont122221* font, NCSTRING text, tcolor116233 fg, tcolor116233 bg);
typedef N_CDECL_PTR(tsurface116255*, TY122419) (tfont122221* font, NCSTRING text, tcolor116233 fg, tcolor116233 bg);
typedef N_CDECL_PTR(tsurface116255*, TY122428) (tfont122221* font, NU16* text, tcolor116233 fg, tcolor116233 bg);
typedef N_CDECL_PTR(tsurface116255*, TY122437) (tfont122221* font, NU16 ch, tcolor116233 fg, tcolor116233 bg);
typedef N_CDECL_PTR(tsurface116255*, TY122446) (tfont122221* font, NCSTRING text, tcolor116233 fg);
typedef N_CDECL_PTR(tsurface116255*, TY122454) (tfont122221* font, NCSTRING text, tcolor116233 fg);
typedef N_CDECL_PTR(tsurface116255*, TY122462) (tfont122221* font, NU16* text, tcolor116233 fg);
typedef N_CDECL_PTR(tsurface116255*, TY122470) (tfont122221* font, NU16 ch, tcolor116233 fg);
typedef N_CDECL_PTR(void, TY122478) (tfont122221* font);
typedef N_CDECL_PTR(void, TY122484) (void);
typedef N_CDECL_PTR(int, TY122489) (void);
struct  tversion115357  {
NU8 Major;
NU8 Minor;
NU8 Patch;
};
typedef N_CDECL_PTR(tsurface116255*, TY122505) (tfont122221* font, NCSTRING text, tcolor116233 fg);
struct  tfont122221  {
char dummy;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CDECL_PTR(NI, tseek115289) (trwops115297* context, NI offset, NI whence);
typedef N_CDECL_PTR(NI, tread115291) (trwops115297* context, void* theptr, NI size, NI maxnum);
typedef N_CDECL_PTR(NI, twrite115293) (trwops115297* context, void* theptr, NI size, NI num);
typedef N_CDECL_PTR(NI, tclose115295) (trwops115297* context);
struct  tmem115285  {
NU8* Base;
NU8* Here;
NU8* Stop;
};
struct  trwops115297  {
tseek115289 Seek;
tread115291 Read;
twrite115293 Write;
tclose115295 Closefile;
int Thetype;
tmem115285 Mem;
};
struct  trect116227  {
NI16 X;
NI16 Y;
NU16 W;
NU16 H;
};
struct  tsurface116255  {
NI32 Flags;
tpixelformat116245* Format;
int W;
int H;
NU16 Pitch;
void* Pixels;
int Offset;
void* Hwdata;
trect116227 Cliprect;
NI32 Unused1;
NI32 Locked;
void* Blitmap;
int Formatversion;
int Refcount;
};
struct  tpixelformat116245  {
tpalette116241* Palette;
NU8 Bitsperpixel;
NU8 Bytesperpixel;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
NI32 Rmask;
NI32 Gmask;
NI32 Bmask;
NI32 Amask;
NI32 Colorkey;
NU8 Alpha;
};
struct  tpalette116241  {
NI Ncolors;
tcolor116233* Colors;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
N_NIMCALL(void, version_122493)(tversion115357* x);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
STRING_LITERAL(TMP390, "libSDL_ttf.so", 13);
STRING_LITERAL(TMP391, "libSDL_ttf.so.1", 15);
STRING_LITERAL(TMP392, "libSDL_ttf.so.0", 15);
STRING_LITERAL(TMP393, "libSDL_ttf-2.0.so", 17);
STRING_LITERAL(TMP394, "libSDL_ttf-2.0.so.1", 19);
STRING_LITERAL(TMP395, "libSDL_ttf-2.0.so.0", 19);
STRING_LITERAL(TMP396, "libSDL_ttf(|-2.0).so(|.1|.0)", 28);
static void* TMP389;
TY122226 Dl_122225;
TY122232 Dl_122231;
TY122238 Dl_122237;
TY122243 Dl_122242;
TY122250 Dl_122249;
TY122258 Dl_122257;
TY122266 Dl_122265;
TY122275 Dl_122274;
TY122281 Dl_122280;
TY122288 Dl_122287;
TY122294 Dl_122293;
TY122300 Dl_122299;
TY122306 Dl_122305;
TY122312 Dl_122311;
TY122318 Dl_122317;
TY122324 Dl_122323;
TY122330 Dl_122329;
TY122336 Dl_122335;
TY122353 Dl_122352;
TY122364 Dl_122363;
TY122375 Dl_122374;
TY122386 Dl_122385;
TY122394 Dl_122393;
TY122402 Dl_122401;
TY122410 Dl_122409;
TY122419 Dl_122418;
TY122428 Dl_122427;
TY122437 Dl_122436;
TY122446 Dl_122445;
TY122454 Dl_122453;
TY122462 Dl_122461;
TY122470 Dl_122469;
TY122478 Dl_122477;
TY122484 Dl_122483;
TY122489 Dl_122488;
extern TFrame* frameptr_16242;
TY122505 Dl_122504;
TNimType NTI122221; /* TFont */
TNimType NTI122219; /* PFont */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

N_NIMCALL(void, version_122493)(tversion115357* x) {
	nimfr("version", "sdl_ttf.nim")
	nimln(331, "sdl_ttf.nim");
	(*x).Major = ((NU8) 2);
	nimln(332, "sdl_ttf.nim");
	(*x).Minor = ((NU8) 0);
	nimln(333, "sdl_ttf.nim");
	(*x).Patch = ((NU8) 8);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_sdl_ttfInit)(void) {
	nimfr("sdl_ttf", "sdl_ttf.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_sdl_ttfDatInit)(void) {
static TNimNode TMP387[1];
NTI122221.size = sizeof(tfont122221);
NTI122221.kind = 18;
NTI122221.base = 0;
NTI122221.flags = 3;
TMP387[0].len = 0; TMP387[0].kind = 2;
NTI122221.node = &TMP387[0];
NTI122219.size = sizeof(tfont122221*);
NTI122219.kind = 21;
NTI122219.base = (&NTI122221);
NTI122219.flags = 3;
if (!((TMP389 = nimLoadLibrary((NimStringDesc*) &TMP390))
||(TMP389 = nimLoadLibrary((NimStringDesc*) &TMP391))
||(TMP389 = nimLoadLibrary((NimStringDesc*) &TMP392))
||(TMP389 = nimLoadLibrary((NimStringDesc*) &TMP393))
||(TMP389 = nimLoadLibrary((NimStringDesc*) &TMP394))
||(TMP389 = nimLoadLibrary((NimStringDesc*) &TMP395))
)) nimLoadLibraryError((NimStringDesc*) &TMP396);
	Dl_122225 = (TY122226) nimGetProcAddr(TMP389, "TTF_Linked_Version");
	Dl_122231 = (TY122232) nimGetProcAddr(TMP389, "TTF_ByteSwappedUNICODE");
	Dl_122237 = (TY122238) nimGetProcAddr(TMP389, "TTF_Init");
	Dl_122242 = (TY122243) nimGetProcAddr(TMP389, "TTF_OpenFont");
	Dl_122249 = (TY122250) nimGetProcAddr(TMP389, "TTF_OpenFontIndex");
	Dl_122257 = (TY122258) nimGetProcAddr(TMP389, "TTF_OpenFontRW");
	Dl_122265 = (TY122266) nimGetProcAddr(TMP389, "TTF_OpenFontIndexRW");
	Dl_122274 = (TY122275) nimGetProcAddr(TMP389, "TTF_GetFontStyle");
	Dl_122280 = (TY122281) nimGetProcAddr(TMP389, "TTF_SetFontStyle");
	Dl_122287 = (TY122288) nimGetProcAddr(TMP389, "TTF_FontHeight");
	Dl_122293 = (TY122294) nimGetProcAddr(TMP389, "TTF_FontAscent");
	Dl_122299 = (TY122300) nimGetProcAddr(TMP389, "TTF_FontDescent");
	Dl_122305 = (TY122306) nimGetProcAddr(TMP389, "TTF_FontLineSkip");
	Dl_122311 = (TY122312) nimGetProcAddr(TMP389, "TTF_FontFaces");
	Dl_122317 = (TY122318) nimGetProcAddr(TMP389, "TTF_FontFaceIsFixedWidth");
	Dl_122323 = (TY122324) nimGetProcAddr(TMP389, "TTF_FontFaceFamilyName");
	Dl_122329 = (TY122330) nimGetProcAddr(TMP389, "TTF_FontFaceStyleName");
	Dl_122335 = (TY122336) nimGetProcAddr(TMP389, "TTF_GlyphMetrics");
	Dl_122352 = (TY122353) nimGetProcAddr(TMP389, "TTF_SizeText");
	Dl_122363 = (TY122364) nimGetProcAddr(TMP389, "TTF_SizeUTF8");
	Dl_122374 = (TY122375) nimGetProcAddr(TMP389, "TTF_SizeUNICODE");
	Dl_122385 = (TY122386) nimGetProcAddr(TMP389, "TTF_RenderUTF8_Solid");
	Dl_122393 = (TY122394) nimGetProcAddr(TMP389, "TTF_RenderUNICODE_Solid");
	Dl_122401 = (TY122402) nimGetProcAddr(TMP389, "TTF_RenderGlyph_Solid");
	Dl_122409 = (TY122410) nimGetProcAddr(TMP389, "TTF_RenderText_Shaded");
	Dl_122418 = (TY122419) nimGetProcAddr(TMP389, "TTF_RenderUTF8_Shaded");
	Dl_122427 = (TY122428) nimGetProcAddr(TMP389, "TTF_RenderUNICODE_Shaded");
	Dl_122436 = (TY122437) nimGetProcAddr(TMP389, "TTF_RenderGlyph_Shaded");
	Dl_122445 = (TY122446) nimGetProcAddr(TMP389, "TTF_RenderText_Blended");
	Dl_122453 = (TY122454) nimGetProcAddr(TMP389, "TTF_RenderUTF8_Blended");
	Dl_122461 = (TY122462) nimGetProcAddr(TMP389, "TTF_RenderUNICODE_Blended");
	Dl_122469 = (TY122470) nimGetProcAddr(TMP389, "TTF_RenderGlyph_Blended");
	Dl_122477 = (TY122478) nimGetProcAddr(TMP389, "TTF_CloseFont");
	Dl_122483 = (TY122484) nimGetProcAddr(TMP389, "TTF_Quit");
	Dl_122488 = (TY122489) nimGetProcAddr(TMP389, "TTF_WasInit");
	Dl_122504 = (TY122505) nimGetProcAddr(TMP389, "TTF_RenderText_Solid");
}

