/* Generated by Nim Compiler v0.10.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/jsudlow/Nim/lib -o .nimcache/stdlib_colors.o .nimcache/stdlib_colors.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>
typedef struct TY99179 TY99179;
typedef struct TY99551 TY99551;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct valueerror3249 valueerror3249;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell45135 tcell45135;
typedef struct tcellseq45151 tcellseq45151;
typedef struct tgcheap47216 tgcheap47216;
typedef struct tcellset45147 tcellset45147;
typedef struct tpagedesc45143 tpagedesc45143;
typedef struct tmemregion27410 tmemregion27410;
typedef struct tsmallchunk26640 tsmallchunk26640;
typedef struct tllchunk27404 tllchunk27404;
typedef struct tbigchunk26642 tbigchunk26642;
typedef struct tintset26617 tintset26617;
typedef struct ttrunk26613 ttrunk26613;
typedef struct tavlnode27408 tavlnode27408;
typedef struct tgcstat47214 tgcstat47214;
typedef struct tbasechunk26638 tbasechunk26638;
typedef struct tfreecell26630 tfreecell26630;
struct TY99179 {
NI Field0;
NI Field1;
NI Field2;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct TY99551 {
NimStringDesc* Field0;
NI Field1;
};
typedef TY99551 TY99550[140];
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  valueerror3249  {
  Exception Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tcell45135  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq45151  {
NI Len;
NI Cap;
tcell45135** D;
};
struct  tcellset45147  {
NI Counter;
NI Max;
tpagedesc45143* Head;
tpagedesc45143** Data;
};
typedef tsmallchunk26640* TY27422[512];
typedef ttrunk26613* ttrunkbuckets26615[256];
struct  tintset26617  {
ttrunkbuckets26615 Data;
};
struct  tmemregion27410  {
NI Minlargeobj;
NI Maxlargeobj;
TY27422 Freesmallchunks;
tllchunk27404* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26642* Freechunkslist;
tintset26617 Chunkstarts;
tavlnode27408* Root;
tavlnode27408* Deleted;
tavlnode27408* Last;
tavlnode27408* Freeavlnodes;
};
struct  tgcstat47214  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47216  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq45151 Zct;
tcellseq45151 Decstack;
tcellset45147 Cycleroots;
tcellseq45151 Tempstack;
NI Recgclock;
tmemregion27410 Region;
tgcstat47214 Stat;
};
typedef NI TY26620[16];
struct  tpagedesc45143  {
tpagedesc45143* Next;
NI Key;
TY26620 Bits;
};
struct  tbasechunk26638  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26640  {
  tbasechunk26638 Sup;
tsmallchunk26640* Next;
tsmallchunk26640* Prev;
tfreecell26630* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27404  {
NI Size;
NI Acc;
tllchunk27404* Next;
};
struct  tbigchunk26642  {
  tbasechunk26638 Sup;
tbigchunk26642* Next;
tbigchunk26642* Prev;
NI Align;
NF Data;
};
struct  ttrunk26613  {
ttrunk26613* Next;
NI Key;
TY26620 Bits;
};
typedef tavlnode27408* TY27414[2];
struct  tavlnode27408  {
TY27414 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell26630  {
tfreecell26630* Next;
NI Zerofield;
};
static N_INLINE(NI, satplus_99060)(NI a, NI b);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, satminus_99083)(NI a, NI b);
N_NIMCALL(NI, HEX2B_99104)(NI a, NI b);
N_NIMCALL(NI, HEX2D_99140)(NI a, NI b);
N_NIMCALL(TY99179, extractrgb_99176)(NI a);
N_NIMCALL(NI, intensity_99201)(NI a, NF f);
N_NIMCALL(NimStringDesc*, HEX24_99695)(NI c);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, nsuToHex)(NI64 x, NI len);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NI, binarystrsearch_99707)(TY99551* x, NI xLen0, NimStringDesc* y);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(NI, cmp_4517)(NimStringDesc* x, NimStringDesc* y);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NI, parsecolor_99742)(NimStringDesc* name);
N_NIMCALL(NI, nsuParseHexInt)(NimStringDesc* s);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell45135*, usrtocell_48846)(void* usr);
static N_INLINE(void, rtladdzct_50404)(tcell45135* c);
N_NOINLINE(void, addzct_48817)(tcellseq45151* s, tcell45135* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NIM_BOOL, iscolor_99776)(NimStringDesc* name);
N_NIMCALL(NI, rgb_99826)(NI r, NI g, NI b);
STRING_LITERAL(TMP139, "aliceblue", 9);
STRING_LITERAL(TMP140, "antiquewhite", 12);
STRING_LITERAL(TMP141, "aqua", 4);
STRING_LITERAL(TMP142, "aquamarine", 10);
STRING_LITERAL(TMP143, "azure", 5);
STRING_LITERAL(TMP144, "beige", 5);
STRING_LITERAL(TMP145, "bisque", 6);
STRING_LITERAL(TMP146, "black", 5);
STRING_LITERAL(TMP147, "blanchedalmond", 14);
STRING_LITERAL(TMP148, "blue", 4);
STRING_LITERAL(TMP149, "blueviolet", 10);
STRING_LITERAL(TMP150, "brown", 5);
STRING_LITERAL(TMP151, "burlywood", 9);
STRING_LITERAL(TMP152, "cadetblue", 9);
STRING_LITERAL(TMP153, "chartreuse", 10);
STRING_LITERAL(TMP154, "chocolate", 9);
STRING_LITERAL(TMP155, "coral", 5);
STRING_LITERAL(TMP156, "cornflowerblue", 14);
STRING_LITERAL(TMP157, "cornsilk", 8);
STRING_LITERAL(TMP158, "crimson", 7);
STRING_LITERAL(TMP159, "cyan", 4);
STRING_LITERAL(TMP160, "darkblue", 8);
STRING_LITERAL(TMP161, "darkcyan", 8);
STRING_LITERAL(TMP162, "darkgoldenrod", 13);
STRING_LITERAL(TMP163, "darkgray", 8);
STRING_LITERAL(TMP164, "darkgreen", 9);
STRING_LITERAL(TMP165, "darkkhaki", 9);
STRING_LITERAL(TMP166, "darkmagenta", 11);
STRING_LITERAL(TMP167, "darkolivegreen", 14);
STRING_LITERAL(TMP168, "darkorange", 10);
STRING_LITERAL(TMP169, "darkorchid", 10);
STRING_LITERAL(TMP170, "darkred", 7);
STRING_LITERAL(TMP171, "darksalmon", 10);
STRING_LITERAL(TMP172, "darkseagreen", 12);
STRING_LITERAL(TMP173, "darkslateblue", 13);
STRING_LITERAL(TMP174, "darkslategray", 13);
STRING_LITERAL(TMP175, "darkturquoise", 13);
STRING_LITERAL(TMP176, "darkviolet", 10);
STRING_LITERAL(TMP177, "deeppink", 8);
STRING_LITERAL(TMP178, "deepskyblue", 11);
STRING_LITERAL(TMP179, "dimgray", 7);
STRING_LITERAL(TMP180, "dodgerblue", 10);
STRING_LITERAL(TMP181, "firebrick", 9);
STRING_LITERAL(TMP182, "floralwhite", 11);
STRING_LITERAL(TMP183, "forestgreen", 11);
STRING_LITERAL(TMP184, "fuchsia", 7);
STRING_LITERAL(TMP185, "gainsboro", 9);
STRING_LITERAL(TMP186, "ghostwhite", 10);
STRING_LITERAL(TMP187, "gold", 4);
STRING_LITERAL(TMP188, "goldenrod", 9);
STRING_LITERAL(TMP189, "gray", 4);
STRING_LITERAL(TMP190, "green", 5);
STRING_LITERAL(TMP191, "greenyellow", 11);
STRING_LITERAL(TMP192, "honeydew", 8);
STRING_LITERAL(TMP193, "hotpink", 7);
STRING_LITERAL(TMP194, "indianred", 9);
STRING_LITERAL(TMP195, "indigo", 6);
STRING_LITERAL(TMP196, "ivory", 5);
STRING_LITERAL(TMP197, "khaki", 5);
STRING_LITERAL(TMP198, "lavender", 8);
STRING_LITERAL(TMP199, "lavenderblush", 13);
STRING_LITERAL(TMP200, "lawngreen", 9);
STRING_LITERAL(TMP201, "lemonchiffon", 12);
STRING_LITERAL(TMP202, "lightblue", 9);
STRING_LITERAL(TMP203, "lightcoral", 10);
STRING_LITERAL(TMP204, "lightcyan", 9);
STRING_LITERAL(TMP205, "lightgoldenrodyellow", 20);
STRING_LITERAL(TMP206, "lightgrey", 9);
STRING_LITERAL(TMP207, "lightgreen", 10);
STRING_LITERAL(TMP208, "lightpink", 9);
STRING_LITERAL(TMP209, "lightsalmon", 11);
STRING_LITERAL(TMP210, "lightseagreen", 13);
STRING_LITERAL(TMP211, "lightskyblue", 12);
STRING_LITERAL(TMP212, "lightslategray", 14);
STRING_LITERAL(TMP213, "lightsteelblue", 14);
STRING_LITERAL(TMP214, "lightyellow", 11);
STRING_LITERAL(TMP215, "lime", 4);
STRING_LITERAL(TMP216, "limegreen", 9);
STRING_LITERAL(TMP217, "linen", 5);
STRING_LITERAL(TMP218, "magenta", 7);
STRING_LITERAL(TMP219, "maroon", 6);
STRING_LITERAL(TMP220, "mediumaquamarine", 16);
STRING_LITERAL(TMP221, "mediumblue", 10);
STRING_LITERAL(TMP222, "mediumorchid", 12);
STRING_LITERAL(TMP223, "mediumpurple", 12);
STRING_LITERAL(TMP224, "mediumseagreen", 14);
STRING_LITERAL(TMP225, "mediumslateblue", 15);
STRING_LITERAL(TMP226, "mediumspringgreen", 17);
STRING_LITERAL(TMP227, "mediumturquoise", 15);
STRING_LITERAL(TMP228, "mediumvioletred", 15);
STRING_LITERAL(TMP229, "midnightblue", 12);
STRING_LITERAL(TMP230, "mintcream", 9);
STRING_LITERAL(TMP231, "mistyrose", 9);
STRING_LITERAL(TMP232, "moccasin", 8);
STRING_LITERAL(TMP233, "navajowhite", 11);
STRING_LITERAL(TMP234, "navy", 4);
STRING_LITERAL(TMP235, "oldlace", 7);
STRING_LITERAL(TMP236, "olive", 5);
STRING_LITERAL(TMP237, "olivedrab", 9);
STRING_LITERAL(TMP238, "orange", 6);
STRING_LITERAL(TMP239, "orangered", 9);
STRING_LITERAL(TMP240, "orchid", 6);
STRING_LITERAL(TMP241, "palegoldenrod", 13);
STRING_LITERAL(TMP242, "palegreen", 9);
STRING_LITERAL(TMP243, "paleturquoise", 13);
STRING_LITERAL(TMP244, "palevioletred", 13);
STRING_LITERAL(TMP245, "papayawhip", 10);
STRING_LITERAL(TMP246, "peachpuff", 9);
STRING_LITERAL(TMP247, "peru", 4);
STRING_LITERAL(TMP248, "pink", 4);
STRING_LITERAL(TMP249, "plum", 4);
STRING_LITERAL(TMP250, "powderblue", 10);
STRING_LITERAL(TMP251, "purple", 6);
STRING_LITERAL(TMP252, "red", 3);
STRING_LITERAL(TMP253, "rosybrown", 9);
STRING_LITERAL(TMP254, "royalblue", 9);
STRING_LITERAL(TMP255, "saddlebrown", 11);
STRING_LITERAL(TMP256, "salmon", 6);
STRING_LITERAL(TMP257, "sandybrown", 10);
STRING_LITERAL(TMP258, "seagreen", 8);
STRING_LITERAL(TMP259, "seashell", 8);
STRING_LITERAL(TMP260, "sienna", 6);
STRING_LITERAL(TMP261, "silver", 6);
STRING_LITERAL(TMP262, "skyblue", 7);
STRING_LITERAL(TMP263, "slateblue", 9);
STRING_LITERAL(TMP264, "slategray", 9);
STRING_LITERAL(TMP265, "snow", 4);
STRING_LITERAL(TMP266, "springgreen", 11);
STRING_LITERAL(TMP267, "steelblue", 9);
STRING_LITERAL(TMP268, "tan", 3);
STRING_LITERAL(TMP269, "teal", 4);
STRING_LITERAL(TMP270, "thistle", 7);
STRING_LITERAL(TMP271, "tomato", 6);
STRING_LITERAL(TMP272, "turquoise", 9);
STRING_LITERAL(TMP273, "violet", 6);
STRING_LITERAL(TMP274, "wheat", 5);
STRING_LITERAL(TMP275, "white", 5);
STRING_LITERAL(TMP276, "whitesmoke", 10);
STRING_LITERAL(TMP277, "yellow", 6);
STRING_LITERAL(TMP278, "yellowgreen", 11);
NIM_CONST TY99550 colornames_99549 = {{((NimStringDesc*) &TMP139),
15792383}
,
{((NimStringDesc*) &TMP140),
16444375}
,
{((NimStringDesc*) &TMP141),
65535}
,
{((NimStringDesc*) &TMP142),
8388564}
,
{((NimStringDesc*) &TMP143),
15794175}
,
{((NimStringDesc*) &TMP144),
16119260}
,
{((NimStringDesc*) &TMP145),
16770244}
,
{((NimStringDesc*) &TMP146),
0}
,
{((NimStringDesc*) &TMP147),
16772045}
,
{((NimStringDesc*) &TMP148),
255}
,
{((NimStringDesc*) &TMP149),
9055202}
,
{((NimStringDesc*) &TMP150),
10824234}
,
{((NimStringDesc*) &TMP151),
14596231}
,
{((NimStringDesc*) &TMP152),
6266528}
,
{((NimStringDesc*) &TMP153),
8388352}
,
{((NimStringDesc*) &TMP154),
13789470}
,
{((NimStringDesc*) &TMP155),
16744272}
,
{((NimStringDesc*) &TMP156),
6591981}
,
{((NimStringDesc*) &TMP157),
16775388}
,
{((NimStringDesc*) &TMP158),
14423100}
,
{((NimStringDesc*) &TMP159),
65535}
,
{((NimStringDesc*) &TMP160),
139}
,
{((NimStringDesc*) &TMP161),
35723}
,
{((NimStringDesc*) &TMP162),
12092939}
,
{((NimStringDesc*) &TMP163),
11119017}
,
{((NimStringDesc*) &TMP164),
25600}
,
{((NimStringDesc*) &TMP165),
12433259}
,
{((NimStringDesc*) &TMP166),
9109643}
,
{((NimStringDesc*) &TMP167),
5597999}
,
{((NimStringDesc*) &TMP168),
16747520}
,
{((NimStringDesc*) &TMP169),
10040012}
,
{((NimStringDesc*) &TMP170),
9109504}
,
{((NimStringDesc*) &TMP171),
15308410}
,
{((NimStringDesc*) &TMP172),
9419919}
,
{((NimStringDesc*) &TMP173),
4734347}
,
{((NimStringDesc*) &TMP174),
3100495}
,
{((NimStringDesc*) &TMP175),
52945}
,
{((NimStringDesc*) &TMP176),
9699539}
,
{((NimStringDesc*) &TMP177),
16716947}
,
{((NimStringDesc*) &TMP178),
49151}
,
{((NimStringDesc*) &TMP179),
6908265}
,
{((NimStringDesc*) &TMP180),
2003199}
,
{((NimStringDesc*) &TMP181),
11674146}
,
{((NimStringDesc*) &TMP182),
16775920}
,
{((NimStringDesc*) &TMP183),
2263842}
,
{((NimStringDesc*) &TMP184),
16711935}
,
{((NimStringDesc*) &TMP185),
14474460}
,
{((NimStringDesc*) &TMP186),
16316671}
,
{((NimStringDesc*) &TMP187),
16766720}
,
{((NimStringDesc*) &TMP188),
14329120}
,
{((NimStringDesc*) &TMP189),
8421504}
,
{((NimStringDesc*) &TMP190),
32768}
,
{((NimStringDesc*) &TMP191),
11403055}
,
{((NimStringDesc*) &TMP192),
15794160}
,
{((NimStringDesc*) &TMP193),
16738740}
,
{((NimStringDesc*) &TMP194),
13458524}
,
{((NimStringDesc*) &TMP195),
4915330}
,
{((NimStringDesc*) &TMP196),
16777200}
,
{((NimStringDesc*) &TMP197),
15787660}
,
{((NimStringDesc*) &TMP198),
15132410}
,
{((NimStringDesc*) &TMP199),
16773365}
,
{((NimStringDesc*) &TMP200),
8190976}
,
{((NimStringDesc*) &TMP201),
16775885}
,
{((NimStringDesc*) &TMP202),
11393254}
,
{((NimStringDesc*) &TMP203),
15761536}
,
{((NimStringDesc*) &TMP204),
14745599}
,
{((NimStringDesc*) &TMP205),
16448210}
,
{((NimStringDesc*) &TMP206),
13882323}
,
{((NimStringDesc*) &TMP207),
9498256}
,
{((NimStringDesc*) &TMP208),
16758465}
,
{((NimStringDesc*) &TMP209),
16752762}
,
{((NimStringDesc*) &TMP210),
2142890}
,
{((NimStringDesc*) &TMP211),
8900346}
,
{((NimStringDesc*) &TMP212),
7833753}
,
{((NimStringDesc*) &TMP213),
11584734}
,
{((NimStringDesc*) &TMP214),
16777184}
,
{((NimStringDesc*) &TMP215),
65280}
,
{((NimStringDesc*) &TMP216),
3329330}
,
{((NimStringDesc*) &TMP217),
16445670}
,
{((NimStringDesc*) &TMP218),
16711935}
,
{((NimStringDesc*) &TMP219),
8388608}
,
{((NimStringDesc*) &TMP220),
6737322}
,
{((NimStringDesc*) &TMP221),
205}
,
{((NimStringDesc*) &TMP222),
12211667}
,
{((NimStringDesc*) &TMP223),
9662680}
,
{((NimStringDesc*) &TMP224),
3978097}
,
{((NimStringDesc*) &TMP225),
8087790}
,
{((NimStringDesc*) &TMP226),
64154}
,
{((NimStringDesc*) &TMP227),
4772300}
,
{((NimStringDesc*) &TMP228),
13047173}
,
{((NimStringDesc*) &TMP229),
1644912}
,
{((NimStringDesc*) &TMP230),
16121850}
,
{((NimStringDesc*) &TMP231),
16770273}
,
{((NimStringDesc*) &TMP232),
16770229}
,
{((NimStringDesc*) &TMP233),
16768685}
,
{((NimStringDesc*) &TMP234),
128}
,
{((NimStringDesc*) &TMP235),
16643558}
,
{((NimStringDesc*) &TMP236),
8421376}
,
{((NimStringDesc*) &TMP237),
7048739}
,
{((NimStringDesc*) &TMP238),
16753920}
,
{((NimStringDesc*) &TMP239),
16729344}
,
{((NimStringDesc*) &TMP240),
14315734}
,
{((NimStringDesc*) &TMP241),
15657130}
,
{((NimStringDesc*) &TMP242),
10025880}
,
{((NimStringDesc*) &TMP243),
11529966}
,
{((NimStringDesc*) &TMP244),
14184595}
,
{((NimStringDesc*) &TMP245),
16773077}
,
{((NimStringDesc*) &TMP246),
16767673}
,
{((NimStringDesc*) &TMP247),
13468991}
,
{((NimStringDesc*) &TMP248),
16761035}
,
{((NimStringDesc*) &TMP249),
14524637}
,
{((NimStringDesc*) &TMP250),
11591910}
,
{((NimStringDesc*) &TMP251),
8388736}
,
{((NimStringDesc*) &TMP252),
16711680}
,
{((NimStringDesc*) &TMP253),
12357519}
,
{((NimStringDesc*) &TMP254),
4286945}
,
{((NimStringDesc*) &TMP255),
9127187}
,
{((NimStringDesc*) &TMP256),
16416882}
,
{((NimStringDesc*) &TMP257),
16032864}
,
{((NimStringDesc*) &TMP258),
3050327}
,
{((NimStringDesc*) &TMP259),
16774638}
,
{((NimStringDesc*) &TMP260),
10506797}
,
{((NimStringDesc*) &TMP261),
12632256}
,
{((NimStringDesc*) &TMP262),
8900331}
,
{((NimStringDesc*) &TMP263),
6970061}
,
{((NimStringDesc*) &TMP264),
7372944}
,
{((NimStringDesc*) &TMP265),
16775930}
,
{((NimStringDesc*) &TMP266),
65407}
,
{((NimStringDesc*) &TMP267),
4620980}
,
{((NimStringDesc*) &TMP268),
13808780}
,
{((NimStringDesc*) &TMP269),
32896}
,
{((NimStringDesc*) &TMP270),
14204888}
,
{((NimStringDesc*) &TMP271),
16737095}
,
{((NimStringDesc*) &TMP272),
4251856}
,
{((NimStringDesc*) &TMP273),
15631086}
,
{((NimStringDesc*) &TMP274),
16113331}
,
{((NimStringDesc*) &TMP275),
16777215}
,
{((NimStringDesc*) &TMP276),
16119285}
,
{((NimStringDesc*) &TMP277),
16776960}
,
{((NimStringDesc*) &TMP278),
10145074}
}
;
NIM_CONST TY99550 TMP295 = {{((NimStringDesc*) &TMP139),
15792383}
,
{((NimStringDesc*) &TMP140),
16444375}
,
{((NimStringDesc*) &TMP141),
65535}
,
{((NimStringDesc*) &TMP142),
8388564}
,
{((NimStringDesc*) &TMP143),
15794175}
,
{((NimStringDesc*) &TMP144),
16119260}
,
{((NimStringDesc*) &TMP145),
16770244}
,
{((NimStringDesc*) &TMP146),
0}
,
{((NimStringDesc*) &TMP147),
16772045}
,
{((NimStringDesc*) &TMP148),
255}
,
{((NimStringDesc*) &TMP149),
9055202}
,
{((NimStringDesc*) &TMP150),
10824234}
,
{((NimStringDesc*) &TMP151),
14596231}
,
{((NimStringDesc*) &TMP152),
6266528}
,
{((NimStringDesc*) &TMP153),
8388352}
,
{((NimStringDesc*) &TMP154),
13789470}
,
{((NimStringDesc*) &TMP155),
16744272}
,
{((NimStringDesc*) &TMP156),
6591981}
,
{((NimStringDesc*) &TMP157),
16775388}
,
{((NimStringDesc*) &TMP158),
14423100}
,
{((NimStringDesc*) &TMP159),
65535}
,
{((NimStringDesc*) &TMP160),
139}
,
{((NimStringDesc*) &TMP161),
35723}
,
{((NimStringDesc*) &TMP162),
12092939}
,
{((NimStringDesc*) &TMP163),
11119017}
,
{((NimStringDesc*) &TMP164),
25600}
,
{((NimStringDesc*) &TMP165),
12433259}
,
{((NimStringDesc*) &TMP166),
9109643}
,
{((NimStringDesc*) &TMP167),
5597999}
,
{((NimStringDesc*) &TMP168),
16747520}
,
{((NimStringDesc*) &TMP169),
10040012}
,
{((NimStringDesc*) &TMP170),
9109504}
,
{((NimStringDesc*) &TMP171),
15308410}
,
{((NimStringDesc*) &TMP172),
9419919}
,
{((NimStringDesc*) &TMP173),
4734347}
,
{((NimStringDesc*) &TMP174),
3100495}
,
{((NimStringDesc*) &TMP175),
52945}
,
{((NimStringDesc*) &TMP176),
9699539}
,
{((NimStringDesc*) &TMP177),
16716947}
,
{((NimStringDesc*) &TMP178),
49151}
,
{((NimStringDesc*) &TMP179),
6908265}
,
{((NimStringDesc*) &TMP180),
2003199}
,
{((NimStringDesc*) &TMP181),
11674146}
,
{((NimStringDesc*) &TMP182),
16775920}
,
{((NimStringDesc*) &TMP183),
2263842}
,
{((NimStringDesc*) &TMP184),
16711935}
,
{((NimStringDesc*) &TMP185),
14474460}
,
{((NimStringDesc*) &TMP186),
16316671}
,
{((NimStringDesc*) &TMP187),
16766720}
,
{((NimStringDesc*) &TMP188),
14329120}
,
{((NimStringDesc*) &TMP189),
8421504}
,
{((NimStringDesc*) &TMP190),
32768}
,
{((NimStringDesc*) &TMP191),
11403055}
,
{((NimStringDesc*) &TMP192),
15794160}
,
{((NimStringDesc*) &TMP193),
16738740}
,
{((NimStringDesc*) &TMP194),
13458524}
,
{((NimStringDesc*) &TMP195),
4915330}
,
{((NimStringDesc*) &TMP196),
16777200}
,
{((NimStringDesc*) &TMP197),
15787660}
,
{((NimStringDesc*) &TMP198),
15132410}
,
{((NimStringDesc*) &TMP199),
16773365}
,
{((NimStringDesc*) &TMP200),
8190976}
,
{((NimStringDesc*) &TMP201),
16775885}
,
{((NimStringDesc*) &TMP202),
11393254}
,
{((NimStringDesc*) &TMP203),
15761536}
,
{((NimStringDesc*) &TMP204),
14745599}
,
{((NimStringDesc*) &TMP205),
16448210}
,
{((NimStringDesc*) &TMP206),
13882323}
,
{((NimStringDesc*) &TMP207),
9498256}
,
{((NimStringDesc*) &TMP208),
16758465}
,
{((NimStringDesc*) &TMP209),
16752762}
,
{((NimStringDesc*) &TMP210),
2142890}
,
{((NimStringDesc*) &TMP211),
8900346}
,
{((NimStringDesc*) &TMP212),
7833753}
,
{((NimStringDesc*) &TMP213),
11584734}
,
{((NimStringDesc*) &TMP214),
16777184}
,
{((NimStringDesc*) &TMP215),
65280}
,
{((NimStringDesc*) &TMP216),
3329330}
,
{((NimStringDesc*) &TMP217),
16445670}
,
{((NimStringDesc*) &TMP218),
16711935}
,
{((NimStringDesc*) &TMP219),
8388608}
,
{((NimStringDesc*) &TMP220),
6737322}
,
{((NimStringDesc*) &TMP221),
205}
,
{((NimStringDesc*) &TMP222),
12211667}
,
{((NimStringDesc*) &TMP223),
9662680}
,
{((NimStringDesc*) &TMP224),
3978097}
,
{((NimStringDesc*) &TMP225),
8087790}
,
{((NimStringDesc*) &TMP226),
64154}
,
{((NimStringDesc*) &TMP227),
4772300}
,
{((NimStringDesc*) &TMP228),
13047173}
,
{((NimStringDesc*) &TMP229),
1644912}
,
{((NimStringDesc*) &TMP230),
16121850}
,
{((NimStringDesc*) &TMP231),
16770273}
,
{((NimStringDesc*) &TMP232),
16770229}
,
{((NimStringDesc*) &TMP233),
16768685}
,
{((NimStringDesc*) &TMP234),
128}
,
{((NimStringDesc*) &TMP235),
16643558}
,
{((NimStringDesc*) &TMP236),
8421376}
,
{((NimStringDesc*) &TMP237),
7048739}
,
{((NimStringDesc*) &TMP238),
16753920}
,
{((NimStringDesc*) &TMP239),
16729344}
,
{((NimStringDesc*) &TMP240),
14315734}
,
{((NimStringDesc*) &TMP241),
15657130}
,
{((NimStringDesc*) &TMP242),
10025880}
,
{((NimStringDesc*) &TMP243),
11529966}
,
{((NimStringDesc*) &TMP244),
14184595}
,
{((NimStringDesc*) &TMP245),
16773077}
,
{((NimStringDesc*) &TMP246),
16767673}
,
{((NimStringDesc*) &TMP247),
13468991}
,
{((NimStringDesc*) &TMP248),
16761035}
,
{((NimStringDesc*) &TMP249),
14524637}
,
{((NimStringDesc*) &TMP250),
11591910}
,
{((NimStringDesc*) &TMP251),
8388736}
,
{((NimStringDesc*) &TMP252),
16711680}
,
{((NimStringDesc*) &TMP253),
12357519}
,
{((NimStringDesc*) &TMP254),
4286945}
,
{((NimStringDesc*) &TMP255),
9127187}
,
{((NimStringDesc*) &TMP256),
16416882}
,
{((NimStringDesc*) &TMP257),
16032864}
,
{((NimStringDesc*) &TMP258),
3050327}
,
{((NimStringDesc*) &TMP259),
16774638}
,
{((NimStringDesc*) &TMP260),
10506797}
,
{((NimStringDesc*) &TMP261),
12632256}
,
{((NimStringDesc*) &TMP262),
8900331}
,
{((NimStringDesc*) &TMP263),
6970061}
,
{((NimStringDesc*) &TMP264),
7372944}
,
{((NimStringDesc*) &TMP265),
16775930}
,
{((NimStringDesc*) &TMP266),
65407}
,
{((NimStringDesc*) &TMP267),
4620980}
,
{((NimStringDesc*) &TMP268),
13808780}
,
{((NimStringDesc*) &TMP269),
32896}
,
{((NimStringDesc*) &TMP270),
14204888}
,
{((NimStringDesc*) &TMP271),
16737095}
,
{((NimStringDesc*) &TMP272),
4251856}
,
{((NimStringDesc*) &TMP273),
15631086}
,
{((NimStringDesc*) &TMP274),
16113331}
,
{((NimStringDesc*) &TMP275),
16777215}
,
{((NimStringDesc*) &TMP276),
16119285}
,
{((NimStringDesc*) &TMP277),
16776960}
,
{((NimStringDesc*) &TMP278),
10145074}
}
;
STRING_LITERAL(TMP296, "unkown color: ", 14);
extern TFrame* frameptr_16242;
extern TNimType NTI21601; /* ref ValueError */
extern TNimType NTI3249; /* ValueError */
extern tgcheap47216 gch_47244;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

static N_INLINE(NI, satplus_99060)(NI a, NI b) {
	NI result;
	nimfr("satPlus", "colors.nim")
	result = 0;
	nimln(36, "colors.nim");
	nimln(36, "colors.nim");
	result = (NI)((NU32)(a) + (NU32)(b));
	nimln(37, "colors.nim");
	{
		nimln(37, "colors.nim");
		if (!(255 < result)) goto LA3;
		nimln(37, "colors.nim");
		result = 255;
	}
	LA3: ;
	popFrame();
	return result;
}

static N_INLINE(NI, satminus_99083)(NI a, NI b) {
	NI result;
	nimfr("satMinus", "colors.nim")
	result = 0;
	nimln(40, "colors.nim");
	nimln(40, "colors.nim");
	result = (NI)((NU32)(a) - (NU32)(b));
	nimln(41, "colors.nim");
	{
		nimln(41, "colors.nim");
		if (!(result < 0)) goto LA3;
		nimln(41, "colors.nim");
		result = 0;
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, HEX2B_99104)(NI a, NI b) {
	NI result;
	NI ar;
	NI ag;
	NI ab;
	NI br;
	NI bg;
	NI bb;
	NI LOC1;
	NI LOC2;
	NI LOC3;
	nimfr("+", "colors.nim")
	result = 0;
	nimln(23, "colors.nim");
	nimln(23, "colors.nim");
	nimln(23, "colors.nim");
	ar = (NI)((NI)((NU32)(a) >> (NU32)(16)) & 255);
	nimln(24, "colors.nim");
	nimln(24, "colors.nim");
	nimln(24, "colors.nim");
	ag = (NI)((NI)((NU32)(a) >> (NU32)(8)) & 255);
	nimln(25, "colors.nim");
	nimln(25, "colors.nim");
	ab = (NI)(a & 255);
	nimln(23, "colors.nim");
	nimln(23, "colors.nim");
	nimln(23, "colors.nim");
	br = (NI)((NI)((NU32)(b) >> (NU32)(16)) & 255);
	nimln(24, "colors.nim");
	nimln(24, "colors.nim");
	nimln(24, "colors.nim");
	bg = (NI)((NI)((NU32)(b) >> (NU32)(8)) & 255);
	nimln(25, "colors.nim");
	nimln(25, "colors.nim");
	bb = (NI)(b & 255);
	nimln(33, "colors.nim");
	nimln(33, "colors.nim");
	nimln(33, "colors.nim");
	nimln(33, "colors.nim");
	nimln(33, "colors.nim");
	LOC1 = 0;
	LOC1 = satplus_99060(((NI) (ar)), ((NI) (br)));
	nimln(33, "colors.nim");
	nimln(33, "colors.nim");
	LOC2 = 0;
	LOC2 = satplus_99060(((NI) (ag)), ((NI) (bg)));
	nimln(33, "colors.nim");
	LOC3 = 0;
	LOC3 = satplus_99060(((NI) (ab)), ((NI) (bb)));
	result = (NI)((NI)((NI)((NU32)(LOC1) << (NU32)(16)) | (NI)((NU32)(LOC2) << (NU32)(8))) | LOC3);
	popFrame();
	return result;
}

N_NIMCALL(NI, HEX2D_99140)(NI a, NI b) {
	NI result;
	NI ar;
	NI ag;
	NI ab;
	NI br;
	NI bg;
	NI bb;
	NI LOC1;
	NI LOC2;
	NI LOC3;
	nimfr("-", "colors.nim")
	result = 0;
	nimln(23, "colors.nim");
	nimln(23, "colors.nim");
	nimln(23, "colors.nim");
	ar = (NI)((NI)((NU32)(a) >> (NU32)(16)) & 255);
	nimln(24, "colors.nim");
	nimln(24, "colors.nim");
	nimln(24, "colors.nim");
	ag = (NI)((NI)((NU32)(a) >> (NU32)(8)) & 255);
	nimln(25, "colors.nim");
	nimln(25, "colors.nim");
	ab = (NI)(a & 255);
	nimln(23, "colors.nim");
	nimln(23, "colors.nim");
	nimln(23, "colors.nim");
	br = (NI)((NI)((NU32)(b) >> (NU32)(16)) & 255);
	nimln(24, "colors.nim");
	nimln(24, "colors.nim");
	nimln(24, "colors.nim");
	bg = (NI)((NI)((NU32)(b) >> (NU32)(8)) & 255);
	nimln(25, "colors.nim");
	nimln(25, "colors.nim");
	bb = (NI)(b & 255);
	nimln(33, "colors.nim");
	nimln(33, "colors.nim");
	nimln(33, "colors.nim");
	nimln(33, "colors.nim");
	nimln(33, "colors.nim");
	LOC1 = 0;
	LOC1 = satminus_99083(((NI) (ar)), ((NI) (br)));
	nimln(33, "colors.nim");
	nimln(33, "colors.nim");
	LOC2 = 0;
	LOC2 = satminus_99083(((NI) (ag)), ((NI) (bg)));
	nimln(33, "colors.nim");
	LOC3 = 0;
	LOC3 = satminus_99083(((NI) (ab)), ((NI) (bb)));
	result = (NI)((NI)((NI)((NU32)(LOC1) << (NU32)(16)) | (NI)((NU32)(LOC2) << (NU32)(8))) | LOC3);
	popFrame();
	return result;
}

N_NIMCALL(TY99179, extractrgb_99176)(NI a) {
	TY99179 result;
	nimfr("extractRGB", "colors.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(55, "colors.nim");
	nimln(55, "colors.nim");
	nimln(55, "colors.nim");
	result.Field0 = (NI)((NI)((NU32)(a) >> (NU32)(16)) & 255);
	nimln(56, "colors.nim");
	nimln(56, "colors.nim");
	nimln(56, "colors.nim");
	result.Field1 = (NI)((NI)((NU32)(a) >> (NU32)(8)) & 255);
	nimln(57, "colors.nim");
	nimln(57, "colors.nim");
	result.Field2 = (NI)(a & 255);
	popFrame();
	return result;
}

N_NIMCALL(NI, intensity_99201)(NI a, NF f) {
	NI result;
	NI r;
	NI g;
	NI b;
	nimfr("intensity", "colors.nim")
	result = 0;
	nimln(62, "colors.nim");
	nimln(62, "colors.nim");
	nimln(62, "colors.nim");
	nimln(62, "colors.nim");
	nimln(62, "colors.nim");
	nimln(62, "colors.nim");
	r = float64ToInt32(((NF)(((double) (((NI) ((NI)((NI)((NU32)(a) >> (NU32)(16)) & 255)))))) * (NF)(f)));
	nimln(63, "colors.nim");
	nimln(63, "colors.nim");
	nimln(63, "colors.nim");
	nimln(63, "colors.nim");
	nimln(63, "colors.nim");
	nimln(63, "colors.nim");
	g = float64ToInt32(((NF)(((double) (((NI) ((NI)((NI)((NU32)(a) >> (NU32)(8)) & 255)))))) * (NF)(f)));
	nimln(64, "colors.nim");
	nimln(64, "colors.nim");
	nimln(64, "colors.nim");
	nimln(64, "colors.nim");
	nimln(64, "colors.nim");
	b = float64ToInt32(((NF)(((double) (((NI) ((NI)(a & 255)))))) * (NF)(f)));
	nimln(65, "colors.nim");
	{
		nimln(65, "colors.nim");
		if (!((NU32)(255) < (NU32)(r))) goto LA3;
		nimln(65, "colors.nim");
		r = 255;
	}
	LA3: ;
	nimln(66, "colors.nim");
	{
		nimln(66, "colors.nim");
		if (!((NU32)(255) < (NU32)(g))) goto LA7;
		nimln(66, "colors.nim");
		g = 255;
	}
	LA7: ;
	nimln(67, "colors.nim");
	{
		nimln(67, "colors.nim");
		if (!((NU32)(255) < (NU32)(b))) goto LA11;
		nimln(67, "colors.nim");
		b = 255;
	}
	LA11: ;
	nimln(68, "colors.nim");
	nimln(68, "colors.nim");
	nimln(68, "colors.nim");
	nimln(68, "colors.nim");
	nimln(68, "colors.nim");
	result = (NI)((NI)((NI)((NU32)(r) << (NU32)(16)) | (NI)((NU32)(g) << (NU32)(8))) | b);
	popFrame();
	return result;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI32)((*dest).Sup.len + 1))- 0] = 0;
	(*dest).Sup.len += 1;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI32)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, HEX24_99695)(NI c) {
	NimStringDesc* result;
	NimStringDesc* LOC1;
	NimStringDesc* LOC2;
	nimfr("$", "colors.nim")
	result = 0;
	nimln(374, "colors.nim");
	nimln(374, "colors.nim");
	LOC1 = 0;
	nimln(374, "colors.nim");
	LOC2 = 0;
	LOC2 = nsuToHex(((NI64) (c)), 6);
	LOC1 = rawNewString(LOC2->Sup.len + 1);
appendChar(LOC1, 35);
appendString(LOC1, LOC2);
	result = LOC1;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) - (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU32) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
	result = 0;
	{
		if (!(b == 0)) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == (-2147483647 -1));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == -1);
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI32)(a / b);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, binarystrsearch_99707)(TY99551* x, NI xLen0, NimStringDesc* y) {
	NI result;
	NI a;
	NI b;
	NI TMP282;
	nimfr("binaryStrSearch", "colors.nim")
	result = 0;
	nimln(378, "colors.nim");
	a = 0;
	nimln(379, "colors.nim");
	nimln(379, "colors.nim");
	nimln(379, "colors.nim");
	TMP282 = subInt(xLen0, 1);
	b = (NI32)(TMP282);
	{
		nimln(380, "colors.nim");
		while (1) {
			NI mid;
			NI TMP283;
			NI TMP284;
			NI c;
			nimln(380, "colors.nim");
			if (!(a <= b)) goto LA2;
			nimln(381, "colors.nim");
			nimln(381, "colors.nim");
			nimln(381, "colors.nim");
			TMP283 = addInt(a, b);
			TMP284 = divInt((NI32)(TMP283), 2);
			mid = (NI32)(TMP284);
			nimln(382, "colors.nim");
			if ((NU)(mid) >= (NU)(xLen0)) raiseIndexError();
			c = cmp_4517(x[mid].Field0, y);
			nimln(383, "colors.nim");
			{
				NI TMP285;
				nimln(383, "colors.nim");
				if (!(c < 0)) goto LA5;
				nimln(383, "colors.nim");
				nimln(383, "colors.nim");
				TMP285 = addInt(mid, 1);
				a = (NI32)(TMP285);
			}
			goto LA3;
			LA5: ;
			{
				NI TMP286;
				nimln(384, "colors.nim");
				if (!(0 < c)) goto LA8;
				nimln(384, "colors.nim");
				nimln(384, "colors.nim");
				TMP286 = subInt(mid, 1);
				b = (NI32)(TMP286);
			}
			goto LA3;
			LA8: ;
			{
				nimln(385, "colors.nim");
				nimln(385, "colors.nim");
				result = mid;
				goto BeforeRet;
			}
			LA3: ;
		} LA2: ;
	}
	nimln(386, "colors.nim");
	result = -1;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(tcell45135*, usrtocell_48846)(void* usr) {
	tcell45135* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell45135*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell45135))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50404)(tcell45135* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48817((&gch_47244.Zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell45135* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_48846(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell45135* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_48846((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50404(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(NI, parsecolor_99742)(NimStringDesc* name) {
	NI result;
	nimfr("parseColor", "colors.nim")
	result = 0;
	nimln(391, "colors.nim");
	{
		nimln(391, "colors.nim");
		if ((NU)(0) > (NU)(name->Sup.len)) raiseIndexError();
		if (!((NU8)(name->data[0]) == (NU8)(35))) goto LA3;
		nimln(392, "colors.nim");
		nimln(392, "colors.nim");
		result = nsuParseHexInt(name);
	}
	goto LA1;
	LA3: ;
	{
		NI idx;
		nimln(394, "colors.nim");
		idx = binarystrsearch_99707(TMP295, 140, name);
		nimln(395, "colors.nim");
		{
			valueerror3249* e_99750;
			NimStringDesc* LOC10;
			nimln(395, "colors.nim");
			if (!(idx < 0)) goto LA8;
			e_99750 = 0;
			nimln(2149, "system.nim");
			e_99750 = (valueerror3249*) newObj((&NTI21601), sizeof(valueerror3249));
			(*e_99750).Sup.Sup.m_type = (&NTI3249);
			nimln(2150, "system.nim");
			nimln(395, "colors.nim");
			LOC10 = 0;
			LOC10 = rawNewString(name->Sup.len + 14);
appendString(LOC10, ((NimStringDesc*) &TMP296));
appendString(LOC10, name);
			asgnRefNoCycle((void**) (&(*e_99750).Sup.message), LOC10);
			nimln(395, "colors.nim");
			raiseException((Exception*)e_99750, "ValueError");
		}
		LA8: ;
		nimln(396, "colors.nim");
		if ((NU)(idx) > (NU)(139)) raiseIndexError();
		result = colornames_99549[(idx)- 0].Field1;
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, iscolor_99776)(NimStringDesc* name) {
	NIM_BOOL result;
	nimfr("isColor", "colors.nim")
	result = 0;
	nimln(401, "colors.nim");
	{
		nimln(401, "colors.nim");
		if ((NU)(0) > (NU)(name->Sup.len)) raiseIndexError();
		if (!((NU8)(name->data[0]) == (NU8)(35))) goto LA3;
		{
			NI i_99790;
			NI HEX3Atmp_99806;
			NI TMP297;
			NI res_99809;
			i_99790 = 0;
			HEX3Atmp_99806 = 0;
			nimln(402, "colors.nim");
			nimln(402, "colors.nim");
			nimln(402, "colors.nim");
			TMP297 = subInt(name->Sup.len, 1);
			HEX3Atmp_99806 = (NI32)(TMP297);
			nimln(1576, "system.nim");
			res_99809 = 1;
			{
				nimln(1577, "system.nim");
				while (1) {
					nimln(1577, "system.nim");
					if (!(res_99809 <= HEX3Atmp_99806)) goto LA7;
					nimln(1576, "system.nim");
					i_99790 = res_99809;
					nimln(403, "colors.nim");
					{
						nimln(403, "colors.nim");
						nimln(403, "colors.nim");
						if ((NU)(i_99790) > (NU)(name->Sup.len)) raiseIndexError();
						if (!!((((NU8)(name->data[i_99790])) >= ((NU8)(48)) && ((NU8)(name->data[i_99790])) <= ((NU8)(57)) || ((NU8)(name->data[i_99790])) >= ((NU8)(97)) && ((NU8)(name->data[i_99790])) <= ((NU8)(102)) || ((NU8)(name->data[i_99790])) >= ((NU8)(65)) && ((NU8)(name->data[i_99790])) <= ((NU8)(70))))) goto LA10;
						nimln(403, "colors.nim");
						nimln(403, "colors.nim");
						result = NIM_FALSE;
						goto BeforeRet;
					}
					LA10: ;
					nimln(1579, "system.nim");
					res_99809 = addInt(res_99809, 1);
				} LA7: ;
			}
		}
		nimln(404, "colors.nim");
		result = NIM_TRUE;
	}
	goto LA1;
	LA3: ;
	{
		NI LOC13;
		nimln(406, "colors.nim");
		nimln(406, "colors.nim");
		nimln(406, "colors.nim");
		LOC13 = 0;
		LOC13 = binarystrsearch_99707(TMP295, 140, name);
		result = (0 <= LOC13);
	}
	LA1: ;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, rgb_99826)(NI r, NI g, NI b) {
	NI result;
	nimfr("rgb", "colors.nim")
	result = 0;
	nimln(410, "colors.nim");
	nimln(410, "colors.nim");
	nimln(410, "colors.nim");
	nimln(410, "colors.nim");
	nimln(410, "colors.nim");
	result = (NI)((NI)((NI)((NU32)(((NI) (r))) << (NU32)(16)) | (NI)((NU32)(((NI) (g))) << (NU32)(8))) | ((NI) (b)));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_colorsInit)(void) {
	nimfr("colors", "colors.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_colorsDatInit)(void) {
}

