/* Generated by Nim Compiler v0.10.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/jsudlow/Nim/lib -o .nimcache/stdlib_graphics.o .nimcache/stdlib_graphics.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>

#include <math.h>
typedef struct tcolor116233 tcolor116233;
typedef struct TY99179 TY99179;
typedef struct tsurface123011 tsurface123011;
typedef struct tpixelformat116245 tpixelformat116245;
typedef struct tsurface116255 tsurface116255;
typedef struct trect116227 trect116227;
typedef struct trect123005 trect123005;
typedef struct egraphics123013 egraphics123013;
typedef struct ioerror3231 ioerror3231;
typedef struct systemerror3229 systemerror3229;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tcell45135 tcell45135;
typedef struct tcellseq45151 tcellseq45151;
typedef struct tgcheap47216 tgcheap47216;
typedef struct tcellset45147 tcellset45147;
typedef struct tpagedesc45143 tpagedesc45143;
typedef struct tmemregion27410 tmemregion27410;
typedef struct tsmallchunk26640 tsmallchunk26640;
typedef struct tllchunk27404 tllchunk27404;
typedef struct tbigchunk26642 tbigchunk26642;
typedef struct tintset26617 tintset26617;
typedef struct ttrunk26613 ttrunk26613;
typedef struct tavlnode27408 tavlnode27408;
typedef struct tgcstat47214 tgcstat47214;
typedef struct tfont123015 tfont123015;
typedef struct tfont122221 tfont122221;
typedef struct tpoint123007 tpoint123007;
typedef struct TY125199 TY125199;
typedef struct tpalette116241 tpalette116241;
typedef struct tbasechunk26638 tbasechunk26638;
typedef struct tfreecell26630 tfreecell26630;
struct  tcolor116233  {
NU8 R;
NU8 G;
NU8 B;
NU8 Unused;
};
struct TY99179 {
NI Field0;
NI Field1;
NI Field2;
};
typedef N_CDECL_PTR(NI32, TY120413) (tpixelformat116245* format, NU8 r, NU8 g, NU8 b, NU8 a);
struct  tsurface123011  {
NI W;
NI H;
tsurface116255* S;
};
struct  trect116227  {
NI16 X;
NI16 Y;
NU16 W;
NU16 H;
};
struct  tsurface116255  {
NI32 Flags;
tpixelformat116245* Format;
int W;
int H;
NU16 Pitch;
void* Pixels;
int Offset;
void* Hwdata;
trect116227 Cliprect;
NI32 Unused1;
NI32 Locked;
void* Blitmap;
int Formatversion;
int Refcount;
};
struct trect123005 {
NI Field0;
NI Field1;
NI Field2;
NI Field3;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  systemerror3229  {
  Exception Sup;
};
struct  ioerror3231  {
  systemerror3229 Sup;
};
struct  egraphics123013  {
  ioerror3231 Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CDECL_PTR(NCSTRING, TY119608) (void);
struct  tcell45135  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq45151  {
NI Len;
NI Cap;
tcell45135** D;
};
struct  tcellset45147  {
NI Counter;
NI Max;
tpagedesc45143* Head;
tpagedesc45143** Data;
};
typedef tsmallchunk26640* TY27422[512];
typedef ttrunk26613* ttrunkbuckets26615[256];
struct  tintset26617  {
ttrunkbuckets26615 Data;
};
struct  tmemregion27410  {
NI Minlargeobj;
NI Maxlargeobj;
TY27422 Freesmallchunks;
tllchunk27404* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26642* Freechunkslist;
tintset26617 Chunkstarts;
tavlnode27408* Root;
tavlnode27408* Deleted;
tavlnode27408* Last;
tavlnode27408* Freeavlnodes;
};
struct  tgcstat47214  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47216  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq45151 Zct;
tcellseq45151 Decstack;
tcellset45147 Cycleroots;
tcellseq45151 Tempstack;
NI Recgclock;
tmemregion27410 Region;
tgcstat47214 Stat;
};
typedef N_CDECL_PTR(void, TY120491) (tsurface116255* surface);
typedef N_CDECL_PTR(tsurface116255*, TY120464) (NI32 flags, NI width, NI height, NI depth, NI32 rmask, NI32 gmask, NI32 bmask, NI32 amask);
typedef N_CDECL_PTR(void, TY122478) (tfont122221* font);
struct  tfont123015  {
tfont122221* F;
tcolor116233 Color;
};
typedef N_CDECL_PTR(tfont122221*, TY122243) (NCSTRING filename, int ptsize);
typedef N_CDECL_PTR(tsurface116255*, TY120328) (NI width, NI height, NI bpp, NU32 flags);
struct tpoint123007 {
NI Field0;
NI Field1;
};
typedef N_CDECL_PTR(int, TY122364) (tfont122221* font, NCSTRING text, int* w, int* y);
typedef N_CDECL_PTR(tsurface116255*, TY122446) (tfont122221* font, NCSTRING text, tcolor116233 fg);
typedef N_CDECL_PTR(tsurface116255*, TY122410) (tfont122221* font, NCSTRING text, tcolor116233 fg, tcolor116233 bg);
typedef N_CDECL_PTR(NI, TY120608) (tsurface116255* dst, trect116227* dstrect, NI32 color);
struct TY125199 {
NF Field0;
NF Field1;
NF Field2;
NF Field3;
};
typedef N_CDECL_PTR(NI, TY119423) (NI32 flags);
typedef N_CDECL_PTR(int, TY122238) (void);
struct  tpixelformat116245  {
tpalette116241* Palette;
NU8 Bitsperpixel;
NU8 Bytesperpixel;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
NI32 Rmask;
NI32 Gmask;
NI32 Bmask;
NI32 Amask;
NI32 Colorkey;
NU8 Alpha;
};
typedef NI TY26620[16];
struct  tpagedesc45143  {
tpagedesc45143* Next;
NI Key;
TY26620 Bits;
};
struct  tbasechunk26638  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26640  {
  tbasechunk26638 Sup;
tsmallchunk26640* Next;
tsmallchunk26640* Prev;
tfreecell26630* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27404  {
NI Size;
NI Acc;
tllchunk27404* Next;
};
struct  tbigchunk26642  {
  tbasechunk26638 Sup;
tbigchunk26642* Next;
tbigchunk26642* Prev;
NI Align;
NF Data;
};
struct  ttrunk26613  {
ttrunk26613* Next;
NI Key;
TY26620 Bits;
};
typedef tavlnode27408* TY27414[2];
struct  tavlnode27408  {
TY27414 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfont122221  {
char dummy;
};
struct  tpalette116241  {
NI Ncolors;
tcolor116233* Colors;
};
struct  tfreecell26630  {
tfreecell26630* Next;
NI Zerofield;
};
N_NIMCALL(tcolor116233, tosdlcolor_123035)(NI c);
N_NIMCALL(TY99179, extractrgb_99176)(NI a);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NI32, createsdlcolor_123053)(tsurface123011* sur, NI c, NI alpha);
N_NIMCALL(trect116227, tosdlrect_123074)(trect123005 r);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, raiseegraphics_123085)(void);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP402)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell45135*, usrtocell_48846)(void* usr);
static N_INLINE(void, rtladdzct_50404)(tcell45135* c);
N_NOINLINE(void, addzct_48817)(tcellseq45151* s, tcell45135* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(void, surfacefinalizer_123114)(tsurface123011* s);
N_NIMCALL(tsurface123011*, newsurface_123123)(NI width, NI height);
N_NIMCALL(void, TMP409)(void* p, NI op);
N_NIMCALL(NIM_BOOL, mustlock_120496)(tsurface116255* surface);
N_NIMCALL(void, failedassertimpl_85425)(NimStringDesc* msg);
N_NIMCALL(void, fontfinalizer_123207)(tfont123015* f);
N_NIMCALL(tfont123015*, newfont_123216)(NimStringDesc* name, NI size, NI color);
N_NIMCALL(void, TMP412)(void* p, NI op);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(void, initdefaultfont_123302)(NimStringDesc* name, NI size, NI color);
N_NIMCALL(tsurface123011*, newscreensurface_123313)(NI width, NI height);
N_NIMCALL(void, writetobmp_123371)(tsurface123011* sur, NimStringDesc* filename);
N_NIMCALL(NI, savebmp_120535)(tsurface116255* surface, NCSTRING filename);
static N_INLINE(NI, getpixel_123440)(tsurface123011* sur, NI x, NI y);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(void, setpixel_123819)(tsurface123011* sur, NI x, NI y, NI col);
N_NIMCALL(NI, HEX5BHEX5D_124220)(tsurface123011* sur, tpoint123007 p);
N_NIMCALL(NI, HEX5BHEX5D_124231)(tsurface123011* sur, NI x, NI y);
N_NIMCALL(void, HEX5BHEX5DHEX3D_124243)(tsurface123011* sur, tpoint123007 p, NI col);
N_NIMCALL(void, HEX5BHEX5DHEX3D_124254)(tsurface123011* sur, NI x, NI y, NI col);
N_NIMCALL(void, blit_124266)(tsurface123011* destsurf, trect123005 destrect, tsurface123011* srcsurf, trect123005 srcrect);
N_NIMCALL(NI, blitsurface_120580)(tsurface116255* src, trect116227* srcrect, tsurface116255* dst, trect116227* dstrect);
N_NIMCALL(tpoint123007, textbounds_124283)(NimStringDesc* text, tfont123015* font);
N_NIMCALL(void, drawtext_124307)(tsurface123011* sur, tpoint123007 p, NimStringDesc* text, tfont123015* font);
N_NIMCALL(void, drawtext_124353)(tsurface123011* sur, tpoint123007 p, NimStringDesc* text, NI bg, tfont123015* font);
N_NIMCALL(void, drawcircle_124400)(tsurface123011* sur, tpoint123007 p, NI r, NI color);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(NI, HEX3EHEX2DHEX3C_124547)(NI val, tsurface123011* s);
static N_INLINE(NI, HEX3EHEX7CHEX3C_124560)(NI val, tsurface123011* s);
N_NIMCALL(void, drawline_124573)(tsurface123011* sur, tpoint123007 p1, tpoint123007 p2, NI color);
N_NIMCALL(void, drawhorline_124621)(tsurface123011* sur, NI x, NI y, NI w, NI color);
N_NIMCALL(void, drawverline_124693)(tsurface123011* sur, NI x, NI y, NI h, NI color);
N_NIMCALL(void, fillcircle_124740)(tsurface123011* s, tpoint123007 p, NI r, NI color);
N_NIMCALL(void, drawrect_124766)(tsurface123011* sur, trect123005 r, NI color);
N_NIMCALL(void, fillrect_124845)(tsurface123011* sur, trect123005 r, NI col);
N_NIMCALL(void, plot4ellipsepoints_124858)(tsurface123011* sur, NI cx, NI cy, NI x, NI y, NI col);
N_NIMCALL(void, drawellipse_124887)(tsurface123011* sur, NI cx, NI cy, NI xradius, NI yradius, NI col);
N_NIMCALL(void, plotaa_125141)(tsurface123011* sur, NI x, NI y, NF c, NI color);
N_NIMCALL(NI, HEX2B_99104)(NI a, NI b);
N_NIMCALL(NI, intensity_99201)(NI a, NF f);
N_NIMCALL(void, drawlineaa_125193)(tsurface123011* sur, tpoint123007 p1, tpoint123007 p2, NI color);
N_NIMCALL(void, fillsurface_125349)(tsurface123011* sur, NI color);
STRING_LITERAL(TMP410, "not sdl.mustLock(result.s) ", 27);
STRING_LITERAL(TMP413, "Could not open font file: ", 26);
STRING_LITERAL(TMP414, "cannot write: ", 14);
STRING_LITERAL(TMP415, "x <% sur.w ", 11);
STRING_LITERAL(TMP416, "y <% sur.h ", 11);
extern TFrame* frameptr_16242;
extern TY120413 Dl_120412;
extern TNimType NTI3231; /* IOError */
TNimType NTI123013; /* EGraphics */
TNimType NTI123090; /* ref EGraphics */
extern TY119608 Dl_119607;
extern tgcheap47216 gch_47244;
extern TY120491 Dl_120490;
TNimType NTI123011; /* TSurface */
extern TNimType NTI75293; /* range 0..2147483647(int) */
extern TNimType NTI116251; /* PSurface */
TNimType NTI123009; /* PSurface */
extern TY120464 Dl_120463;
extern TY122478 Dl_122477;
TNimType NTI123015; /* TFont */
extern TNimType NTI122219; /* PFont */
extern TNimType NTI116233; /* TColor */
TNimType NTI123017; /* PFont */
extern TY122243 Dl_122242;
extern TNimType NTI12801; /* ref IOError */
tfont123015* defaultfont_123297;
extern TY120328 Dl_120327;
extern TY122364 Dl_122363;
extern TY122446 Dl_122445;
extern TY122410 Dl_122409;
extern TY120608 Dl_120607;
extern TY119423 Dl_119422;
extern TY122238 Dl_122237;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

N_NIMCALL(tcolor116233, tosdlcolor_123035)(NI c) {
	tcolor116233 result;
	TY99179 x;
	nimfr("toSdlColor", "graphics.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(37, "graphics.nim");
	x = extractrgb_99176(c);
	nimln(38, "graphics.nim");
	nimln(38, "graphics.nim");
	result.R = ((NU8) ((NI)(((NI) (x.Field0)) & 255)));
	nimln(39, "graphics.nim");
	nimln(39, "graphics.nim");
	result.G = ((NU8) ((NI)(((NI) (x.Field1)) & 255)));
	nimln(40, "graphics.nim");
	nimln(40, "graphics.nim");
	result.B = ((NU8) ((NI)(((NI) (x.Field2)) & 255)));
	popFrame();
	return result;
}

N_NIMCALL(NI32, createsdlcolor_123053)(tsurface123011* sur, NI c, NI alpha) {
	NI32 result;
	TY99179 x;
	nimfr("createSdlColor", "graphics.nim")
	result = 0;
	nimln(44, "graphics.nim");
	x = extractrgb_99176(c);
	nimln(45, "graphics.nim");
	nimln(45, "graphics.nim");
	nimln(45, "graphics.nim");
	nimln(45, "graphics.nim");
	nimln(46, "graphics.nim");
	nimln(46, "graphics.nim");
	result = Dl_120412((*(*sur).S).Format, ((NU8) ((NI)(((NI) (x.Field0)) & 255))), ((NU8) ((NI)(((NI) (x.Field1)) & 255))), ((NU8) ((NI)(((NI) (x.Field2)) & 255))), ((NU8) ((NI)(alpha & 255))));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	BeforeRet: ;
	return result;
}

N_NIMCALL(trect116227, tosdlrect_123074)(trect123005 r) {
	trect116227 result;
	nimfr("toSdlRect", "graphics.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(50, "graphics.nim");
	result.X = ((NI16)chckRange(r.Field0, ((NI16) -32768), ((NI16) 32767)));
	nimln(51, "graphics.nim");
	result.Y = ((NI16)chckRange(r.Field1, ((NI16) -32768), ((NI16) 32767)));
	nimln(52, "graphics.nim");
	result.W = ((NU16) (r.Field2));
	nimln(53, "graphics.nim");
	result.H = ((NU16) (r.Field3));
	popFrame();
	return result;
}
N_NIMCALL(void, TMP402)(void* p, NI op) {
	egraphics123013* a;
	a = (egraphics123013*)p;
	nimGCvisit((void*)(*a).Sup.Sup.Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.message, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.trace, op);
}

static N_INLINE(tcell45135*, usrtocell_48846)(void* usr) {
	tcell45135* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell45135*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell45135))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50404)(tcell45135* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48817((&gch_47244.Zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell45135* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_48846(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell45135* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_48846((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50404(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, raiseegraphics_123085)(void) {
	egraphics123013* e_123089;
	NCSTRING LOC1;
	nimfr("raiseEGraphics", "graphics.nim")
	e_123089 = 0;
	nimln(2149, "system.nim");
	e_123089 = (egraphics123013*) newObj((&NTI123090), sizeof(egraphics123013));
	(*e_123089).Sup.Sup.Sup.Sup.m_type = (&NTI123013);
	nimln(2150, "system.nim");
	nimln(56, "graphics.nim");
	nimln(56, "graphics.nim");
	LOC1 = 0;
	LOC1 = Dl_119607();
	asgnRefNoCycle((void**) (&(*e_123089).Sup.Sup.Sup.message), cstrToNimstr(LOC1));
	nimln(56, "graphics.nim");
	raiseException((Exception*)e_123089, "EGraphics");
	popFrame();
}

N_NIMCALL(void, surfacefinalizer_123114)(tsurface123011* s) {
	nimfr("surfaceFinalizer", "graphics.nim")
	nimln(58, "graphics.nim");
	Dl_120490((*s).S);
	popFrame();
}
N_NIMCALL(void, TMP409)(void* p, NI op) {
	tsurface123011* a;
	a = (tsurface123011*)p;
}

N_NIMCALL(tsurface123011*, newsurface_123123)(NI width, NI height) {
	tsurface123011* result;
	nimfr("newSurface", "graphics.nim")
	result = 0;
	nimln(62, "graphics.nim");
	result = (tsurface123011*) newObj((&NTI123009), sizeof(tsurface123011));
	nimln(63, "graphics.nim");
	(*result).W = ((NI)chckRange(width, 0, 2147483647));
	nimln(64, "graphics.nim");
	(*result).H = ((NI)chckRange(height, 0, 2147483647));
	nimln(65, "graphics.nim");
	(*result).S = Dl_120463(((NI32) 0), width, height, 32, ((NI32) 16711680), ((NI32) 65280), ((NI32) 255), ((NI32) 0));
	nimln(67, "graphics.nim");
	{
		nimln(67, "graphics.nim");
		if (!((*result).S == NIM_NIL)) goto LA3;
		nimln(68, "graphics.nim");
		raiseegraphics_123085();
	}
	LA3: ;
	nimln(70, "graphics.nim");
	{
		NIM_BOOL LOC7;
		nimln(70, "graphics.nim");
		nimln(70, "graphics.nim");
		nimln(70, "graphics.nim");
		LOC7 = 0;
		LOC7 = mustlock_120496((*result).S);
		if (!!(!(LOC7))) goto LA8;
		nimln(70, "graphics.nim");
		failedassertimpl_85425(((NimStringDesc*) &TMP410));
	}
	LA8: ;
	popFrame();
	return result;
}

N_NIMCALL(void, fontfinalizer_123207)(tfont123015* f) {
	nimfr("fontFinalizer", "graphics.nim")
	nimln(72, "graphics.nim");
	Dl_122477((*f).F);
	popFrame();
}
N_NIMCALL(void, TMP412)(void* p, NI op) {
	tfont123015* a;
	a = (tfont123015*)p;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI32)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(tfont123015*, newfont_123216)(NimStringDesc* name, NI size, NI color) {
	tfont123015* result;
	nimfr("newFont", "graphics.nim")
	result = 0;
	nimln(76, "graphics.nim");
	result = (tfont123015*) newObj((&NTI123017), sizeof(tfont123015));
	nimln(77, "graphics.nim");
	(*result).F = Dl_122242(name->data, ((int) (size)));
	nimln(78, "graphics.nim");
	{
		ioerror3231* e_123271;
		NimStringDesc* LOC5;
		nimln(78, "graphics.nim");
		if (!((*result).F == NIM_NIL)) goto LA3;
		e_123271 = 0;
		nimln(2149, "system.nim");
		e_123271 = (ioerror3231*) newObj((&NTI12801), sizeof(ioerror3231));
		(*e_123271).Sup.Sup.Sup.m_type = (&NTI3231);
		nimln(2150, "system.nim");
		nimln(79, "graphics.nim");
		LOC5 = 0;
		LOC5 = rawNewString(name->Sup.len + 26);
appendString(LOC5, ((NimStringDesc*) &TMP413));
appendString(LOC5, name);
		asgnRefNoCycle((void**) (&(*e_123271).Sup.Sup.message), LOC5);
		nimln(79, "graphics.nim");
		raiseException((Exception*)e_123271, "IOError");
	}
	LA3: ;
	nimln(80, "graphics.nim");
	(*result).Color = tosdlcolor_123035(color);
	popFrame();
	return result;
}

N_NIMCALL(void, initdefaultfont_123302)(NimStringDesc* name, NI size, NI color) {
	nimfr("initDefaultFont", "graphics.nim")
	nimln(88, "graphics.nim");
	asgnRefNoCycle((void**) (&defaultfont_123297), newfont_123216(name, size, color));
	popFrame();
}

N_NIMCALL(tsurface123011*, newscreensurface_123313)(NI width, NI height) {
	tsurface123011* result;
	nimfr("newScreenSurface", "graphics.nim")
	result = 0;
	nimln(92, "graphics.nim");
	result = (tsurface123011*) newObj((&NTI123009), sizeof(tsurface123011));
	nimln(93, "graphics.nim");
	(*result).W = ((NI)chckRange(width, 0, 2147483647));
	nimln(94, "graphics.nim");
	(*result).H = ((NI)chckRange(height, 0, 2147483647));
	nimln(95, "graphics.nim");
	(*result).S = Dl_120327(width, height, 0, ((NU32) 0));
	nimln(96, "graphics.nim");
	{
		nimln(96, "graphics.nim");
		if (!((*result).S == NIM_NIL)) goto LA3;
		nimln(97, "graphics.nim");
		raiseegraphics_123085();
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(void, writetobmp_123371)(tsurface123011* sur, NimStringDesc* filename) {
	nimfr("writeToBMP", "graphics.nim")
	nimln(102, "graphics.nim");
	{
		NI LOC3;
		ioerror3231* e_123377;
		NimStringDesc* LOC6;
		nimln(102, "graphics.nim");
		nimln(102, "graphics.nim");
		nimln(102, "graphics.nim");
		LOC3 = 0;
		LOC3 = savebmp_120535((*sur).S, filename->data);
		if (!!((LOC3 == 0))) goto LA4;
		e_123377 = 0;
		nimln(2149, "system.nim");
		e_123377 = (ioerror3231*) newObj((&NTI12801), sizeof(ioerror3231));
		(*e_123377).Sup.Sup.Sup.m_type = (&NTI3231);
		nimln(2150, "system.nim");
		nimln(103, "graphics.nim");
		LOC6 = 0;
		LOC6 = rawNewString(filename->Sup.len + 14);
appendString(LOC6, ((NimStringDesc*) &TMP414));
appendString(LOC6, filename);
		asgnRefNoCycle((void**) (&(*e_123377).Sup.Sup.message), LOC6);
		nimln(103, "graphics.nim");
		raiseException((Exception*)e_123377, "IOError");
	}
	LA4: ;
	popFrame();
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
	result = 0;
	{
		if (!(b == 0)) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == (-2147483647 -1));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == -1);
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI32)(a / b);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, getpixel_123440)(tsurface123011* sur, NI x, NI y) {
	NI result;
	NI TMP417;
	NI TMP418;
	NI TMP419;
	nimfr("getPixel", "graphics.nim")
	result = 0;
	nimln(119, "graphics.nim");
	{
		nimln(119, "graphics.nim");
		nimln(119, "graphics.nim");
		if (!!(((NU32)(x) < (NU32)(((NI) ((*sur).W)))))) goto LA3;
		nimln(119, "graphics.nim");
		failedassertimpl_85425(((NimStringDesc*) &TMP415));
	}
	LA3: ;
	nimln(120, "graphics.nim");
	{
		nimln(120, "graphics.nim");
		nimln(120, "graphics.nim");
		if (!!(((NU32)(y) < (NU32)(((NI) ((*sur).H)))))) goto LA7;
		nimln(120, "graphics.nim");
		failedassertimpl_85425(((NimStringDesc*) &TMP416));
	}
	LA7: ;
	nimln(121, "graphics.nim");
	nimln(121, "graphics.nim");
	nimln(121, "graphics.nim");
	nimln(121, "graphics.nim");
	TMP417 = divInt(((NI) ((*(*sur).S).Pitch)), 4);
	TMP418 = mulInt(((NI) (y)), (NI32)(TMP417));
	TMP419 = addInt((NI32)(TMP418), ((NI) (x)));
	if ((NU)((NI32)(TMP419)) > (NU)(999999)) raiseIndexError();
	result = ((NI) (((NI32*) ((*(*sur).S).Pixels))[((NI32)(TMP419))- 0]));
	popFrame();
	return result;
}

static N_INLINE(void, setpixel_123819)(tsurface123011* sur, NI x, NI y, NI col) {
	NI32* pixs;
	NI TMP420;
	NI TMP421;
	NI TMP422;
	nimfr("setPixel", "graphics.nim")
	nimln(125, "graphics.nim");
	{
		nimln(125, "graphics.nim");
		nimln(125, "graphics.nim");
		if (!!(((NU32)(x) < (NU32)(((NI) ((*sur).W)))))) goto LA3;
		nimln(125, "graphics.nim");
		failedassertimpl_85425(((NimStringDesc*) &TMP415));
	}
	LA3: ;
	nimln(126, "graphics.nim");
	{
		nimln(126, "graphics.nim");
		nimln(126, "graphics.nim");
		if (!!(((NU32)(y) < (NU32)(((NI) ((*sur).H)))))) goto LA7;
		nimln(126, "graphics.nim");
		failedassertimpl_85425(((NimStringDesc*) &TMP416));
	}
	LA7: ;
	nimln(127, "graphics.nim");
	pixs = ((NI32*) ((*(*sur).S).Pixels));
	nimln(110, "graphics.nim");
	nimln(110, "graphics.nim");
	nimln(110, "graphics.nim");
	nimln(129, "graphics.nim");
	TMP420 = divInt(((NI) ((*(*sur).S).Pitch)), 4);
	TMP421 = mulInt(((NI) (y)), (NI32)(TMP420));
	TMP422 = addInt((NI32)(TMP421), ((NI) (x)));
	if ((NU)((NI32)(TMP422)) > (NU)(999999)) raiseIndexError();
	pixs[((NI32)(TMP422))- 0] = ((NI32) (col));
	popFrame();
}

N_NIMCALL(NI, HEX5BHEX5D_124220)(tsurface123011* sur, tpoint123007 p) {
	NI result;
	nimfr("[]", "graphics.nim")
	result = 0;
	nimln(133, "graphics.nim");
	result = getpixel_123440(sur, ((NI)chckRange(p.Field0, 0, 2147483647)), ((NI)chckRange(p.Field1, 0, 2147483647)));
	popFrame();
	return result;
}

N_NIMCALL(NI, HEX5BHEX5D_124231)(tsurface123011* sur, NI x, NI y) {
	NI result;
	nimfr("[]", "graphics.nim")
	result = 0;
	nimln(137, "graphics.nim");
	result = getpixel_123440(sur, ((NI)chckRange(x, 0, 2147483647)), ((NI)chckRange(y, 0, 2147483647)));
	popFrame();
	return result;
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_124243)(tsurface123011* sur, tpoint123007 p, NI col) {
	nimfr("[]=", "graphics.nim")
	nimln(141, "graphics.nim");
	setpixel_123819(sur, ((NI)chckRange(p.Field0, 0, 2147483647)), ((NI)chckRange(p.Field1, 0, 2147483647)), col);
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_124254)(tsurface123011* sur, NI x, NI y, NI col) {
	nimfr("[]=", "graphics.nim")
	nimln(145, "graphics.nim");
	setpixel_123819(sur, ((NI)chckRange(x, 0, 2147483647)), ((NI)chckRange(y, 0, 2147483647)), col);
	popFrame();
}

N_NIMCALL(void, blit_124266)(tsurface123011* destsurf, trect123005 destrect, tsurface123011* srcsurf, trect123005 srcrect) {
	trect116227 desttrect;
	trect116227 srctrect;
	nimfr("blit", "graphics.nim")
	memset((void*)(&desttrect), 0, sizeof(desttrect));
	memset((void*)(&srctrect), 0, sizeof(srctrect));
	nimln(152, "graphics.nim");
	desttrect.X = ((NI16)chckRange(destrect.Field0, ((NI16) -32768), ((NI16) 32767)));
	nimln(153, "graphics.nim");
	desttrect.Y = ((NI16)chckRange(destrect.Field1, ((NI16) -32768), ((NI16) 32767)));
	nimln(154, "graphics.nim");
	desttrect.W = ((NU16) (destrect.Field2));
	nimln(155, "graphics.nim");
	desttrect.H = ((NU16) (destrect.Field3));
	nimln(157, "graphics.nim");
	srctrect.X = ((NI16)chckRange(srcrect.Field0, ((NI16) -32768), ((NI16) 32767)));
	nimln(158, "graphics.nim");
	srctrect.Y = ((NI16)chckRange(srcrect.Field1, ((NI16) -32768), ((NI16) 32767)));
	nimln(159, "graphics.nim");
	srctrect.W = ((NU16) (srcrect.Field2));
	nimln(160, "graphics.nim");
	srctrect.H = ((NU16) (srcrect.Field3));
	nimln(162, "graphics.nim");
	{
		NI LOC3;
		nimln(162, "graphics.nim");
		nimln(162, "graphics.nim");
		nimln(162, "graphics.nim");
		LOC3 = 0;
		LOC3 = blitsurface_120580((*srcsurf).S, (&srctrect), (*destsurf).S, (&desttrect));
		if (!!((LOC3 == 0))) goto LA4;
		nimln(163, "graphics.nim");
		raiseegraphics_123085();
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(tpoint123007, textbounds_124283)(NimStringDesc* text, tfont123015* font) {
	tpoint123007 result;
	int w;
	int h;
	nimfr("textBounds", "graphics.nim")
	memset((void*)(&result), 0, sizeof(result));
	w = 0;
	h = 0;
	nimln(167, "graphics.nim");
	{
		int LOC3;
		nimln(167, "graphics.nim");
		nimln(167, "graphics.nim");
		LOC3 = 0;
		LOC3 = Dl_122363((*font).F, text->data, (&w), (&h));
		if (!(LOC3 < ((NI32) 0))) goto LA4;
		nimln(167, "graphics.nim");
		raiseegraphics_123085();
	}
	LA4: ;
	nimln(168, "graphics.nim");
	result.Field0 = ((NI) (w));
	nimln(169, "graphics.nim");
	result.Field1 = ((NI) (h));
	popFrame();
	return result;
}

N_NIMCALL(void, drawtext_124307)(tsurface123011* sur, tpoint123007 p, NimStringDesc* text, tfont123015* font) {
	tsurface123011* textsur;
	trect123005 LOC1;
	trect123005 LOC2;
	nimfr("drawText", "graphics.nim")
	textsur = 0;
	nimln(175, "graphics.nim");
	textsur = (tsurface123011*) newObj((&NTI123009), sizeof(tsurface123011));
	nimln(178, "graphics.nim");
	(*textsur).S = Dl_122445((*font).F, text->data, (*font).Color);
	nimln(180, "graphics.nim");
	LOC1.Field0 = p.Field0;
	LOC1.Field1 = p.Field1;
	LOC1.Field2 = (*sur).W;
	LOC1.Field3 = (*sur).H;
	LOC2.Field0 = 0;
	LOC2.Field1 = 0;
	LOC2.Field2 = (*sur).W;
	LOC2.Field3 = (*sur).H;
	blit_124266(sur, LOC1, textsur, LOC2);
	popFrame();
}

N_NIMCALL(void, drawtext_124353)(tsurface123011* sur, tpoint123007 p, NimStringDesc* text, NI bg, tfont123015* font) {
	tsurface123011* textsur;
	tcolor116233 LOC1;
	trect123005 LOC2;
	trect123005 LOC3;
	nimfr("drawText", "graphics.nim")
	textsur = 0;
	nimln(187, "graphics.nim");
	textsur = (tsurface123011*) newObj((&NTI123009), sizeof(tsurface123011));
	nimln(188, "graphics.nim");
	nimln(188, "graphics.nim");
	LOC1 = tosdlcolor_123035(bg);
	(*textsur).S = Dl_122409((*font).F, text->data, (*font).Color, LOC1);
	nimln(190, "graphics.nim");
	LOC2.Field0 = p.Field0;
	LOC2.Field1 = p.Field1;
	LOC2.Field2 = (*sur).W;
	LOC2.Field3 = (*sur).H;
	LOC3.Field0 = 0;
	LOC3.Field1 = 0;
	LOC3.Field2 = (*sur).W;
	LOC3.Field3 = (*sur).H;
	blit_124266(sur, LOC2, textsur, LOC3);
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) - (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU32) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, drawcircle_124400)(tsurface123011* sur, tpoint123007 p, NI r, NI color) {
	NI32* video;
	NI pitch;
	NI TMP423;
	NI a;
	NI TMP424;
	NI py;
	NI px;
	NI x;
	NI y;
	nimfr("drawCircle", "graphics.nim")
	nimln(195, "graphics.nim");
	video = ((NI32*) ((*(*sur).S).Pixels));
	nimln(196, "graphics.nim");
	nimln(196, "graphics.nim");
	TMP423 = divInt(((NI) ((*(*sur).S).Pitch)), 4);
	pitch = (NI32)(TMP423);
	nimln(197, "graphics.nim");
	nimln(197, "graphics.nim");
	TMP424 = subInt(1, ((NI) (r)));
	a = (NI32)(TMP424);
	nimln(198, "graphics.nim");
	py = r;
	nimln(199, "graphics.nim");
	px = 0;
	nimln(200, "graphics.nim");
	x = p.Field0;
	nimln(201, "graphics.nim");
	y = p.Field1;
	{
		nimln(202, "graphics.nim");
		while (1) {
			NI TMP425;
			NI TMP478;
			nimln(202, "graphics.nim");
			nimln(202, "graphics.nim");
			TMP425 = addInt(((NI) (py)), 1);
			if (!(px <= ((NI)chckRange((NI32)(TMP425), (-2147483647 -1), 2147483647)))) goto LA2;
			nimln(203, "graphics.nim");
			{
				NI TMP426;
				nimln(203, "graphics.nim");
				nimln(203, "graphics.nim");
				TMP426 = addInt(x, px);
				if (!((NU32)((NI32)(TMP426)) < (NU32)(((NI) ((*sur).W))))) goto LA5;
				nimln(204, "graphics.nim");
				{
					NI TMP427;
					NI TMP428;
					NI TMP429;
					NI TMP430;
					NI TMP431;
					nimln(204, "graphics.nim");
					nimln(204, "graphics.nim");
					TMP427 = addInt(y, ((NI) (py)));
					if (!((NU32)((NI32)(TMP427)) < (NU32)(((NI) ((*sur).H))))) goto LA9;
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(204, "graphics.nim");
					TMP428 = addInt(y, ((NI) (py)));
					TMP429 = mulInt((NI32)(TMP428), pitch);
					nimln(204, "graphics.nim");
					TMP430 = addInt(x, px);
					TMP431 = addInt((NI32)(TMP429), (NI32)(TMP430));
					if ((NU)((NI32)(TMP431)) > (NU)(999999)) raiseIndexError();
					video[((NI32)(TMP431))- 0] = ((NI32) (color));
				}
				LA9: ;
				nimln(205, "graphics.nim");
				{
					NI TMP432;
					NI TMP433;
					NI TMP434;
					NI TMP435;
					NI TMP436;
					nimln(205, "graphics.nim");
					nimln(205, "graphics.nim");
					TMP432 = subInt(y, ((NI) (py)));
					if (!((NU32)((NI32)(TMP432)) < (NU32)(((NI) ((*sur).H))))) goto LA13;
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(205, "graphics.nim");
					TMP433 = subInt(y, ((NI) (py)));
					TMP434 = mulInt((NI32)(TMP433), pitch);
					nimln(205, "graphics.nim");
					TMP435 = addInt(x, px);
					TMP436 = addInt((NI32)(TMP434), (NI32)(TMP435));
					if ((NU)((NI32)(TMP436)) > (NU)(999999)) raiseIndexError();
					video[((NI32)(TMP436))- 0] = ((NI32) (color));
				}
				LA13: ;
			}
			LA5: ;
			nimln(207, "graphics.nim");
			{
				NI TMP437;
				nimln(207, "graphics.nim");
				nimln(207, "graphics.nim");
				TMP437 = subInt(x, px);
				if (!((NU32)((NI32)(TMP437)) < (NU32)(((NI) ((*sur).W))))) goto LA17;
				nimln(208, "graphics.nim");
				{
					NI TMP438;
					NI TMP439;
					NI TMP440;
					NI TMP441;
					NI TMP442;
					nimln(208, "graphics.nim");
					nimln(208, "graphics.nim");
					TMP438 = addInt(y, ((NI) (py)));
					if (!((NU32)((NI32)(TMP438)) < (NU32)(((NI) ((*sur).H))))) goto LA21;
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(208, "graphics.nim");
					TMP439 = addInt(y, ((NI) (py)));
					TMP440 = mulInt((NI32)(TMP439), pitch);
					nimln(208, "graphics.nim");
					TMP441 = subInt(x, px);
					TMP442 = addInt((NI32)(TMP440), (NI32)(TMP441));
					if ((NU)((NI32)(TMP442)) > (NU)(999999)) raiseIndexError();
					video[((NI32)(TMP442))- 0] = ((NI32) (color));
				}
				LA21: ;
				nimln(209, "graphics.nim");
				{
					NI TMP443;
					NI TMP444;
					NI TMP445;
					NI TMP446;
					NI TMP447;
					nimln(209, "graphics.nim");
					nimln(209, "graphics.nim");
					TMP443 = subInt(y, ((NI) (py)));
					if (!((NU32)((NI32)(TMP443)) < (NU32)(((NI) ((*sur).H))))) goto LA25;
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(209, "graphics.nim");
					TMP444 = subInt(y, ((NI) (py)));
					TMP445 = mulInt((NI32)(TMP444), pitch);
					nimln(209, "graphics.nim");
					TMP446 = subInt(x, px);
					TMP447 = addInt((NI32)(TMP445), (NI32)(TMP446));
					if ((NU)((NI32)(TMP447)) > (NU)(999999)) raiseIndexError();
					video[((NI32)(TMP447))- 0] = ((NI32) (color));
				}
				LA25: ;
			}
			LA17: ;
			nimln(211, "graphics.nim");
			{
				NI TMP448;
				nimln(211, "graphics.nim");
				nimln(211, "graphics.nim");
				TMP448 = addInt(x, ((NI) (py)));
				if (!((NU32)((NI32)(TMP448)) < (NU32)(((NI) ((*sur).W))))) goto LA29;
				nimln(212, "graphics.nim");
				{
					NI TMP449;
					NI TMP450;
					NI TMP451;
					NI TMP452;
					NI TMP453;
					nimln(212, "graphics.nim");
					nimln(212, "graphics.nim");
					TMP449 = addInt(y, px);
					if (!((NU32)((NI32)(TMP449)) < (NU32)(((NI) ((*sur).H))))) goto LA33;
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(212, "graphics.nim");
					TMP450 = addInt(y, px);
					TMP451 = mulInt((NI32)(TMP450), pitch);
					nimln(212, "graphics.nim");
					TMP452 = addInt(x, ((NI) (py)));
					TMP453 = addInt((NI32)(TMP451), (NI32)(TMP452));
					if ((NU)((NI32)(TMP453)) > (NU)(999999)) raiseIndexError();
					video[((NI32)(TMP453))- 0] = ((NI32) (color));
				}
				LA33: ;
				nimln(213, "graphics.nim");
				{
					NI TMP454;
					NI TMP455;
					NI TMP456;
					NI TMP457;
					NI TMP458;
					nimln(213, "graphics.nim");
					nimln(213, "graphics.nim");
					TMP454 = subInt(y, px);
					if (!((NU32)((NI32)(TMP454)) < (NU32)(((NI) ((*sur).H))))) goto LA37;
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(213, "graphics.nim");
					TMP455 = subInt(y, px);
					TMP456 = mulInt((NI32)(TMP455), pitch);
					nimln(213, "graphics.nim");
					TMP457 = addInt(x, ((NI) (py)));
					TMP458 = addInt((NI32)(TMP456), (NI32)(TMP457));
					if ((NU)((NI32)(TMP458)) > (NU)(999999)) raiseIndexError();
					video[((NI32)(TMP458))- 0] = ((NI32) (color));
				}
				LA37: ;
			}
			LA29: ;
			nimln(215, "graphics.nim");
			{
				NI TMP459;
				nimln(215, "graphics.nim");
				nimln(215, "graphics.nim");
				TMP459 = subInt(x, ((NI) (py)));
				if (!((NU32)((NI32)(TMP459)) < (NU32)(((NI) ((*sur).W))))) goto LA41;
				nimln(216, "graphics.nim");
				{
					NI TMP460;
					NI TMP461;
					NI TMP462;
					NI TMP463;
					NI TMP464;
					nimln(216, "graphics.nim");
					nimln(216, "graphics.nim");
					TMP460 = addInt(y, px);
					if (!((NU32)((NI32)(TMP460)) < (NU32)(((NI) ((*sur).H))))) goto LA45;
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(216, "graphics.nim");
					TMP461 = addInt(y, px);
					TMP462 = mulInt((NI32)(TMP461), pitch);
					nimln(216, "graphics.nim");
					TMP463 = subInt(x, ((NI) (py)));
					TMP464 = addInt((NI32)(TMP462), (NI32)(TMP463));
					if ((NU)((NI32)(TMP464)) > (NU)(999999)) raiseIndexError();
					video[((NI32)(TMP464))- 0] = ((NI32) (color));
				}
				LA45: ;
				nimln(217, "graphics.nim");
				{
					NI TMP465;
					NI TMP466;
					NI TMP467;
					NI TMP468;
					NI TMP469;
					nimln(217, "graphics.nim");
					nimln(217, "graphics.nim");
					TMP465 = subInt(y, px);
					if (!((NU32)((NI32)(TMP465)) < (NU32)(((NI) ((*sur).H))))) goto LA49;
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(217, "graphics.nim");
					TMP466 = subInt(y, px);
					TMP467 = mulInt((NI32)(TMP466), pitch);
					nimln(217, "graphics.nim");
					TMP468 = subInt(x, ((NI) (py)));
					TMP469 = addInt((NI32)(TMP467), (NI32)(TMP468));
					if ((NU)((NI32)(TMP469)) > (NU)(999999)) raiseIndexError();
					video[((NI32)(TMP469))- 0] = ((NI32) (color));
				}
				LA49: ;
			}
			LA41: ;
			nimln(219, "graphics.nim");
			{
				NI TMP470;
				NI TMP471;
				NI TMP472;
				nimln(219, "graphics.nim");
				if (!(a < 0)) goto LA53;
				nimln(220, "graphics.nim");
				nimln(220, "graphics.nim");
				nimln(220, "graphics.nim");
				nimln(220, "graphics.nim");
				TMP470 = mulInt(2, px);
				TMP471 = addInt((NI32)(TMP470), 3);
				TMP472 = addInt(a, (NI32)(TMP471));
				a = (NI32)(TMP472);
			}
			goto LA51;
			LA53: ;
			{
				NI TMP473;
				NI TMP474;
				NI TMP475;
				NI TMP476;
				NI TMP477;
				nimln(222, "graphics.nim");
				nimln(222, "graphics.nim");
				nimln(222, "graphics.nim");
				nimln(222, "graphics.nim");
				nimln(222, "graphics.nim");
				TMP473 = subInt(px, ((NI) (py)));
				TMP474 = mulInt(2, (NI32)(TMP473));
				TMP475 = addInt((NI32)(TMP474), 5);
				TMP476 = addInt(a, (NI32)(TMP475));
				a = (NI32)(TMP476);
				nimln(223, "graphics.nim");
				nimln(223, "graphics.nim");
				TMP477 = subInt(((NI) (py)), 1);
				py = ((NI)chckRange((NI32)(TMP477), 0, 2147483647));
			}
			LA51: ;
			nimln(224, "graphics.nim");
			nimln(224, "graphics.nim");
			TMP478 = addInt(px, 1);
			px = (NI32)(TMP478);
		} LA2: ;
	}
	popFrame();
}

static N_INLINE(NI, HEX3EHEX2DHEX3C_124547)(NI val, tsurface123011* s) {
	NI result;
	nimfr(">-<", "graphics.nim")
	result = 0;
	nimln(227, "graphics.nim");
	nimln(227, "graphics.nim");
	nimln(227, "graphics.nim");
	{
		nimln(227, "graphics.nim");
		if (!(val < 0)) goto LA3;
		result = 0;
	}
	goto LA1;
	LA3: ;
	{
		NI TMP479;
		nimln(227, "graphics.nim");
		if (!(((NI) ((*s).W)) <= val)) goto LA6;
		nimln(227, "graphics.nim");
		TMP479 = subInt(((NI) ((*s).W)), 1);
		result = ((NI) ((NI32)(TMP479)));
	}
	goto LA1;
	LA6: ;
	{
		result = val;
	}
	LA1: ;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI, HEX3EHEX7CHEX3C_124560)(NI val, tsurface123011* s) {
	NI result;
	nimfr(">|<", "graphics.nim")
	result = 0;
	nimln(230, "graphics.nim");
	nimln(230, "graphics.nim");
	nimln(230, "graphics.nim");
	{
		nimln(230, "graphics.nim");
		if (!(val < 0)) goto LA3;
		result = 0;
	}
	goto LA1;
	LA3: ;
	{
		NI TMP480;
		nimln(230, "graphics.nim");
		if (!(((NI) ((*s).H)) <= val)) goto LA6;
		nimln(230, "graphics.nim");
		TMP480 = subInt(((NI) ((*s).H)), 1);
		result = ((NI) ((NI32)(TMP480)));
	}
	goto LA1;
	LA6: ;
	{
		result = val;
	}
	LA1: ;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, drawline_124573)(tsurface123011* sur, tpoint123007 p1, tpoint123007 p2, NI color) {
	NI stepx;
	NI stepy;
	NI x0;
	NI x1;
	NI y0;
	NI y1;
	NI dy;
	NI TMP481;
	NI dx;
	NI TMP482;
	NI TMP483;
	NI TMP484;
	NI32* video;
	NI pitch;
	NI TMP485;
	NI TMP486;
	NI TMP487;
	nimfr("drawLine", "graphics.nim")
	nimln(235, "graphics.nim");
	stepx = 0;
	nimln(235, "graphics.nim");
	stepy = 0;
	nimln(236, "graphics.nim");
	x0 = HEX3EHEX2DHEX3C_124547(p1.Field0, sur);
	nimln(237, "graphics.nim");
	x1 = HEX3EHEX2DHEX3C_124547(p2.Field0, sur);
	nimln(238, "graphics.nim");
	y0 = HEX3EHEX7CHEX3C_124560(p1.Field1, sur);
	nimln(239, "graphics.nim");
	y1 = HEX3EHEX7CHEX3C_124560(p2.Field1, sur);
	nimln(240, "graphics.nim");
	nimln(240, "graphics.nim");
	TMP481 = subInt(y1, y0);
	dy = (NI32)(TMP481);
	nimln(241, "graphics.nim");
	nimln(241, "graphics.nim");
	TMP482 = subInt(x1, x0);
	dx = (NI32)(TMP482);
	nimln(242, "graphics.nim");
	{
		nimln(242, "graphics.nim");
		if (!(dy < 0)) goto LA3;
		nimln(243, "graphics.nim");
		nimln(243, "graphics.nim");
		if (dy == (-2147483647 -1)) raiseOverflow();
		dy = ((NI32)-(dy));
		nimln(244, "graphics.nim");
		stepy = -1;
	}
	goto LA1;
	LA3: ;
	{
		nimln(246, "graphics.nim");
		stepy = 1;
	}
	LA1: ;
	nimln(247, "graphics.nim");
	{
		nimln(247, "graphics.nim");
		if (!(dx < 0)) goto LA8;
		nimln(248, "graphics.nim");
		nimln(248, "graphics.nim");
		if (dx == (-2147483647 -1)) raiseOverflow();
		dx = ((NI32)-(dx));
		nimln(249, "graphics.nim");
		stepx = -1;
	}
	goto LA6;
	LA8: ;
	{
		nimln(251, "graphics.nim");
		stepx = 1;
	}
	LA6: ;
	nimln(252, "graphics.nim");
	nimln(252, "graphics.nim");
	TMP483 = mulInt(dy, 2);
	dy = (NI32)(TMP483);
	nimln(253, "graphics.nim");
	nimln(253, "graphics.nim");
	TMP484 = mulInt(dx, 2);
	dx = (NI32)(TMP484);
	nimln(254, "graphics.nim");
	video = ((NI32*) ((*(*sur).S).Pixels));
	nimln(255, "graphics.nim");
	nimln(255, "graphics.nim");
	TMP485 = divInt(((NI) ((*(*sur).S).Pitch)), 4);
	pitch = (NI32)(TMP485);
	nimln(110, "graphics.nim");
	nimln(110, "graphics.nim");
	nimln(110, "graphics.nim");
	TMP486 = mulInt(y0, pitch);
	TMP487 = addInt((NI32)(TMP486), x0);
	if ((NU)((NI32)(TMP487)) > (NU)(999999)) raiseIndexError();
	video[((NI32)(TMP487))- 0] = ((NI32) (color));
	nimln(257, "graphics.nim");
	{
		NI fraction;
		NI TMP488;
		NI TMP489;
		nimln(257, "graphics.nim");
		if (!(dy < dx)) goto LA13;
		nimln(258, "graphics.nim");
		nimln(258, "graphics.nim");
		nimln(258, "graphics.nim");
		TMP488 = divInt(dx, 2);
		TMP489 = subInt(dy, (NI32)(TMP488));
		fraction = (NI32)(TMP489);
		{
			nimln(259, "graphics.nim");
			while (1) {
				NI TMP492;
				NI TMP493;
				NI TMP494;
				NI TMP495;
				nimln(259, "graphics.nim");
				nimln(259, "graphics.nim");
				if (!!((x0 == x1))) goto LA16;
				nimln(260, "graphics.nim");
				{
					NI TMP490;
					NI TMP491;
					nimln(260, "graphics.nim");
					if (!(0 <= fraction)) goto LA19;
					nimln(261, "graphics.nim");
					nimln(261, "graphics.nim");
					TMP490 = addInt(y0, stepy);
					y0 = (NI32)(TMP490);
					nimln(262, "graphics.nim");
					nimln(262, "graphics.nim");
					TMP491 = subInt(fraction, dx);
					fraction = (NI32)(TMP491);
				}
				LA19: ;
				nimln(263, "graphics.nim");
				nimln(263, "graphics.nim");
				TMP492 = addInt(x0, stepx);
				x0 = (NI32)(TMP492);
				nimln(264, "graphics.nim");
				nimln(264, "graphics.nim");
				TMP493 = addInt(fraction, dy);
				fraction = (NI32)(TMP493);
				nimln(110, "graphics.nim");
				nimln(110, "graphics.nim");
				nimln(110, "graphics.nim");
				TMP494 = mulInt(y0, pitch);
				TMP495 = addInt((NI32)(TMP494), x0);
				if ((NU)((NI32)(TMP495)) > (NU)(999999)) raiseIndexError();
				video[((NI32)(TMP495))- 0] = ((NI32) (color));
			} LA16: ;
		}
	}
	goto LA11;
	LA13: ;
	{
		NI fraction;
		NI TMP496;
		NI TMP497;
		nimln(267, "graphics.nim");
		nimln(267, "graphics.nim");
		nimln(267, "graphics.nim");
		TMP496 = divInt(dy, 2);
		TMP497 = subInt(dx, (NI32)(TMP496));
		fraction = (NI32)(TMP497);
		{
			nimln(268, "graphics.nim");
			while (1) {
				NI TMP500;
				NI TMP501;
				NI TMP502;
				NI TMP503;
				nimln(268, "graphics.nim");
				nimln(268, "graphics.nim");
				if (!!((y0 == y1))) goto LA23;
				nimln(269, "graphics.nim");
				{
					NI TMP498;
					NI TMP499;
					nimln(269, "graphics.nim");
					if (!(0 <= fraction)) goto LA26;
					nimln(270, "graphics.nim");
					nimln(270, "graphics.nim");
					TMP498 = addInt(x0, stepx);
					x0 = (NI32)(TMP498);
					nimln(271, "graphics.nim");
					nimln(271, "graphics.nim");
					TMP499 = subInt(fraction, dy);
					fraction = (NI32)(TMP499);
				}
				LA26: ;
				nimln(272, "graphics.nim");
				nimln(272, "graphics.nim");
				TMP500 = addInt(y0, stepy);
				y0 = (NI32)(TMP500);
				nimln(273, "graphics.nim");
				nimln(273, "graphics.nim");
				TMP501 = addInt(fraction, dx);
				fraction = (NI32)(TMP501);
				nimln(110, "graphics.nim");
				nimln(110, "graphics.nim");
				nimln(110, "graphics.nim");
				TMP502 = mulInt(y0, pitch);
				TMP503 = addInt((NI32)(TMP502), x0);
				if ((NU)((NI32)(TMP503)) > (NU)(999999)) raiseIndexError();
				video[((NI32)(TMP503))- 0] = ((NI32) (color));
			} LA23: ;
		}
	}
	LA11: ;
	popFrame();
}

N_NIMCALL(void, drawhorline_124621)(tsurface123011* sur, NI x, NI y, NI w, NI color) {
	NI32* video;
	NI pitch;
	NI TMP504;
	nimfr("drawHorLine", "graphics.nim")
	nimln(278, "graphics.nim");
	video = ((NI32*) ((*(*sur).S).Pixels));
	nimln(279, "graphics.nim");
	nimln(279, "graphics.nim");
	TMP504 = divInt(((NI) ((*(*sur).S).Pitch)), 4);
	pitch = (NI32)(TMP504);
	nimln(281, "graphics.nim");
	{
		NIM_BOOL LOC3;
		nimln(281, "graphics.nim");
		LOC3 = 0;
		nimln(281, "graphics.nim");
		LOC3 = (0 <= ((NI) (y)));
		if (!(LOC3)) goto LA4;
		nimln(281, "graphics.nim");
		LOC3 = (((NI32) (y)) <= (*(*sur).S).H);
		LA4: ;
		if (!LOC3) goto LA5;
		{
			NI32 i_124668;
			NI32 HEX3Atmp_124673;
			NI32 TMP505;
			NI32 TMP506;
			NI32 res_124676;
			i_124668 = 0;
			HEX3Atmp_124673 = 0;
			nimln(282, "graphics.nim");
			nimln(282, "graphics.nim");
			nimln(282, "graphics.nim");
			nimln(282, "graphics.nim");
			TMP505 = subInt((*(*sur).S).W, ((NI32) (x)));
			TMP506 = subInt((((NI32)(TMP505) <= ((NI32) (w))) ? (NI32)(TMP505) : ((NI32) (w))), ((NI32) 1));
			HEX3Atmp_124673 = (NI32)(TMP506);
			nimln(1576, "system.nim");
			res_124676 = ((NI32) 0);
			{
				nimln(1577, "system.nim");
				while (1) {
					NI TMP507;
					NI32 TMP508;
					NI TMP509;
					nimln(1577, "system.nim");
					if (!(res_124676 <= HEX3Atmp_124673)) goto LA9;
					nimln(1576, "system.nim");
					i_124668 = res_124676;
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					TMP507 = mulInt(((NI) (y)), pitch);
					nimln(283, "graphics.nim");
					TMP508 = addInt(((NI32) (x)), i_124668);
					TMP509 = addInt((NI32)(TMP507), ((NI) ((NI32)(TMP508))));
					if ((NU)((NI32)(TMP509)) > (NU)(999999)) raiseIndexError();
					video[((NI32)(TMP509))- 0] = ((NI32) (color));
					nimln(1579, "system.nim");
					res_124676 = addInt(res_124676, 1);
				} LA9: ;
			}
		}
	}
	LA5: ;
	popFrame();
}

N_NIMCALL(void, drawverline_124693)(tsurface123011* sur, NI x, NI y, NI h, NI color) {
	NI32* video;
	NI pitch;
	NI TMP510;
	nimfr("drawVerLine", "graphics.nim")
	nimln(287, "graphics.nim");
	video = ((NI32*) ((*(*sur).S).Pixels));
	nimln(288, "graphics.nim");
	nimln(288, "graphics.nim");
	TMP510 = divInt(((NI) ((*(*sur).S).Pitch)), 4);
	pitch = (NI32)(TMP510);
	nimln(290, "graphics.nim");
	{
		NIM_BOOL LOC3;
		nimln(290, "graphics.nim");
		LOC3 = 0;
		nimln(290, "graphics.nim");
		LOC3 = (0 <= ((NI) (x)));
		if (!(LOC3)) goto LA4;
		nimln(290, "graphics.nim");
		LOC3 = (((NI32) (x)) <= (*(*sur).S).W);
		LA4: ;
		if (!LOC3) goto LA5;
		{
			NI32 i_124715;
			NI32 HEX3Atmp_124720;
			NI32 TMP511;
			NI32 TMP512;
			NI32 res_124723;
			i_124715 = 0;
			HEX3Atmp_124720 = 0;
			nimln(291, "graphics.nim");
			nimln(291, "graphics.nim");
			nimln(291, "graphics.nim");
			nimln(291, "graphics.nim");
			TMP511 = subInt((*(*sur).S).H, ((NI32) (y)));
			TMP512 = subInt((((NI32)(TMP511) <= ((NI32) (h))) ? (NI32)(TMP511) : ((NI32) (h))), ((NI32) 1));
			HEX3Atmp_124720 = (NI32)(TMP512);
			nimln(1576, "system.nim");
			res_124723 = ((NI32) 0);
			{
				nimln(1577, "system.nim");
				while (1) {
					NI32 TMP513;
					NI TMP514;
					NI TMP515;
					nimln(1577, "system.nim");
					if (!(res_124723 <= HEX3Atmp_124720)) goto LA9;
					nimln(1576, "system.nim");
					i_124715 = res_124723;
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(292, "graphics.nim");
					TMP513 = addInt(((NI32) (y)), i_124715);
					TMP514 = mulInt(((NI) ((NI32)(TMP513))), pitch);
					TMP515 = addInt((NI32)(TMP514), ((NI) (x)));
					if ((NU)((NI32)(TMP515)) > (NU)(999999)) raiseIndexError();
					video[((NI32)(TMP515))- 0] = ((NI32) (color));
					nimln(1579, "system.nim");
					res_124723 = addInt(res_124723, 1);
				} LA9: ;
			}
		}
	}
	LA5: ;
	popFrame();
}

N_NIMCALL(void, fillcircle_124740)(tsurface123011* s, tpoint123007 p, NI r, NI color) {
	NI a;
	NI TMP516;
	NI py;
	NI px;
	NI x;
	NI y;
	nimfr("fillCircle", "graphics.nim")
	nimln(297, "graphics.nim");
	nimln(297, "graphics.nim");
	TMP516 = subInt(1, ((NI) (r)));
	a = (NI32)(TMP516);
	nimln(298, "graphics.nim");
	py = ((NI) (r));
	nimln(299, "graphics.nim");
	px = 0;
	nimln(300, "graphics.nim");
	x = p.Field0;
	nimln(301, "graphics.nim");
	y = p.Field1;
	{
		nimln(302, "graphics.nim");
		while (1) {
			NI TMP517;
			NI TMP518;
			NI TMP519;
			NI TMP520;
			NI TMP545;
			nimln(302, "graphics.nim");
			if (!(px <= py)) goto LA2;
			nimln(304, "graphics.nim");
			nimln(304, "graphics.nim");
			TMP517 = addInt(x, px);
			nimln(304, "graphics.nim");
			TMP518 = addInt(py, 1);
			drawverline_124693(s, ((NI)chckRange((NI32)(TMP517), 0, 2147483647)), ((NI)chckRange(y, 0, 2147483647)), ((NI)chckRange((NI32)(TMP518), 0, 2147483647)), color);
			nimln(305, "graphics.nim");
			nimln(305, "graphics.nim");
			TMP519 = addInt(x, px);
			nimln(305, "graphics.nim");
			TMP520 = subInt(y, py);
			drawverline_124693(s, ((NI)chckRange((NI32)(TMP519), 0, 2147483647)), ((NI)chckRange((NI32)(TMP520), 0, 2147483647)), ((NI)chckRange(py, 0, 2147483647)), color);
			nimln(306, "graphics.nim");
			{
				NI TMP521;
				NI TMP522;
				NI TMP523;
				NI TMP524;
				nimln(306, "graphics.nim");
				nimln(306, "graphics.nim");
				if (!!((px == 0))) goto LA5;
				nimln(307, "graphics.nim");
				nimln(307, "graphics.nim");
				TMP521 = subInt(x, px);
				nimln(307, "graphics.nim");
				TMP522 = addInt(py, 1);
				drawverline_124693(s, ((NI)chckRange((NI32)(TMP521), 0, 2147483647)), ((NI)chckRange(y, 0, 2147483647)), ((NI)chckRange((NI32)(TMP522), 0, 2147483647)), color);
				nimln(308, "graphics.nim");
				nimln(308, "graphics.nim");
				TMP523 = subInt(x, px);
				nimln(308, "graphics.nim");
				TMP524 = subInt(y, py);
				drawverline_124693(s, ((NI)chckRange((NI32)(TMP523), 0, 2147483647)), ((NI)chckRange((NI32)(TMP524), 0, 2147483647)), ((NI)chckRange(py, 0, 2147483647)), color);
			}
			LA5: ;
			nimln(309, "graphics.nim");
			{
				NI TMP525;
				NI TMP526;
				NI TMP527;
				nimln(309, "graphics.nim");
				if (!(a < 0)) goto LA9;
				nimln(310, "graphics.nim");
				nimln(310, "graphics.nim");
				nimln(310, "graphics.nim");
				nimln(310, "graphics.nim");
				TMP525 = mulInt(2, px);
				TMP526 = addInt((NI32)(TMP525), 3);
				TMP527 = addInt(a, (NI32)(TMP526));
				a = (NI32)(TMP527);
			}
			goto LA7;
			LA9: ;
			{
				NI TMP528;
				NI TMP529;
				NI TMP530;
				NI TMP531;
				NI TMP532;
				nimln(312, "graphics.nim");
				nimln(312, "graphics.nim");
				nimln(312, "graphics.nim");
				nimln(312, "graphics.nim");
				nimln(312, "graphics.nim");
				TMP528 = subInt(px, py);
				TMP529 = mulInt(2, (NI32)(TMP528));
				TMP530 = addInt((NI32)(TMP529), 5);
				TMP531 = addInt(a, (NI32)(TMP530));
				a = (NI32)(TMP531);
				nimln(313, "graphics.nim");
				nimln(313, "graphics.nim");
				TMP532 = subInt(py, 1);
				py = (NI32)(TMP532);
				nimln(315, "graphics.nim");
				{
					NI TMP533;
					NI TMP534;
					NI TMP535;
					NI TMP536;
					NI TMP537;
					NI TMP538;
					NI TMP539;
					NI TMP540;
					NI TMP541;
					NI TMP542;
					NI TMP543;
					NI TMP544;
					nimln(315, "graphics.nim");
					if (!(px <= py)) goto LA14;
					nimln(316, "graphics.nim");
					nimln(316, "graphics.nim");
					nimln(316, "graphics.nim");
					TMP533 = addInt(x, py);
					TMP534 = addInt((NI32)(TMP533), 1);
					nimln(316, "graphics.nim");
					TMP535 = addInt(px, 1);
					drawverline_124693(s, ((NI)chckRange((NI32)(TMP534), 0, 2147483647)), ((NI)chckRange(y, 0, 2147483647)), ((NI)chckRange((NI32)(TMP535), 0, 2147483647)), color);
					nimln(317, "graphics.nim");
					nimln(317, "graphics.nim");
					nimln(317, "graphics.nim");
					TMP536 = addInt(x, py);
					TMP537 = addInt((NI32)(TMP536), 1);
					nimln(317, "graphics.nim");
					TMP538 = subInt(y, px);
					drawverline_124693(s, ((NI)chckRange((NI32)(TMP537), 0, 2147483647)), ((NI)chckRange((NI32)(TMP538), 0, 2147483647)), ((NI)chckRange(px, 0, 2147483647)), color);
					nimln(318, "graphics.nim");
					nimln(318, "graphics.nim");
					nimln(318, "graphics.nim");
					TMP539 = subInt(x, py);
					TMP540 = subInt((NI32)(TMP539), 1);
					nimln(318, "graphics.nim");
					TMP541 = addInt(px, 1);
					drawverline_124693(s, ((NI)chckRange((NI32)(TMP540), 0, 2147483647)), ((NI)chckRange(y, 0, 2147483647)), ((NI)chckRange((NI32)(TMP541), 0, 2147483647)), color);
					nimln(319, "graphics.nim");
					nimln(319, "graphics.nim");
					nimln(319, "graphics.nim");
					TMP542 = subInt(x, py);
					TMP543 = subInt((NI32)(TMP542), 1);
					nimln(319, "graphics.nim");
					TMP544 = subInt(y, px);
					drawverline_124693(s, ((NI)chckRange((NI32)(TMP543), 0, 2147483647)), ((NI)chckRange((NI32)(TMP544), 0, 2147483647)), ((NI)chckRange(px, 0, 2147483647)), color);
				}
				LA14: ;
			}
			LA7: ;
			nimln(320, "graphics.nim");
			nimln(320, "graphics.nim");
			TMP545 = addInt(px, 1);
			px = (NI32)(TMP545);
		} LA2: ;
	}
	popFrame();
}

N_NIMCALL(void, drawrect_124766)(tsurface123011* sur, trect123005 r, NI color) {
	NI32* video;
	NI pitch;
	NI TMP546;
	nimfr("drawRect", "graphics.nim")
	nimln(324, "graphics.nim");
	video = ((NI32*) ((*(*sur).S).Pixels));
	nimln(325, "graphics.nim");
	nimln(325, "graphics.nim");
	TMP546 = divInt(((NI) ((*(*sur).S).Pitch)), 4);
	pitch = (NI32)(TMP546);
	nimln(326, "graphics.nim");
	{
		NIM_BOOL LOC3;
		NIM_BOOL LOC4;
		NIM_BOOL LOC7;
		NI minw;
		NI TMP547;
		NI minh;
		NI TMP548;
		nimln(326, "graphics.nim");
		LOC3 = 0;
		nimln(326, "graphics.nim");
		LOC4 = 0;
		nimln(326, "graphics.nim");
		LOC4 = (0 <= r.Field0);
		if (!(LOC4)) goto LA5;
		nimln(326, "graphics.nim");
		LOC4 = (r.Field0 <= ((NI) ((*(*sur).S).W)));
		LA5: ;
		LOC3 = LOC4;
		if (!(LOC3)) goto LA6;
		nimln(326, "graphics.nim");
		LOC7 = 0;
		nimln(326, "graphics.nim");
		LOC7 = (0 <= r.Field1);
		if (!(LOC7)) goto LA8;
		nimln(326, "graphics.nim");
		LOC7 = (r.Field1 <= ((NI) ((*(*sur).S).H)));
		LA8: ;
		LOC3 = LOC7;
		LA6: ;
		if (!LOC3) goto LA9;
		nimln(327, "graphics.nim");
		nimln(327, "graphics.nim");
		nimln(327, "graphics.nim");
		TMP547 = subInt(((NI) ((*(*sur).S).W)), r.Field0);
		minw = (((NI32)(TMP547) <= r.Field2) ? (NI32)(TMP547) : r.Field2);
		nimln(328, "graphics.nim");
		nimln(328, "graphics.nim");
		nimln(328, "graphics.nim");
		TMP548 = subInt(((NI) ((*(*sur).S).H)), r.Field1);
		minh = (((NI32)(TMP548) <= r.Field3) ? (NI32)(TMP548) : r.Field3);
		{
			NI i_124791;
			NI HEX3Atmp_124808;
			NI TMP549;
			NI res_124811;
			i_124791 = 0;
			HEX3Atmp_124808 = 0;
			nimln(331, "graphics.nim");
			nimln(331, "graphics.nim");
			TMP549 = subInt(minw, 1);
			HEX3Atmp_124808 = (NI32)(TMP549);
			nimln(1576, "system.nim");
			res_124811 = 0;
			{
				nimln(1577, "system.nim");
				while (1) {
					NI TMP550;
					NI TMP551;
					NI TMP552;
					NI TMP553;
					NI TMP554;
					NI TMP555;
					NI TMP556;
					NI TMP557;
					nimln(1577, "system.nim");
					if (!(res_124811 <= HEX3Atmp_124808)) goto LA13;
					nimln(1576, "system.nim");
					i_124791 = res_124811;
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					TMP550 = mulInt(r.Field1, pitch);
					nimln(332, "graphics.nim");
					TMP551 = addInt(r.Field0, i_124791);
					TMP552 = addInt((NI32)(TMP550), (NI32)(TMP551));
					if ((NU)((NI32)(TMP552)) > (NU)(999999)) raiseIndexError();
					video[((NI32)(TMP552))- 0] = ((NI32) (color));
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(333, "graphics.nim");
					nimln(333, "graphics.nim");
					TMP553 = addInt(r.Field1, minh);
					TMP554 = subInt((NI32)(TMP553), 1);
					TMP555 = mulInt((NI32)(TMP554), pitch);
					nimln(333, "graphics.nim");
					TMP556 = addInt(r.Field0, i_124791);
					TMP557 = addInt((NI32)(TMP555), (NI32)(TMP556));
					if ((NU)((NI32)(TMP557)) > (NU)(999999)) raiseIndexError();
					video[((NI32)(TMP557))- 0] = ((NI32) (color));
					nimln(1579, "system.nim");
					res_124811 = addInt(res_124811, 1);
				} LA13: ;
			}
		}
		{
			NI i_124802;
			NI HEX3Atmp_124816;
			NI TMP558;
			NI res_124819;
			i_124802 = 0;
			HEX3Atmp_124816 = 0;
			nimln(336, "graphics.nim");
			nimln(336, "graphics.nim");
			TMP558 = subInt(minh, 1);
			HEX3Atmp_124816 = (NI32)(TMP558);
			nimln(1576, "system.nim");
			res_124819 = 0;
			{
				nimln(1577, "system.nim");
				while (1) {
					NI TMP559;
					NI TMP560;
					NI TMP561;
					NI TMP562;
					NI TMP563;
					NI TMP564;
					NI TMP565;
					NI TMP566;
					nimln(1577, "system.nim");
					if (!(res_124819 <= HEX3Atmp_124816)) goto LA16;
					nimln(1576, "system.nim");
					i_124802 = res_124819;
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(337, "graphics.nim");
					TMP559 = addInt(r.Field1, i_124802);
					TMP560 = mulInt((NI32)(TMP559), pitch);
					TMP561 = addInt((NI32)(TMP560), r.Field0);
					if ((NU)((NI32)(TMP561)) > (NU)(999999)) raiseIndexError();
					video[((NI32)(TMP561))- 0] = ((NI32) (color));
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(110, "graphics.nim");
					nimln(338, "graphics.nim");
					TMP562 = addInt(r.Field1, i_124802);
					TMP563 = mulInt((NI32)(TMP562), pitch);
					nimln(338, "graphics.nim");
					nimln(338, "graphics.nim");
					TMP564 = addInt(r.Field0, minw);
					TMP565 = subInt((NI32)(TMP564), 1);
					TMP566 = addInt((NI32)(TMP563), (NI32)(TMP565));
					if ((NU)((NI32)(TMP566)) > (NU)(999999)) raiseIndexError();
					video[((NI32)(TMP566))- 0] = ((NI32) (color));
					nimln(1579, "system.nim");
					res_124819 = addInt(res_124819, 1);
				} LA16: ;
			}
		}
	}
	LA9: ;
	popFrame();
}

N_NIMCALL(void, fillrect_124845)(tsurface123011* sur, trect123005 r, NI col) {
	trect116227 rect;
	nimfr("fillRect", "graphics.nim")
	nimln(342, "graphics.nim");
	rect = tosdlrect_123074(r);
	nimln(343, "graphics.nim");
	{
		NI32 LOC3;
		NI LOC4;
		nimln(343, "graphics.nim");
		nimln(343, "graphics.nim");
		nimln(343, "graphics.nim");
		LOC3 = 0;
		LOC3 = createsdlcolor_123053(sur, col, 0);
		LOC4 = 0;
		LOC4 = Dl_120607((*sur).S, (&rect), LOC3);
		if (!(LOC4 == -1)) goto LA5;
		nimln(344, "graphics.nim");
		raiseegraphics_123085();
	}
	LA5: ;
	popFrame();
}

N_NIMCALL(void, plot4ellipsepoints_124858)(tsurface123011* sur, NI cx, NI cy, NI x, NI y, NI col) {
	NI32* video;
	NI pitch;
	NI TMP567;
	nimfr("plot4EllipsePoints", "graphics.nim")
	nimln(347, "graphics.nim");
	video = ((NI32*) ((*(*sur).S).Pixels));
	nimln(348, "graphics.nim");
	nimln(348, "graphics.nim");
	TMP567 = divInt(((NI) ((*(*sur).S).Pitch)), 4);
	pitch = (NI32)(TMP567);
	nimln(349, "graphics.nim");
	{
		NI TMP568;
		NI32 TMP569;
		nimln(349, "graphics.nim");
		nimln(349, "graphics.nim");
		TMP568 = addInt(((NI) (cx)), ((NI) (x)));
		nimln(349, "graphics.nim");
		TMP569 = subInt((*(*sur).S).W, ((NI32) 1));
		if (!(((NI)chckRange((NI32)(TMP568), (-2147483647 -1), 2147483647)) <= ((NI) ((NI32)(TMP569))))) goto LA3;
		nimln(350, "graphics.nim");
		{
			NI TMP570;
			NI32 TMP571;
			NI TMP572;
			NI TMP573;
			NI TMP574;
			NI TMP575;
			nimln(350, "graphics.nim");
			nimln(350, "graphics.nim");
			TMP570 = addInt(((NI) (cy)), ((NI) (y)));
			nimln(350, "graphics.nim");
			TMP571 = subInt((*(*sur).S).H, ((NI32) 1));
			if (!(((NI)chckRange((NI32)(TMP570), (-2147483647 -1), 2147483647)) <= ((NI) ((NI32)(TMP571))))) goto LA7;
			nimln(110, "graphics.nim");
			nimln(110, "graphics.nim");
			nimln(110, "graphics.nim");
			nimln(350, "graphics.nim");
			TMP572 = addInt(((NI) (cy)), ((NI) (y)));
			TMP573 = mulInt(((NI)chckRange((NI32)(TMP572), (-2147483647 -1), 2147483647)), pitch);
			nimln(350, "graphics.nim");
			TMP574 = addInt(((NI) (cx)), ((NI) (x)));
			TMP575 = addInt((NI32)(TMP573), ((NI)chckRange((NI32)(TMP574), (-2147483647 -1), 2147483647)));
			if ((NU)((NI32)(TMP575)) > (NU)(999999)) raiseIndexError();
			video[((NI32)(TMP575))- 0] = ((NI32) (col));
		}
		LA7: ;
		nimln(351, "graphics.nim");
		{
			NI TMP576;
			NI32 TMP577;
			NI TMP578;
			NI TMP579;
			NI TMP580;
			NI TMP581;
			nimln(351, "graphics.nim");
			nimln(351, "graphics.nim");
			TMP576 = subInt(((NI) (cy)), ((NI) (y)));
			nimln(351, "graphics.nim");
			TMP577 = subInt((*(*sur).S).H, ((NI32) 1));
			if (!((NI32)(TMP576) <= ((NI) ((NI32)(TMP577))))) goto LA11;
			nimln(110, "graphics.nim");
			nimln(110, "graphics.nim");
			nimln(110, "graphics.nim");
			nimln(351, "graphics.nim");
			TMP578 = subInt(((NI) (cy)), ((NI) (y)));
			TMP579 = mulInt((NI32)(TMP578), pitch);
			nimln(351, "graphics.nim");
			TMP580 = addInt(((NI) (cx)), ((NI) (x)));
			TMP581 = addInt((NI32)(TMP579), ((NI)chckRange((NI32)(TMP580), (-2147483647 -1), 2147483647)));
			if ((NU)((NI32)(TMP581)) > (NU)(999999)) raiseIndexError();
			video[((NI32)(TMP581))- 0] = ((NI32) (col));
		}
		LA11: ;
	}
	LA3: ;
	nimln(352, "graphics.nim");
	{
		NI TMP582;
		NI32 TMP583;
		nimln(352, "graphics.nim");
		nimln(352, "graphics.nim");
		TMP582 = subInt(((NI) (cx)), ((NI) (x)));
		nimln(352, "graphics.nim");
		TMP583 = subInt((*(*sur).S).W, ((NI32) 1));
		if (!((NI32)(TMP582) <= ((NI) ((NI32)(TMP583))))) goto LA15;
		nimln(353, "graphics.nim");
		{
			NI TMP584;
			NI32 TMP585;
			NI TMP586;
			NI TMP587;
			NI TMP588;
			NI TMP589;
			nimln(353, "graphics.nim");
			nimln(353, "graphics.nim");
			TMP584 = addInt(((NI) (cy)), ((NI) (y)));
			nimln(353, "graphics.nim");
			TMP585 = subInt((*(*sur).S).H, ((NI32) 1));
			if (!(((NI)chckRange((NI32)(TMP584), (-2147483647 -1), 2147483647)) <= ((NI) ((NI32)(TMP585))))) goto LA19;
			nimln(110, "graphics.nim");
			nimln(110, "graphics.nim");
			nimln(110, "graphics.nim");
			nimln(353, "graphics.nim");
			TMP586 = addInt(((NI) (cy)), ((NI) (y)));
			TMP587 = mulInt(((NI)chckRange((NI32)(TMP586), (-2147483647 -1), 2147483647)), pitch);
			nimln(353, "graphics.nim");
			TMP588 = subInt(((NI) (cx)), ((NI) (x)));
			TMP589 = addInt((NI32)(TMP587), (NI32)(TMP588));
			if ((NU)((NI32)(TMP589)) > (NU)(999999)) raiseIndexError();
			video[((NI32)(TMP589))- 0] = ((NI32) (col));
		}
		LA19: ;
		nimln(354, "graphics.nim");
		{
			NI TMP590;
			NI32 TMP591;
			NI TMP592;
			NI TMP593;
			NI TMP594;
			NI TMP595;
			nimln(354, "graphics.nim");
			nimln(354, "graphics.nim");
			TMP590 = subInt(((NI) (cy)), ((NI) (y)));
			nimln(354, "graphics.nim");
			TMP591 = subInt((*(*sur).S).H, ((NI32) 1));
			if (!((NI32)(TMP590) <= ((NI) ((NI32)(TMP591))))) goto LA23;
			nimln(110, "graphics.nim");
			nimln(110, "graphics.nim");
			nimln(110, "graphics.nim");
			nimln(354, "graphics.nim");
			TMP592 = subInt(((NI) (cy)), ((NI) (y)));
			TMP593 = mulInt((NI32)(TMP592), pitch);
			nimln(354, "graphics.nim");
			TMP594 = subInt(((NI) (cx)), ((NI) (x)));
			TMP595 = addInt((NI32)(TMP593), (NI32)(TMP594));
			if ((NU)((NI32)(TMP595)) > (NU)(999999)) raiseIndexError();
			video[((NI32)(TMP595))- 0] = ((NI32) (col));
		}
		LA23: ;
	}
	LA15: ;
	popFrame();
}

N_NIMCALL(void, drawellipse_124887)(tsurface123011* sur, NI cx, NI cy, NI xradius, NI yradius, NI col) {
	NI x;
	NI y;
	NI xchange;
	NI ychange;
	NI ellipseerror;
	NI twoasquare;
	NI twobsquare;
	NI stoppingx;
	NI stoppingy;
	NI TMP596;
	NI TMP597;
	NI TMP598;
	NI TMP599;
	NI TMP600;
	NI TMP601;
	NI TMP602;
	NI TMP603;
	NI TMP604;
	NI TMP605;
	NI TMP608;
	NI TMP609;
	NI TMP610;
	NI TMP611;
	NI TMP612;
	NI TMP613;
	nimfr("drawEllipse", "graphics.nim")
	x = 0;
	y = 0;
	xchange = 0;
	ychange = 0;
	ellipseerror = 0;
	twoasquare = 0;
	twobsquare = 0;
	stoppingx = 0;
	stoppingy = 0;
	nimln(368, "graphics.nim");
	nimln(368, "graphics.nim");
	nimln(368, "graphics.nim");
	TMP596 = mulInt(2, ((NI) (xradius)));
	TMP597 = mulInt(((NI)chckRange((NI32)(TMP596), (-2147483647 -1), 2147483647)), ((NI) (xradius)));
	twoasquare = ((NI)chckRange((NI32)(TMP597), 0, 2147483647));
	nimln(369, "graphics.nim");
	nimln(369, "graphics.nim");
	nimln(369, "graphics.nim");
	TMP598 = mulInt(2, ((NI) (yradius)));
	TMP599 = mulInt(((NI)chckRange((NI32)(TMP598), (-2147483647 -1), 2147483647)), ((NI) (yradius)));
	twobsquare = ((NI)chckRange((NI32)(TMP599), 0, 2147483647));
	nimln(370, "graphics.nim");
	x = xradius;
	nimln(371, "graphics.nim");
	y = 0;
	nimln(372, "graphics.nim");
	nimln(372, "graphics.nim");
	nimln(372, "graphics.nim");
	TMP600 = mulInt(((NI) (yradius)), ((NI) (yradius)));
	nimln(372, "graphics.nim");
	nimln(372, "graphics.nim");
	TMP601 = mulInt(2, ((NI) (xradius)));
	TMP602 = subInt(1, ((NI)chckRange((NI32)(TMP601), (-2147483647 -1), 2147483647)));
	TMP603 = mulInt(((NI)chckRange((NI32)(TMP600), (-2147483647 -1), 2147483647)), (NI32)(TMP602));
	xchange = (NI32)(TMP603);
	nimln(373, "graphics.nim");
	nimln(373, "graphics.nim");
	TMP604 = mulInt(((NI) (xradius)), ((NI) (xradius)));
	ychange = ((NI)chckRange((NI32)(TMP604), (-2147483647 -1), 2147483647));
	nimln(374, "graphics.nim");
	ellipseerror = 0;
	nimln(375, "graphics.nim");
	nimln(375, "graphics.nim");
	TMP605 = mulInt(((NI) (twobsquare)), ((NI) (xradius)));
	stoppingx = ((NI)chckRange((NI32)(TMP605), 0, 2147483647));
	nimln(376, "graphics.nim");
	stoppingy = 0;
	{
		nimln(378, "graphics.nim");
		while (1) {
			nimln(378, "graphics.nim");
			if (!(((NI) (stoppingy)) <= ((NI) (stoppingx)))) goto LA2;
			nimln(379, "graphics.nim");
			plot4ellipsepoints_124858(sur, cx, cy, x, y, col);
			nimln(380, "graphics.nim");
			y = addInt(y, 1);
			nimln(381, "graphics.nim");
			stoppingy = addInt(stoppingy, ((NI) (twoasquare)));
			nimln(382, "graphics.nim");
			ellipseerror = addInt(ellipseerror, ychange);
			nimln(383, "graphics.nim");
			ychange = addInt(ychange, ((NI) (twoasquare)));
			nimln(384, "graphics.nim");
			{
				NI TMP606;
				NI TMP607;
				nimln(384, "graphics.nim");
				nimln(384, "graphics.nim");
				nimln(384, "graphics.nim");
				TMP606 = mulInt(2, ((NI) (ellipseerror)));
				TMP607 = addInt(((NI)chckRange((NI32)(TMP606), (-2147483647 -1), 2147483647)), xchange);
				if (!(0 < (NI32)(TMP607))) goto LA5;
				nimln(385, "graphics.nim");
				x = subInt(x, 1);
				nimln(386, "graphics.nim");
				stoppingx = subInt(stoppingx, ((NI) (twobsquare)));
				nimln(387, "graphics.nim");
				ellipseerror = addInt(ellipseerror, xchange);
				nimln(388, "graphics.nim");
				xchange = addInt(xchange, ((NI) (twobsquare)));
			}
			LA5: ;
		} LA2: ;
	}
	nimln(391, "graphics.nim");
	x = 0;
	nimln(392, "graphics.nim");
	y = yradius;
	nimln(393, "graphics.nim");
	nimln(393, "graphics.nim");
	TMP608 = mulInt(((NI) (yradius)), ((NI) (yradius)));
	xchange = ((NI)chckRange((NI32)(TMP608), (-2147483647 -1), 2147483647));
	nimln(394, "graphics.nim");
	nimln(394, "graphics.nim");
	nimln(394, "graphics.nim");
	TMP609 = mulInt(((NI) (xradius)), ((NI) (xradius)));
	nimln(394, "graphics.nim");
	nimln(394, "graphics.nim");
	TMP610 = mulInt(2, ((NI) (yradius)));
	TMP611 = subInt(1, ((NI)chckRange((NI32)(TMP610), (-2147483647 -1), 2147483647)));
	TMP612 = mulInt(((NI)chckRange((NI32)(TMP609), (-2147483647 -1), 2147483647)), (NI32)(TMP611));
	ychange = (NI32)(TMP612);
	nimln(395, "graphics.nim");
	ellipseerror = 0;
	nimln(396, "graphics.nim");
	stoppingx = 0;
	nimln(397, "graphics.nim");
	nimln(397, "graphics.nim");
	TMP613 = mulInt(((NI) (twoasquare)), ((NI) (yradius)));
	stoppingy = ((NI)chckRange((NI32)(TMP613), 0, 2147483647));
	{
		nimln(398, "graphics.nim");
		while (1) {
			nimln(398, "graphics.nim");
			if (!(((NI) (stoppingx)) <= ((NI) (stoppingy)))) goto LA8;
			nimln(399, "graphics.nim");
			plot4ellipsepoints_124858(sur, cx, cy, x, y, col);
			nimln(400, "graphics.nim");
			x = addInt(x, 1);
			nimln(401, "graphics.nim");
			stoppingx = addInt(stoppingx, ((NI) (twobsquare)));
			nimln(402, "graphics.nim");
			ellipseerror = addInt(ellipseerror, xchange);
			nimln(403, "graphics.nim");
			xchange = addInt(xchange, ((NI) (twobsquare)));
			nimln(404, "graphics.nim");
			{
				NI TMP614;
				NI TMP615;
				nimln(404, "graphics.nim");
				nimln(404, "graphics.nim");
				nimln(404, "graphics.nim");
				TMP614 = mulInt(2, ((NI) (ellipseerror)));
				TMP615 = addInt(((NI)chckRange((NI32)(TMP614), (-2147483647 -1), 2147483647)), ychange);
				if (!(0 < (NI32)(TMP615))) goto LA11;
				nimln(405, "graphics.nim");
				y = subInt(y, 1);
				nimln(406, "graphics.nim");
				stoppingy = subInt(stoppingy, ((NI) (twoasquare)));
				nimln(407, "graphics.nim");
				ellipseerror = addInt(ellipseerror, ychange);
				nimln(408, "graphics.nim");
				ychange = addInt(ychange, ((NI) (twoasquare)));
			}
			LA11: ;
		} LA8: ;
	}
	popFrame();
}

N_NIMCALL(void, plotaa_125141)(tsurface123011* sur, NI x, NI y, NF c, NI color) {
	nimfr("plotAA", "graphics.nim")
	nimln(412, "graphics.nim");
	{
		NIM_BOOL LOC3;
		NIM_BOOL LOC4;
		NIM_BOOL LOC7;
		NI32* video;
		NI pitch;
		NI TMP616;
		NI pixcolor;
		NI TMP617;
		NI TMP618;
		NI TMP619;
		NI TMP620;
		NI LOC11;
		NI LOC12;
		NI LOC13;
		nimln(412, "graphics.nim");
		LOC3 = 0;
		nimln(412, "graphics.nim");
		LOC4 = 0;
		nimln(412, "graphics.nim");
		LOC4 = (0 < x);
		if (!(LOC4)) goto LA5;
		nimln(412, "graphics.nim");
		LOC4 = (x < ((NI) ((*(*sur).S).W)));
		LA5: ;
		LOC3 = LOC4;
		if (!(LOC3)) goto LA6;
		nimln(412, "graphics.nim");
		LOC7 = 0;
		nimln(412, "graphics.nim");
		LOC7 = (0 < y);
		if (!(LOC7)) goto LA8;
		nimln(412, "graphics.nim");
		LOC7 = (y < ((NI) ((*(*sur).S).H)));
		LA8: ;
		LOC3 = LOC7;
		LA6: ;
		if (!LOC3) goto LA9;
		nimln(413, "graphics.nim");
		video = ((NI32*) ((*(*sur).S).Pixels));
		nimln(414, "graphics.nim");
		nimln(414, "graphics.nim");
		TMP616 = divInt(((NI) ((*(*sur).S).Pitch)), 4);
		pitch = (NI32)(TMP616);
		nimln(416, "graphics.nim");
		nimln(416, "graphics.nim");
		nimln(416, "graphics.nim");
		TMP617 = mulInt(y, pitch);
		TMP618 = addInt((NI32)(TMP617), x);
		if ((NU)((NI32)(TMP618)) > (NU)(999999)) raiseIndexError();
		pixcolor = ((NI) (video[((NI32)(TMP618))- 0]));
		nimln(110, "graphics.nim");
		nimln(110, "graphics.nim");
		nimln(110, "graphics.nim");
		TMP619 = mulInt(y, pitch);
		TMP620 = addInt((NI32)(TMP619), x);
		if ((NU)((NI32)(TMP620)) > (NU)(999999)) raiseIndexError();
		nimln(419, "graphics.nim");
		nimln(419, "graphics.nim");
		nimln(419, "graphics.nim");
		LOC11 = 0;
		LOC11 = intensity_99201(pixcolor, ((NF)(1.0000000000000000e+00) - (NF)(c)));
		nimln(419, "graphics.nim");
		LOC12 = 0;
		LOC12 = intensity_99201(color, c);
		LOC13 = 0;
		LOC13 = HEX2B_99104(LOC11, LOC12);
		video[((NI32)(TMP620))- 0] = ((NI32) (LOC13));
	}
	LA9: ;
	popFrame();
}

N_NIMCALL(void, drawlineaa_125193)(tsurface123011* sur, tpoint123007 p1, tpoint123007 p2, NI color) {
	TY125199 LOC1;
	NF x1;
	NF x2;
	NF y1;
	NF y2;
	NF dx;
	NF dy;
	NF ax;
	NF ay;
	NF gradient;
	NF xend;
	NF yend;
	NF xgap;
	NF LOC23;
	NI xpxl1;
	NI ypxl1;
	NF LOC24;
	NF intery;
	NF LOC39;
	NI xpxl2;
	NI ypxl2;
	NF LOC40;
	NI x;
	NI TMP625;
	nimfr("drawLineAA", "graphics.nim")
	nimln(430, "graphics.nim");
	nimln(430, "graphics.nim");
	LOC1.Field0 = ((double) (p1.Field0));
	nimln(430, "graphics.nim");
	LOC1.Field1 = ((double) (p2.Field0));
	nimln(431, "graphics.nim");
	LOC1.Field2 = ((double) (p1.Field1));
	nimln(431, "graphics.nim");
	LOC1.Field3 = ((double) (p2.Field1));
	x1 = LOC1.Field0;
	x2 = LOC1.Field1;
	y1 = LOC1.Field2;
	y2 = LOC1.Field3;
	nimln(432, "graphics.nim");
	nimln(432, "graphics.nim");
	dx = ((NF)(x2) - (NF)(x1));
	nimln(433, "graphics.nim");
	nimln(433, "graphics.nim");
	dy = ((NF)(y2) - (NF)(y1));
	nimln(435, "graphics.nim");
	ax = dx;
	nimln(436, "graphics.nim");
	{
		nimln(436, "graphics.nim");
		if (!(ax < 0.0)) goto LA4;
		nimln(437, "graphics.nim");
		nimln(437, "graphics.nim");
		ax = ((NF)(0.0) - (NF)(ax));
	}
	LA4: ;
	nimln(438, "graphics.nim");
	ay = dy;
	nimln(439, "graphics.nim");
	{
		nimln(439, "graphics.nim");
		if (!(ay < 0.0)) goto LA8;
		nimln(440, "graphics.nim");
		nimln(440, "graphics.nim");
		ay = ((NF)(0.0) - (NF)(ay));
	}
	LA8: ;
	nimln(442, "graphics.nim");
	{
		NF LOC14;
		NF LOC15;
		NF LOC16;
		nimln(442, "graphics.nim");
		if (!(ax < ay)) goto LA12;
		nimln(443, "graphics.nim");
		LOC14 = 0;
		LOC14 = x1;
		x1 = y1;
		y1 = LOC14;
		nimln(444, "graphics.nim");
		LOC15 = 0;
		LOC15 = x2;
		x2 = y2;
		y2 = LOC15;
		nimln(445, "graphics.nim");
		LOC16 = 0;
		LOC16 = dx;
		dx = dy;
		dy = LOC16;
	}
	LA12: ;
	nimln(453, "graphics.nim");
	{
		NF LOC21;
		NF LOC22;
		nimln(453, "graphics.nim");
		if (!(x2 < x1)) goto LA19;
		nimln(454, "graphics.nim");
		LOC21 = 0;
		LOC21 = x1;
		x1 = x2;
		x2 = LOC21;
		nimln(455, "graphics.nim");
		LOC22 = 0;
		LOC22 = y1;
		y1 = y2;
		y2 = LOC22;
	}
	LA19: ;
	nimln(457, "graphics.nim");
	nimln(457, "graphics.nim");
	gradient = ((NF)(dy) / (NF)(dx));
	nimln(459, "graphics.nim");
	nimln(459, "graphics.nim");
	xend = floor(((NF)(x1) + (NF)(5.0000000000000000e-01)));
	nimln(460, "graphics.nim");
	nimln(460, "graphics.nim");
	nimln(460, "graphics.nim");
	nimln(460, "graphics.nim");
	yend = ((NF)(y1) + (NF)(((NF)(gradient) * (NF)(((NF)(xend) - (NF)(x1))))));
	nimln(461, "graphics.nim");
	nimln(461, "graphics.nim");
	nimln(461, "graphics.nim");
	nimln(461, "graphics.nim");
	nimln(461, "graphics.nim");
	nimln(461, "graphics.nim");
	LOC23 = 0;
	LOC23 = floor(((NF)(x1) + (NF)(5.0000000000000000e-01)));
	xgap = ((NF)(1.0000000000000000e+00) - (NF)(((NF)(((NF)(x1) + (NF)(5.0000000000000000e-01))) - (NF)(LOC23))));
	nimln(462, "graphics.nim");
	xpxl1 = ((NI) (xend));
	nimln(463, "graphics.nim");
	nimln(463, "graphics.nim");
	LOC24 = 0;
	LOC24 = floor(yend);
	ypxl1 = ((NI) (LOC24));
	nimln(448, "graphics.nim");
	{
		NF LOC29;
		nimln(448, "graphics.nim");
		if (!(ax < ay)) goto LA27;
		nimln(449, "graphics.nim");
		nimln(464, "graphics.nim");
		nimln(464, "graphics.nim");
		nimln(464, "graphics.nim");
		nimln(464, "graphics.nim");
		LOC29 = 0;
		LOC29 = floor(yend);
		plotaa_125141(sur, ypxl1, xpxl1, ((NF)(((NF)(1.0000000000000000e+00) - (NF)(((NF)(yend) - (NF)(LOC29))))) * (NF)(xgap)), color);
	}
	goto LA25;
	LA27: ;
	{
		NF LOC31;
		nimln(451, "graphics.nim");
		nimln(464, "graphics.nim");
		nimln(464, "graphics.nim");
		nimln(464, "graphics.nim");
		nimln(464, "graphics.nim");
		LOC31 = 0;
		LOC31 = floor(yend);
		plotaa_125141(sur, xpxl1, ypxl1, ((NF)(((NF)(1.0000000000000000e+00) - (NF)(((NF)(yend) - (NF)(LOC31))))) * (NF)(xgap)), color);
	}
	LA25: ;
	nimln(448, "graphics.nim");
	{
		NI TMP621;
		NF LOC36;
		nimln(448, "graphics.nim");
		if (!(ax < ay)) goto LA34;
		nimln(449, "graphics.nim");
		nimln(465, "graphics.nim");
		TMP621 = addInt(ypxl1, 1);
		nimln(465, "graphics.nim");
		nimln(465, "graphics.nim");
		nimln(465, "graphics.nim");
		LOC36 = 0;
		LOC36 = floor(yend);
		plotaa_125141(sur, (NI32)(TMP621), xpxl1, ((NF)(((NF)(yend) - (NF)(LOC36))) * (NF)(xgap)), color);
	}
	goto LA32;
	LA34: ;
	{
		NI TMP622;
		NF LOC38;
		nimln(451, "graphics.nim");
		nimln(465, "graphics.nim");
		TMP622 = addInt(ypxl1, 1);
		nimln(465, "graphics.nim");
		nimln(465, "graphics.nim");
		nimln(465, "graphics.nim");
		LOC38 = 0;
		LOC38 = floor(yend);
		plotaa_125141(sur, xpxl1, (NI32)(TMP622), ((NF)(((NF)(yend) - (NF)(LOC38))) * (NF)(xgap)), color);
	}
	LA32: ;
	nimln(466, "graphics.nim");
	nimln(466, "graphics.nim");
	intery = ((NF)(yend) + (NF)(gradient));
	nimln(469, "graphics.nim");
	nimln(469, "graphics.nim");
	xend = floor(((NF)(x2) + (NF)(5.0000000000000000e-01)));
	nimln(470, "graphics.nim");
	nimln(470, "graphics.nim");
	nimln(470, "graphics.nim");
	nimln(470, "graphics.nim");
	yend = ((NF)(y2) + (NF)(((NF)(gradient) * (NF)(((NF)(xend) - (NF)(x2))))));
	nimln(471, "graphics.nim");
	nimln(471, "graphics.nim");
	nimln(471, "graphics.nim");
	nimln(471, "graphics.nim");
	nimln(471, "graphics.nim");
	LOC39 = 0;
	LOC39 = floor(((NF)(x2) + (NF)(5.0000000000000000e-01)));
	xgap = ((NF)(((NF)(x2) + (NF)(5.0000000000000000e-01))) - (NF)(LOC39));
	nimln(472, "graphics.nim");
	xpxl2 = ((NI) (xend));
	nimln(473, "graphics.nim");
	nimln(473, "graphics.nim");
	LOC40 = 0;
	LOC40 = floor(yend);
	ypxl2 = ((NI) (LOC40));
	nimln(448, "graphics.nim");
	{
		NF LOC45;
		nimln(448, "graphics.nim");
		if (!(ax < ay)) goto LA43;
		nimln(449, "graphics.nim");
		nimln(474, "graphics.nim");
		nimln(474, "graphics.nim");
		nimln(474, "graphics.nim");
		nimln(474, "graphics.nim");
		LOC45 = 0;
		LOC45 = floor(yend);
		plotaa_125141(sur, ypxl2, xpxl2, ((NF)(((NF)(1.0000000000000000e+00) - (NF)(((NF)(yend) - (NF)(LOC45))))) * (NF)(xgap)), color);
	}
	goto LA41;
	LA43: ;
	{
		NF LOC47;
		nimln(451, "graphics.nim");
		nimln(474, "graphics.nim");
		nimln(474, "graphics.nim");
		nimln(474, "graphics.nim");
		nimln(474, "graphics.nim");
		LOC47 = 0;
		LOC47 = floor(yend);
		plotaa_125141(sur, xpxl2, ypxl2, ((NF)(((NF)(1.0000000000000000e+00) - (NF)(((NF)(yend) - (NF)(LOC47))))) * (NF)(xgap)), color);
	}
	LA41: ;
	nimln(448, "graphics.nim");
	{
		NI TMP623;
		NF LOC52;
		nimln(448, "graphics.nim");
		if (!(ax < ay)) goto LA50;
		nimln(449, "graphics.nim");
		nimln(475, "graphics.nim");
		TMP623 = addInt(ypxl2, 1);
		nimln(475, "graphics.nim");
		nimln(475, "graphics.nim");
		nimln(475, "graphics.nim");
		LOC52 = 0;
		LOC52 = floor(yend);
		plotaa_125141(sur, (NI32)(TMP623), xpxl2, ((NF)(((NF)(yend) - (NF)(LOC52))) * (NF)(xgap)), color);
	}
	goto LA48;
	LA50: ;
	{
		NI TMP624;
		NF LOC54;
		nimln(451, "graphics.nim");
		nimln(475, "graphics.nim");
		TMP624 = addInt(ypxl2, 1);
		nimln(475, "graphics.nim");
		nimln(475, "graphics.nim");
		nimln(475, "graphics.nim");
		LOC54 = 0;
		LOC54 = floor(yend);
		plotaa_125141(sur, xpxl2, (NI32)(TMP624), ((NF)(((NF)(yend) - (NF)(LOC54))) * (NF)(xgap)), color);
	}
	LA48: ;
	nimln(478, "graphics.nim");
	nimln(478, "graphics.nim");
	TMP625 = addInt(xpxl1, 1);
	x = (NI32)(TMP625);
	{
		nimln(479, "graphics.nim");
		while (1) {
			NI TMP626;
			nimln(479, "graphics.nim");
			nimln(479, "graphics.nim");
			TMP626 = subInt(xpxl2, 1);
			if (!(x <= (NI32)(TMP626))) goto LA56;
			nimln(448, "graphics.nim");
			{
				NF LOC61;
				NF LOC62;
				nimln(448, "graphics.nim");
				if (!(ax < ay)) goto LA59;
				nimln(449, "graphics.nim");
				nimln(480, "graphics.nim");
				LOC61 = 0;
				LOC61 = floor(intery);
				nimln(480, "graphics.nim");
				nimln(480, "graphics.nim");
				nimln(480, "graphics.nim");
				LOC62 = 0;
				LOC62 = floor(intery);
				plotaa_125141(sur, ((NI) (LOC61)), x, ((NF)(1.0000000000000000e+00) - (NF)(((NF)(intery) - (NF)(LOC62)))), color);
			}
			goto LA57;
			LA59: ;
			{
				NF LOC64;
				NF LOC65;
				nimln(451, "graphics.nim");
				nimln(480, "graphics.nim");
				LOC64 = 0;
				LOC64 = floor(intery);
				nimln(480, "graphics.nim");
				nimln(480, "graphics.nim");
				nimln(480, "graphics.nim");
				LOC65 = 0;
				LOC65 = floor(intery);
				plotaa_125141(sur, x, ((NI) (LOC64)), ((NF)(1.0000000000000000e+00) - (NF)(((NF)(intery) - (NF)(LOC65)))), color);
			}
			LA57: ;
			nimln(448, "graphics.nim");
			{
				NF LOC70;
				NI TMP627;
				NF LOC71;
				nimln(448, "graphics.nim");
				if (!(ax < ay)) goto LA68;
				nimln(449, "graphics.nim");
				nimln(481, "graphics.nim");
				nimln(481, "graphics.nim");
				LOC70 = 0;
				LOC70 = floor(intery);
				TMP627 = addInt(((NI) (LOC70)), 1);
				nimln(481, "graphics.nim");
				nimln(481, "graphics.nim");
				LOC71 = 0;
				LOC71 = floor(intery);
				plotaa_125141(sur, (NI32)(TMP627), x, ((NF)(intery) - (NF)(LOC71)), color);
			}
			goto LA66;
			LA68: ;
			{
				NF LOC73;
				NI TMP628;
				NF LOC74;
				nimln(451, "graphics.nim");
				nimln(481, "graphics.nim");
				nimln(481, "graphics.nim");
				LOC73 = 0;
				LOC73 = floor(intery);
				TMP628 = addInt(((NI) (LOC73)), 1);
				nimln(481, "graphics.nim");
				nimln(481, "graphics.nim");
				LOC74 = 0;
				LOC74 = floor(intery);
				plotaa_125141(sur, x, (NI32)(TMP628), ((NF)(intery) - (NF)(LOC74)), color);
			}
			LA66: ;
			nimln(482, "graphics.nim");
			nimln(482, "graphics.nim");
			intery = ((NF)(intery) + (NF)(gradient));
			nimln(483, "graphics.nim");
			x = addInt(x, 1);
		} LA56: ;
	}
	popFrame();
}

N_NIMCALL(void, fillsurface_125349)(tsurface123011* sur, NI color) {
	nimfr("fillSurface", "graphics.nim")
	nimln(487, "graphics.nim");
	{
		NI32 LOC3;
		NI LOC4;
		nimln(487, "graphics.nim");
		nimln(487, "graphics.nim");
		nimln(487, "graphics.nim");
		LOC3 = 0;
		LOC3 = createsdlcolor_123053(sur, color, 0);
		LOC4 = 0;
		LOC4 = Dl_120607((*sur).S, NIM_NIL, LOC3);
		if (!(LOC4 == -1)) goto LA5;
		nimln(488, "graphics.nim");
		raiseegraphics_123085();
	}
	LA5: ;
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_graphicsInit)(void) {
	nimfr("graphics", "graphics.nim")
	nimln(499, "graphics.nim");
	{
		NI LOC3;
		nimln(499, "graphics.nim");
		nimln(499, "graphics.nim");
		LOC3 = 0;
		LOC3 = Dl_119422(((NI32) 32));
		if (!(LOC3 < 0)) goto LA4;
		nimln(499, "graphics.nim");
		raiseegraphics_123085();
	}
	LA4: ;
	nimln(500, "graphics.nim");
	{
		int LOC8;
		nimln(500, "graphics.nim");
		nimln(500, "graphics.nim");
		LOC8 = 0;
		LOC8 = Dl_122237();
		if (!(LOC8 < ((NI32) 0))) goto LA9;
		nimln(500, "graphics.nim");
		raiseegraphics_123085();
	}
	LA9: ;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_graphicsDatInit)(void) {
static TNimNode* TMP403[3];
static TNimNode* TMP411[2];
static TNimNode TMP385[8];
NTI123013.size = sizeof(egraphics123013);
NTI123013.kind = 17;
NTI123013.base = (&NTI3231);
TMP385[0].len = 0; TMP385[0].kind = 2;
NTI123013.node = &TMP385[0];
NTI123090.size = sizeof(egraphics123013*);
NTI123090.kind = 22;
NTI123090.base = (&NTI123013);
NTI123090.marker = TMP402;
NTI123011.size = sizeof(tsurface123011);
NTI123011.kind = 18;
NTI123011.base = 0;
NTI123011.flags = 3;
TMP403[0] = &TMP385[2];
TMP385[2].kind = 1;
TMP385[2].offset = offsetof(tsurface123011, W);
TMP385[2].typ = (&NTI75293);
TMP385[2].name = "w";
TMP403[1] = &TMP385[3];
TMP385[3].kind = 1;
TMP385[3].offset = offsetof(tsurface123011, H);
TMP385[3].typ = (&NTI75293);
TMP385[3].name = "h";
TMP403[2] = &TMP385[4];
TMP385[4].kind = 1;
TMP385[4].offset = offsetof(tsurface123011, S);
TMP385[4].typ = (&NTI116251);
TMP385[4].name = "s";
TMP385[1].len = 3; TMP385[1].kind = 2; TMP385[1].sons = &TMP403[0];
NTI123011.node = &TMP385[1];
NTI123009.size = sizeof(tsurface123011*);
NTI123009.kind = 22;
NTI123009.base = (&NTI123011);
NTI123009.flags = 2;
NTI123009.marker = TMP409;
(&NTI123009)->finalizer = (void*)surfacefinalizer_123114;
NTI123015.size = sizeof(tfont123015);
NTI123015.kind = 18;
NTI123015.base = 0;
NTI123015.flags = 3;
TMP411[0] = &TMP385[6];
TMP385[6].kind = 1;
TMP385[6].offset = offsetof(tfont123015, F);
TMP385[6].typ = (&NTI122219);
TMP385[6].name = "f";
TMP411[1] = &TMP385[7];
TMP385[7].kind = 1;
TMP385[7].offset = offsetof(tfont123015, Color);
TMP385[7].typ = (&NTI116233);
TMP385[7].name = "color";
TMP385[5].len = 2; TMP385[5].kind = 2; TMP385[5].sons = &TMP411[0];
NTI123015.node = &TMP385[5];
NTI123017.size = sizeof(tfont123015*);
NTI123017.kind = 22;
NTI123017.base = (&NTI123015);
NTI123017.flags = 2;
NTI123017.marker = TMP412;
(&NTI123017)->finalizer = (void*)fontfinalizer_123207;
(&NTI123009)->finalizer = (void*)surfacefinalizer_123114;
(&NTI123009)->finalizer = (void*)surfacefinalizer_123114;
(&NTI123009)->finalizer = (void*)surfacefinalizer_123114;
}

