/* Generated by Nim Compiler v0.10.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/jsudlow/Nim/lib -o .nimcache/stdlib_times.o .nimcache/stdlib_times.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <sys/time.h>

#include <string.h>

#include <time.h>

#include <sys/select.h>
typedef struct timeinterval104407 timeinterval104407;
typedef struct timeinfo104405 timeinfo104405;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY104551 TY104551;
typedef struct slice84665 slice84665;
typedef struct valueerror3249 valueerror3249;
typedef struct Exception Exception;
typedef struct tcell45135 tcell45135;
typedef struct tcellseq45151 tcellseq45151;
typedef struct tgcheap47216 tgcheap47216;
typedef struct tcellset45147 tcellset45147;
typedef struct tpagedesc45143 tpagedesc45143;
typedef struct tmemregion27410 tmemregion27410;
typedef struct tsmallchunk26640 tsmallchunk26640;
typedef struct tllchunk27404 tllchunk27404;
typedef struct tbigchunk26642 tbigchunk26642;
typedef struct tintset26617 tintset26617;
typedef struct ttrunk26613 ttrunk26613;
typedef struct tavlnode27408 tavlnode27408;
typedef struct tgcstat47214 tgcstat47214;
typedef struct tbasechunk26638 tbasechunk26638;
typedef struct tfreecell26630 tfreecell26630;
struct  timeinterval104407  {
NI Miliseconds;
NI Seconds;
NI Minutes;
NI Hours;
NI Days;
NI Months;
NI Years;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  timeinfo104405  {
  TNimObject Sup;
NI Second;
NI Minute;
NI Hour;
NI Monthday;
NU8 Month;
NI Year;
NU8 Weekday;
NI Yearday;
NIM_BOOL Isdst;
NimStringDesc* Tzname;
NI Timezone;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 TY105054[7];
struct TY104551 {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
typedef NI8 TY105075[7];
typedef NimStringDesc* TY106239[7];
typedef NimStringDesc* TY106255[12];
struct  slice84665  {
NI A;
NI B;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  valueerror3249  {
  Exception Sup;
};
struct  tcell45135  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq45151  {
NI Len;
NI Cap;
tcell45135** D;
};
struct  tcellset45147  {
NI Counter;
NI Max;
tpagedesc45143* Head;
tpagedesc45143** Data;
};
typedef tsmallchunk26640* TY27422[512];
typedef ttrunk26613* ttrunkbuckets26615[256];
struct  tintset26617  {
ttrunkbuckets26615 Data;
};
struct  tmemregion27410  {
NI Minlargeobj;
NI Maxlargeobj;
TY27422 Freesmallchunks;
tllchunk27404* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26642* Freechunkslist;
tintset26617 Chunkstarts;
tavlnode27408* Root;
tavlnode27408* Deleted;
tavlnode27408* Last;
tavlnode27408* Freeavlnodes;
};
struct  tgcstat47214  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47216  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq45151 Zct;
tcellseq45151 Decstack;
tcellset45147 Cycleroots;
tcellseq45151 Tempstack;
NI Recgclock;
tmemregion27410 Region;
tgcstat47214 Stat;
};
typedef NI TY26620[16];
struct  tpagedesc45143  {
tpagedesc45143* Next;
NI Key;
TY26620 Bits;
};
struct  tbasechunk26638  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26640  {
  tbasechunk26638 Sup;
tsmallchunk26640* Next;
tsmallchunk26640* Prev;
tfreecell26630* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27404  {
NI Size;
NI Acc;
tllchunk27404* Next;
};
struct  tbigchunk26642  {
  tbasechunk26638 Sup;
tbigchunk26642* Next;
tbigchunk26642* Prev;
NI Align;
NF Data;
};
struct  ttrunk26613  {
ttrunk26613* Next;
NI Key;
TY26620 Bits;
};
typedef tavlnode27408* TY27414[2];
struct  tavlnode27408  {
TY27414 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell26630  {
tfreecell26630* Next;
NI Zerofield;
};
N_NIMCALL(time_t, fromseconds_104478)(NI64 since1970);
N_NIMCALL(NIM_BOOL, ntLtTime)(time_t a, time_t b);
N_NIMCALL(NIM_BOOL, ntLeTime)(time_t a, time_t b);
N_NIMCALL(NIM_BOOL, ntEqTime)(time_t a, time_t b);
N_NIMCALL(timeinterval104407, initinterval_104614)(NI miliseconds, NI seconds, NI minutes, NI hours, NI days, NI months, NI years);
N_NIMCALL(NIM_BOOL, isleapyear_104630)(NI year);
N_NIMCALL(NI, getdaysinmonth_104645)(NU8 month, NI year);
static N_INLINE(void, HEX2BHEX3D_104693)(NF* x_104699, NF y_104702);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NF, toseconds_104658)(timeinfo104405* a, timeinterval104407* interval);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
static N_INLINE(NF, HEX2F_84603)(NI x, NI y);
N_NIMCALL(void, HEX2B_104833)(timeinfo104405* a, timeinterval104407* interval, timeinfo104405* Result);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, HEX2D_104846)(timeinfo104405* a, timeinterval104407* interval, timeinfo104405* Result);
N_NIMCALL(void, tmtotimeinfo_105048)(struct tm* tm, NIM_BOOL local, timeinfo104405* Result);
N_NIMCALL(void, gettzname_104549)(TY104551* Result);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NI, gettimezone_104604)(void);
N_NIMCALL(void, genericShallowAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(struct tm, timeinfototm_105070)(timeinfo104405* t);
N_NIMCALL(NI64, ntDiffTime)(time_t a, time_t b);
N_NIMCALL(NI, getstartmilsecs_104609)(void);
N_NIMCALL(time_t, gettime_104449)(void);
N_NIMCALL(void, getlocaltime_104454)(time_t t, timeinfo104405* Result);
N_NIMCALL(void, getgmtime_104460)(time_t t, timeinfo104405* Result);
N_NIMCALL(time_t, timeinfototime_104466)(timeinfo104405* timeinfo);
N_NIMCALL(NimStringDesc*, tostringtillnl_105637)(NCSTRING p);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, HEX24_104495)(timeinfo104405* timeinfo);
N_NIMCALL(NimStringDesc*, HEX24_104501)(time_t time);
N_NIMCALL(NI64, unixtimetowintime_105683)(time_t t);
N_NIMCALL(time_t, wintimetounixtime_105691)(NI64 t);
N_NIMCALL(time_t, fromseconds_104472)(NF since1970);
N_NIMCALL(NF, toseconds_104489)(time_t time);
N_NIMCALL(NF, ntepochTime)(void);
N_NIMCALL(NF, ntcpuTime)(void);
N_NIMCALL(NimStringDesc*, ntgetDateStr)(void);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x, NI minchars);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, ntgetClockStr)(void);
N_NIMCALL(NimStringDesc*, HEX24_106234)(NU8 day);
N_NIMCALL(NimStringDesc*, HEX24_106250)(NU8 m);
N_NIMCALL(void, formattoken_106266)(timeinfo104405* info, NimStringDesc* token, NimStringDesc** buf);
N_NIMCALL(NI, hashString)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
static N_INLINE(NimStringDesc*, HEX5BHEX5D_84658)(NimStringDesc* s, slice84665 x);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_75228, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(slice84665, HEX2EHEX2E_91098)(NI a_91102, NI b_91104);
N_NIMCALL(NimStringDesc*, nsuRepeatChar)(NI count, NIM_CHAR c);
N_NIMCALL(void, insert_86401)(NimStringDesc** x, NimStringDesc* item, NI i);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell45135*, usrtocell_48846)(void* usr);
static N_INLINE(void, rtladdzct_50404)(tcell45135* c);
N_NOINLINE(void, addzct_48817)(tcellseq45151* s, tcell45135* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NimStringDesc*, format_106421)(timeinfo104405* info, NimStringDesc* f);
STRING_LITERAL(TMP318, "UTC", 3);
NIM_CONST TY105054 weekdays_105053 = {((NU8) 6),
((NU8) 0),
((NU8) 1),
((NU8) 2),
((NU8) 3),
((NU8) 4),
((NU8) 5)}
;
NIM_CONST TY105075 weekdays_105074 = {((NI8) 1),
((NI8) 2),
((NI8) 3),
((NI8) 4),
((NI8) 5),
((NI8) 6),
((NI8) 0)}
;
STRING_LITERAL(TMP319, "", 0);
STRING_LITERAL(TMP321, "Monday", 6);
STRING_LITERAL(TMP322, "Tuesday", 7);
STRING_LITERAL(TMP323, "Wednesday", 9);
STRING_LITERAL(TMP324, "Thursday", 8);
STRING_LITERAL(TMP325, "Friday", 6);
STRING_LITERAL(TMP326, "Saturday", 8);
STRING_LITERAL(TMP327, "Sunday", 6);
NIM_CONST TY106239 lookup_106238 = {((NimStringDesc*) &TMP321),
((NimStringDesc*) &TMP322),
((NimStringDesc*) &TMP323),
((NimStringDesc*) &TMP324),
((NimStringDesc*) &TMP325),
((NimStringDesc*) &TMP326),
((NimStringDesc*) &TMP327)}
;
STRING_LITERAL(TMP328, "January", 7);
STRING_LITERAL(TMP329, "February", 8);
STRING_LITERAL(TMP330, "March", 5);
STRING_LITERAL(TMP331, "April", 5);
STRING_LITERAL(TMP332, "May", 3);
STRING_LITERAL(TMP333, "June", 4);
STRING_LITERAL(TMP334, "July", 4);
STRING_LITERAL(TMP335, "August", 6);
STRING_LITERAL(TMP336, "September", 9);
STRING_LITERAL(TMP337, "October", 7);
STRING_LITERAL(TMP338, "November", 8);
STRING_LITERAL(TMP339, "December", 8);
NIM_CONST TY106255 lookup_106254 = {((NimStringDesc*) &TMP328),
((NimStringDesc*) &TMP329),
((NimStringDesc*) &TMP330),
((NimStringDesc*) &TMP331),
((NimStringDesc*) &TMP332),
((NimStringDesc*) &TMP333),
((NimStringDesc*) &TMP334),
((NimStringDesc*) &TMP335),
((NimStringDesc*) &TMP336),
((NimStringDesc*) &TMP337),
((NimStringDesc*) &TMP338),
((NimStringDesc*) &TMP339)}
;
STRING_LITERAL(TMP340, "d", 1);
STRING_LITERAL(TMP341, "dd", 2);
STRING_LITERAL(TMP342, "ddd", 3);
STRING_LITERAL(TMP343, "dddd", 4);
STRING_LITERAL(TMP344, "h", 1);
STRING_LITERAL(TMP345, "hh", 2);
STRING_LITERAL(TMP346, "H", 1);
STRING_LITERAL(TMP347, "HH", 2);
STRING_LITERAL(TMP348, "m", 1);
STRING_LITERAL(TMP349, "mm", 2);
STRING_LITERAL(TMP350, "M", 1);
STRING_LITERAL(TMP351, "MM", 2);
STRING_LITERAL(TMP352, "MMM", 3);
STRING_LITERAL(TMP353, "MMMM", 4);
STRING_LITERAL(TMP354, "s", 1);
STRING_LITERAL(TMP355, "ss", 2);
STRING_LITERAL(TMP356, "t", 1);
STRING_LITERAL(TMP357, "tt", 2);
STRING_LITERAL(TMP358, "y", 1);
STRING_LITERAL(TMP359, "yy", 2);
STRING_LITERAL(TMP360, "yyy", 3);
STRING_LITERAL(TMP361, "yyyy", 4);
STRING_LITERAL(TMP362, "yyyyy", 5);
STRING_LITERAL(TMP363, "z", 1);
STRING_LITERAL(TMP364, "zz", 2);
STRING_LITERAL(TMP365, "zzz", 3);
STRING_LITERAL(TMP366, "ZZZ", 3);
STRING_LITERAL(TMP367, "0", 1);
STRING_LITERAL(TMP370, "PM", 2);
STRING_LITERAL(TMP371, "AM", 2);
STRING_LITERAL(TMP373, ":00", 3);
STRING_LITERAL(TMP374, "Invalid format string: ", 23);
extern TFrame* frameptr_16242;
extern TNimType NTI3211; /* RootObj */
TNimType NTI104405; /* TimeInfo */
extern TNimType NTI108; /* int */
TNimType NTI104408; /* range 0..61(int) */
TNimType NTI104411; /* range 0..59(int) */
TNimType NTI104413; /* range 0..23(int) */
TNimType NTI104416; /* range 1..31(int) */
TNimType NTI104206; /* Month */
TNimType NTI104419; /* range -10000..10000(int) */
TNimType NTI104208; /* WeekDay */
TNimType NTI104425; /* range 0..365(int) */
extern TNimType NTI138; /* bool */
extern TNimType NTI149; /* string */
extern TNimType NTI21601; /* ref ValueError */
extern TNimType NTI3249; /* ValueError */
extern tgcheap47216 gch_47244;

N_NIMCALL(time_t, fromseconds_104478)(NI64 since1970) {
	time_t result;
	result = 0;
	result = fromseconds_104472(((NF) (since1970)));
	return result;
}

N_NIMCALL(NIM_BOOL, ntLtTime)(time_t a, time_t b) {
	NIM_BOOL result;
	NI64 LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = ntDiffTime(a, b);
	result = (LOC1 < IL64(0));
	return result;
}

N_NIMCALL(NIM_BOOL, ntLeTime)(time_t a, time_t b) {
	NIM_BOOL result;
	NI64 LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = ntDiffTime(a, b);
	result = (LOC1 <= IL64(0));
	return result;
}

N_NIMCALL(NIM_BOOL, ntEqTime)(time_t a, time_t b) {
	NIM_BOOL result;
	NI64 LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = ntDiffTime(a, b);
	result = (LOC1 == IL64(0));
	return result;
}

N_NIMCALL(timeinterval104407, initinterval_104614)(NI miliseconds, NI seconds, NI minutes, NI hours, NI days, NI months, NI years) {
	timeinterval104407 result;
	memset((void*)(&result), 0, sizeof(result));
	result.Miliseconds = miliseconds;
	result.Seconds = seconds;
	result.Minutes = minutes;
	result.Hours = hours;
	result.Days = days;
	result.Months = months;
	result.Years = years;
	return result;
}

N_NIMCALL(NIM_BOOL, isleapyear_104630)(NI year) {
	NIM_BOOL result;
	result = 0;
	{
		if (!(((NI) ((NI32)(year % 400))) == 0)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	goto LA1;
	LA3: ;
	{
		if (!(((NI) ((NI32)(year % 100))) == 0)) goto LA6;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	goto LA1;
	LA6: ;
	{
		if (!(((NI) ((NI32)(year % 4))) == 0)) goto LA9;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	goto LA1;
	LA9: ;
	{
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA1: ;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, getdaysinmonth_104645)(NU8 month, NI year) {
	NI result;
	result = 0;
	switch (month) {
	case ((NU8) 1):
	{
		{
			NIM_BOOL LOC4;
			LOC4 = 0;
			LOC4 = isleapyear_104630(year);
			if (!LOC4) goto LA5;
			result = 29;
		}
		goto LA2;
		LA5: ;
		{
			result = 28;
		}
		LA2: ;
	}
	break;
	case ((NU8) 3):
	case ((NU8) 5):
	case ((NU8) 8):
	case ((NU8) 10):
	{
		result = 30;
	}
	break;
	default:
	{
		result = 31;
	}
	break;
	}
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

static N_INLINE(void, HEX2BHEX3D_104693)(NF* x_104699, NF y_104702) {
	nimfr("+=", "system.nim")
	nimln(2893, "system.nim");
	nimln(2893, "system.nim");
	(*x_104699) = ((NF)((*x_104699)) + (NF)(y_104702));
	popFrame();
}

static N_INLINE(NF, HEX2F_84603)(NI x, NI y) {
	NF result;
	nimfr("/", "system.nim")
	result = 0;
	nimln(2749, "system.nim");
	nimln(2749, "system.nim");
	nimln(2749, "system.nim");
	nimln(2749, "system.nim");
	result = ((NF)(((double) (x))) / (NF)(((double) (y))));
	popFrame();
	return result;
}

N_NIMCALL(NF, toseconds_104658)(timeinfo104405* a, timeinterval104407* interval) {
	NF result;
	timeinfo104405 anew;
	timeinterval104407 newinterv;
	NU8 curmonth;
	NF LOC10;
	result = 0;
	memset((void*)(&anew), 0, sizeof(anew));
	anew.Sup.m_type = (&NTI104405);
	genericAssign((void*)(&anew), (void*)a, (&NTI104405));
	newinterv = (*interval);
	result = 0.0;
	newinterv.Months += (NI32)((*interval).Years * 12);
	curmonth = anew.Month;
	{
		NI mth_104688;
		NI HEX3Atmp_104809;
		NI res_104812;
		mth_104688 = 0;
		HEX3Atmp_104809 = 0;
		HEX3Atmp_104809 = newinterv.Months;
		res_104812 = 1;
		{
			while (1) {
				NI LOC4;
				if (!(res_104812 <= HEX3Atmp_104809)) goto LA3;
				mth_104688 = res_104812;
				LOC4 = 0;
				LOC4 = getdaysinmonth_104645(curmonth, ((NI) (anew.Year)));
				HEX2BHEX3D_104693((&result), ((NF) ((NI32)((NI32)((NI32)(LOC4 * 24) * 60) * 60))));
				{
					if (!(curmonth == ((NU8) 11))) goto LA7;
					curmonth = ((NU8) 0);
					anew.Year += 1;
				}
				goto LA5;
				LA7: ;
				{
					curmonth += 1;
				}
				LA5: ;
				res_104812 += 1;
			} LA3: ;
		}
	}
	HEX2BHEX3D_104693((&result), ((NF) ((NI32)((NI32)((NI32)(newinterv.Days * 24) * 60) * 60))));
	HEX2BHEX3D_104693((&result), ((NF) ((NI32)((NI32)(newinterv.Hours * 60) * 60))));
	HEX2BHEX3D_104693((&result), ((NF) ((NI32)(newinterv.Minutes * 60))));
	HEX2BHEX3D_104693((&result), ((NF) (newinterv.Seconds)));
	LOC10 = 0;
	LOC10 = HEX2F_84603(newinterv.Miliseconds, 1000);
	HEX2BHEX3D_104693((&result), LOC10);
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (NI32)((*a).Sup.len * 1));
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, HEX2B_104833)(timeinfo104405* a, timeinterval104407* interval, timeinfo104405* Result) {
	NF t;
	time_t LOC1;
	NF secs;
	LOC1 = 0;
	LOC1 = timeinfototime_104466(a);
	t = toseconds_104489(LOC1);
	secs = toseconds_104658(a, interval);
	{
		time_t LOC6;
		if (!eqStrings((*a).Tzname, ((NimStringDesc*) &TMP318))) goto LA4;
		LOC6 = 0;
		LOC6 = fromseconds_104472(((NF)(t) + (NF)(secs)));
		genericReset((void*)Result, (&NTI104405));
		(*Result).Sup.m_type = (&NTI104405);
		getgmtime_104460(LOC6, Result);
	}
	goto LA2;
	LA4: ;
	{
		time_t LOC8;
		LOC8 = 0;
		LOC8 = fromseconds_104472(((NF)(t) + (NF)(secs)));
		genericReset((void*)Result, (&NTI104405));
		(*Result).Sup.m_type = (&NTI104405);
		getlocaltime_104454(LOC8, Result);
	}
	LA2: ;
}

N_NIMCALL(void, HEX2D_104846)(timeinfo104405* a, timeinterval104407* interval, timeinfo104405* Result) {
	NF t;
	time_t LOC1;
	NF secs;
	LOC1 = 0;
	LOC1 = timeinfototime_104466(a);
	t = toseconds_104489(LOC1);
	secs = toseconds_104658(a, interval);
	{
		time_t LOC6;
		if (!eqStrings((*a).Tzname, ((NimStringDesc*) &TMP318))) goto LA4;
		LOC6 = 0;
		LOC6 = fromseconds_104472(((NF)(t) - (NF)(secs)));
		genericReset((void*)Result, (&NTI104405));
		(*Result).Sup.m_type = (&NTI104405);
		getgmtime_104460(LOC6, Result);
	}
	goto LA2;
	LA4: ;
	{
		time_t LOC8;
		LOC8 = 0;
		LOC8 = fromseconds_104472(((NF)(t) - (NF)(secs)));
		genericReset((void*)Result, (&NTI104405));
		(*Result).Sup.m_type = (&NTI104405);
		getlocaltime_104454(LOC8, Result);
	}
	LA2: ;
}

N_NIMCALL(void, gettzname_104549)(TY104551* Result) {
	unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(tzname[(0)- 0]));
	unsureAsgnRef((void**) (&(*Result).Field1), cstrToNimstr(tzname[(1)- 0]));
	goto BeforeRet;
	BeforeRet: ;
}

N_NIMCALL(NI, gettimezone_104604)(void) {
	NI result;
	result = 0;
	result = timezone;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, tmtotimeinfo_105048)(struct tm* tm, NIM_BOOL local, timeinfo104405* Result) {
	timeinfo104405 LOC1;
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.Sup.m_type = (&NTI104405);
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.Sup.m_type = (&NTI104405);
	LOC1.Second = ((NI) (((NI) ((*tm).tm_sec))));
	LOC1.Minute = ((NI) (((NI) ((*tm).tm_min))));
	LOC1.Hour = ((NI) (((NI) ((*tm).tm_hour))));
	LOC1.Monthday = ((NI) (((NI) ((*tm).tm_mday))));
	LOC1.Month = ((NU8) ((*tm).tm_mon));
	LOC1.Year = ((NI) ((NI32)((*tm).tm_year + ((NI32) 1900))));
	LOC1.Weekday = weekdays_105053[(((NI) ((*tm).tm_wday)))- 0];
	LOC1.Yearday = ((NI) (((NI) ((*tm).tm_yday))));
	LOC1.Isdst = (((NI32) 0) < (*tm).tm_isdst);
	{
		if (!local) goto LA4;
		{
			TY104551 LOC10;
			if (!(((NI32) 0) < (*tm).tm_isdst)) goto LA8;
			memset((void*)(&LOC10), 0, sizeof(LOC10));
			gettzname_104549((&LOC10));
			LOC1.Tzname = copyString(LOC10.Field1);
		}
		goto LA6;
		LA8: ;
		{
			TY104551 LOC12;
			memset((void*)(&LOC12), 0, sizeof(LOC12));
			gettzname_104549((&LOC12));
			LOC1.Tzname = copyString(LOC12.Field0);
		}
		LA6: ;
	}
	goto LA2;
	LA4: ;
	{
		LOC1.Tzname = copyString(((NimStringDesc*) &TMP318));
	}
	LA2: ;
	{
		if (!local) goto LA16;
		LOC1.Timezone = gettimezone_104604();
	}
	goto LA14;
	LA16: ;
	{
		LOC1.Timezone = 0;
	}
	LA14: ;
	genericShallowAssign((void*)Result, (void*)(&LOC1), (&NTI104405));
}

N_NIMCALL(struct tm, timeinfototm_105070)(timeinfo104405* t) {
	struct tm result;
	NI LOC1;
	memset((void*)(&result), 0, sizeof(result));
	result.tm_sec = ((int) ((*t).Second));
	result.tm_min = ((int) ((*t).Minute));
	result.tm_hour = ((int) ((*t).Hour));
	result.tm_mday = ((int) ((*t).Monthday));
	result.tm_mon = ((int) ((*t).Month));
	result.tm_year = ((int) ((NI32)(((NI) ((*t).Year)) - 1900)));
	result.tm_wday = ((int) (weekdays_105074[((*t).Weekday)- 0]));
	result.tm_yday = ((int) ((*t).Yearday));
	LOC1 = 0;
	{
		if (!(*t).Isdst) goto LA4;
		LOC1 = 1;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = 0;
	}
	LA2: ;
	result.tm_isdst = ((int) (LOC1));
	return result;
}

N_NIMCALL(NI64, ntDiffTime)(time_t a, time_t b) {
	NI64 result;
	NF LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = difftime(a, b);
	result = float64ToInt64(LOC1);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, getstartmilsecs_104609)(void) {
	NI result;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = clock();
	result = (NI32)(LOC1 / (NI32)(CLOCKS_PER_SEC / 1000));
	return result;
}

N_NIMCALL(time_t, gettime_104449)(void) {
	time_t result;
	result = 0;
	result = time(NIM_NIL);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, getlocaltime_104454)(time_t t, timeinfo104405* Result) {
	time_t a;
	struct tm* LOC1;
	a = t;
	LOC1 = 0;
	LOC1 = localtime((&a));
	genericReset((void*)Result, (&NTI104405));
	(*Result).Sup.m_type = (&NTI104405);
	tmtotimeinfo_105048((&(*LOC1)), NIM_TRUE, Result);
}

N_NIMCALL(void, getgmtime_104460)(time_t t, timeinfo104405* Result) {
	time_t a;
	struct tm* LOC1;
	a = t;
	LOC1 = 0;
	LOC1 = gmtime((&a));
	genericReset((void*)Result, (&NTI104405));
	(*Result).Sup.m_type = (&NTI104405);
	tmtotimeinfo_105048((&(*LOC1)), NIM_FALSE, Result);
}

N_NIMCALL(time_t, timeinfototime_104466)(timeinfo104405* timeinfo) {
	time_t result;
	timeinfo104405 ctimeinfo;
	struct tm LOC1;
	result = 0;
	memset((void*)(&ctimeinfo), 0, sizeof(ctimeinfo));
	ctimeinfo.Sup.m_type = (&NTI104405);
	genericAssign((void*)(&ctimeinfo), (void*)timeinfo, (&NTI104405));
	LOC1 = timeinfototm_105070((&ctimeinfo));
	result = mktime((&LOC1));
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NimStringDesc*, tostringtillnl_105637)(NCSTRING p) {
	NimStringDesc* result;
	NI i;
	result = 0;
	result = copyString(((NimStringDesc*) &TMP319));
	i = 0;
	{
		while (1) {
			NIM_BOOL LOC3;
			NIM_BOOL LOC4;
			LOC3 = 0;
			LOC4 = 0;
			LOC4 = !(((NU8)(p[i]) == (NU8)(0)));
			if (!(LOC4)) goto LA5;
			LOC4 = !(((NU8)(p[i]) == (NU8)(10)));
			LA5: ;
			LOC3 = LOC4;
			if (!(LOC3)) goto LA6;
			LOC3 = !(((NU8)(p[i]) == (NU8)(13)));
			LA6: ;
			if (!LOC3) goto LA2;
			result = addChar(result, p[i]);
			i += 1;
		} LA2: ;
	}
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_104495)(timeinfo104405* timeinfo) {
	NimStringDesc* result;
	NCSTRING p;
	struct tm LOC1;
	result = 0;
	LOC1 = timeinfototm_105070(timeinfo);
	p = asctime((&LOC1));
	result = tostringtillnl_105637(p);
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_104501)(time_t time) {
	NimStringDesc* result;
	time_t a;
	NCSTRING LOC1;
	result = 0;
	a = time;
	LOC1 = 0;
	LOC1 = ctime((&a));
	result = tostringtillnl_105637(LOC1);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI64, unixtimetowintime_105683)(time_t t) {
	NI64 result;
	result = 0;
	result = (NI64)((NI64)(((NI64) (t)) * IL64(10000000)) + IL64(116444736000000000));
	return result;
}

N_NIMCALL(time_t, wintimetounixtime_105691)(NI64 t) {
	time_t result;
	result = 0;
	result = ((time_t) ((NI64)((NI64)(t - IL64(116444736000000000)) / IL64(10000000))));
	return result;
}

N_NIMCALL(time_t, fromseconds_104472)(NF since1970) {
	time_t result;
	result = 0;
	result = ((time_t) (since1970));
	return result;
}

N_NIMCALL(NF, toseconds_104489)(time_t time) {
	NF result;
	result = 0;
	result = ((NF) (time));
	return result;
}

N_NIMCALL(NF, ntepochTime)(void) {
	NF result;
	struct timeval a;
	result = 0;
	memset((void*)(&a), 0, sizeof(a));
	gettimeofday((&a), NIM_NIL);
	result = ((NF)(((double) (a.tv_sec))) + (NF)(((NF)(((double) (a.tv_usec))) * (NF)(9.9999999999999995e-07))));
	return result;
}

N_NIMCALL(NF, ntcpuTime)(void) {
	NF result;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = clock();
	result = ((NF)(((double) (LOC1))) / (NF)(((double) (CLOCKS_PER_SEC))));
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI32)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI32)((*dest).Sup.len + 1))- 0] = 0;
	(*dest).Sup.len += 1;
}

N_NIMCALL(NimStringDesc*, ntgetDateStr)(void) {
	NimStringDesc* result;
	timeinfo104405 ti;
	time_t LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	result = 0;
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI104405);
	LOC1 = 0;
	LOC1 = gettime_104449();
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI104405);
	getlocaltime_104454(LOC1, (&ti));
	LOC2 = 0;
	LOC3 = 0;
	LOC3 = nimIntToStr(((NI) (ti.Year)));
	LOC4 = 0;
	LOC4 = nsuIntToStr(((NI) ((NI32)(((NI) (ti.Month)) + 1))), 2);
	LOC5 = 0;
	LOC5 = nsuIntToStr(((NI) (ti.Monthday)), 2);
	LOC2 = rawNewString(LOC3->Sup.len + LOC4->Sup.len + LOC5->Sup.len + 2);
appendString(LOC2, LOC3);
appendChar(LOC2, 45);
appendString(LOC2, LOC4);
appendChar(LOC2, 45);
appendString(LOC2, LOC5);
	result = LOC2;
	return result;
}

N_NIMCALL(NimStringDesc*, ntgetClockStr)(void) {
	NimStringDesc* result;
	timeinfo104405 ti;
	time_t LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	result = 0;
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI104405);
	LOC1 = 0;
	LOC1 = gettime_104449();
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI104405);
	getlocaltime_104454(LOC1, (&ti));
	LOC2 = 0;
	LOC3 = 0;
	LOC3 = nsuIntToStr(((NI) (ti.Hour)), 2);
	LOC4 = 0;
	LOC4 = nsuIntToStr(((NI) (ti.Minute)), 2);
	LOC5 = 0;
	LOC5 = nsuIntToStr(((NI) (ti.Second)), 2);
	LOC2 = rawNewString(LOC3->Sup.len + LOC4->Sup.len + LOC5->Sup.len + 2);
appendString(LOC2, LOC3);
appendChar(LOC2, 58);
appendString(LOC2, LOC4);
appendChar(LOC2, 58);
appendString(LOC2, LOC5);
	result = LOC2;
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_106234)(NU8 day) {
	NimStringDesc* result;
	result = 0;
	result = copyString(lookup_106238[(day)- 0]);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_106250)(NU8 m) {
	NimStringDesc* result;
	result = 0;
	result = copyString(lookup_106254[(m)- 0]);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NimStringDesc*, HEX5BHEX5D_84658)(NimStringDesc* s, slice84665 x) {
	NimStringDesc* result;
	NI LOC1;
	NI LOC7;
	nimfr("[]", "system.nim")
	result = 0;
	nimln(2773, "system.nim");
	nimln(2773, "system.nim");
	LOC1 = 0;
	nimln(2752, "system.nim");
	{
		nimln(2752, "system.nim");
		if (!(0 <= x.A)) goto LA4;
		LOC1 = x.A;
	}
	goto LA2;
	LA4: ;
	{
		NI TMP368;
		nimln(2752, "system.nim");
		nimln(2752, "system.nim");
		TMP368 = addInt(s->Sup.len, x.A);
		LOC1 = (NI32)(TMP368);
	}
	LA2: ;
	LOC7 = 0;
	nimln(2752, "system.nim");
	{
		nimln(2752, "system.nim");
		if (!(0 <= x.B)) goto LA10;
		LOC7 = x.B;
	}
	goto LA8;
	LA10: ;
	{
		NI TMP369;
		nimln(2752, "system.nim");
		nimln(2752, "system.nim");
		TMP369 = addInt(s->Sup.len, x.B);
		LOC7 = (NI32)(TMP369);
	}
	LA8: ;
	result = copyStrLast(s, LOC1, LOC7);
	popFrame();
	return result;
}

static N_INLINE(slice84665, HEX2EHEX2E_91098)(NI a_91102, NI b_91104) {
	slice84665 result;
	nimfr("..", "system.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(226, "system.nim");
	result.A = a_91102;
	nimln(227, "system.nim");
	result.B = b_91104;
	popFrame();
	return result;
}

static N_INLINE(tcell45135*, usrtocell_48846)(void* usr) {
	tcell45135* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell45135*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell45135))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50404)(tcell45135* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48817((&gch_47244.Zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell45135* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_48846(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell45135* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_48846((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50404(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, formattoken_106266)(timeinfo104405* info, NimStringDesc* token, NimStringDesc** buf) {
	switch (hashString(token) & 31) {
	case 0: 
if (eqStrings(token, ((NimStringDesc*) &TMP319))) goto LA28;
break;
	case 1: 
if (eqStrings(token, ((NimStringDesc*) &TMP349))) goto LA10;
break;
	case 4: 
if (eqStrings(token, ((NimStringDesc*) &TMP362))) goto LA23;
break;
	case 5: 
if (eqStrings(token, ((NimStringDesc*) &TMP340))) goto LA1;
break;
	case 6: 
if (eqStrings(token, ((NimStringDesc*) &TMP357))) goto LA18;
break;
	case 7: 
if (eqStrings(token, ((NimStringDesc*) &TMP366))) goto LA27;
break;
	case 8: 
if (eqStrings(token, ((NimStringDesc*) &TMP358))) goto LA19;
break;
	case 10: 
if (eqStrings(token, ((NimStringDesc*) &TMP344))) goto LA5;
if (eqStrings(token, ((NimStringDesc*) &TMP350))) goto LA11;
if (eqStrings(token, ((NimStringDesc*) &TMP351))) goto LA12;
if (eqStrings(token, ((NimStringDesc*) &TMP355))) goto LA16;
if (eqStrings(token, ((NimStringDesc*) &TMP359))) goto LA20;
break;
	case 12: 
if (eqStrings(token, ((NimStringDesc*) &TMP352))) goto LA13;
break;
	case 14: 
if (eqStrings(token, ((NimStringDesc*) &TMP365))) goto LA26;
break;
	case 15: 
if (eqStrings(token, ((NimStringDesc*) &TMP343))) goto LA4;
if (eqStrings(token, ((NimStringDesc*) &TMP356))) goto LA17;
break;
	case 21: 
if (eqStrings(token, ((NimStringDesc*) &TMP341))) goto LA2;
if (eqStrings(token, ((NimStringDesc*) &TMP348))) goto LA9;
break;
	case 22: 
if (eqStrings(token, ((NimStringDesc*) &TMP354))) goto LA15;
if (eqStrings(token, ((NimStringDesc*) &TMP364))) goto LA25;
break;
	case 24: 
if (eqStrings(token, ((NimStringDesc*) &TMP346))) goto LA7;
break;
	case 25: 
if (eqStrings(token, ((NimStringDesc*) &TMP347))) goto LA8;
break;
	case 28: 
if (eqStrings(token, ((NimStringDesc*) &TMP353))) goto LA14;
break;
	case 29: 
if (eqStrings(token, ((NimStringDesc*) &TMP360))) goto LA21;
break;
	case 30: 
if (eqStrings(token, ((NimStringDesc*) &TMP363))) goto LA24;
break;
	case 31: 
if (eqStrings(token, ((NimStringDesc*) &TMP342))) goto LA3;
if (eqStrings(token, ((NimStringDesc*) &TMP345))) goto LA6;
if (eqStrings(token, ((NimStringDesc*) &TMP361))) goto LA22;
break;
	}
	goto LA29;
	LA1: ;
	{
		NimStringDesc* LOC32;
		LOC32 = 0;
		LOC32 = nimIntToStr(((NI) ((*info).Monthday)));
		(*buf) = resizeString((*buf), LOC32->Sup.len + 0);
appendString((*buf), LOC32);
	}
	goto LA30;
	LA2: ;
	{
		NimStringDesc* LOC38;
		{
			if (!(((NI) ((*info).Monthday)) < 10)) goto LA36;
			(*buf) = resizeString((*buf), 1);
appendString((*buf), ((NimStringDesc*) &TMP367));
		}
		LA36: ;
		LOC38 = 0;
		LOC38 = nimIntToStr(((NI) ((*info).Monthday)));
		(*buf) = resizeString((*buf), LOC38->Sup.len + 0);
appendString((*buf), LOC38);
	}
	goto LA30;
	LA3: ;
	{
		NimStringDesc* LOC40;
		slice84665 LOC41;
		NimStringDesc* LOC42;
		LOC40 = 0;
		LOC40 = HEX24_106234((*info).Weekday);
		LOC41 = HEX2EHEX2E_91098(0, 2);
		LOC42 = 0;
		LOC42 = HEX5BHEX5D_84658(LOC40, LOC41);
		(*buf) = resizeString((*buf), LOC42->Sup.len + 0);
appendString((*buf), LOC42);
	}
	goto LA30;
	LA4: ;
	{
		NimStringDesc* LOC44;
		LOC44 = 0;
		LOC44 = HEX24_106234((*info).Weekday);
		(*buf) = resizeString((*buf), LOC44->Sup.len + 0);
appendString((*buf), LOC44);
	}
	goto LA30;
	LA5: ;
	{
		NI LOC46;
		NimStringDesc* LOC52;
		LOC46 = 0;
		{
			if (!(12 < ((NI) ((*info).Hour)))) goto LA49;
			LOC46 = ((NI) ((NI32)(((NI) ((*info).Hour)) - 12)));
		}
		goto LA47;
		LA49: ;
		{
			LOC46 = ((NI) ((*info).Hour));
		}
		LA47: ;
		LOC52 = 0;
		LOC52 = nimIntToStr(LOC46);
		(*buf) = resizeString((*buf), LOC52->Sup.len + 0);
appendString((*buf), LOC52);
	}
	goto LA30;
	LA6: ;
	{
		NI amerhour;
		NimStringDesc* LOC63;
		{
			if (!(12 < ((NI) ((*info).Hour)))) goto LA56;
			amerhour = ((NI) ((NI32)(((NI) ((*info).Hour)) - 12)));
		}
		goto LA54;
		LA56: ;
		{
			amerhour = ((NI) ((*info).Hour));
		}
		LA54: ;
		{
			if (!(amerhour < 10)) goto LA61;
			(*buf) = addChar((*buf), 48);
		}
		LA61: ;
		LOC63 = 0;
		LOC63 = nimIntToStr(amerhour);
		(*buf) = resizeString((*buf), LOC63->Sup.len + 0);
appendString((*buf), LOC63);
	}
	goto LA30;
	LA7: ;
	{
		NimStringDesc* LOC65;
		LOC65 = 0;
		LOC65 = nimIntToStr(((NI) ((*info).Hour)));
		(*buf) = resizeString((*buf), LOC65->Sup.len + 0);
appendString((*buf), LOC65);
	}
	goto LA30;
	LA8: ;
	{
		NimStringDesc* LOC71;
		{
			if (!(((NI) ((*info).Hour)) < 10)) goto LA69;
			(*buf) = addChar((*buf), 48);
		}
		LA69: ;
		LOC71 = 0;
		LOC71 = nimIntToStr(((NI) ((*info).Hour)));
		(*buf) = resizeString((*buf), LOC71->Sup.len + 0);
appendString((*buf), LOC71);
	}
	goto LA30;
	LA9: ;
	{
		NimStringDesc* LOC73;
		LOC73 = 0;
		LOC73 = nimIntToStr(((NI) ((*info).Minute)));
		(*buf) = resizeString((*buf), LOC73->Sup.len + 0);
appendString((*buf), LOC73);
	}
	goto LA30;
	LA10: ;
	{
		NimStringDesc* LOC79;
		{
			if (!(((NI) ((*info).Minute)) < 10)) goto LA77;
			(*buf) = addChar((*buf), 48);
		}
		LA77: ;
		LOC79 = 0;
		LOC79 = nimIntToStr(((NI) ((*info).Minute)));
		(*buf) = resizeString((*buf), LOC79->Sup.len + 0);
appendString((*buf), LOC79);
	}
	goto LA30;
	LA11: ;
	{
		NimStringDesc* LOC81;
		LOC81 = 0;
		LOC81 = nimIntToStr((NI32)(((NI) ((*info).Month)) + 1));
		(*buf) = resizeString((*buf), LOC81->Sup.len + 0);
appendString((*buf), LOC81);
	}
	goto LA30;
	LA12: ;
	{
		NimStringDesc* LOC87;
		{
			if (!((*info).Month < ((NU8) 9))) goto LA85;
			(*buf) = addChar((*buf), 48);
		}
		LA85: ;
		LOC87 = 0;
		LOC87 = nimIntToStr((NI32)(((NI) ((*info).Month)) + 1));
		(*buf) = resizeString((*buf), LOC87->Sup.len + 0);
appendString((*buf), LOC87);
	}
	goto LA30;
	LA13: ;
	{
		NimStringDesc* LOC89;
		slice84665 LOC90;
		NimStringDesc* LOC91;
		LOC89 = 0;
		LOC89 = HEX24_106250((*info).Month);
		LOC90 = HEX2EHEX2E_91098(0, 2);
		LOC91 = 0;
		LOC91 = HEX5BHEX5D_84658(LOC89, LOC90);
		(*buf) = resizeString((*buf), LOC91->Sup.len + 0);
appendString((*buf), LOC91);
	}
	goto LA30;
	LA14: ;
	{
		NimStringDesc* LOC93;
		LOC93 = 0;
		LOC93 = HEX24_106250((*info).Month);
		(*buf) = resizeString((*buf), LOC93->Sup.len + 0);
appendString((*buf), LOC93);
	}
	goto LA30;
	LA15: ;
	{
		NimStringDesc* LOC95;
		LOC95 = 0;
		LOC95 = nimIntToStr(((NI) ((*info).Second)));
		(*buf) = resizeString((*buf), LOC95->Sup.len + 0);
appendString((*buf), LOC95);
	}
	goto LA30;
	LA16: ;
	{
		NimStringDesc* LOC101;
		{
			if (!(((NI) ((*info).Second)) < 10)) goto LA99;
			(*buf) = addChar((*buf), 48);
		}
		LA99: ;
		LOC101 = 0;
		LOC101 = nimIntToStr(((NI) ((*info).Second)));
		(*buf) = resizeString((*buf), LOC101->Sup.len + 0);
appendString((*buf), LOC101);
	}
	goto LA30;
	LA17: ;
	{
		{
			if (!(12 <= ((NI) ((*info).Hour)))) goto LA105;
			(*buf) = addChar((*buf), 80);
		}
		goto LA103;
		LA105: ;
		{
			(*buf) = addChar((*buf), 65);
		}
		LA103: ;
	}
	goto LA30;
	LA18: ;
	{
		{
			if (!(12 <= ((NI) ((*info).Hour)))) goto LA111;
			(*buf) = resizeString((*buf), 2);
appendString((*buf), ((NimStringDesc*) &TMP370));
		}
		goto LA109;
		LA111: ;
		{
			(*buf) = resizeString((*buf), 2);
appendString((*buf), ((NimStringDesc*) &TMP371));
		}
		LA109: ;
	}
	goto LA30;
	LA19: ;
	{
		NI fr;
		NimStringDesc* LOC115;
		NimStringDesc* LOC120;
		NimStringDesc* LOC121;
		slice84665 LOC122;
		NimStringDesc* LOC123;
		LOC115 = 0;
		LOC115 = nimIntToStr(((NI) ((*info).Year)));
		fr = (NI32)(LOC115->Sup.len - 1);
		{
			if (!(fr < 0)) goto LA118;
			fr = 0;
		}
		LA118: ;
		LOC120 = 0;
		LOC120 = nimIntToStr(((NI) ((*info).Year)));
		LOC121 = 0;
		LOC121 = nimIntToStr(((NI) ((*info).Year)));
		LOC122 = HEX2EHEX2E_91098(fr, (NI32)(LOC121->Sup.len - 1));
		LOC123 = 0;
		LOC123 = HEX5BHEX5D_84658(LOC120, LOC122);
		(*buf) = resizeString((*buf), LOC123->Sup.len + 0);
appendString((*buf), LOC123);
	}
	goto LA30;
	LA20: ;
	{
		NI fr;
		NimStringDesc* LOC125;
		NimStringDesc* fyear;
		NimStringDesc* LOC130;
		NimStringDesc* LOC131;
		slice84665 LOC132;
		LOC125 = 0;
		LOC125 = nimIntToStr(((NI) ((*info).Year)));
		fr = (NI32)(LOC125->Sup.len - 2);
		{
			if (!(fr < 0)) goto LA128;
			fr = 0;
		}
		LA128: ;
		LOC130 = 0;
		LOC130 = nimIntToStr(((NI) ((*info).Year)));
		LOC131 = 0;
		LOC131 = nimIntToStr(((NI) ((*info).Year)));
		LOC132 = HEX2EHEX2E_91098(fr, (NI32)(LOC131->Sup.len - 1));
		fyear = HEX5BHEX5D_84658(LOC130, LOC132);
		{
			NimStringDesc* LOC137;
			NimStringDesc* LOC138;
			if (!!((fyear->Sup.len == 2))) goto LA135;
			LOC137 = 0;
			LOC138 = 0;
			LOC138 = nsuRepeatChar((NI32)(2 - fyear->Sup.len), 48);
			LOC137 = rawNewString(LOC138->Sup.len + fyear->Sup.len + 0);
appendString(LOC137, LOC138);
appendString(LOC137, fyear);
			fyear = LOC137;
		}
		LA135: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA21: ;
	{
		NI fr;
		NimStringDesc* LOC140;
		NimStringDesc* fyear;
		NimStringDesc* LOC145;
		NimStringDesc* LOC146;
		slice84665 LOC147;
		LOC140 = 0;
		LOC140 = nimIntToStr(((NI) ((*info).Year)));
		fr = (NI32)(LOC140->Sup.len - 3);
		{
			if (!(fr < 0)) goto LA143;
			fr = 0;
		}
		LA143: ;
		LOC145 = 0;
		LOC145 = nimIntToStr(((NI) ((*info).Year)));
		LOC146 = 0;
		LOC146 = nimIntToStr(((NI) ((*info).Year)));
		LOC147 = HEX2EHEX2E_91098(fr, (NI32)(LOC146->Sup.len - 1));
		fyear = HEX5BHEX5D_84658(LOC145, LOC147);
		{
			NimStringDesc* LOC152;
			NimStringDesc* LOC153;
			if (!!((fyear->Sup.len == 3))) goto LA150;
			LOC152 = 0;
			LOC153 = 0;
			LOC153 = nsuRepeatChar((NI32)(3 - fyear->Sup.len), 48);
			LOC152 = rawNewString(LOC153->Sup.len + fyear->Sup.len + 0);
appendString(LOC152, LOC153);
appendString(LOC152, fyear);
			fyear = LOC152;
		}
		LA150: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA22: ;
	{
		NI fr;
		NimStringDesc* LOC155;
		NimStringDesc* fyear;
		NimStringDesc* LOC160;
		NimStringDesc* LOC161;
		slice84665 LOC162;
		LOC155 = 0;
		LOC155 = nimIntToStr(((NI) ((*info).Year)));
		fr = (NI32)(LOC155->Sup.len - 4);
		{
			if (!(fr < 0)) goto LA158;
			fr = 0;
		}
		LA158: ;
		LOC160 = 0;
		LOC160 = nimIntToStr(((NI) ((*info).Year)));
		LOC161 = 0;
		LOC161 = nimIntToStr(((NI) ((*info).Year)));
		LOC162 = HEX2EHEX2E_91098(fr, (NI32)(LOC161->Sup.len - 1));
		fyear = HEX5BHEX5D_84658(LOC160, LOC162);
		{
			NimStringDesc* LOC167;
			NimStringDesc* LOC168;
			if (!!((fyear->Sup.len == 4))) goto LA165;
			LOC167 = 0;
			LOC168 = 0;
			LOC168 = nsuRepeatChar((NI32)(4 - fyear->Sup.len), 48);
			LOC167 = rawNewString(LOC168->Sup.len + fyear->Sup.len + 0);
appendString(LOC167, LOC168);
appendString(LOC167, fyear);
			fyear = LOC167;
		}
		LA165: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA23: ;
	{
		NI fr;
		NimStringDesc* LOC170;
		NimStringDesc* fyear;
		NimStringDesc* LOC175;
		NimStringDesc* LOC176;
		slice84665 LOC177;
		LOC170 = 0;
		LOC170 = nimIntToStr(((NI) ((*info).Year)));
		fr = (NI32)(LOC170->Sup.len - 5);
		{
			if (!(fr < 0)) goto LA173;
			fr = 0;
		}
		LA173: ;
		LOC175 = 0;
		LOC175 = nimIntToStr(((NI) ((*info).Year)));
		LOC176 = 0;
		LOC176 = nimIntToStr(((NI) ((*info).Year)));
		LOC177 = HEX2EHEX2E_91098(fr, (NI32)(LOC176->Sup.len - 1));
		fyear = HEX5BHEX5D_84658(LOC175, LOC177);
		{
			NimStringDesc* LOC182;
			NimStringDesc* LOC183;
			if (!!((fyear->Sup.len == 5))) goto LA180;
			LOC182 = 0;
			LOC183 = 0;
			LOC183 = nsuRepeatChar((NI32)(5 - fyear->Sup.len), 48);
			LOC182 = rawNewString(LOC183->Sup.len + fyear->Sup.len + 0);
appendString(LOC182, LOC183);
appendString(LOC182, fyear);
			fyear = LOC182;
		}
		LA180: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA24: ;
	{
		NI hrs;
		NimStringDesc* LOC185;
		hrs = (NI32)((NI32)((*info).Timezone / 60) / 60);
		LOC185 = 0;
		LOC185 = nimIntToStr(hrs);
		(*buf) = resizeString((*buf), LOC185->Sup.len + 0);
appendString((*buf), LOC185);
	}
	goto LA30;
	LA25: ;
	{
		NI hrs;
		NimStringDesc* LOC187;
		hrs = (NI32)((NI32)((*info).Timezone / 60) / 60);
		LOC187 = 0;
		LOC187 = nimIntToStr(hrs);
		(*buf) = resizeString((*buf), LOC187->Sup.len + 0);
appendString((*buf), LOC187);
		{
			NI atindex;
			NimStringDesc* LOC192;
			NI LOC193;
			if (!((hrs > 0? (hrs) : -(hrs)) < 10)) goto LA190;
			LOC192 = 0;
			LOC192 = nimIntToStr(hrs);
			LOC193 = 0;
			{
				if (!(hrs < 0)) goto LA196;
				LOC193 = 1;
			}
			goto LA194;
			LA196: ;
			{
				LOC193 = 0;
			}
			LA194: ;
			atindex = (NI32)((*buf)->Sup.len - (NI32)(LOC192->Sup.len - LOC193));
			insert_86401(buf, ((NimStringDesc*) &TMP367), atindex);
		}
		LA190: ;
	}
	goto LA30;
	LA26: ;
	{
		NI hrs;
		NimStringDesc* LOC200;
		NimStringDesc* LOC201;
		hrs = (NI32)((NI32)((*info).Timezone / 60) / 60);
		LOC200 = 0;
		LOC201 = 0;
		LOC201 = nimIntToStr(hrs);
		LOC200 = rawNewString(LOC201->Sup.len + 3);
appendString(LOC200, LOC201);
appendString(LOC200, ((NimStringDesc*) &TMP373));
		(*buf) = resizeString((*buf), LOC200->Sup.len + 0);
appendString((*buf), LOC200);
		{
			NI atindex;
			NimStringDesc* LOC206;
			NimStringDesc* LOC207;
			NI LOC208;
			if (!((hrs > 0? (hrs) : -(hrs)) < 10)) goto LA204;
			LOC206 = 0;
			LOC207 = 0;
			LOC207 = nimIntToStr(hrs);
			LOC206 = rawNewString(LOC207->Sup.len + 3);
appendString(LOC206, LOC207);
appendString(LOC206, ((NimStringDesc*) &TMP373));
			LOC208 = 0;
			{
				if (!(hrs < 0)) goto LA211;
				LOC208 = 1;
			}
			goto LA209;
			LA211: ;
			{
				LOC208 = 0;
			}
			LA209: ;
			atindex = (NI32)((*buf)->Sup.len - (NI32)(LOC206->Sup.len - LOC208));
			insert_86401(buf, ((NimStringDesc*) &TMP367), atindex);
		}
		LA204: ;
	}
	goto LA30;
	LA27: ;
	{
		(*buf) = resizeString((*buf), (*info).Tzname->Sup.len + 0);
appendString((*buf), (*info).Tzname);
	}
	goto LA30;
	LA28: ;
	{
	}
	goto LA30;
	LA29: ;
	{
		valueerror3249* e_106394;
		NimStringDesc* LOC217;
		e_106394 = 0;
		e_106394 = (valueerror3249*) newObj((&NTI21601), sizeof(valueerror3249));
		(*e_106394).Sup.Sup.m_type = (&NTI3249);
		LOC217 = 0;
		LOC217 = rawNewString(token->Sup.len + 23);
appendString(LOC217, ((NimStringDesc*) &TMP374));
appendString(LOC217, token);
		asgnRefNoCycle((void**) (&(*e_106394).Sup.message), LOC217);
		raiseException((Exception*)e_106394, "ValueError");
	}
	LA30: ;
}

N_NIMCALL(NimStringDesc*, format_106421)(timeinfo104405* info, NimStringDesc* f) {
	NimStringDesc* result;
	NI i;
	NimStringDesc* currentf;
	result = 0;
	result = copyString(((NimStringDesc*) &TMP319));
	i = 0;
	currentf = copyString(((NimStringDesc*) &TMP319));
	{
		while (1) {
			switch (((NU8)(f->data[i]))) {
			case 32:
			case 45:
			case 47:
			case 58:
			case 39:
			case 0:
			case 40:
			case 41:
			case 91:
			case 93:
			case 44:
			{
				formattoken_106266(info, currentf, (&result));
				currentf = copyString(((NimStringDesc*) &TMP319));
				{
					if (!((NU8)(f->data[i]) == (NU8)(0))) goto LA6;
					goto LA1;
				}
				LA6: ;
				{
					if (!((NU8)(f->data[i]) == (NU8)(39))) goto LA10;
					i += 1;
					{
						while (1) {
							NIM_BOOL LOC14;
							LOC14 = 0;
							LOC14 = !(((NU8)(f->data[i]) == (NU8)(39)));
							if (!(LOC14)) goto LA15;
							LOC14 = (i < (NI32)(f->Sup.len - 1));
							LA15: ;
							if (!LOC14) goto LA13;
							result = addChar(result, f->data[i]);
							i += 1;
						} LA13: ;
					}
				}
				goto LA8;
				LA10: ;
				{
					result = addChar(result, f->data[i]);
				}
				LA8: ;
			}
			break;
			default:
			{
				{
					NIM_BOOL LOC20;
					LOC20 = 0;
					LOC20 = (currentf->Sup.len < 1);
					if (LOC20) goto LA21;
					LOC20 = ((NU8)(currentf->data[(currentf->Sup.len-1)]) == (NU8)(f->data[i]));
					LA21: ;
					if (!LOC20) goto LA22;
					currentf = addChar(currentf, f->data[i]);
				}
				goto LA18;
				LA22: ;
				{
					formattoken_106266(info, currentf, (&result));
					i -= 1;
					currentf = copyString(((NimStringDesc*) &TMP319));
				}
				LA18: ;
			}
			break;
			}
			i += 1;
		}
	} LA1: ;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit)(void) {
static TNimNode* TMP311[11];
static TNimNode* TMP312[12];
NI TMP314;
static char* NIM_CONST TMP313[12] = {
"mJan", 
"mFeb", 
"mMar", 
"mApr", 
"mMay", 
"mJun", 
"mJul", 
"mAug", 
"mSep", 
"mOct", 
"mNov", 
"mDec"};
static TNimNode* TMP315[7];
NI TMP317;
static char* NIM_CONST TMP316[7] = {
"dMon", 
"dTue", 
"dWed", 
"dThu", 
"dFri", 
"dSat", 
"dSun"};
static TNimNode TMP309[33];
NTI104405.size = sizeof(timeinfo104405);
NTI104405.kind = 17;
NTI104405.base = (&NTI3211);
TMP311[0] = &TMP309[1];
NTI104408.size = sizeof(NI);
NTI104408.kind = 20;
NTI104408.base = (&NTI108);
NTI104408.flags = 3;
TMP309[1].kind = 1;
TMP309[1].offset = offsetof(timeinfo104405, Second);
TMP309[1].typ = (&NTI104408);
TMP309[1].name = "second";
TMP311[1] = &TMP309[2];
NTI104411.size = sizeof(NI);
NTI104411.kind = 20;
NTI104411.base = (&NTI108);
NTI104411.flags = 3;
TMP309[2].kind = 1;
TMP309[2].offset = offsetof(timeinfo104405, Minute);
TMP309[2].typ = (&NTI104411);
TMP309[2].name = "minute";
TMP311[2] = &TMP309[3];
NTI104413.size = sizeof(NI);
NTI104413.kind = 20;
NTI104413.base = (&NTI108);
NTI104413.flags = 3;
TMP309[3].kind = 1;
TMP309[3].offset = offsetof(timeinfo104405, Hour);
TMP309[3].typ = (&NTI104413);
TMP309[3].name = "hour";
TMP311[3] = &TMP309[4];
NTI104416.size = sizeof(NI);
NTI104416.kind = 20;
NTI104416.base = (&NTI108);
NTI104416.flags = 3;
TMP309[4].kind = 1;
TMP309[4].offset = offsetof(timeinfo104405, Monthday);
TMP309[4].typ = (&NTI104416);
TMP309[4].name = "monthday";
TMP311[4] = &TMP309[5];
NTI104206.size = sizeof(NU8);
NTI104206.kind = 14;
NTI104206.base = 0;
NTI104206.flags = 3;
for (TMP314 = 0; TMP314 < 12; TMP314++) {
TMP309[TMP314+6].kind = 1;
TMP309[TMP314+6].offset = TMP314;
TMP309[TMP314+6].name = TMP313[TMP314];
TMP312[TMP314] = &TMP309[TMP314+6];
}
TMP309[18].len = 12; TMP309[18].kind = 2; TMP309[18].sons = &TMP312[0];
NTI104206.node = &TMP309[18];
TMP309[5].kind = 1;
TMP309[5].offset = offsetof(timeinfo104405, Month);
TMP309[5].typ = (&NTI104206);
TMP309[5].name = "month";
TMP311[5] = &TMP309[19];
NTI104419.size = sizeof(NI);
NTI104419.kind = 20;
NTI104419.base = (&NTI108);
NTI104419.flags = 3;
TMP309[19].kind = 1;
TMP309[19].offset = offsetof(timeinfo104405, Year);
TMP309[19].typ = (&NTI104419);
TMP309[19].name = "year";
TMP311[6] = &TMP309[20];
NTI104208.size = sizeof(NU8);
NTI104208.kind = 14;
NTI104208.base = 0;
NTI104208.flags = 3;
for (TMP317 = 0; TMP317 < 7; TMP317++) {
TMP309[TMP317+21].kind = 1;
TMP309[TMP317+21].offset = TMP317;
TMP309[TMP317+21].name = TMP316[TMP317];
TMP315[TMP317] = &TMP309[TMP317+21];
}
TMP309[28].len = 7; TMP309[28].kind = 2; TMP309[28].sons = &TMP315[0];
NTI104208.node = &TMP309[28];
TMP309[20].kind = 1;
TMP309[20].offset = offsetof(timeinfo104405, Weekday);
TMP309[20].typ = (&NTI104208);
TMP309[20].name = "weekday";
TMP311[7] = &TMP309[29];
NTI104425.size = sizeof(NI);
NTI104425.kind = 20;
NTI104425.base = (&NTI108);
NTI104425.flags = 3;
TMP309[29].kind = 1;
TMP309[29].offset = offsetof(timeinfo104405, Yearday);
TMP309[29].typ = (&NTI104425);
TMP309[29].name = "yearday";
TMP311[8] = &TMP309[30];
TMP309[30].kind = 1;
TMP309[30].offset = offsetof(timeinfo104405, Isdst);
TMP309[30].typ = (&NTI138);
TMP309[30].name = "isDST";
TMP311[9] = &TMP309[31];
TMP309[31].kind = 1;
TMP309[31].offset = offsetof(timeinfo104405, Tzname);
TMP309[31].typ = (&NTI149);
TMP309[31].name = "tzname";
TMP311[10] = &TMP309[32];
TMP309[32].kind = 1;
TMP309[32].offset = offsetof(timeinfo104405, Timezone);
TMP309[32].typ = (&NTI108);
TMP309[32].name = "timezone";
TMP309[0].len = 11; TMP309[0].kind = 2; TMP309[0].sons = &TMP311[0];
NTI104405.node = &TMP309[0];
}

