/* Generated by Nim Compiler v0.10.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/jsudlow/Nim/lib -o .nimcache/stdlib_intsets.o .nimcache/stdlib_intsets.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct ttrunk158034 ttrunk158034;
typedef struct intset158038 intset158038;
typedef struct ttrunkseq158036 ttrunkseq158036;
typedef struct tcell45135 tcell45135;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcellset45147 tcellset45147;
typedef struct tgcheap47216 tgcheap47216;
typedef struct tcellseq45151 tcellseq45151;
typedef struct tpagedesc45143 tpagedesc45143;
typedef struct tmemregion27410 tmemregion27410;
typedef struct tsmallchunk26640 tsmallchunk26640;
typedef struct tllchunk27404 tllchunk27404;
typedef struct tbigchunk26642 tbigchunk26642;
typedef struct tintset26617 tintset26617;
typedef struct ttrunk26613 ttrunk26613;
typedef struct tavlnode27408 tavlnode27408;
typedef struct tgcstat47214 tgcstat47214;
typedef struct tbasechunk26638 tbasechunk26638;
typedef struct tfreecell26630 tfreecell26630;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  intset158038  {
NI Counter;
NI Max;
ttrunk158034* Head;
ttrunkseq158036* Data;
};
typedef NI TY26620[16];
struct  ttrunk158034  {
ttrunk158034* Next;
NI Key;
TY26620 Bits;
};
struct  tcell45135  {
NI Refcount;
TNimType* Typ;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  tcellseq45151  {
NI Len;
NI Cap;
tcell45135** D;
};
struct  tcellset45147  {
NI Counter;
NI Max;
tpagedesc45143* Head;
tpagedesc45143** Data;
};
typedef tsmallchunk26640* TY27422[512];
typedef ttrunk26613* ttrunkbuckets26615[256];
struct  tintset26617  {
ttrunkbuckets26615 Data;
};
struct  tmemregion27410  {
NI Minlargeobj;
NI Maxlargeobj;
TY27422 Freesmallchunks;
tllchunk27404* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26642* Freechunkslist;
tintset26617 Chunkstarts;
tavlnode27408* Root;
tavlnode27408* Deleted;
tavlnode27408* Last;
tavlnode27408* Freeavlnodes;
};
struct  tgcstat47214  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47216  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq45151 Zct;
tcellseq45151 Decstack;
tcellset45147 Cycleroots;
tcellseq45151 Tempstack;
NI Recgclock;
tmemregion27410 Region;
tgcstat47214 Stat;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tpagedesc45143  {
tpagedesc45143* Next;
NI Key;
TY26620 Bits;
};
struct  tbasechunk26638  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26640  {
  tbasechunk26638 Sup;
tsmallchunk26640* Next;
tsmallchunk26640* Prev;
tfreecell26630* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27404  {
NI Size;
NI Acc;
tllchunk27404* Next;
};
struct  tbigchunk26642  {
  tbasechunk26638 Sup;
tbigchunk26642* Next;
tbigchunk26642* Prev;
NI Align;
NF Data;
};
struct  ttrunk26613  {
ttrunk26613* Next;
NI Key;
TY26620 Bits;
};
typedef tavlnode27408* TY27414[2];
struct  tavlnode27408  {
TY27414 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell26630  {
tfreecell26630* Next;
NI Zerofield;
};
struct ttrunkseq158036 {
  TGenericSeq Sup;
  ttrunk158034* data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, mustrehash_158055)(NI length, NI counter);
N_NIMCALL(void, failedassertimpl_85425)(NimStringDesc* msg);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, nexttry_158210)(NI h, NI maxhash);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(ttrunk158034*, intsetget_158221)(intset158038 t, NI key);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(void, intsetrawinsert_158257)(intset158038 t, ttrunkseq158036** data, ttrunk158034* desc);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_51225)(tcell45135* c);
static N_INLINE(NIM_BOOL, canbecycleroot_48867)(tcell45135* c);
static N_INLINE(void, rtladdcycleroot_49629)(tcell45135* c);
N_NOINLINE(void, incl_45871)(tcellset45147* s, tcell45135* cell);
static N_INLINE(tcell45135*, usrtocell_48846)(void* usr);
static N_INLINE(void, decref_50804)(tcell45135* c);
static N_INLINE(void, rtladdzct_50404)(tcell45135* c);
N_NOINLINE(void, addzct_48817)(tcellseq45151* s, tcell45135* c);
N_NIMCALL(void, intsetenlarge_158631)(intset158038* t);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP705)(void* p, NI op);
N_NIMCALL(void, TMP706)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(ttrunk158034*, intsetput_158720)(intset158038* t, NI key);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NIM_BOOL, contains_158854)(intset158038 s, NI key);
N_NIMCALL(void, incl_158886)(intset158038* s, NI key);
N_NIMCALL(void, excl_158901)(intset158038* s, NI key);
N_NIMCALL(NIM_BOOL, containsorincl_158933)(intset158038* s, NI key);
N_NIMCALL(void, initintset_158967)(intset158038* Result);
N_NIMCALL(void, assign_158992)(intset158038* dest, intset158038 src);
N_NIMCALL(NimStringDesc*, HEX24_159354)(intset158038 s);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(NIM_BOOL, empty_159400)(intset158038 s);
STRING_LITERAL(TMP692, "length > counter ", 17);
STRING_LITERAL(TMP698, "data[h] != desc ", 16);
STRING_LITERAL(TMP699, "data[h] == nil ", 15);
STRING_LITERAL(TMP708, "t.data[h] == nil ", 17);
STRING_LITERAL(TMP709, "dest.data[h] == nil ", 20);
STRING_LITERAL(TMP710, "{", 1);
STRING_LITERAL(TMP711, ", ", 2);
STRING_LITERAL(TMP712, "}", 1);
extern TFrame* frameptr_16242;
extern tgcheap47216 gch_47244;
TNimType NTI158034; /* TTrunk */
extern TNimType NTI108; /* int */
extern TNimType NTI26620; /* array[0..15, int] */
TNimType NTI158032; /* PTrunk */
TNimType NTI158036; /* TTrunkSeq */

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) - (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU32) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

static N_INLINE(NIM_BOOL, mustrehash_158055)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL LOC5;
	NI TMP693;
	NI TMP694;
	NI TMP695;
	nimfr("mustRehash", "intsets.nim")
	result = 0;
	nimln(48, "intsets.nim");
	{
		nimln(48, "intsets.nim");
		nimln(48, "intsets.nim");
		if (!!((counter < length))) goto LA3;
		nimln(48, "intsets.nim");
		failedassertimpl_85425(((NimStringDesc*) &TMP692));
	}
	LA3: ;
	nimln(49, "intsets.nim");
	nimln(49, "intsets.nim");
	LOC5 = 0;
	nimln(49, "intsets.nim");
	nimln(49, "intsets.nim");
	TMP693 = mulInt(length, 2);
	nimln(49, "intsets.nim");
	TMP694 = mulInt(counter, 3);
	LOC5 = ((NI32)(TMP693) < (NI32)(TMP694));
	if (LOC5) goto LA6;
	nimln(49, "intsets.nim");
	nimln(49, "intsets.nim");
	TMP695 = subInt(length, counter);
	LOC5 = ((NI32)(TMP695) < 4);
	LA6: ;
	result = LOC5;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, nexttry_158210)(NI h, NI maxhash) {
	NI result;
	NI TMP696;
	NI TMP697;
	nimfr("nextTry", "intsets.nim")
	result = 0;
	nimln(52, "intsets.nim");
	nimln(52, "intsets.nim");
	nimln(52, "intsets.nim");
	nimln(52, "intsets.nim");
	TMP696 = mulInt(5, h);
	TMP697 = addInt((NI32)(TMP696), 1);
	result = (NI)((NI32)(TMP697) & maxhash);
	popFrame();
	return result;
}

N_NIMCALL(ttrunk158034*, intsetget_158221)(intset158038 t, NI key) {
	ttrunk158034* result;
	NI h;
	nimfr("intSetGet", "intsets.nim")
	result = 0;
	nimln(55, "intsets.nim");
	nimln(55, "intsets.nim");
	h = (NI)(key & t.Max);
	{
		nimln(56, "intsets.nim");
		while (1) {
			nimln(56, "intsets.nim");
			nimln(56, "intsets.nim");
			if ((NU)(h) >= (NU)(t.Data->Sup.len)) raiseIndexError();
			if (!!((t.Data->data[h] == NIM_NIL))) goto LA2;
			nimln(57, "intsets.nim");
			{
				nimln(57, "intsets.nim");
				if ((NU)(h) >= (NU)(t.Data->Sup.len)) raiseIndexError();
				if (!((*t.Data->data[h]).Key == key)) goto LA5;
				nimln(58, "intsets.nim");
				nimln(58, "intsets.nim");
				if ((NU)(h) >= (NU)(t.Data->Sup.len)) raiseIndexError();
				result = t.Data->data[h];
				goto BeforeRet;
			}
			LA5: ;
			nimln(59, "intsets.nim");
			h = nexttry_158210(h, t.Max);
		} LA2: ;
	}
	nimln(60, "intsets.nim");
	result = NIM_NIL;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, canbecycleroot_48867)(tcell45135* c) {
	NIM_BOOL result;
	nimfr("canbeCycleRoot", "gc.nim")
	result = 0;
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	result = !((((*(*c).Typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_49629)(tcell45135* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(189, "gc.nim");
	{
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		if (!!((((NI) ((NI)((*c).Refcount & 3))) == 3))) goto LA3;
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		(*c).Refcount = (NI)((NI)((*c).Refcount & -4) | 3);
		nimln(191, "gc.nim");
		incl_45871((&gch_47244.Cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_51225)(tcell45135* c) {
	nimfr("incRef", "gc.nim")
	nimln(216, "gc.nim");
	nimln(216, "gc.nim");
	(*c).Refcount = (NI)((NU32)((*c).Refcount) + (NU32)(8));
	nimln(219, "gc.nim");
	{
		NIM_BOOL LOC3;
		nimln(219, "gc.nim");
		LOC3 = 0;
		LOC3 = canbecycleroot_48867(c);
		if (!LOC3) goto LA4;
		nimln(220, "gc.nim");
		rtladdcycleroot_49629(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(tcell45135*, usrtocell_48846)(void* usr) {
	tcell45135* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell45135*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell45135))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50404)(tcell45135* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48817((&gch_47244.Zct), c);
	popFrame();
}

static N_INLINE(void, decref_50804)(tcell45135* c) {
	nimfr("decRef", "gc.nim")
	nimln(206, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA3;
		nimln(207, "gc.nim");
		rtladdzct_50404(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(208, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_48867(c);
		if (!LOC6) goto LA7;
		nimln(211, "gc.nim");
		rtladdcycleroot_49629(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(244, "gc.nim");
	{
		tcell45135* LOC5;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_48846(src);
		incref_51225(LOC5);
	}
	LA3: ;
	nimln(245, "gc.nim");
	{
		tcell45135* LOC10;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_48846((*dest));
		decref_50804(LOC10);
	}
	LA8: ;
	nimln(246, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, intsetrawinsert_158257)(intset158038 t, ttrunkseq158036** data, ttrunk158034* desc) {
	NI h;
	nimfr("intSetRawInsert", "intsets.nim")
	nimln(63, "intsets.nim");
	nimln(63, "intsets.nim");
	h = (NI)((*desc).Key & t.Max);
	{
		nimln(64, "intsets.nim");
		while (1) {
			nimln(64, "intsets.nim");
			nimln(64, "intsets.nim");
			if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
			if (!!(((*data)->data[h] == NIM_NIL))) goto LA2;
			nimln(65, "intsets.nim");
			{
				nimln(65, "intsets.nim");
				nimln(65, "intsets.nim");
				nimln(65, "intsets.nim");
				if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
				if (!!(!(((*data)->data[h] == desc)))) goto LA5;
				nimln(65, "intsets.nim");
				failedassertimpl_85425(((NimStringDesc*) &TMP698));
			}
			LA5: ;
			nimln(66, "intsets.nim");
			h = nexttry_158210(h, t.Max);
		} LA2: ;
	}
	nimln(67, "intsets.nim");
	{
		nimln(67, "intsets.nim");
		nimln(67, "intsets.nim");
		if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
		if (!!(((*data)->data[h] == NIM_NIL))) goto LA9;
		nimln(67, "intsets.nim");
		failedassertimpl_85425(((NimStringDesc*) &TMP699));
	}
	LA9: ;
	nimln(68, "intsets.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	asgnRef((void**) (&(*data)->data[h]), desc);
	popFrame();
}
N_NIMCALL(void, TMP705)(void* p, NI op) {
	ttrunk158034* a;
	NI LOC1;
	a = (ttrunk158034*)p;
	nimGCvisit((void*)(*a).Next, op);
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < 16; LOC1++) {
	}
}
N_NIMCALL(void, TMP706)(void* p, NI op) {
	ttrunkseq158036* a;
	NI LOC1;
	a = (ttrunkseq158036*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);
	}
}

N_NIMCALL(void, intsetenlarge_158631)(intset158038* t) {
	ttrunkseq158036* n;
	NI oldmax;
	NI TMP700;
	NI TMP701;
	NI TMP702;
	NI TMP703;
	ttrunkseq158036* LOC8;
	nimfr("intSetEnlarge", "intsets.nim")
	n = 0;
	nimln(72, "intsets.nim");
	oldmax = (*t).Max;
	nimln(73, "intsets.nim");
	nimln(73, "intsets.nim");
	nimln(73, "intsets.nim");
	nimln(73, "intsets.nim");
	TMP700 = addInt((*t).Max, 1);
	TMP701 = mulInt((NI32)(TMP700), 2);
	TMP702 = subInt((NI32)(TMP701), 1);
	(*t).Max = (NI32)(TMP702);
	nimln(74, "intsets.nim");
	nimln(74, "intsets.nim");
	TMP703 = addInt((*t).Max, 1);
	n = (ttrunkseq158036*) newSeq((&NTI158036), (NI32)(TMP703));
	{
		NI i_158665;
		NI res_158703;
		i_158665 = 0;
		nimln(1569, "system.nim");
		res_158703 = 0;
		{
			nimln(1570, "system.nim");
			while (1) {
				nimln(1570, "system.nim");
				if (!(res_158703 <= oldmax)) goto LA3;
				nimln(1569, "system.nim");
				i_158665 = res_158703;
				nimln(76, "intsets.nim");
				{
					nimln(76, "intsets.nim");
					nimln(76, "intsets.nim");
					if ((NU)(i_158665) >= (NU)((*t).Data->Sup.len)) raiseIndexError();
					if (!!(((*t).Data->data[i_158665] == NIM_NIL))) goto LA6;
					nimln(76, "intsets.nim");
					if ((NU)(i_158665) >= (NU)((*t).Data->Sup.len)) raiseIndexError();
					intsetrawinsert_158257((*t), (&n), (*t).Data->data[i_158665]);
				}
				LA6: ;
				nimln(1572, "system.nim");
				res_158703 = addInt(res_158703, 1);
			} LA3: ;
		}
	}
	nimln(77, "intsets.nim");
	LOC8 = 0;
	LOC8 = (*t).Data;
	unsureAsgnRef((void**) (&(*t).Data), n);
	n = LOC8;
	popFrame();
}

N_NIMCALL(ttrunk158034*, intsetput_158720)(intset158038* t, NI key) {
	ttrunk158034* result;
	NI h;
	nimfr("intSetPut", "intsets.nim")
	result = 0;
	nimln(80, "intsets.nim");
	nimln(80, "intsets.nim");
	h = (NI)(key & (*t).Max);
	{
		nimln(81, "intsets.nim");
		while (1) {
			nimln(81, "intsets.nim");
			nimln(81, "intsets.nim");
			if ((NU)(h) >= (NU)((*t).Data->Sup.len)) raiseIndexError();
			if (!!(((*t).Data->data[h] == NIM_NIL))) goto LA2;
			nimln(82, "intsets.nim");
			{
				nimln(82, "intsets.nim");
				if ((NU)(h) >= (NU)((*t).Data->Sup.len)) raiseIndexError();
				if (!((*(*t).Data->data[h]).Key == key)) goto LA5;
				nimln(83, "intsets.nim");
				nimln(83, "intsets.nim");
				if ((NU)(h) >= (NU)((*t).Data->Sup.len)) raiseIndexError();
				result = (*t).Data->data[h];
				goto BeforeRet;
			}
			LA5: ;
			nimln(84, "intsets.nim");
			h = nexttry_158210(h, (*t).Max);
		} LA2: ;
	}
	nimln(85, "intsets.nim");
	{
		NI TMP707;
		NIM_BOOL LOC9;
		nimln(85, "intsets.nim");
		nimln(85, "intsets.nim");
		TMP707 = addInt((*t).Max, 1);
		LOC9 = 0;
		LOC9 = mustrehash_158055((NI32)(TMP707), (*t).Counter);
		if (!LOC9) goto LA10;
		nimln(85, "intsets.nim");
		intsetenlarge_158631(t);
	}
	LA10: ;
	nimln(86, "intsets.nim");
	(*t).Counter = addInt((*t).Counter, 1);
	nimln(87, "intsets.nim");
	nimln(87, "intsets.nim");
	h = (NI)(key & (*t).Max);
	{
		nimln(88, "intsets.nim");
		while (1) {
			nimln(88, "intsets.nim");
			nimln(88, "intsets.nim");
			if ((NU)(h) >= (NU)((*t).Data->Sup.len)) raiseIndexError();
			if (!!(((*t).Data->data[h] == NIM_NIL))) goto LA13;
			nimln(88, "intsets.nim");
			h = nexttry_158210(h, (*t).Max);
		} LA13: ;
	}
	nimln(89, "intsets.nim");
	{
		nimln(89, "intsets.nim");
		nimln(89, "intsets.nim");
		if ((NU)(h) >= (NU)((*t).Data->Sup.len)) raiseIndexError();
		if (!!(((*t).Data->data[h] == NIM_NIL))) goto LA16;
		nimln(89, "intsets.nim");
		failedassertimpl_85425(((NimStringDesc*) &TMP708));
	}
	LA16: ;
	nimln(90, "intsets.nim");
	result = (ttrunk158034*) newObj((&NTI158032), sizeof(ttrunk158034));
	nimln(91, "intsets.nim");
	asgnRef((void**) (&(*result).Next), (*t).Head);
	nimln(92, "intsets.nim");
	(*result).Key = key;
	nimln(93, "intsets.nim");
	unsureAsgnRef((void**) (&(*t).Head), result);
	nimln(94, "intsets.nim");
	if ((NU)(h) >= (NU)((*t).Data->Sup.len)) raiseIndexError();
	asgnRef((void**) (&(*t).Data->data[h]), result);
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, contains_158854)(intset158038 s, NI key) {
	NIM_BOOL result;
	ttrunk158034* t;
	nimfr("contains", "intsets.nim")
	result = 0;
	nimln(98, "intsets.nim");
	nimln(98, "intsets.nim");
	t = intsetget_158221(s, (NI)((NU32)(key) >> (NU32)(9)));
	nimln(99, "intsets.nim");
	{
		NI u;
		nimln(99, "intsets.nim");
		nimln(99, "intsets.nim");
		if (!!((t == NIM_NIL))) goto LA3;
		nimln(100, "intsets.nim");
		nimln(100, "intsets.nim");
		u = (NI)(key & 511);
		nimln(101, "intsets.nim");
		nimln(101, "intsets.nim");
		nimln(101, "intsets.nim");
		nimln(101, "intsets.nim");
		nimln(101, "intsets.nim");
		if ((NU)((NI)((NU32)(((NI) (u))) >> (NU32)(5))) > (NU)(15)) raiseIndexError();
		nimln(101, "intsets.nim");
		nimln(101, "intsets.nim");
		result = !(((NI)((*t).Bits[((NI)((NU32)(((NI) (u))) >> (NU32)(5)))- 0] & (NI)((NU32)(1) << (NU32)(((NI) ((NI)(((NI) (u)) & 31)))))) == 0));
	}
	goto LA1;
	LA3: ;
	{
		nimln(103, "intsets.nim");
		result = NIM_FALSE;
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(void, incl_158886)(intset158038* s, NI key) {
	ttrunk158034* t;
	NI u;
	nimfr("incl", "intsets.nim")
	nimln(107, "intsets.nim");
	nimln(107, "intsets.nim");
	t = intsetput_158720(s, (NI)((NU32)(key) >> (NU32)(9)));
	nimln(108, "intsets.nim");
	nimln(108, "intsets.nim");
	u = (NI)(key & 511);
	nimln(109, "intsets.nim");
	nimln(109, "intsets.nim");
	if ((NU)((NI)((NU32)(((NI) (u))) >> (NU32)(5))) > (NU)(15)) raiseIndexError();
	nimln(109, "intsets.nim");
	nimln(109, "intsets.nim");
	if ((NU)((NI)((NU32)(((NI) (u))) >> (NU32)(5))) > (NU)(15)) raiseIndexError();
	nimln(110, "intsets.nim");
	nimln(110, "intsets.nim");
	(*t).Bits[((NI)((NU32)(((NI) (u))) >> (NU32)(5)))- 0] = (NI)((*t).Bits[((NI)((NU32)(((NI) (u))) >> (NU32)(5)))- 0] | (NI)((NU32)(1) << (NU32)(((NI) ((NI)(((NI) (u)) & 31))))));
	popFrame();
}

N_NIMCALL(void, excl_158901)(intset158038* s, NI key) {
	ttrunk158034* t;
	nimfr("excl", "intsets.nim")
	nimln(114, "intsets.nim");
	nimln(114, "intsets.nim");
	t = intsetget_158221((*s), (NI)((NU32)(key) >> (NU32)(9)));
	nimln(115, "intsets.nim");
	{
		NI u;
		nimln(115, "intsets.nim");
		nimln(115, "intsets.nim");
		if (!!((t == NIM_NIL))) goto LA3;
		nimln(116, "intsets.nim");
		nimln(116, "intsets.nim");
		u = (NI)(key & 511);
		nimln(117, "intsets.nim");
		nimln(117, "intsets.nim");
		if ((NU)((NI)((NU32)(((NI) (u))) >> (NU32)(5))) > (NU)(15)) raiseIndexError();
		nimln(117, "intsets.nim");
		nimln(117, "intsets.nim");
		if ((NU)((NI)((NU32)(((NI) (u))) >> (NU32)(5))) > (NU)(15)) raiseIndexError();
		nimln(118, "intsets.nim");
		nimln(118, "intsets.nim");
		nimln(118, "intsets.nim");
		(*t).Bits[((NI)((NU32)(((NI) (u))) >> (NU32)(5)))- 0] = (NI)((*t).Bits[((NI)((NU32)(((NI) (u))) >> (NU32)(5)))- 0] & (NI)((NU32) ~((NI)((NU32)(1) << (NU32)(((NI) ((NI)(((NI) (u)) & 31))))))));
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(NIM_BOOL, containsorincl_158933)(intset158038* s, NI key) {
	NIM_BOOL result;
	ttrunk158034* t;
	nimfr("containsOrIncl", "intsets.nim")
	result = 0;
	nimln(123, "intsets.nim");
	nimln(123, "intsets.nim");
	t = intsetget_158221((*s), (NI)((NU32)(key) >> (NU32)(9)));
	nimln(124, "intsets.nim");
	{
		NI u;
		nimln(124, "intsets.nim");
		nimln(124, "intsets.nim");
		if (!!((t == NIM_NIL))) goto LA3;
		nimln(125, "intsets.nim");
		nimln(125, "intsets.nim");
		u = (NI)(key & 511);
		nimln(126, "intsets.nim");
		nimln(126, "intsets.nim");
		nimln(126, "intsets.nim");
		nimln(126, "intsets.nim");
		nimln(126, "intsets.nim");
		if ((NU)((NI)((NU32)(((NI) (u))) >> (NU32)(5))) > (NU)(15)) raiseIndexError();
		nimln(126, "intsets.nim");
		nimln(126, "intsets.nim");
		result = !(((NI)((*t).Bits[((NI)((NU32)(((NI) (u))) >> (NU32)(5)))- 0] & (NI)((NU32)(1) << (NU32)(((NI) ((NI)(((NI) (u)) & 31)))))) == 0));
		nimln(127, "intsets.nim");
		{
			nimln(127, "intsets.nim");
			if (!!(result)) goto LA7;
			nimln(128, "intsets.nim");
			nimln(128, "intsets.nim");
			if ((NU)((NI)((NU32)(((NI) (u))) >> (NU32)(5))) > (NU)(15)) raiseIndexError();
			nimln(128, "intsets.nim");
			nimln(128, "intsets.nim");
			if ((NU)((NI)((NU32)(((NI) (u))) >> (NU32)(5))) > (NU)(15)) raiseIndexError();
			nimln(129, "intsets.nim");
			nimln(129, "intsets.nim");
			(*t).Bits[((NI)((NU32)(((NI) (u))) >> (NU32)(5)))- 0] = (NI)((*t).Bits[((NI)((NU32)(((NI) (u))) >> (NU32)(5)))- 0] | (NI)((NU32)(1) << (NU32)(((NI) ((NI)(((NI) (u)) & 31))))));
		}
		LA7: ;
	}
	goto LA1;
	LA3: ;
	{
		nimln(131, "intsets.nim");
		incl_158886(s, key);
		nimln(132, "intsets.nim");
		result = NIM_FALSE;
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(void, initintset_158967)(intset158038* Result) {
	nimfr("initIntSet", "intsets.nim")
	nimln(136, "intsets.nim");
	unsureAsgnRef((void**) (&(*Result).Data), (ttrunkseq158036*) newSeq((&NTI158036), 8));
	nimln(137, "intsets.nim");
	(*Result).Max = 7;
	nimln(138, "intsets.nim");
	(*Result).Counter = 0;
	nimln(139, "intsets.nim");
	unsureAsgnRef((void**) (&(*Result).Head), NIM_NIL);
	popFrame();
}

N_NIMCALL(void, assign_158992)(intset158038* dest, intset158038 src) {
	ttrunk158034* it;
	nimfr("assign", "intsets.nim")
	nimln(144, "intsets.nim");
	(*dest).Counter = src.Counter;
	nimln(145, "intsets.nim");
	(*dest).Max = src.Max;
	nimln(146, "intsets.nim");
	nimln(146, "intsets.nim");
	unsureAsgnRef((void**) (&(*dest).Data), (ttrunkseq158036*) newSeq((&NTI158036), src.Data->Sup.len));
	nimln(148, "intsets.nim");
	it = src.Head;
	{
		nimln(149, "intsets.nim");
		while (1) {
			NI h;
			ttrunk158034* n;
			nimln(149, "intsets.nim");
			nimln(149, "intsets.nim");
			if (!!((it == NIM_NIL))) goto LA2;
			nimln(151, "intsets.nim");
			nimln(151, "intsets.nim");
			h = (NI)((*it).Key & (*dest).Max);
			{
				nimln(152, "intsets.nim");
				while (1) {
					nimln(152, "intsets.nim");
					nimln(152, "intsets.nim");
					if ((NU)(h) >= (NU)((*dest).Data->Sup.len)) raiseIndexError();
					if (!!(((*dest).Data->data[h] == NIM_NIL))) goto LA4;
					nimln(152, "intsets.nim");
					h = nexttry_158210(h, (*dest).Max);
				} LA4: ;
			}
			nimln(153, "intsets.nim");
			{
				nimln(153, "intsets.nim");
				nimln(153, "intsets.nim");
				if ((NU)(h) >= (NU)((*dest).Data->Sup.len)) raiseIndexError();
				if (!!(((*dest).Data->data[h] == NIM_NIL))) goto LA7;
				nimln(153, "intsets.nim");
				failedassertimpl_85425(((NimStringDesc*) &TMP709));
			}
			LA7: ;
			n = 0;
			nimln(156, "intsets.nim");
			n = (ttrunk158034*) newObj((&NTI158032), sizeof(ttrunk158034));
			nimln(157, "intsets.nim");
			asgnRef((void**) (&(*n).Next), (*dest).Head);
			nimln(158, "intsets.nim");
			(*n).Key = (*it).Key;
			nimln(159, "intsets.nim");
			memcpy((void*)(*n).Bits, (NIM_CONST void*)(*it).Bits, sizeof((*n).Bits));
			nimln(160, "intsets.nim");
			unsureAsgnRef((void**) (&(*dest).Head), n);
			nimln(161, "intsets.nim");
			if ((NU)(h) >= (NU)((*dest).Data->Sup.len)) raiseIndexError();
			asgnRef((void**) (&(*dest).Data->data[h]), n);
			nimln(163, "intsets.nim");
			it = (*it).Next;
		} LA2: ;
	}
	popFrame();
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI32)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, HEX24_159354)(intset158038 s) {
	NimStringDesc* result;
	nimfr("$", "intsets.nim")
	result = 0;
	nimln(184, "intsets.nim");
	result = copyString(((NimStringDesc*) &TMP710));
	{
		NI key_159359;
		ttrunk158034* r_159366;
		key_159359 = 0;
		nimln(167, "intsets.nim");
		r_159366 = s.Head;
		{
			nimln(168, "intsets.nim");
			while (1) {
				NI i_159368;
				nimln(168, "intsets.nim");
				nimln(168, "intsets.nim");
				if (!!((r_159366 == NIM_NIL))) goto LA3;
				nimln(169, "intsets.nim");
				i_159368 = 0;
				{
					nimln(170, "intsets.nim");
					while (1) {
						NI w_159370;
						NI j_159372;
						nimln(170, "intsets.nim");
						if (!(i_159368 <= 15)) goto LA5;
						nimln(171, "intsets.nim");
						if ((NU)(i_159368) > (NU)(15)) raiseIndexError();
						w_159370 = (*r_159366).Bits[(i_159368)- 0];
						nimln(174, "intsets.nim");
						j_159372 = 0;
						{
							nimln(175, "intsets.nim");
							while (1) {
								nimln(175, "intsets.nim");
								nimln(175, "intsets.nim");
								if (!!((w_159370 == 0))) goto LA7;
								nimln(176, "intsets.nim");
								{
									NimStringDesc* LOC16;
									nimln(176, "intsets.nim");
									nimln(176, "intsets.nim");
									nimln(176, "intsets.nim");
									if (!!((((NI) ((NI)(w_159370 & 1))) == 0))) goto LA10;
									nimln(177, "intsets.nim");
									nimln(177, "intsets.nim");
									nimln(177, "intsets.nim");
									nimln(177, "intsets.nim");
									nimln(177, "intsets.nim");
									key_159359 = (NI)((NI)((NU32)((*r_159366).Key) << (NU32)(9)) | (NI)((NU32)((NI)((NU32)(i_159368) << (NU32)(5))) + (NU32)(j_159372)));
									nimln(186, "intsets.nim");
									{
										nimln(186, "intsets.nim");
										nimln(186, "intsets.nim");
										if (!(1 < result->Sup.len)) goto LA14;
										nimln(186, "intsets.nim");
										result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TMP711));
									}
									LA14: ;
									nimln(187, "intsets.nim");
									nimln(187, "intsets.nim");
									LOC16 = 0;
									LOC16 = nimIntToStr(key_159359);
									result = resizeString(result, LOC16->Sup.len + 0);
appendString(result, LOC16);
								}
								LA10: ;
								nimln(178, "intsets.nim");
								j_159372 = addInt(j_159372, 1);
								nimln(179, "intsets.nim");
								nimln(179, "intsets.nim");
								w_159370 = (NI)((NU32)(w_159370) >> (NU32)(1));
							} LA7: ;
						}
						nimln(180, "intsets.nim");
						i_159368 = addInt(i_159368, 1);
					} LA5: ;
				}
				nimln(181, "intsets.nim");
				r_159366 = (*r_159366).Next;
			} LA3: ;
		}
	}
	nimln(188, "intsets.nim");
	result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TMP712));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, empty_159400)(intset158038 s) {
	NIM_BOOL result;
	nimfr("empty", "intsets.nim")
	result = 0;
	nimln(197, "intsets.nim");
	nimln(197, "intsets.nim");
	result = (s.Counter == 0);
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_intsetsInit)(void) {
	nimfr("intsets", "intsets.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_intsetsDatInit)(void) {
static TNimNode* TMP704[3];
static TNimNode TMP685[4];
NTI158034.size = sizeof(ttrunk158034);
NTI158034.kind = 18;
NTI158034.base = 0;
TMP704[0] = &TMP685[1];
TMP685[1].kind = 1;
TMP685[1].offset = offsetof(ttrunk158034, Next);
TMP685[1].typ = (&NTI158032);
TMP685[1].name = "next";
TMP704[1] = &TMP685[2];
TMP685[2].kind = 1;
TMP685[2].offset = offsetof(ttrunk158034, Key);
TMP685[2].typ = (&NTI108);
TMP685[2].name = "key";
TMP704[2] = &TMP685[3];
TMP685[3].kind = 1;
TMP685[3].offset = offsetof(ttrunk158034, Bits);
TMP685[3].typ = (&NTI26620);
TMP685[3].name = "bits";
TMP685[0].len = 3; TMP685[0].kind = 2; TMP685[0].sons = &TMP704[0];
NTI158034.node = &TMP685[0];
NTI158032.size = sizeof(ttrunk158034*);
NTI158032.kind = 22;
NTI158032.base = (&NTI158034);
NTI158032.marker = TMP705;
NTI158036.size = sizeof(ttrunkseq158036*);
NTI158036.kind = 24;
NTI158036.base = (&NTI158032);
NTI158036.flags = 2;
NTI158036.marker = TMP706;
}

