/* Generated by Nim Compiler v0.10.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/jsudlow/Nim/lib -o .nimcache/stdlib_strutils.o .nimcache/stdlib_strutils.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct valueerror3249 valueerror3249;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell45135 tcell45135;
typedef struct tcellseq45151 tcellseq45151;
typedef struct tgcheap47216 tgcheap47216;
typedef struct tcellset45147 tcellset45147;
typedef struct tpagedesc45143 tpagedesc45143;
typedef struct tmemregion27410 tmemregion27410;
typedef struct tsmallchunk26640 tsmallchunk26640;
typedef struct tllchunk27404 tllchunk27404;
typedef struct tbigchunk26642 tbigchunk26642;
typedef struct tintset26617 tintset26617;
typedef struct ttrunk26613 ttrunk26613;
typedef struct tavlnode27408 tavlnode27408;
typedef struct tgcstat47214 tgcstat47214;
typedef struct tbasechunk26638 tbasechunk26638;
typedef struct tfreecell26630 tfreecell26630;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  valueerror3249  {
  Exception Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tcell45135  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq45151  {
NI Len;
NI Cap;
tcell45135** D;
};
struct  tcellset45147  {
NI Counter;
NI Max;
tpagedesc45143* Head;
tpagedesc45143** Data;
};
typedef tsmallchunk26640* TY27422[512];
typedef ttrunk26613* ttrunkbuckets26615[256];
struct  tintset26617  {
ttrunkbuckets26615 Data;
};
struct  tmemregion27410  {
NI Minlargeobj;
NI Maxlargeobj;
TY27422 Freesmallchunks;
tllchunk27404* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26642* Freechunkslist;
tintset26617 Chunkstarts;
tavlnode27408* Root;
tavlnode27408* Deleted;
tavlnode27408* Last;
tavlnode27408* Freeavlnodes;
};
struct  tgcstat47214  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47216  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq45151 Zct;
tcellseq45151 Decstack;
tcellset45147 Cycleroots;
tcellseq45151 Tempstack;
NI Recgclock;
tmemregion27410 Region;
tgcstat47214 Stat;
};
typedef NI TY26620[16];
struct  tpagedesc45143  {
tpagedesc45143* Next;
NI Key;
TY26620 Bits;
};
struct  tbasechunk26638  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26640  {
  tbasechunk26638 Sup;
tsmallchunk26640* Next;
tsmallchunk26640* Prev;
tfreecell26630* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27404  {
NI Size;
NI Acc;
tllchunk27404* Next;
};
struct  tbigchunk26642  {
  tbasechunk26638 Sup;
tbigchunk26642* Next;
tbigchunk26642* Prev;
NI Align;
NF Data;
};
struct  ttrunk26613  {
ttrunk26613* Next;
NI Key;
TY26620 Bits;
};
typedef tavlnode27408* TY27414[2];
struct  tavlnode27408  {
TY27414 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell26630  {
tfreecell26630* Next;
NI Zerofield;
};
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI64, addInt64)(NI64 a, NI64 b);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell45135*, usrtocell_48846)(void* usr);
static N_INLINE(void, rtladdzct_50404)(tcell45135* c);
N_NOINLINE(void, addzct_48817)(tcellseq45151* s, tcell45135* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
STRING_LITERAL(TMP280, "0123456789ABCDEF", 16);
STRING_LITERAL(TMP294, "invalid integer: ", 17);
extern TFrame* frameptr_16242;
extern TNimType NTI21601; /* ref ValueError */
extern TNimType NTI3249; /* ValueError */
extern tgcheap47216 gch_47244;

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) - (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU32) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI64, addInt64)(NI64 a, NI64 b) {
	NI64 result;
	result = 0;
	result = (NI64)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (IL64(0) <= (NI64)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (IL64(0) <= (NI64)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

N_NIMCALL(NimStringDesc*, nsuToHex)(NI64 x, NI len) {
	NimStringDesc* result;
	NI64 shift;
	nimfr("toHex", "strutils.nim")
	result = 0;
	shift = 0;
	nimln(399, "strutils.nim");
	nimln(399, "strutils.nim");
	result = mnewString(len);
	{
		NI j_94588;
		NI HEX3Atmp_94592;
		NI TMP279;
		NI res_94595;
		j_94588 = 0;
		HEX3Atmp_94592 = 0;
		nimln(400, "strutils.nim");
		nimln(400, "strutils.nim");
		TMP279 = subInt(len, 1);
		HEX3Atmp_94592 = (NI32)(TMP279);
		nimln(1560, "system.nim");
		res_94595 = HEX3Atmp_94592;
		{
			nimln(1561, "system.nim");
			while (1) {
				NI64 TMP281;
				nimln(1561, "system.nim");
				if (!(0 <= res_94595)) goto LA3;
				nimln(1560, "system.nim");
				j_94588 = res_94595;
				nimln(401, "strutils.nim");
				if ((NU)(j_94588) > (NU)(result->Sup.len)) raiseIndexError();
				nimln(401, "strutils.nim");
				nimln(401, "strutils.nim");
				nimln(401, "strutils.nim");
				if ((NU)((NI32)(((NI32)(NU32)(NU64)((NI64)((NU64)(x) >> (NU64)(shift)))) & ((NI32) 15))) > (NU)(((NimStringDesc*) &TMP280)->Sup.len)) raiseIndexError();
				result->data[j_94588] = ((NimStringDesc*) &TMP280)->data[(NI32)(((NI32)(NU32)(NU64)((NI64)((NU64)(x) >> (NU64)(shift)))) & ((NI32) 15))];
				nimln(402, "strutils.nim");
				nimln(402, "strutils.nim");
				TMP281 = addInt64(shift, IL64(4));
				shift = (NI64)(TMP281);
				nimln(1563, "system.nim");
				res_94595 = subInt(res_94595, 1);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI32)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(tcell45135*, usrtocell_48846)(void* usr) {
	tcell45135* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell45135*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell45135))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50404)(tcell45135* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48817((&gch_47244.Zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell45135* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_48846(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell45135* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_48846((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50404(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(NI, nsuParseHexInt)(NimStringDesc* s) {
	NI result;
	NI i;
	nimfr("parseHexInt", "strutils.nim")
	result = 0;
	nimln(450, "strutils.nim");
	i = 0;
	nimln(451, "strutils.nim");
	{
		NIM_BOOL LOC3;
		NIM_BOOL LOC5;
		NI TMP287;
		NI TMP288;
		nimln(451, "strutils.nim");
		LOC3 = 0;
		nimln(451, "strutils.nim");
		if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
		LOC3 = ((NU8)(s->data[i]) == (NU8)(48));
		if (!(LOC3)) goto LA4;
		nimln(451, "strutils.nim");
		LOC5 = 0;
		nimln(451, "strutils.nim");
		nimln(451, "strutils.nim");
		TMP287 = addInt(i, 1);
		if ((NU)((NI32)(TMP287)) > (NU)(s->Sup.len)) raiseIndexError();
		LOC5 = ((NU8)(s->data[(NI32)(TMP287)]) == (NU8)(120));
		if (LOC5) goto LA6;
		nimln(451, "strutils.nim");
		nimln(451, "strutils.nim");
		TMP288 = addInt(i, 1);
		if ((NU)((NI32)(TMP288)) > (NU)(s->Sup.len)) raiseIndexError();
		LOC5 = ((NU8)(s->data[(NI32)(TMP288)]) == (NU8)(88));
		LA6: ;
		LOC3 = LOC5;
		LA4: ;
		if (!LOC3) goto LA7;
		nimln(451, "strutils.nim");
		i = addInt(i, 2);
	}
	goto LA1;
	LA7: ;
	{
		nimln(452, "strutils.nim");
		if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
		if (!((NU8)(s->data[i]) == (NU8)(35))) goto LA10;
		nimln(452, "strutils.nim");
		i = addInt(i, 1);
	}
	goto LA1;
	LA10: ;
	LA1: ;
	{
		nimln(453, "strutils.nim");
		while (1) {
			nimln(454, "strutils.nim");
			if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
			switch (((NU8)(s->data[i]))) {
			case 95:
			{
				nimln(455, "strutils.nim");
				i = addInt(i, 1);
			}
			break;
			case 48 ... 57:
			{
				NI TMP289;
				nimln(457, "strutils.nim");
				nimln(457, "strutils.nim");
				nimln(457, "strutils.nim");
				nimln(457, "strutils.nim");
				nimln(457, "strutils.nim");
				if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
				TMP289 = subInt(((NI) (((NU8)(s->data[i])))), 48);
				result = (NI)((NI)((NU32)(result) << (NU32)(4)) | ((NI) ((NI32)(TMP289))));
				nimln(458, "strutils.nim");
				i = addInt(i, 1);
			}
			break;
			case 97 ... 102:
			{
				NI TMP290;
				NI TMP291;
				nimln(460, "strutils.nim");
				nimln(460, "strutils.nim");
				nimln(460, "strutils.nim");
				nimln(460, "strutils.nim");
				nimln(460, "strutils.nim");
				nimln(460, "strutils.nim");
				if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
				TMP290 = subInt(((NI) (((NU8)(s->data[i])))), 97);
				TMP291 = addInt(((NI) ((NI32)(TMP290))), 10);
				result = (NI)((NI)((NU32)(result) << (NU32)(4)) | ((NI) ((NI32)(TMP291))));
				nimln(461, "strutils.nim");
				i = addInt(i, 1);
			}
			break;
			case 65 ... 70:
			{
				NI TMP292;
				NI TMP293;
				nimln(463, "strutils.nim");
				nimln(463, "strutils.nim");
				nimln(463, "strutils.nim");
				nimln(463, "strutils.nim");
				nimln(463, "strutils.nim");
				nimln(463, "strutils.nim");
				if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
				TMP292 = subInt(((NI) (((NU8)(s->data[i])))), 65);
				TMP293 = addInt(((NI) ((NI32)(TMP292))), 10);
				result = (NI)((NI)((NU32)(result) << (NU32)(4)) | ((NI) ((NI32)(TMP293))));
				nimln(464, "strutils.nim");
				i = addInt(i, 1);
			}
			break;
			case 0:
			{
				nimln(465, "strutils.nim");
				goto LA12;
			}
			break;
			default:
			{
				valueerror3249* e_94882;
				NimStringDesc* LOC20;
				e_94882 = 0;
				nimln(2149, "system.nim");
				e_94882 = (valueerror3249*) newObj((&NTI21601), sizeof(valueerror3249));
				(*e_94882).Sup.Sup.m_type = (&NTI3249);
				nimln(2150, "system.nim");
				nimln(466, "strutils.nim");
				LOC20 = 0;
				LOC20 = rawNewString(s->Sup.len + 17);
appendString(LOC20, ((NimStringDesc*) &TMP294));
appendString(LOC20, s);
				asgnRefNoCycle((void**) (&(*e_94882).Sup.message), LOC20);
				nimln(466, "strutils.nim");
				raiseException((Exception*)e_94882, "ValueError");
			}
			break;
			}
		}
	} LA12: ;
	popFrame();
	return result;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI32)((*dest).Sup.len + 1))- 0] = 0;
	(*dest).Sup.len += 1;
}

N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x, NI minchars) {
	NimStringDesc* result;
	nimfr("intToStr", "strutils.nim")
	result = 0;
	nimln(410, "strutils.nim");
	nimln(410, "strutils.nim");
	nimln(410, "strutils.nim");
	if (x == (-2147483647 -1)) raiseOverflow();
	result = nimIntToStr((x > 0? (x) : -(x)));
	{
		NI i_94626;
		NI HEX3Atmp_94629;
		NI TMP320;
		NI res_94632;
		i_94626 = 0;
		HEX3Atmp_94629 = 0;
		nimln(411, "strutils.nim");
		nimln(411, "strutils.nim");
		nimln(411, "strutils.nim");
		TMP320 = subInt(minchars, result->Sup.len);
		HEX3Atmp_94629 = (NI32)(TMP320);
		nimln(1576, "system.nim");
		res_94632 = 1;
		{
			nimln(1577, "system.nim");
			while (1) {
				NimStringDesc* LOC4;
				nimln(1577, "system.nim");
				if (!(res_94632 <= HEX3Atmp_94629)) goto LA3;
				nimln(1576, "system.nim");
				i_94626 = res_94632;
				nimln(412, "strutils.nim");
				nimln(412, "strutils.nim");
				LOC4 = 0;
				LOC4 = rawNewString(result->Sup.len + 1);
appendChar(LOC4, 48);
appendString(LOC4, result);
				result = LOC4;
				nimln(1579, "system.nim");
				res_94632 = addInt(res_94632, 1);
			} LA3: ;
		}
	}
	nimln(413, "strutils.nim");
	{
		NimStringDesc* LOC9;
		nimln(413, "strutils.nim");
		if (!(x < 0)) goto LA7;
		nimln(414, "strutils.nim");
		nimln(414, "strutils.nim");
		LOC9 = 0;
		LOC9 = rawNewString(result->Sup.len + 1);
appendChar(LOC9, 45);
appendString(LOC9, result);
		result = LOC9;
	}
	LA7: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nsuRepeatChar)(NI count, NIM_CHAR c) {
	NimStringDesc* result;
	nimfr("repeatChar", "strutils.nim")
	result = 0;
	nimln(512, "strutils.nim");
	nimln(512, "strutils.nim");
	result = mnewString(count);
	{
		NI i_94993;
		NI HEX3Atmp_94995;
		NI TMP372;
		NI res_94998;
		i_94993 = 0;
		HEX3Atmp_94995 = 0;
		nimln(513, "strutils.nim");
		nimln(513, "strutils.nim");
		TMP372 = subInt(count, 1);
		HEX3Atmp_94995 = (NI32)(TMP372);
		nimln(1576, "system.nim");
		res_94998 = 0;
		{
			nimln(1577, "system.nim");
			while (1) {
				nimln(1577, "system.nim");
				if (!(res_94998 <= HEX3Atmp_94995)) goto LA3;
				nimln(1576, "system.nim");
				i_94993 = res_94998;
				nimln(513, "strutils.nim");
				if ((NU)(i_94993) > (NU)(result->Sup.len)) raiseIndexError();
				result->data[i_94993] = c;
				nimln(1579, "system.nim");
				res_94998 = addInt(res_94998, 1);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit)(void) {
	nimfr("strutils", "strutils.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit)(void) {
}

