/* Generated by Nim Compiler v0.10.1 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/jsudlow/Nim/lib -o .nimcache/systems.o .nimcache/systems.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>
typedef struct controller129005 controller129005;
typedef struct TY132029 TY132029;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TY133216 TY133216;
typedef struct TY133219 TY133219;
typedef struct tsurface124011 tsurface124011;
typedef struct table120030 table120030;
typedef struct keyvaluepairseq120033 keyvaluepairseq120033;
typedef struct keyvaluepair120036 keyvaluepair120036;
typedef struct TGenericSeq TGenericSeq;
typedef struct tsurface114255 tsurface114255;
typedef struct tpixelformat114245 tpixelformat114245;
typedef struct trect114227 trect114227;
typedef struct tpalette114241 tpalette114241;
typedef struct tcolor114233 tcolor114233;
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (NI t, NI dt, void* ClEnv);
void* ClEnv;
} TY132019;
struct  TY132029  {
NI HEX3Astate;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TY133216 {
void* Field0;
TY133219* Field1;
};
struct TY133219 {
char dummy;
};
struct keyvaluepair120036 {
NU8 Field0;
NI32 Field1;
NIM_BOOL Field2;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  table120030  {
keyvaluepairseq120033* Data;
NI Counter;
};
typedef NIM_BOOL TY129014[100];
struct  controller129005  {
tsurface124011* Display;
NIM_BOOL Shouldclose;
table120030 Keys;
table120030 Mods;
NI Mousex;
NI Mousey;
NIM_BOOL Mousedown;
TY129014 Grid;
};
struct  tsurface124011  {
NI W;
NI H;
tsurface114255* S;
};
struct  trect114227  {
NI16 X;
NI16 Y;
NU16 W;
NU16 H;
};
struct  tsurface114255  {
NI32 Flags;
tpixelformat114245* Format;
int W;
int H;
NU16 Pitch;
void* Pixels;
int Offset;
void* Hwdata;
trect114227 Cliprect;
NI32 Unused1;
NI32 Locked;
void* Blitmap;
int Formatversion;
int Refcount;
};
struct  tpixelformat114245  {
tpalette114241* Palette;
NU8 Bitsperpixel;
NU8 Bytesperpixel;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
NI32 Rmask;
NI32 Gmask;
NI32 Bmask;
NI32 Amask;
NI32 Colorkey;
NU8 Alpha;
};
struct  tpalette114241  {
NI Ncolors;
tcolor114233* Colors;
};
struct  tcolor114233  {
NU8 R;
NU8 G;
NU8 B;
NU8 Unused;
};
struct keyvaluepairseq120033 {
  TGenericSeq Sup;
  keyvaluepair120036 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, newdonothingsystem_132015)(controller129005* ctl, TY132019* Result);
N_NIMCALL(void, TMP665)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_CLOSURE(void, HEX3Aanonymous_132024)(NI t, NI dt, void* ClEnv);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(void, TMP682)(void* p, NI op);
TNimType NTI132029; /* object */
extern TNimType NTI108; /* int */
TNimType NTI132031; /* range -1..1(int) */
TNimType NTI132038; /* ref object */
extern TFrame* frameptr_16242;
TNimType NTI132019; /* tuple[pointer, ref tuple[]] */
extern TNimType NTI153; /* pointer */
TNimType NTI133219; /* tuple[] */
TNimType NTI133218; /* ref tuple[] */
N_NIMCALL(void, TMP665)(void* p, NI op) {
	TY132029* a;
	a = (TY132029*)p;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

N_CLOSURE(void, HEX3Aanonymous_132024)(NI t, NI dt, void* ClEnv) {
	TY132029* HEX3Aenvp_132035;
	nimfr(":anonymous", "systems.nim")
	HEX3Aenvp_132035 = (TY132029*) ClEnv;
	switch ((*HEX3Aenvp_132035).HEX3Astate) {
	case -1: goto BeforeRet;
	case 0: goto STATE0;
	case 1: goto STATE1;
	}
	STATE0: ;
	{
		nimln(5, "systems.nim");
		while (1) {
			nimln(6, "systems.nim");
			(*HEX3Aenvp_132035).HEX3Astate = 1;
			nimln(6, "systems.nim");
			goto BeforeRet;
			STATE1: ;
		}
	}
	nimln(4, "systems.nim");
	(*HEX3Aenvp_132035).HEX3Astate = -1;
	BeforeRet: ;
	popFrame();
}

N_NIMCALL(void, newdonothingsystem_132015)(controller129005* ctl, TY132019* Result) {
	TY132029* HEX3Aenv_132037;
	TY132019 LOC1;
	nimfr("newDoNothingSystem", "systems.nim")
	HEX3Aenv_132037 = 0;
	nimln(172, "system.nim");
	HEX3Aenv_132037 = (TY132029*) newObj((&NTI132038), sizeof(TY132029));
	nimln(4, "systems.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.ClPrc = HEX3Aanonymous_132024; LOC1.ClEnv = HEX3Aenv_132037;
	unsureAsgnRef((void**) (&(*Result).ClEnv), LOC1.ClEnv);
	(*Result).ClPrc = LOC1.ClPrc;
	popFrame();
}
N_NIMCALL(void, TMP682)(void* p, NI op) {
	TY133219* a;
	a = (TY133219*)p;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_systemsInit)(void) {
	nimfr("systems", "systems.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_systemsDatInit)(void) {
static TNimNode* TMP681[2];
static TNimNode TMP663[5];
NTI132029.size = sizeof(TY132029);
NTI132029.kind = 18;
NTI132029.base = 0;
NTI132029.flags = 3;
NTI132031.size = sizeof(NI);
NTI132031.kind = 20;
NTI132031.base = (&NTI108);
NTI132031.flags = 3;
TMP663[0].kind = 1;
TMP663[0].offset = offsetof(TY132029, HEX3Astate);
TMP663[0].typ = (&NTI132031);
TMP663[0].name = ":state";
NTI132029.node = &TMP663[0];
NTI132038.size = sizeof(TY132029*);
NTI132038.kind = 22;
NTI132038.base = (&NTI132029);
NTI132038.flags = 2;
NTI132038.marker = TMP665;
NTI132019.size = sizeof(TY133216);
NTI132019.kind = 18;
NTI132019.base = 0;
NTI132019.flags = 2;
TMP681[0] = &TMP663[2];
TMP663[2].kind = 1;
TMP663[2].offset = offsetof(TY133216, Field0);
TMP663[2].typ = (&NTI153);
TMP663[2].name = "Field0";
TMP681[1] = &TMP663[3];
NTI133219.size = sizeof(TY133219);
NTI133219.kind = 18;
NTI133219.base = 0;
NTI133219.flags = 3;
TMP663[4].len = 0; TMP663[4].kind = 2;
NTI133219.node = &TMP663[4];
NTI133218.size = sizeof(TY133219*);
NTI133218.kind = 22;
NTI133218.base = (&NTI133219);
NTI133218.flags = 2;
NTI133218.marker = TMP682;
TMP663[3].kind = 1;
TMP663[3].offset = offsetof(TY133216, Field1);
TMP663[3].typ = (&NTI133218);
TMP663[3].name = "Field1";
TMP663[1].len = 2; TMP663[1].kind = 2; TMP663[1].sons = &TMP681[0];
NTI132019.node = &TMP663[1];
}

